import {createPrivateMiniflare,fixtureToken} from '../run11/private-runtime.mjs';
import {test,expect} from 'vitest';
import {createRequire} from 'node:module';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {decryptBackup} from '../../apps/web/lib/vault/backup.ts';
import {privateAccountRequest} from '../../apps/web/lib/server/private-account.ts';
const require=createRequire(new URL('../../apps/web/package.json',import.meta.url));
const {chromium}=require('@playwright/test');
// Explicit opt-in: requires an already running local Next preview and installed Chrome.
test.skipIf(process.env.RUN10_BROWSER!=='1')('two real browser profiles use encrypted account transport, local durable stores and persistent Worker; auth delivery is a fixture',async()=>{
 const origin=process.env.RUN11_REVIEW_ORIGIN??'http://127.0.0.1:3110',account='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',persist=await mkdtemp(join(tmpdir(),'run10-browser-vault-'));
 const mf=await createPrivateMiniflare({persist,origin,outboundService:async()=>Response.json({id:account})});
 const sentOperations=[];
 const browser=await chromium.launch({channel:'chrome',headless:true});
 async function context(mobile=false){const token=fixtureToken('fixture-'+crypto.randomUUID(),account);const c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile});
  await c.route('**/api/private-account*',async route=>{const r=route.request(),headers=await r.allHeaders();const req=new Request(r.url(),{method:r.method(),headers,...(r.postData()?{body:r.postData()}: {})});
   const result=await privateAccountRequest(req,{authOrigin:'https://fixture.supabase.co',publicKey:'public-fixture',syncOrigin:'https://fixture.workers.dev'},async(url,init)=>{
    const path=new URL(url).pathname;if(new URL(url).hostname==='fixture.workers.dev'){if(path==='/v1/vault'&&init?.body)sentOperations.push(JSON.parse(init.body).operation);return mf.dispatchFetch(url,init);}
    if(path.endsWith('/verify'))return Response.json({access_token:token,expires_in:3600,user:{id:account}});
    if(path.endsWith('/user'))return Response.json({id:account});return Response.json({});
   });if(result.status>=400)console.log('Fixture adapter status',r.method(),result.status,'origin',headers.origin??'absent');await route.fulfill({status:result.status,headers:{...Object.fromEntries(result.headers),...(result.headers.getSetCookie().length?{'set-cookie':result.headers.getSetCookie().join('\n')}:{})},body:await result.text()});});return c;}
 async function login(page){await page.goto(origin+'/app/settings');await page.getByLabel('Email address',{exact:true}).fill('fixture@example.invalid');await page.getByRole('button',{name:'Send email code',exact:true}).click();try{await page.getByLabel('Email code',{exact:true}).fill('123456',{timeout:10000});}catch(e){console.log('Email fixture UI',await page.getByRole('region',{name:'Email account access'}).innerText());throw e;}await page.getByRole('button',{name:'Verify email code',exact:true}).click();}
 async function synced(page){await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Sync now'&&!b.disabled),{},{timeout:10000});const panel=page.getByRole('region',{name:'Encrypted account sync',exact:true});try{await panel.getByText(/Account records synced and acknowledged/).waitFor({timeout:8000});}catch(e){console.log('Sync diagnostic',await panel.getByRole('status').allTextContents(),await panel.getByRole('alert').allTextContents());throw e;}}
 try{
  const a=await context(),b=await context(true),pa=await a.newPage(),pb=await b.newPage();
  // Existing local records stay separate through sign-in and only copy after explicit protected review.
  await pa.goto(origin+'/app/habits');await pa.getByRole('button',{name:'+ New habit',exact:true}).click();await pa.getByLabel('Start from template').selectOption('read');await pa.getByLabel('Habit title',{exact:true}).fill('Fictional local before sign-in');await pa.getByRole('button',{name:'Create habit',exact:true}).click();
  await pa.getByRole('article',{name:'Fictional local before sign-in',exact:true}).waitFor();
  await login(pa);await pa.getByLabel('Sync my Health records with this account.',{exact:false}).check();await pa.getByRole('button',{name:'Create encrypted account vault',exact:true}).click();const recovery=await pa.getByLabel('New vault recovery secret',{exact:true}).inputValue();await pa.getByLabel('I saved this vault recovery secret separately.').check();await pa.getByRole('button',{name:'Confirm and create vault',exact:true}).click();await synced(pa);
  const attach=pa.getByRole('region',{name:'Copy local records to account',exact:true});
  await attach.getByRole('checkbox',{name:'Habits',exact:true}).check();await attach.getByRole('button',{name:'Review selected local records',exact:true}).click();await attach.getByText(/habits: 1/).waitFor();
  expect(await attach.getByRole('button',{name:'Copy selected records and sync'}).isDisabled()).toBe(true);
  const copySecret=await attach.getByLabel('Local copy backup secret',{exact:true}).inputValue();expect(copySecret.length).toBeGreaterThan(20);
  await attach.getByLabel('I saved this local-copy backup secret separately.').check();
  const downloadEvent=pa.waitForEvent('download');await attach.getByRole('button',{name:'Download protected local copy'}).click();const download=await downloadEvent;
  const reader=await download.createReadStream();let protectedFile='';for await(const chunk of reader)protectedFile+=chunk.toString();expect(protectedFile).not.toContain('Fictional local before sign-in');expect(JSON.parse(protectedFile).format).toBe('zigoals-encrypted-backup');expect((await decryptBackup(protectedFile,copySecret)).habits).toContain('Fictional local before sign-in');
  await attach.getByLabel('I saved the backup file and want these selected records copied into this account.').check();await attach.getByRole('button',{name:'Copy selected records and sync'}).click();await synced(pa);
  // Originals remain a separate local source; populated account sections refuse a repeated import.
  await attach.getByRole('button',{name:'Review selected local records',exact:true}).click();await pa.getByRole('region',{name:'Encrypted account sync',exact:true}).getByRole('alert').filter({hasText:'already contains'}).waitFor();
  await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);
  // Client navigation preserves the memory-only unlocked session.
  await pa.getByRole('link',{name:'Habits',exact:true}).first().click();await pa.getByRole('button',{name:'+ New habit',exact:true}).click();await pa.getByLabel('Start from template').selectOption('read');await pa.getByLabel('Habit title',{exact:true}).fill('Fictional synchronized reading');await pa.getByRole('button',{name:'Create habit',exact:true}).click();
  await pa.getByRole('link',{name:'Settings',exact:true}).first().click();await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);
  await pa.getByRole('link',{name:'Health',exact:true}).first().click();await pa.getByRole('button',{name:'Foods & recipes',exact:true}).click();await pa.getByRole('button',{name:'New food',exact:true}).click();
  const food=pa.getByRole('form',{name:'Food details'});for(const [label,value]of [['Food name','Fictional encrypted oats'],['Serving weight (g)','40'],['Calories (kcal)','150'],['Protein (g)','5'],['Carbs (g)','27'],['Fat (g)','3']])await food.getByLabel(label).fill(value);await food.getByRole('button',{name:'Save food',exact:true}).click();await pa.getByRole('button',{name:'Diary',exact:true}).click();
  const meal=pa.getByRole('form',{name:'Log a meal',exact:true});await meal.getByLabel('Food or recipe').selectOption({label:'Fictional encrypted oats · food'});await meal.getByRole('button',{name:'Log to diary'}).click();
  await pa.getByRole('button',{name:'Measurements',exact:true}).click();await pa.getByLabel('Measurement history type',{exact:true}).selectOption('waist');const measurement=pa.getByRole('form',{name:'Body measurement entry'});await measurement.getByLabel('Measurement value',{exact:true}).fill('80');await measurement.getByLabel('Measured at (device time)',{exact:true}).fill('2026-09-20T09:30');await measurement.getByLabel('Measurement source',{exact:true}).fill('Fictional synchronized tape');await measurement.getByRole('button',{name:'Save measurement',exact:true}).click();await pa.getByRole('region',{name:'Measurement records'}).getByText('80 cm',{exact:true}).waitFor();
  await pa.getByRole('link',{name:'Today',exact:true}).first().click();await pa.getByRole('link',{name:'+ Create a goal',exact:true}).click();await pa.getByLabel('Goal name',{exact:true}).fill('Fictional encrypted project');await pa.getByRole('radio',{name:'Project',exact:true}).check();await pa.getByLabel('Milestones, one per line').fill('Read evidence\nReview');for(let i=0;i<3;i++)await pa.getByRole('button',{name:'Continue →'}).click();await pa.getByRole('button',{name:'Create goal',exact:true}).click();await pa.getByTestId('tracked-progress').waitFor();
  await pa.getByRole('link',{name:'Today',exact:true}).first().click();await pa.getByRole('button',{name:'Customize Today',exact:true}).click();await pa.getByRole('button',{name:'Add widget',exact:true}).click();const editor=pa.getByRole('dialog',{name:'Add a widget'});await editor.getByRole('group',{name:'Choose a metric'}).getByRole('button',{name:'Water today',exact:true}).click();await editor.getByText('Title and display size').click();await editor.getByLabel('Card title (optional)').fill('Fictional synced nutrition');await editor.getByRole('button',{name:'Save widget'}).click();try{await pa.getByRole('article',{name:'Fictional synced nutrition',exact:true}).waitFor({timeout:7000});}catch(e){console.log('Widget save diagnostics',await pa.locator('[role=alert]').allTextContents(),await pa.locator('[role=status]').allTextContents());throw e;}
  await pa.getByRole('link',{name:'Settings',exact:true}).first().click();await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);
  await login(pb);await pb.getByLabel('Sync my Health records with this account.',{exact:false}).check();await pb.getByLabel('Vault recovery secret',{exact:true}).fill(recovery);await pb.getByRole('button',{name:'Unlock account vault',exact:true}).click();await synced(pb);
  await pb.getByRole('link',{name:'Today',exact:true}).first().click();await pb.getByRole('article',{name:'Fictional synced nutrition',exact:true}).waitFor();
  await pb.getByRole('link',{name:'Health',exact:true}).first().click();await pb.getByRole('region',{name:'Breakfast diary'}).getByText('Fictional encrypted oats',{exact:true}).waitFor();
  await pb.getByRole('button',{name:'Measurements',exact:true}).click();await pb.getByLabel('Measurement history type',{exact:true}).selectOption('waist');await pb.getByRole('region',{name:'Measurement records'}).getByText('80 cm',{exact:true}).waitFor();await pb.getByRole('button',{name:'Correct measurement',exact:true}).click();await pb.getByRole('form',{name:'Body measurement entry'}).getByLabel('Measurement value',{exact:true}).fill('79');await pb.getByRole('button',{name:'Save measurement',exact:true}).click();await pb.getByRole('region',{name:'Measurement records'}).getByText('79 cm',{exact:true}).waitFor();
  await pb.getByRole('link',{name:'Goals',exact:true}).first().click();await pb.getByRole('heading',{name:'Fictional encrypted project',exact:true}).waitFor();
  await pb.getByRole('link',{name:'Habits',exact:true}).first().click();await pb.getByRole('article',{name:'Fictional synchronized reading',exact:true}).waitFor();await pb.getByRole('article',{name:'Fictional local before sign-in',exact:true}).waitFor();
  await pb.getByRole('article',{name:'Fictional synchronized reading',exact:true}).getByRole('button',{name:'Complete Fictional synchronized reading',exact:true}).click();
  await pb.getByRole('link',{name:'Settings',exact:true}).first().click();await pb.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pb);
  await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);await pa.getByRole('link',{name:'Habits',exact:true}).first().click();await pa.getByRole('article',{name:'Fictional synchronized reading',exact:true}).getByRole('button',{name:'Undo completion for Fictional synchronized reading',exact:true}).waitFor();
  // Cold reload requires the separate vault secret; accepted account data survives.
  await pb.reload();await pb.getByLabel('Vault recovery secret',{exact:true}).fill(recovery);await pb.getByLabel('Sync my Health records with this account.',{exact:false}).check();await pb.getByRole('button',{name:'Unlock account vault',exact:true}).click();await synced(pb);
  // Two independent offline app edits merge by their stable water-entry identities.
  for(const page of [pa,pb]){await page.getByRole('link',{name:'Health',exact:true}).first().click();await page.getByRole('button',{name:'Add 250 mL',exact:true}).waitFor();}await a.setOffline(true);await b.setOffline(true);
  await pa.getByRole('button',{name:'Add 250 mL',exact:true}).click();await pa.getByRole('region',{name:'Water journal'}).getByText('250 mL recorded',{exact:false}).waitFor();await pb.getByRole('button',{name:'Add 500 mL',exact:true}).click();await pb.getByRole('region',{name:'Water journal'}).getByText('500 mL recorded',{exact:false}).waitFor();
  await b.setOffline(false);await pb.getByRole('link',{name:'Settings',exact:true}).first().click();await pb.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pb);
  await a.setOffline(false);await pa.getByRole('link',{name:'Settings',exact:true}).first().click();await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);await pa.getByRole('link',{name:'Health',exact:true}).first().click();await pa.getByRole('region',{name:'Water journal'}).getByText('750 mL recorded',{exact:false}).waitFor({timeout:5000});
  await pb.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pb);await pb.getByRole('link',{name:'Health',exact:true}).first().click();await pb.getByRole('region',{name:'Water journal'}).getByText('750 mL recorded',{exact:false}).waitFor();await pb.getByRole('link',{name:'Settings',exact:true}).first().click();
  await pa.getByRole('link',{name:'Health',exact:true}).first().click();await pa.getByRole('button',{name:'Measurements',exact:true}).click();await pa.getByLabel('Measurement history type',{exact:true}).selectOption('waist');await pa.getByRole('region',{name:'Measurement records'}).getByText('79 cm',{exact:true}).waitFor();await pa.getByRole('region',{name:'Measurement records'}).getByText('Record history',{exact:true}).click();await pa.getByText(/Previous: 80 cm/).waitFor();
  // Concurrent corrections keep both readings until an explicit protected review.
  for(const page of [pa,pb]){await page.getByRole('link',{name:'Health',exact:true}).first().click();await page.getByRole('button',{name:'Measurements',exact:true}).click();await page.getByLabel('Measurement history type',{exact:true}).selectOption('waist');}
  await a.setOffline(true);await b.setOffline(true);
  for(const [page,value]of [[pa,'78'],[pb,'77']]){await page.getByRole('button',{name:'Correct measurement',exact:true}).click();const form=page.getByRole('form',{name:'Body measurement entry'});await form.getByLabel('Measurement value',{exact:true}).fill(value);await form.getByRole('button',{name:'Save measurement',exact:true}).click();}
  await a.setOffline(false);await pa.getByRole('link',{name:'Settings',exact:true}).first().click();await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);await b.setOffline(false);await pb.getByRole('link',{name:'Settings',exact:true}).first().click();await pb.getByRole('button',{name:'Sync now',exact:true}).click();await pb.getByRole('alert').filter({hasText:'Conflicting'}).waitFor();
  await pb.getByText('Review conflicting account records',{exact:true}).click();await pb.getByRole('button',{name:'Prepare conflict review',exact:true}).click();await pb.getByLabel('Conflict recovery secret',{exact:true}).waitFor();const conflictSecret=await pb.getByLabel('Conflict recovery secret',{exact:true}).inputValue();await pb.getByLabel('I saved the conflict recovery secret separately.').check();const conflictDownload=pb.waitForEvent('download');await pb.getByRole('button',{name:'Download both conflict copies',exact:true}).click();let conflictBytes='';for await(const chunk of await (await conflictDownload).createReadStream())conflictBytes+=chunk.toString();const conflictData=JSON.parse((await decryptBackup(conflictBytes,conflictSecret)).settings);expect(conflictData.local.health).toContain('77000');expect(conflictData.cloud.health).toContain('78000');
  const choices=pb.getByLabel(/^Choose value for /);for(let i=0;i<await choices.count();i++)await choices.nth(i).selectOption('cloud');await pb.getByLabel('Conflict confirmation',{exact:true}).fill('RESOLVE RECORDS');await pb.getByRole('button',{name:'Confirm reviewed resolution',exact:true}).click();await synced(pb);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);
  await pa.getByRole('link',{name:'Health',exact:true}).first().click();await pa.getByRole('button',{name:'Measurements',exact:true}).click();await pa.getByLabel('Measurement history type',{exact:true}).selectOption('waist');await pa.getByRole('region',{name:'Measurement records'}).getByText('78 cm',{exact:true}).waitFor();await pa.getByRole('region',{name:'Measurement records'}).getByText('Record history',{exact:true}).click();await pa.getByText(/Previous: 77 cm/).waitFor();
  // Exercise the installed UI's forward-recovery path against a persisted older-policy journal.
  await pa.getByRole('link',{name:'Settings',exact:true}).first().click();await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);
  const obsolete=await pa.evaluate(async account=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('zigoals-account-sync-v1',2);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),r=store.get(account);r.onsuccess=()=>{const value=r.result,operation=crypto.randomUUID();value.pending={protocol:1,vault:'00000000-0000-4000-8000-000000000099',operation,base:value.revision,changes:[]};value.pendingPolicy=1;store.put(value,account);tx.oncomplete=()=>resolve(operation);};tx.onerror=()=>reject(tx.error);});}finally{db.close();}},account);
  // Bind the fictional older operation to this actual vault, without reading secret material.
  const tokenBeforeRecovery=(await a.cookies(origin+'/api/private-account')).find(c=>c.name==='zigoals_session').value;const vaultBeforeRecovery=await (await mf.dispatchFetch('https://fixture.workers.dev/v1/vault',{headers:{origin,authorization:'Bearer '+tokenBeforeRecovery,'x-zigoals-account':account}})).json();
  await pa.evaluate(async({account,vault})=>{const db=await new Promise(resolve=>{const r=indexedDB.open('zigoals-account-sync-v1',2);r.onsuccess=()=>resolve(r.result);});await new Promise(resolve=>{const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),r=store.get(account);r.onsuccess=()=>{const value=r.result;value.pending.vault=vault;store.put(value,account);};tx.oncomplete=resolve;});db.close();},{account,vault:vaultBeforeRecovery.manifest.vault});
  await pa.getByRole('button',{name:'Sync now',exact:true}).click();await pa.getByRole('alert').filter({hasText:'older sync policy'}).waitFor();
  await pa.getByText('Repair a blocked sync queue',{exact:true}).click();await pa.getByRole('button',{name:'Prepare forward recovery review',exact:true}).click();await pa.getByLabel('Forward recovery secret',{exact:true}).waitFor();const forwardSecret=await pa.getByLabel('Forward recovery secret',{exact:true}).inputValue();await pa.getByLabel('I saved the forward recovery secret separately.').check();const forwardDownload=pa.waitForEvent('download');await pa.getByRole('button',{name:'Download forward recovery copy',exact:true}).click();let forwardBytes='';for await(const chunk of await (await forwardDownload).createReadStream())forwardBytes+=chunk.toString();expect(JSON.parse((await decryptBackup(forwardBytes,forwardSecret)).settings).journal.pending.operation).toBe(obsolete);
  await pa.getByLabel('Recovery confirmation',{exact:true}).fill('RECOVER QUEUE');await pa.getByRole('button',{name:'Confirm forward recovery',exact:true}).click();await synced(pa);expect(sentOperations).not.toContain(obsolete);
  // Rotation is a real UI → account adapter → persistent Worker journey.
  await pa.getByRole('link',{name:'Settings',exact:true}).first().click();await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa);
  await pa.getByText('Rotate vault encryption',{exact:true}).click();await pa.getByRole('button',{name:'Prepare key rotation',exact:true}).click();
  const nextRecovery=await pa.getByLabel('New rotation recovery secret',{exact:true}).inputValue();expect(nextRecovery).not.toBe(recovery);
  await pa.getByLabel('I saved the new rotation recovery secret separately.').check();await pa.getByRole('button',{name:'Activate new vault key',exact:true}).click();await pa.getByText(/Vault key rotated and activated/).waitFor();
  await pb.getByRole('button',{name:'Sync now',exact:true}).click();await pb.getByRole('alert').filter({hasText:'Account or vault changed'}).waitFor();
  await pb.reload();await pb.getByLabel('Vault recovery secret',{exact:true}).fill(recovery);await pb.getByRole('button',{name:'Unlock account vault',exact:true}).click();await pb.getByRole('alert').filter({hasText:'Unlock or integrity check failed'}).waitFor();
  await pb.getByLabel('Vault recovery secret',{exact:true}).fill(nextRecovery);await pb.getByLabel('Sync my Health records with this account.',{exact:false}).check();await pb.getByRole('button',{name:'Unlock account vault',exact:true}).click();await synced(pb);
  await pb.getByRole('link',{name:'Health',exact:true}).first().click();await pb.getByRole('region',{name:'Water journal'}).getByText('750 mL recorded',{exact:false}).waitFor();await pb.getByRole('link',{name:'Settings',exact:true}).first().click();
  // Selected-domain deletion is a backed-up UI choice; a stale client cannot restore it implicitly.
  await pa.getByText('Cloud copies by section',{exact:true}).click();await pa.getByRole('button',{name:'Review section deletion',exact:true}).click();
  const sectionSecret=await pa.getByLabel('Section recovery secret',{exact:true}).inputValue();await pa.getByLabel('I saved this section recovery secret separately.').check();
  const sectionDownload=pa.waitForEvent('download');await pa.getByRole('button',{name:'Download section recovery copy',exact:true}).click();let sectionBytes='';for await(const chunk of await (await sectionDownload).createReadStream())sectionBytes+=chunk.toString();const sectionArchive=JSON.parse((await decryptBackup(sectionBytes,sectionSecret)).settings);expect(sectionArchive.local.health).toContain('Fictional encrypted oats');expect(sectionArchive.cloud.health).toContain('Fictional encrypted oats');
  await pa.getByLabel('Section confirmation',{exact:true}).fill('DELETE SECTION');await pa.getByRole('button',{name:'Confirm section deletion',exact:true}).click();await pa.getByText(/Cloud section deleted. Local records were kept/).waitFor();
  await pb.getByRole('button',{name:'Sync now',exact:true}).click();await pb.getByRole('alert').filter({hasText:'Health cloud copy was deleted'}).waitFor();
  await pa.getByRole('button',{name:'Review restoring local section',exact:true}).click();await pa.getByLabel('Section recovery secret',{exact:true}).waitFor();await pa.getByLabel('I saved this section recovery secret separately.').check();
  const restoreDownload=pa.waitForEvent('download');await pa.getByRole('button',{name:'Download section recovery copy',exact:true}).click();await restoreDownload;await pa.getByLabel('Section confirmation',{exact:true}).fill('RESTORE SECTION');await pa.getByRole('button',{name:'Confirm section restore',exact:true}).click();await synced(pa);
  // The second client explicitly accepts the restored, identical cloud generation before auto-sync resumes.
  await pb.getByText('Cloud copies by section',{exact:true}).click();await pb.getByRole('button',{name:'Review restoring local section',exact:true}).click();await pb.getByLabel('Section recovery secret',{exact:true}).waitFor();await pb.getByLabel('I saved this section recovery secret separately.').check();const secondRestore=pb.waitForEvent('download');await pb.getByRole('button',{name:'Download section recovery copy',exact:true}).click();await secondRestore;await pb.getByLabel('Section confirmation',{exact:true}).fill('RESTORE SECTION');await pb.getByRole('button',{name:'Confirm section restore',exact:true}).click();await synced(pb);
  const tokenA=(await a.cookies(origin+'/api/private-account')).find(c=>c.name==='zigoals_session').value;
  const raw=await (await mf.dispatchFetch('https://fixture.workers.dev/v1/vault',{headers:{origin,authorization:'Bearer '+tokenA,'x-zigoals-account':account}})).text();for(const marker of ['Fictional synchronized reading','Fictional encrypted oats','Fictional encrypted project','Fictional synced nutrition'])expect(raw).not.toContain(marker);expect(JSON.parse(raw).records.length).toBeGreaterThan(1);
  await pa.getByRole('link',{name:'Settings',exact:true}).first().click();await pa.getByRole('button',{name:'Refresh sessions',exact:true}).click();await pa.getByRole('button',{name:'Revoke other sessions',exact:true}).click();await pa.getByRole('button',{name:'Confirm session revocation',exact:true}).click();await pa.getByRole('region',{name:'Account sessions',exact:true}).getByText('1 session(s) revoked.',{exact:false}).waitFor();
  await pb.bringToFront();await pb.evaluate(()=>window.dispatchEvent(new Event('focus')));await pb.getByRole('region',{name:'Encrypted account sync',exact:true}).getByText('Account access changed. Sign in and unlock again.',{exact:true}).waitFor();expect(await pb.getByRole('button',{name:'Sync now',exact:true}).count()).toBe(0);
  const deletion=pa.getByRole('region',{name:'Account deletion',exact:true});await deletion.getByRole('button',{name:'Prepare backup before deletion'}).click();await deletion.getByLabel('Deletion backup recovery secret',{exact:true}).waitFor();
  const deletionSecret=await deletion.getByLabel('Deletion backup recovery secret',{exact:true}).inputValue();await deletion.getByLabel('I saved the deletion backup secret separately.').check();
  const deletionDownload=pa.waitForEvent('download');await deletion.getByRole('button',{name:'Download deletion recovery copy'}).click();const deletionFile=await deletionDownload;let deletionBytes='';for await(const chunk of await deletionFile.createReadStream())deletionBytes+=chunk.toString();expect((await decryptBackup(deletionBytes,deletionSecret)).health).toContain('Fictional encrypted oats');
  await deletion.getByLabel('Deletion confirmation',{exact:true}).fill('DELETE CLOUD DATA');await deletion.getByRole('button',{name:'Confirm cloud deletion',exact:true}).click();await deletion.getByRole('status').filter({hasText:'Cloud vault deleted and stale access blocked'}).waitFor();
  expect((await mf.dispatchFetch('https://fixture.workers.dev/v1/vault',{headers:{origin,authorization:'Bearer '+tokenA,'x-zigoals-account':account}})).status).toBe(410);
  await pa.goto(origin+'/app/habits');expect(await pa.getByRole('article',{name:'Fictional synchronized reading',exact:true}).count()).toBe(0);
  await pa.goto(origin+'/app/settings');await pa.getByRole('button',{name:'Sign out',exact:true}).click();await pa.getByRole('link',{name:'Habits',exact:true}).first().click();await pa.getByRole('article',{name:'Fictional local before sign-in',exact:true}).waitFor();expect(await pa.getByRole('article',{name:'Fictional synchronized reading',exact:true}).count()).toBe(0);
  await a.close();await b.close();
 }finally{await browser.close();await mf.dispose();}
},90000);
