import {createPrivateMiniflare,fixtureToken} from '../run11/private-runtime.mjs';
import {armSyncCompletion} from '../run11/sync-completion.mjs';import {createDiagnostics} from './account-browser-diagnostics.mjs';
import {test,expect} from 'vitest';
import {createRequire} from 'node:module';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {decryptBackup} from '../../apps/web/lib/vault/backup.ts';
import {privateAccountRequest} from '../../apps/web/lib/server/private-account.ts';
const require=createRequire(new URL('../../apps/web/package.json',import.meta.url));
const {chromium}=require('@playwright/test');
// Explicit opt-in: requires an already running local Next preview and installed Chrome.
test.skipIf(process.env.RUN10_BROWSER!=='1').each(['a-first','b-first'])('two real browser profiles use encrypted account transport and persistent Worker (%s reconnect); auth delivery is a fixture',async(order)=>{
 const origin=process.env.RUN11_REVIEW_ORIGIN??'http://127.0.0.1:3110',account='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',persist=await mkdtemp(join(tmpdir(),'run10-browser-vault-'));
 const mf=await createPrivateMiniflare({persist,origin,outboundService:async()=>Response.json({id:account})});
 const sentOperations=[],diag=createDiagnostics(account);
 const browser=await chromium.launch({channel:'chrome',headless:true});
 async function context(mobile=false){const token=fixtureToken('fixture-'+crypto.randomUUID(),account);const c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile}),label=mobile?'B':'A';await diag.watchContext(c);let offline=false;const toggleOffline=c.setOffline.bind(c);c.setOffline=async value=>{offline=value;await toggleOffline(value);};
  await c.route('**/api/private-account*',async route=>{if(offline){diag.request(label,route.request().method(),route.request().url(),route.request().postData())('aborted: offline');await route.abort('internetdisconnected');return;}const r=route.request(),headers=await r.allHeaders();const done=diag.request(label,r.method(),r.url(),r.postData()),req=new Request(r.url(),{method:r.method(),headers,...(r.postData()?{body:r.postData()}: {})});
   const result=await privateAccountRequest(req,{authOrigin:'https://fixture.supabase.co',publicKey:'public-fixture',syncOrigin:'https://fixture.workers.dev'},async(url,init)=>{
    const path=new URL(url).pathname;if(new URL(url).hostname==='fixture.workers.dev'){if(path==='/v1/vault'&&init?.body){const operation=JSON.parse(init.body).operation;sentOperations.push(operation);diag.operation(label,operation);}return mf.dispatchFetch(url,init);}
    if(path.endsWith('/verify'))return Response.json({access_token:token,expires_in:3600,user:{id:account}});
    if(path.endsWith('/user'))return Response.json({id:account});return Response.json({});
   });if(result.status>=400)console.log('Fixture adapter status',r.method(),result.status,'origin',headers.origin??'absent');await route.fulfill({status:result.status,headers:{...Object.fromEntries(result.headers),...(result.headers.getSetCookie().length?{'set-cookie':result.headers.getSetCookie().join('\n')}:{})},body:await result.text()});done(result.status);});return c;}
 async function login(page){await page.goto(origin+'/app/settings');await page.getByLabel('Email address',{exact:true}).fill('fixture@example.invalid');await page.getByRole('button',{name:'Send email code',exact:true}).click();try{await page.getByLabel('Email code',{exact:true}).fill('123456',{timeout:10000});}catch(e){console.log('Email fixture UI',await page.getByRole('region',{name:'Email account access'}).innerText());throw e;}await page.getByRole('button',{name:'Verify email code',exact:true}).click();
  // Verification finishes asynchronously and re-renders the panel; a Health consent ticked before
  // that is lost, so wait until the verified vault controls are shown.
  await page.getByRole('button',{name:'Create encrypted account vault',exact:true}).or(page.getByLabel('Vault recovery secret',{exact:true})).waitFor();}
 // Every wait needs a sync that completes after it was armed: the success message stays on screen,
 // so reading it alone can accept an earlier completion (see ../run11/sync-completion.mjs).
 async function arm(page){await armSyncCompletion(page);return page.evaluate(()=>window.__zigoalsSyncCompletions);}
 async function synced(page,mark){try{await page.waitForFunction(m=>window.__zigoalsSyncCompletions>m&&[...document.querySelectorAll('button')].some(b=>b.textContent==='Sync now'&&!b.disabled),mark,{timeout:10000});}catch(e){console.log(`[account-browser] synced(): within 10 s no sync completed after mark ${mark}, or Sync now stayed disabled`);throw e;}const panel=page.getByRole('region',{name:'Encrypted account sync',exact:true});try{await panel.getByText(/Account records synced and acknowledged/).waitFor({timeout:8000});}catch(e){console.log('Sync diagnostic',await panel.getByRole('status').allTextContents(),await panel.getByRole('alert').allTextContents());throw e;}}
 try{
  const a=await context(),b=await context(true),pa=await a.newPage(),pb=await b.newPage();diag.watchPage(pa,'A');diag.watchPage(pb,'B');
  // Existing local records stay separate through sign-in and only copy after explicit protected review.
  diag.step('L36 A: local habit before sign-in');await pa.goto(origin+'/app/habits');await pa.getByRole('button',{name:'+ New habit',exact:true}).click();await pa.getByLabel('Start from template').selectOption('read');await pa.getByLabel('Habit title',{exact:true}).fill('Fictional local before sign-in');await pa.getByRole('button',{name:'Create habit',exact:true}).click();
  await pa.getByRole('article',{name:'Fictional local before sign-in',exact:true}).waitFor();
  diag.step('L38 A: sign in, create vault, first sync');await login(pa);await pa.getByLabel('Sync my Health records with this account.',{exact:false}).check();await pa.getByRole('button',{name:'Create encrypted account vault',exact:true}).click();const recovery=await pa.getByLabel('New vault recovery secret',{exact:true}).inputValue();await pa.getByLabel('I saved this vault recovery secret separately.').check();const fresh1=await arm(pa);await pa.getByRole('button',{name:'Confirm and create vault',exact:true}).click();await synced(pa,fresh1);
  const attach=pa.getByRole('region',{name:'Copy local records to account',exact:true});
  diag.step('L40 A: review local copy');await attach.getByRole('checkbox',{name:'Habits',exact:true}).check();await attach.getByRole('button',{name:'Review selected local records',exact:true}).click();await attach.getByText(/habits: 1/).waitFor();
  expect(await attach.getByRole('button',{name:'Copy selected records and sync'}).isDisabled()).toBe(true);
  // Session M (owner decision M2): the copy happens in place, with no file and no backup secret; one explicit approval.
  expect(await attach.getByLabel('Local copy backup secret',{exact:true}).count()).toBe(0);expect(await attach.getByRole('button',{name:'Download protected local copy'}).count()).toBe(0);
  const approve=attach.getByLabel('Copy these records into this account. The originals stay on this device.',{exact:true});
  expect(await approve.isDisabled()).toBe(false);expect(await approve.isChecked()).toBe(false);
  diag.step('L46 A: copy local records and sync');await approve.check();const fresh2=await arm(pa);await attach.getByRole('button',{name:'Copy selected records and sync'}).click();await synced(pa,fresh2);
  // Originals remain a separate local source; populated account sections refuse a repeated import.
  diag.step('L48 A: repeated import refused');await attach.getByRole('button',{name:'Review selected local records',exact:true}).click();await pa.getByRole('region',{name:'Encrypted account sync',exact:true}).getByRole('alert').filter({hasText:'already contains'}).waitFor();
  diag.step('L49 A: Sync now');const fresh3=await arm(pa);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa,fresh3);
  // Client navigation preserves the memory-only unlocked session.
  diag.step('L51 A: new habit via client navigation');await pa.getByRole('link',{name:'Habits',exact:true}).first().click();await pa.getByRole('button',{name:'+ New habit',exact:true}).click();await pa.getByLabel('Start from template').selectOption('read');await pa.getByLabel('Habit title',{exact:true}).fill('Fictional synchronized reading');await pa.getByRole('button',{name:'Create habit',exact:true}).click();
  diag.step('L52 A: Sync now');await pa.getByRole('link',{name:'Settings',exact:true}).first().click();const fresh4=await arm(pa);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa,fresh4);
  diag.step('L53 A: new food');await pa.getByRole('link',{name:'Health',exact:true}).first().click();await pa.getByRole('button',{name:'Foods & recipes',exact:true}).click();await pa.getByRole('button',{name:'New food',exact:true}).click();
  const food=pa.getByRole('form',{name:'Food details'});for(const [label,value]of [['Food name','Fictional encrypted oats'],['Serving weight (g)','40'],['Calories (kcal)','150'],['Protein (g)','5'],['Carbs (g)','27'],['Fat (g)','3']])await food.getByLabel(label).fill(value);await food.getByRole('button',{name:'Save food',exact:true}).click();await pa.getByRole('button',{name:'Diary',exact:true}).click();
  diag.step('L55 A: log a meal');const meal=pa.getByRole('form',{name:'Log a meal',exact:true});await meal.getByLabel('Food or recipe').selectOption({label:'Fictional encrypted oats · food'});await meal.getByRole('button',{name:'Log to diary'}).click();
  diag.step('L56 A: waist measurement');await pa.getByRole('button',{name:'Measurements',exact:true}).click();await pa.getByLabel('Measurement history type',{exact:true}).selectOption('waist');const measurement=pa.getByRole('form',{name:'Body measurement entry'});await measurement.getByLabel('Measurement value',{exact:true}).fill('80');await measurement.getByLabel('Measured at (device time)',{exact:true}).fill('2026-09-20T09:30');await measurement.getByLabel('Measurement source',{exact:true}).fill('Fictional synchronized tape');await measurement.getByRole('button',{name:'Save measurement',exact:true}).click();await pa.getByRole('region',{name:'Measurement records'}).getByText('80 cm',{exact:true}).waitFor();
  diag.step('L57 A: project goal');await pa.getByRole('link',{name:'Today',exact:true}).first().click();await pa.locator('.today-hero').getByRole('button',{name:'+ Quick add',exact:true}).click();await pa.getByRole('navigation',{name:'Quick add actions'}).getByRole('link').filter({hasText:'Goal'}).click();await pa.getByLabel('Goal name',{exact:true}).fill('Fictional encrypted project');await pa.getByRole('radio',{name:'Project',exact:true}).check();await pa.getByLabel('Milestones, one per line').fill('Read evidence\nReview');for(let i=0;i<3;i++)await pa.getByRole('button',{name:'Continue →'}).click();await pa.getByRole('button',{name:'Create goal',exact:true}).click();await pa.getByTestId('tracked-progress').waitFor();
  diag.step('L58 A: Today widget');await pa.getByRole('link',{name:'Today',exact:true}).first().click();await pa.getByRole('button',{name:'Customize Today',exact:true}).click();await pa.getByRole('button',{name:'Add widget',exact:true}).click();const editor=pa.getByRole('dialog',{name:'Add a widget'});await editor.getByRole('group',{name:'Choose a metric'}).getByRole('button',{name:'Water today',exact:true}).click();await editor.getByText('Title and display size').click();await editor.getByLabel('Card title (optional)').fill('Fictional synced nutrition');await editor.getByRole('button',{name:'Save widget'}).click();try{await pa.getByRole('article',{name:'Fictional synced nutrition',exact:true}).waitFor({timeout:7000});}catch(e){console.log('Widget save diagnostics',await pa.locator('[role=alert]').allTextContents(),await pa.locator('[role=status]').allTextContents());throw e;}
  diag.step('L59 A: Sync now');await pa.getByRole('link',{name:'Settings',exact:true}).first().click();const fresh5=await arm(pa);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa,fresh5);
  diag.step('L60 B: sign in, unlock, sync');await login(pb);await pb.getByLabel('Sync my Health records with this account.',{exact:false}).check();await pb.getByLabel('Vault recovery secret',{exact:true}).fill(recovery);const fresh6=await arm(pb);await pb.getByRole('button',{name:'Unlock account vault',exact:true}).click();await synced(pb,fresh6);
  diag.step('L61 B: sees widget');await pb.getByRole('link',{name:'Today',exact:true}).first().click();/* Session U follow-up F3: on this phone the card is a row named by it; open it. */await pb.getByRole('button',{name:'Fictional synced nutrition',exact:true}).click();await pb.getByRole('article',{name:'Fictional synced nutrition',exact:true}).waitFor();
  diag.step('L62 B: sees meal');await pb.getByRole('link',{name:'Health',exact:true}).first().click();await pb.getByRole('region',{name:'Breakfast diary'}).getByText('Fictional encrypted oats',{exact:true}).waitFor();
  diag.step('L63 B: corrects measurement');await pb.getByRole('button',{name:'Measurements',exact:true}).click();await pb.getByLabel('Measurement history type',{exact:true}).selectOption('waist');await pb.getByRole('region',{name:'Measurement records'}).getByText('80 cm',{exact:true}).waitFor();await pb.getByRole('button',{name:'Correct measurement',exact:true}).click();await pb.getByRole('form',{name:'Body measurement entry'}).getByLabel('Measurement value',{exact:true}).fill('79');await pb.getByRole('button',{name:'Save measurement',exact:true}).click();await pb.getByRole('region',{name:'Measurement records'}).getByText('79 cm',{exact:true}).waitFor();
  diag.step('L64 B: sees goal');await pb.getByRole('link',{name:'Goals',exact:true}).first().click();await pb.getByRole('heading',{name:'Fictional encrypted project',exact:true}).waitFor();
  diag.step('L65 B: sees habits');await pb.getByRole('link',{name:'Habits',exact:true}).first().click();await pb.getByRole('article',{name:'Fictional synchronized reading',exact:true}).waitFor();await pb.getByRole('article',{name:'Fictional local before sign-in',exact:true}).waitFor();
  diag.step('L66 B: completes habit');await pb.getByRole('article',{name:'Fictional synchronized reading',exact:true}).getByRole('button',{name:'Complete Fictional synchronized reading',exact:true}).click();
  diag.step('L67 B: Sync now');await pb.getByRole('link',{name:'Settings',exact:true}).first().click();const fresh7=await arm(pb);await pb.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pb,fresh7);
  diag.step('L68 A: Sync now, sees completion');const fresh8=await arm(pa);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa,fresh8);await pa.getByRole('link',{name:'Habits',exact:true}).first().click();await pa.getByRole('article',{name:'Fictional synchronized reading',exact:true}).getByRole('button',{name:'Undo completion for Fictional synchronized reading',exact:true}).waitFor();
  // Cold reload requires the separate vault secret; accepted account data survives.
  diag.step('L70 B: reload and unlock');await pb.reload();await pb.getByLabel('Vault recovery secret',{exact:true}).fill(recovery);await pb.getByLabel('Sync my Health records with this account.',{exact:false}).check();const fresh9=await arm(pb);await pb.getByRole('button',{name:'Unlock account vault',exact:true}).click();await synced(pb,fresh9);
  // Open and unlock each domain before going offline; no offline shell/navigation claim.
  diag.step('L72 A2/B2: second tabs unlock');const ha=await a.newPage(),hb=await b.newPage();diag.watchPage(ha,'A2');diag.watchPage(hb,'B2');for(const page of [ha,hb]){await page.goto(origin+'/app/settings');await page.getByLabel('Sync my Health records with this account.',{exact:false}).check();await page.getByLabel('Vault recovery secret',{exact:true}).fill(recovery);const fresh10=await arm(page);await page.getByRole('button',{name:'Unlock account vault',exact:true}).click();await synced(page,fresh10);await page.getByRole('link',{name:'Habits',exact:true}).first().click();await page.getByRole('button',{name:'+ New habit',exact:true}).waitFor();}
  // Activating a second tab intentionally locks peers; reload and explicitly unlock them again.
  diag.step('L74 A/B: reload and unlock again');for(const page of [pa,pb]){await page.goto(origin+'/app/settings');await page.getByLabel('Sync my Health records with this account.',{exact:false}).check();await page.getByLabel('Vault recovery secret',{exact:true}).fill(recovery);const fresh11=await arm(page);await page.getByRole('button',{name:'Unlock account vault',exact:true}).click();await synced(page,fresh11);}
  // Two independent offline app edits merge by their stable water-entry identities.
  diag.step('L76 A/B: Health, both offline');for(const page of [pa,pb]){await page.getByRole('link',{name:'Health',exact:true}).first().click();await page.getByRole('button',{name:'Add 250 mL',exact:true}).waitFor();}await a.setOffline(true);await b.setOffline(true);
  diag.step('L77 A/B: offline water');await pa.getByRole('button',{name:'Add 250 mL',exact:true}).click();await pa.getByRole('region',{name:'Water journal'}).getByText('250 mL recorded',{exact:false}).waitFor();await pb.getByRole('button',{name:'Add 500 mL',exact:true}).click();await pb.getByRole('region',{name:'Water journal'}).getByText('500 mL recorded',{exact:false}).waitFor();
  diag.step('L78 A/B: offline settings and habits');for(const [page,habitPage,title]of [[pa,ha,'Offline Habit A'],[pb,hb,'Offline Habit B']]){await page.getByRole('button',{name:'Journal settings',exact:true}).click();if(page===pa)await page.getByLabel('Preferred weight unit').selectOption('lb');else await page.getByLabel('Personal water target (mL, optional)',{exact:true}).fill('2500');await page.getByRole('button',{name:'Save journal preferences',exact:true}).click();await page.getByText('Journal preferences saved. Existing entry dates are unchanged.',{exact:true}).waitFor();await habitPage.getByRole('button',{name:'+ New habit',exact:true}).click();await habitPage.getByLabel('Start from template').selectOption('read');await habitPage.getByLabel('Habit title',{exact:true}).fill(title);await habitPage.getByRole('button',{name:'Create habit',exact:true}).click();await habitPage.getByRole('article',{name:title,exact:true}).waitFor();}
  diag.step('L79 close second tabs');await ha.close();await hb.close();
  diag.step('L80 reconnect in test order and sync');for(const [context,page]of order==='a-first'?[[a,pa],[b,pb]]:[[b,pb],[a,pa]]){await context.setOffline(false);await page.getByRole('link',{name:'Settings',exact:true}).first().click();const fresh12=await arm(page);await page.getByRole('button',{name:'Sync now',exact:true}).click();await synced(page,fresh12);}
  diag.step('L81 A/B: sync, water 750 mL');for(const page of [pa,pb]){const fresh13=await arm(page);await page.getByRole('button',{name:'Sync now',exact:true}).click();await synced(page,fresh13);await page.getByRole('link',{name:'Health',exact:true}).first().click();await page.getByRole('region',{name:'Water journal'}).getByText('750 mL recorded',{exact:false}).waitFor();await page.getByRole('link',{name:'Settings',exact:true}).first().click();}
  diag.step('L82 A/B: habits and settings merged');for(const page of [pa,pb]){await page.getByRole('link',{name:'Habits',exact:true}).first().click();for(const title of ['Offline Habit A','Offline Habit B'])await page.getByRole('article',{name:title,exact:true}).waitFor();await page.getByRole('link',{name:'Health',exact:true}).first().click();await page.getByRole('button',{name:'Journal settings',exact:true}).click();expect(await page.getByLabel('Preferred weight unit').inputValue()).toBe('lb');expect(await page.getByLabel('Personal water target (mL, optional)',{exact:true}).inputValue()).toBe('2500');await page.getByRole('link',{name:'Settings',exact:true}).first().click();}
  diag.step('L83 A: measurement history');await pa.getByRole('link',{name:'Health',exact:true}).first().click();await pa.getByRole('button',{name:'Measurements',exact:true}).click();await pa.getByLabel('Measurement history type',{exact:true}).selectOption('waist');await pa.getByRole('region',{name:'Measurement records'}).getByText('79 cm',{exact:true}).waitFor();await pa.getByRole('region',{name:'Measurement records'}).getByText('Record history',{exact:true}).click();await pa.getByText(/Previous: 80 cm/).waitFor();
  // Concurrent corrections keep both readings until an explicit protected review.
  diag.step('L85 A/B: open measurements');for(const page of [pa,pb]){await page.getByRole('link',{name:'Health',exact:true}).first().click();await page.getByRole('button',{name:'Measurements',exact:true}).click();await page.getByLabel('Measurement history type',{exact:true}).selectOption('waist');}
  diag.step('L86 both offline');await a.setOffline(true);await b.setOffline(true);
  diag.step('L87 A/B: concurrent corrections offline');for(const [page,value]of [[pa,'78'],[pb,'77']]){await page.getByRole('button',{name:'Correct measurement',exact:true}).click();const form=page.getByRole('form',{name:'Body measurement entry'});await form.getByLabel('Measurement value',{exact:true}).fill(value);await form.getByRole('button',{name:'Save measurement',exact:true}).click();}
  diag.step('L88 A online and sync; B online, conflict');await a.setOffline(false);await pa.getByRole('link',{name:'Settings',exact:true}).first().click();const fresh14=await arm(pa);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa,fresh14);await b.setOffline(false);await pb.getByRole('link',{name:'Settings',exact:true}).first().click();await pb.getByRole('button',{name:'Sync now',exact:true}).click();await pb.getByRole('alert').filter({hasText:'Conflicting'}).waitFor();
  diag.step('L89 B: prepare conflict review, download');await pb.getByText('Review conflicting account records',{exact:true}).click();await pb.getByRole('button',{name:'Prepare conflict review',exact:true}).click();await pb.getByLabel('Conflict recovery secret',{exact:true}).waitFor();const conflictSecret=await pb.getByLabel('Conflict recovery secret',{exact:true}).inputValue();await pb.getByLabel('I saved the conflict recovery secret separately.').check();const conflictDownload=pb.waitForEvent('download');await pb.getByRole('button',{name:'Download both conflict copies',exact:true}).click();let conflictBytes='';for await(const chunk of await (await conflictDownload).createReadStream())conflictBytes+=chunk.toString();const conflictData=JSON.parse((await decryptBackup(conflictBytes,conflictSecret)).settings);expect(conflictData.local.health).toContain('77000');expect(conflictData.cloud.health).toContain('78000');
  diag.step('L90 B: confirm reviewed resolution; A syncs');const choices=pb.getByLabel(/^Choose value for /);for(let i=0;i<await choices.count();i++)await choices.nth(i).selectOption('cloud');await pb.getByLabel('Conflict confirmation',{exact:true}).fill('RESOLVE RECORDS');const fresh15=await arm(pb);await pb.getByRole('button',{name:'Confirm reviewed resolution',exact:true}).click();await synced(pb,fresh15);const fresh16=await arm(pa);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa,fresh16);
  diag.step('L91 A: sees resolved 78 cm');await pa.getByRole('link',{name:'Health',exact:true}).first().click();await pa.getByRole('button',{name:'Measurements',exact:true}).click();await pa.getByLabel('Measurement history type',{exact:true}).selectOption('waist');await pa.getByRole('region',{name:'Measurement records'}).getByText('78 cm',{exact:true}).waitFor();await pa.getByRole('region',{name:'Measurement records'}).getByText('Record history',{exact:true}).click();await pa.getByText(/Previous: 77 cm/).waitFor();
  // Exercise the installed UI's forward-recovery path against a persisted older-policy journal.
  diag.step('L93 A: Sync now');await pa.getByRole('link',{name:'Settings',exact:true}).first().click();const fresh17=await arm(pa);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa,fresh17);
  diag.step('L94 A: plant older-policy journal');const obsolete=await pa.evaluate(async account=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('zigoals-account-sync-v1',2);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),r=store.get(account);r.onsuccess=()=>{const value=r.result,operation=crypto.randomUUID();value.pending={protocol:1,vault:'00000000-0000-4000-8000-000000000099',operation,base:value.revision,changes:[]};value.pendingPolicy=1;store.put(value,account);tx.oncomplete=()=>resolve(operation);};tx.onerror=()=>reject(tx.error);});}finally{db.close();}},account);
  // Bind the fictional older operation to this actual vault, without reading secret material.
  diag.step('L96 read vault before recovery');const tokenBeforeRecovery=(await a.cookies(origin+'/api/private-account')).find(c=>c.name==='zigoals_session').value;const vaultBeforeRecovery=await (await mf.dispatchFetch('https://fixture.workers.dev/v1/vault',{headers:{origin,authorization:'Bearer '+tokenBeforeRecovery,'x-zigoals-account':account}})).json();
  diag.step('L97 bind pending to vault');await pa.evaluate(async({account,vault})=>{const db=await new Promise(resolve=>{const r=indexedDB.open('zigoals-account-sync-v1',2);r.onsuccess=()=>resolve(r.result);});await new Promise(resolve=>{const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),r=store.get(account);r.onsuccess=()=>{const value=r.result;value.pending.vault=vault;store.put(value,account);};tx.oncomplete=resolve;});db.close();},{account,vault:vaultBeforeRecovery.manifest.vault});
  diag.step('L98 A: Sync now, older policy alert');await pa.getByRole('button',{name:'Sync now',exact:true}).click();await pa.getByRole('alert').filter({hasText:'older sync policy'}).waitFor();
  diag.step('L99 A: forward recovery review');await pa.getByText('Repair a blocked sync queue',{exact:true}).click();await pa.getByRole('button',{name:'Prepare forward recovery review',exact:true}).click();await pa.getByLabel('Forward recovery secret',{exact:true}).waitFor();const forwardSecret=await pa.getByLabel('Forward recovery secret',{exact:true}).inputValue();await pa.getByLabel('I saved the forward recovery secret separately.').check();const forwardDownload=pa.waitForEvent('download');await pa.getByRole('button',{name:'Download forward recovery copy',exact:true}).click();let forwardBytes='';for await(const chunk of await (await forwardDownload).createReadStream())forwardBytes+=chunk.toString();expect(JSON.parse((await decryptBackup(forwardBytes,forwardSecret)).settings).journal.pending.operation).toBe(obsolete);
  diag.step('L100 A: confirm forward recovery');await pa.getByLabel('Recovery confirmation',{exact:true}).fill('RECOVER QUEUE');const fresh18=await arm(pa);await pa.getByRole('button',{name:'Confirm forward recovery',exact:true}).click();await synced(pa,fresh18);expect(sentOperations).not.toContain(obsolete);
  // Rotation is a real UI → account adapter → persistent Worker journey.
  diag.step('L102 A: Sync now');await pa.getByRole('link',{name:'Settings',exact:true}).first().click();const fresh19=await arm(pa);await pa.getByRole('button',{name:'Sync now',exact:true}).click();await synced(pa,fresh19);
  diag.step('L103 A: prepare key rotation');await pa.getByText('Rotate vault encryption',{exact:true}).click();await pa.getByRole('button',{name:'Prepare key rotation',exact:true}).click();
  diag.step('L104 A: new rotation secret');const nextRecovery=await pa.getByLabel('New rotation recovery secret',{exact:true}).inputValue();expect(nextRecovery).not.toBe(recovery);
  diag.step('L105 A: activate new key');await pa.getByLabel('I saved the new rotation recovery secret separately.').check();await pa.getByRole('button',{name:'Activate new vault key',exact:true}).click();await pa.getByText(/Vault key rotated and activated/).waitFor();
  diag.step('L106 B: Sync now, vault changed');await pb.getByRole('button',{name:'Sync now',exact:true}).click();await pb.getByRole('alert').filter({hasText:'Account or vault changed'}).waitFor();
  diag.step('L107 B: reload, old secret fails');await pb.reload();await pb.getByLabel('Vault recovery secret',{exact:true}).fill(recovery);await pb.getByRole('button',{name:'Unlock account vault',exact:true}).click();await pb.getByRole('alert').filter({hasText:'Unlock or integrity check failed'}).waitFor();
  diag.step('L108 B: unlock with new secret');await pb.getByLabel('Vault recovery secret',{exact:true}).fill(nextRecovery);await pb.getByLabel('Sync my Health records with this account.',{exact:false}).check();const fresh20=await arm(pb);await pb.getByRole('button',{name:'Unlock account vault',exact:true}).click();await synced(pb,fresh20);
  diag.step('L109 B: water 750 mL after rotation');await pb.getByRole('link',{name:'Health',exact:true}).first().click();await pb.getByRole('region',{name:'Water journal'}).getByText('750 mL recorded',{exact:false}).waitFor();await pb.getByRole('link',{name:'Settings',exact:true}).first().click();
  // Selected-domain deletion is a backed-up UI choice; a stale client cannot restore it implicitly.
  diag.step('L111 A: review section deletion');await pa.getByText('Cloud copies by section',{exact:true}).click();await pa.getByRole('button',{name:'Review section deletion',exact:true}).click();
  diag.step('L112 A: section recovery secret');const sectionSecret=await pa.getByLabel('Section recovery secret',{exact:true}).inputValue();await pa.getByLabel('I saved this section recovery secret separately.').check();
  diag.step('L113 A: download section copy');const sectionDownload=pa.waitForEvent('download');await pa.getByRole('button',{name:'Download section recovery copy',exact:true}).click();let sectionBytes='';for await(const chunk of await (await sectionDownload).createReadStream())sectionBytes+=chunk.toString();const sectionArchive=JSON.parse((await decryptBackup(sectionBytes,sectionSecret)).settings);expect(sectionArchive.local.health).toContain('Fictional encrypted oats');expect(sectionArchive.cloud.health).toContain('Fictional encrypted oats');
  diag.step('L114 A: delete section');await pa.getByLabel('Section confirmation',{exact:true}).fill('DELETE SECTION');await pa.getByRole('button',{name:'Confirm section deletion',exact:true}).click();await pa.getByText(/Cloud section deleted. Local records were kept/).waitFor();
  diag.step('L115 B: Sync now, section deleted');await pb.getByRole('button',{name:'Sync now',exact:true}).click();await pb.getByRole('alert').filter({hasText:'Health cloud copy was deleted'}).waitFor();
  diag.step('L116 A: review restoring section');await pa.getByRole('button',{name:'Review restoring local section',exact:true}).click();await pa.getByLabel('Section recovery secret',{exact:true}).waitFor();await pa.getByLabel('I saved this section recovery secret separately.').check();
  diag.step('L117 A: confirm section restore');const restoreDownload=pa.waitForEvent('download');await pa.getByRole('button',{name:'Download section recovery copy',exact:true}).click();await restoreDownload;await pa.getByLabel('Section confirmation',{exact:true}).fill('RESTORE SECTION');const fresh21=await arm(pa);await pa.getByRole('button',{name:'Confirm section restore',exact:true}).click();await synced(pa,fresh21);
  // The second client explicitly accepts the restored, identical cloud generation before auto-sync resumes.
  diag.step('L119 B: accept restored section');await pb.getByText('Cloud copies by section',{exact:true}).click();await pb.getByRole('button',{name:'Review restoring local section',exact:true}).click();await pb.getByLabel('Section recovery secret',{exact:true}).waitFor();await pb.getByLabel('I saved this section recovery secret separately.').check();const secondRestore=pb.waitForEvent('download');await pb.getByRole('button',{name:'Download section recovery copy',exact:true}).click();await secondRestore;await pb.getByLabel('Section confirmation',{exact:true}).fill('RESTORE SECTION');const fresh22=await arm(pb);await pb.getByRole('button',{name:'Confirm section restore',exact:true}).click();await synced(pb,fresh22);
  diag.step('L120 read token');const tokenA=(await a.cookies(origin+'/api/private-account')).find(c=>c.name==='zigoals_session').value;
  diag.step('L121 cloud holds ciphertext only');const raw=await (await mf.dispatchFetch('https://fixture.workers.dev/v1/vault',{headers:{origin,authorization:'Bearer '+tokenA,'x-zigoals-account':account}})).text();for(const marker of ['Fictional synchronized reading','Fictional encrypted oats','Fictional encrypted project','Fictional synced nutrition'])expect(raw).not.toContain(marker);expect(JSON.parse(raw).records.length).toBeGreaterThan(1);
  diag.step('L122 A: sign out all other devices');await pa.getByRole('link',{name:'Settings',exact:true}).first().click();await pa.getByRole('button',{name:'Refresh sessions',exact:true}).click();await pa.getByRole('button',{name:'Sign out all other devices…',exact:true}).click();await pa.getByRole('button',{name:'Sign out all other devices',exact:true}).click();await pa.getByRole('region',{name:'Account sessions',exact:true}).getByText('1 session(s) revoked.',{exact:false}).waitFor();
  diag.step('L123 B: access changed');await pb.bringToFront();await pb.evaluate(()=>window.dispatchEvent(new Event('focus')));await pb.getByRole('region',{name:'Encrypted account sync',exact:true}).getByText('Account access changed. Sign in and unlock again.',{exact:true}).waitFor();expect(await pb.getByRole('button',{name:'Sync now',exact:true}).count()).toBe(0);
  diag.step('L124 A: prepare deletion backup');const deletion=pa.getByRole('region',{name:'Account deletion',exact:true});await deletion.getByRole('button',{name:'Prepare backup before deletion'}).click();await deletion.getByLabel('Deletion backup recovery secret',{exact:true}).waitFor();
  diag.step('L125 A: deletion secret');const deletionSecret=await deletion.getByLabel('Deletion backup recovery secret',{exact:true}).inputValue();await deletion.getByLabel('I saved the deletion backup secret separately.').check();
  diag.step('L126 A: download deletion copy');const deletionDownload=pa.waitForEvent('download');await deletion.getByRole('button',{name:'Download deletion recovery copy'}).click();const deletionFile=await deletionDownload;let deletionBytes='';for await(const chunk of await deletionFile.createReadStream())deletionBytes+=chunk.toString();expect((await decryptBackup(deletionBytes,deletionSecret)).health).toContain('Fictional encrypted oats');
  diag.step('L127 A: delete cloud data');await deletion.getByLabel('Deletion confirmation',{exact:true}).fill('DELETE CLOUD DATA');await deletion.getByRole('button',{name:'Confirm cloud deletion',exact:true}).click();await deletion.getByRole('status').filter({hasText:'Cloud vault deleted and stale access blocked'}).waitFor();
  diag.step('L128 vault gone (410)');expect((await mf.dispatchFetch('https://fixture.workers.dev/v1/vault',{headers:{origin,authorization:'Bearer '+tokenA,'x-zigoals-account':account}})).status).toBe(410);
  diag.step('L129 A: habits page');await pa.goto(origin+'/app/habits');expect(await pa.getByRole('article',{name:'Fictional synchronized reading',exact:true}).count()).toBe(0);
  diag.step('L130 A: sign out');await pa.goto(origin+'/app/settings');await pa.getByRole('button',{name:'Sign out',exact:true}).click();await pa.getByRole('link',{name:'Habits',exact:true}).first().click();await pa.getByRole('article',{name:'Fictional local before sign-in',exact:true}).waitFor();expect(await pa.getByRole('article',{name:'Fictional synchronized reading',exact:true}).count()).toBe(0);
  await a.close();await b.close();
 }catch(error){await diag.print(order,error).catch(e=>console.log('[account-browser] diagnostics failed:',e?.message));throw error;}finally{await browser.close();await mf.dispose();}
},90000);
