import {type Page} from '@playwright/test';
import {applyLocal,initialLedger} from '../lib/local-ledger';
import {emptyPlatform,positionSchema,privateGoalSchema} from '../lib/positions';
import {nativeZigIdentity} from '../lib/market-quotes';
const quote=()=>({base:nativeZigIdentity,currency:'USD',price:'43',priceDecimals:3,source:'CoinGecko',providerAssetId:'zignaly',observedAt:new Date().toISOString(),verification:'VERIFIED'});
export async function seed(page:Page){
 await page.route('**/api/market-quotes*',route=>route.fulfill({json:{quote:quote()}}));
 await page.goto('/app/goals');
 const now=new Date().toISOString();
 const data={...emptyPlatform(),positions:['a','b'].map(id=>positionSchema.parse({id,providerId:'native-zig',sourceType:'NATIVE_STAKING',network:'zigchain-1',account:'fictional-account',asset:'ZIG',denom:'uzig',decimals:6,quantity:'263000000000',verification:'VERIFIED_READ_ONLY',sync:'CURRENT',observedAt:now,liquidity:'BONDED',provenance:'Fictional acceptance fixture',validator:{address:`fictional-validator-${id}`,name:`Example validator ${id.toUpperCase()}`,status:'BONDED',commission:'0.05',votingTokens:'263000000000'}})),goals:[['81','ZIG destination','QUANTITY'],['82','Financial Freedom','VALUE'],['83','Learning journey','PROJECT']].map(([id,name,type])=>privateGoalSchema.parse({id,name,type,status:'active',asset:type==='VALUE'?'USD':'ZIG',denom:type==='VALUE'?'fiat:USD':'azig',decimals:type==='VALUE'?2:type==='PROJECT'?0:18,target:type==='VALUE'?'50000000':'300000000000000000000000',notes:'Fictional owner acceptance',createdAt:now,milestones:type==='PROJECT'?[{id:'read',title:'Read a book',done:false}]:[],plan:type==='VALUE'?{amount:'50000',asset:'USD',decimals:2,cadence:'monthly',nextDate:'2027-01-01',active:true}:undefined})),allocations:[{goalId:'81',positionId:'a',quantity:'263000000000'},{goalId:'82',positionId:'b',quantity:'263000000000'}],watchScope:{network:'zigchain-1',account:'fictional-account'},aprAssumptions:[{network:'zigchain-1',account:'fictional-account',percent:'6'}]};
 await page.evaluate(({data,q,ledger,metadata})=>{localStorage.setItem('zigoals:platform:v1',JSON.stringify(data));localStorage.setItem('zigoals:public-market-quotes:v1',JSON.stringify(q));localStorage.setItem('zigoals:local-ledger:v1',JSON.stringify(ledger));localStorage.setItem('zigoals:metadata:v1:local-simulation:local-demo-user',JSON.stringify(metadata));},{data,q:quote(),ledger:applyLocal(applyLocal(initialLedger(),{kind:'create'},'2026-09-17T00:00:00.000Z'),{kind:'deposit',id:'1',amount:'100000000000000000000'},'2026-09-17T00:00:00.000Z'),metadata:{schemaVersion:1,chainId:'local-simulation',walletAddress:'local-demo-user',goals:{'1':{name:'Kyoto in spring',category:'Travel',targetValue:'1200',currency:'ZIG',targetDate:'2027-09-18',startingAmount:'0',monthlyContribution:'100',riskPreference:'Conservative',liquidityPreference:'Anytime',deadlineFlexible:false,notes:''}}}});
 await page.reload();await page.emulateMedia({reducedMotion:'reduce'});
}
