import {test,expect,type Page} from '@playwright/test';
import {seed} from './coherence-fixture';
import {createHabit,emptyHabitData,logHabitCount} from '../lib/habits';
test.beforeEach(async({page})=>{await page.route('**/api/market-assets',route=>route.fulfill({json:{assets:[]}}));});
async function shot(page:Page,name:string){if(process.env.COHERENCE_CAPTURE==='1')await page.screenshot({path:`../../docs/verification/run8-1-coherence/screenshots/${name}.png`,fullPage:true,animations:'disabled'});}
test('release, reallocate, pin, lock and delete preserve wealth and Habit history',async({page})=>{
 await seed(page);let habits=createHabit(emptyHabitData(),{title:'Keep my history',category:'Goals',description:'',notes:'',goalLink:{chainId:'private',owner:'local',goalId:'81'},schedule:{kind:'weekdays',days:[0,1,2,3,4,5,6]},target:1});
 habits=logHabitCount(habits,habits.habits[0]!.id,new Date().toLocaleDateString('en-CA'),1);
 await page.evaluate(h=>localStorage.setItem('zigoals:habits:v1',JSON.stringify(h)),habits);
 await page.goto('/app/goals/tracked/81');await page.locator('#allocate > summary').click();await shot(page,'04-edit-release');
 await page.getByRole('button',{name:'Release allocation',exact:true}).click();await page.getByRole('button',{name:'Confirm release'}).click();await expect(page.locator('#allocate')).toContainText('No allocation yet');
 await page.goto('/app/goals/tracked/82#allocate');await page.locator('#allocate .picker-existing').getByRole('button',{name:/native-zig.*263000 ZIG/}).first().click();await expect(page.locator('#allocate')).toContainText('Available for this Goal: 263000 ZIG');await shot(page,'05-released-available');await page.getByLabel('Allocation quantity').fill('263000');await page.getByRole('button',{name:'Save allocation',exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('$22618');
 await page.getByLabel('Goal actions').click();await shot(page,'03-goal-actions');await page.getByRole('button',{name:'Pin Goal',exact:true}).click();await page.getByRole('button',{name:'Lock editing',exact:true}).click();await expect(page.getByRole('button',{name:'Delete Goal',exact:true})).toBeDisabled();await expect(page.getByLabel('Allocation quantity').last()).toBeDisabled();await page.reload();await page.getByLabel('Goal actions').click();await page.getByRole('button',{name:'Unlock editing',exact:true}).click();
 await page.goto('/app/goals');await expect(page.locator('.unified-goal-card').first()).toHaveAttribute('data-goal-key','private:82');await page.goto('/app');await expect(page.locator('.today-goals .unified-goal-card').first()).toHaveAttribute('data-goal-key','private:82');
 await page.goto('/app/goals/tracked/81');await page.getByLabel('Goal actions').click();await page.getByRole('button',{name:'Delete Goal',exact:true}).click();await page.getByRole('button',{name:'Confirm delete'}).click();await expect(page).toHaveURL(/\/app\/goals$/);
 const saved=await page.evaluate(()=>({p:JSON.parse(localStorage.getItem('zigoals:platform:v1')!),h:JSON.parse(localStorage.getItem('zigoals:habits:v1')!)}));expect(saved.p.positions).toHaveLength(2);expect(saved.p.goals.some((g:{id:string})=>g.id==='81')).toBe(false);expect(saved.h.habits).toEqual(habits.habits.map(h=>{const copy={...h};delete copy.goalLink;return copy;}));
});
test('legacy overview keeps optional simulation recoverable and archives safely',async({page})=>{
 await seed(page);await page.goto('/app/goals/1');await expect(page.locator('.goal-detail-overview')).toContainText('Kyoto in spring');await expect(page.getByRole('button',{name:'Add funds',exact:true})).not.toBeVisible();await shot(page,'02-legacy-detail');await page.locator('#local-simulation > summary').click();await expect(page.getByRole('button',{name:'Add funds',exact:true})).toBeVisible();const before=await page.evaluate(()=>localStorage.getItem('zigoals:local-ledger:v1'));await page.getByLabel('Goal actions').click();await page.getByRole('button',{name:'Remove Goal from ZIGoals'}).click();await page.getByRole('button',{name:'Confirm removal'}).click();await expect(page.locator('[data-goal-key="legacy:1"]')).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('zigoals:local-ledger:v1'))).toBe(before);await page.goto('/app/goals/1');await page.getByRole('button',{name:'Restore Goal to ZIGoals'}).click();await expect(page.getByRole('button',{name:'Restore Goal to ZIGoals'})).toHaveCount(0);await page.goto('/app/goals');await expect(page.locator('[data-goal-key="legacy:1"]')).toBeVisible();
});
test('manual selector creates a cash Position and allocates its value on Goal creation',async({page})=>{
 await seed(page);await page.goto('/app/goals/new');await page.getByLabel('Goal name',{exact:true}).fill('Manual wealth destination');await page.getByRole('radio',{name:'Value',exact:true}).check();await page.getByLabel('Target amount',{exact:true}).fill('1000');await page.getByRole('button',{name:'Continue'}).click();await shot(page,'08-manual-selector');await page.getByRole('button',{name:'Cash',exact:true}).click();await page.getByLabel('Asset name',{exact:true}).fill('Fictional cash');await page.getByLabel('Cash amount',{exact:true}).fill('500');await shot(page,'09-cash-expanded');await page.getByRole('button',{name:'Save asset for this Goal',exact:true}).click();await expect(page.getByLabel('Units to allocate')).toHaveValue('500');await page.getByRole('button',{name:'Precious metals',exact:true}).click();await page.getByRole('button',{name:'Use manual entry',exact:true}).click();await shot(page,'10-metal-expanded');await page.getByRole('button',{name:'Cash',exact:true}).click();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Continue'}).click();await expect(page.locator('.wizard')).toContainText('500 USD');await page.getByRole('button',{name:'Create goal',exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('$500');
});
test('deterministic smooth progress rings and responsive top-right wealth dashboard',async({page})=>{
 await seed(page);await page.setViewportSize({width:1440,height:1100});
 const palettes=()=>page.locator('.goal-progress-ring .flow-ring').evaluateAll(nodes=>nodes.map(n=>getComputedStyle(n).backgroundImage));
 await expect(page.locator('.goal-progress-ring .flow-ring')).toHaveCount(4);const first=await palettes();expect(first.every(background=>background.includes('conic-gradient'))).toBe(true);expect(new Set(first).size).toBe(4);await page.reload();expect(await palettes()).toEqual(first);await shot(page,'01-nebula-goals');
 await page.goto('/app/goals/positions');await expect(page.locator('.wallet-totals')).toContainText('526000');const metric=await page.locator('.position-metrics').boundingBox(),rail=await page.locator('.positions-rail').boundingBox();expect(Math.abs(metric!.y-rail!.y)).toBeLessThan(5);expect(rail!.x).toBeGreaterThan(metric!.x);await shot(page,'06-positions-top');await page.locator('#observed-positions-title').scrollIntoViewIfNeeded();await shot(page,'07-position-cards');
 for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:1000});for(const route of ['/app/goals','/app/goals/positions','/app/goals/new','/app/goals/1','/app/goals/tracked/82']){await page.goto(route);await expect(page.locator('main h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${route} at ${width}`).toBe(true);if(width===390&&route==='/app/goals')await shot(page,'11-goals-390');if(width===390&&route==='/app/goals/positions')await shot(page,'12-positions-390');if(width===390&&route==='/app/goals/new')await shot(page,'13-create-390');}}
});
