import { expect, test } from "@playwright/test";

test("saved meal, preview copy, water, planner and export work with fictional private records", async ({ page }) => {
  await page.goto("/app/health");
  await page.getByRole("button", { name: "Foods & recipes", exact: true }).click();
  await page.getByRole("button", { name: "New food", exact: true }).click();
  const food = page.getByRole("form", { name: "Food details" });
  for (const [label, value] of [["Food name", "Fictional breakfast oats"], ["Serving weight (g)", "40"], ["Calories (kcal)", "150"], ["Protein (g)", "5"], ["Carbs (g)", "27"], ["Fat (g)", "3"]]) await food.getByLabel(label!).fill(value!);
  await food.getByRole("button", { name: "Save food", exact: true }).click();
  await page.getByRole("button", { name: "Diary", exact: true }).click();
  await page.getByLabel("Journal date").fill("2026-09-23");
  const log = page.getByRole("form", { name: "Log a meal", exact: true });
  await log.getByLabel("Food or recipe").selectOption({ label: "Fictional breakfast oats · food" });
  await log.getByRole("button", { name: "Log to diary" }).click();
  await page.getByRole("button", { name: "Favorite Fictional breakfast oats", exact: true }).click();
  await page.getByRole("button", { name: "Favorites", exact: true }).click();
  await expect(page.getByRole("button", { name: /^Choose Fictional breakfast oats/ })).toBeVisible();
  await page.getByRole("button", { name: "Add 250 mL", exact: true }).click();
  await expect(page.getByRole("region", { name: "Water journal" })).toContainText("250 mL recorded");
  await page.getByRole("button", { name: "Meals & planning", exact: true }).click();
  const save = page.getByRole("form", { name: "Save a reusable meal" });
  await save.getByLabel("Saved meal name").fill("Morning bowl");
  await save.getByRole("button", { name: "Save meal", exact: true }).click();
  const copy = page.getByRole("form", { name: "Copy a meal" });
  await copy.getByLabel("Copy source").selectOption({ label: "Morning bowl" });
  await copy.getByLabel("Copy date 1").fill("2026-09-24");
  await copy.getByRole("button", { name: "Preview copy" }).click();
  await expect(page.getByRole("region", { name: "Copy preview" })).toContainText("2026-09-24");
  await page.getByRole("button", { name: "Confirm copy", exact: true }).click();
  const plan = page.getByRole("form", { name: "Plan a meal" });
  await plan.getByLabel("Planned saved meal").selectOption({ label: "Morning bowl" });
  await plan.getByLabel("Plan date").fill("2026-09-25");
  await plan.getByRole("button", { name: "Save plan" }).click();
  await page.getByLabel("Grocery end date").fill("2026-09-26");
  await expect(page.getByRole("region", { name: "Grocery list" })).toContainText("40 g");
  await page.reload();
  await page.getByLabel("Journal date").fill("2026-09-24");
  await expect(page.getByRole("region", { name: "Breakfast diary" })).toContainText("150 kcal");
  await page.getByRole("button", { name: "Meals & planning", exact: true }).click();
  await page.getByRole("button", { name: "Log planned Morning bowl" }).click();
  await page.getByRole("button", { name: "Diary", exact: true }).click();
  await page.getByLabel("Journal date").fill("2026-09-25");
  await expect(page.getByRole("region", { name: "Breakfast diary" })).toContainText("150 kcal");
  await page.getByRole("button", { name: "Journal settings", exact: true }).click();
  await page.getByLabel("I understand this CSV contains readable private Health data").check();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export Health CSV" }).click();
  expect((await download).suggestedFilename()).toMatch(/^zigoals-health-/);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test("label basis, gram entry, water corrections and preferred weight units preserve recorded values", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 });
  await page.goto("/app/health");
  await page.getByRole("button", { name: "Foods & recipes", exact: true }).click();
  await page.getByRole("button", { name: "New food", exact: true }).click();
  const food = page.getByRole("form", { name: "Food details" });
  for (const [label, value] of [["Food name", "Fictional hundred-gram label"], ["Serving weight (g)", "40"], ["Calories (kcal)", "375"], ["Protein (g)", "12.5"], ["Carbs (g)", "67.5"], ["Fat (g)", "7.5"]]) await food.getByLabel(label!).fill(value!);
  await food.getByLabel("Nutrition label basis").selectOption("100g");
  await food.getByRole("button", { name: "Save food", exact: true }).click();
  await page.getByRole("button", { name: "Diary", exact: true }).click();
  const log = page.getByRole("form", { name: "Log a meal", exact: true });
  await log.getByLabel("Food or recipe").selectOption({ label: "Fictional hundred-gram label · food" });
  await log.getByLabel("Quantity unit", { exact: true }).selectOption("grams");
  await log.getByLabel("Food weight (g)").fill("60");
  await log.getByRole("button", { name: "Log to diary" }).click();
  await expect(page.getByRole("region", { name: "Breakfast diary" })).toContainText("225 kcal");
  await page.getByRole("button", { name: "Add 250 mL", exact: true }).click();
  await page.getByRole("button", { name: "Edit water 250", exact: true }).click();
  await page.getByLabel("Water amount", { exact: true }).fill("300");
  await page.getByRole("button", { name: "Save water correction" }).click();
  await expect(page.getByRole("region", { name: "Water journal" })).toContainText("300 mL recorded");
  await page.getByRole("button", { name: "Journal settings", exact: true }).click();
  await page.getByLabel("Journal timezone", { exact: true }).fill("Europe/Brussels");
  await page.getByLabel("Preferred weight unit").selectOption("lb");
  await page.getByRole("button", { name: "Save journal preferences" }).click();
  await page.getByRole("button", { name: "Weight", exact: true }).click();
  await page.getByLabel("Weight (lb)", { exact: true }).fill("150");
  await page.getByRole("button", { name: "Save weight", exact: true }).click();
  await expect(page.getByRole("table", { name: "Weight history", exact: true })).toContainText("68.039 kg");
  await page.getByRole("button", { name: "Activity", exact: true }).click();
  const activity = page.getByRole("form", { name: "Manual activity", exact: true });
  await activity.getByLabel("Activity name").fill("Fictional walk");
  await activity.getByLabel("Steps", { exact: true }).fill("500");
  await activity.getByRole("button", { name: "Save activity" }).click();
  await page.getByRole("button", { name: "Edit activity Fictional walk" }).click();
  await activity.getByLabel("Steps", { exact: true }).fill("800");
  await activity.getByRole("button", { name: "Save correction" }).click();
  await expect(page.getByText("800 steps · 0 minutes", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test("Health daily panels reflow at phone tablet and desktop widths", async ({ page }, testInfo) => {
  const widths = [320, 360, 390, 430, 768, 1024, 1440];
  await page.goto("/app/health");
  await page.getByRole("button", { name: "Add 250 mL", exact: true }).click();
  for (const width of widths) {
    await page.setViewportSize({ width, height: 1000 });
    await expect(page.getByRole("region", { name: "Water journal" })).toContainText("250 mL recorded");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const controls = await page.locator('.health-content button:visible, .health-content input:visible').evaluateAll(nodes => nodes.map(node => { const r = node.getBoundingClientRect(); return { width: r.width, height: r.height, right: r.right, left: r.left }; }));
    expect(controls.every(r => r.width >= 30 && r.height >= 36 && r.left >= 0 && r.right <= width)).toBe(true);
    if ([320, 390, 1440].includes(width)) await page.screenshot({ path: `../../docs/run10/evidence/health-diary-${width}-${testInfo.project.name}.png`, fullPage: true });
  }
  await page.getByRole("button", { name: "Meals & planning", exact: true }).click();
  await page.setViewportSize({ width: 320, height: 1000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `../../docs/run10/evidence/health-planning-320-${testInfo.project.name}.png`, fullPage: true });
});
