import {test,expect} from '@playwright/test';
test.use({timezoneId:'Europe/Brussels'});
test('a future Habit target preserves today, and a saved duration timer survives reload and applies once',async({page},info)=>{
 await page.clock.install({time:new Date('2026-09-23T12:00:00Z')});await page.clock.setFixedTime(new Date('2026-09-23T12:00:00Z'));
 await page.goto('/app/habits');await page.getByRole('button',{name:'+ New habit',exact:true}).click();await page.getByLabel('Start from template').selectOption('read');await page.getByLabel('Habit title',{exact:true}).fill('Fictional reading session');await page.getByRole('button',{name:'Create habit',exact:true}).click();
 const card=page.getByRole('article',{name:'Fictional reading session',exact:true});
 await card.getByRole('button',{name:'Edit Fictional reading session'}).click();await page.getByLabel('Changes effective from').fill('2026-09-25');await page.getByLabel('Target value',{exact:true}).fill('60');await page.getByRole('button',{name:'Save habit',exact:true}).click();
 await expect(card.locator('.habit-count')).toContainText('/ 30 minutes');await expect(card).toContainText('Scheduled change from 2026-09-25');
 await page.clock.setFixedTime(new Date('2026-09-23T12:00:00Z'));await card.getByRole('button',{name:'Start timer',exact:true}).click();await expect(card.getByRole('button',{name:'Pause timer',exact:true})).toBeVisible();await page.clock.setFixedTime(new Date('2026-09-23T12:01:30Z'));await page.reload();await expect(card.getByRole('button',{name:'Pause timer',exact:true})).toBeVisible();await card.getByRole('button',{name:'Pause timer',exact:true}).click();
 await expect(card.getByRole('region',{name:'Saved timer'})).toContainText('1.5 minutes');await card.getByRole('button',{name:'Log reviewed duration',exact:true}).click();await expect(card.locator('.habit-count')).toContainText('1.5 / 30 minutes');await page.reload();await expect(card.locator('.habit-count')).toContainText('1.5 / 30 minutes');await expect(card.getByRole('button',{name:'Log reviewed duration',exact:true})).toHaveCount(0);
 await page.setViewportSize({width:320,height:900});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await card.screenshot({path:`../../docs/run10/evidence/habit-future-timer-320-${info.project.name}.png`});
});
test('cross-midnight timers retain evidence and require manual day review',async({page})=>{
 await page.clock.install({time:new Date('2026-09-23T21:59:00Z')});await page.clock.setFixedTime(new Date('2026-09-23T21:59:00Z'));await page.goto('/app/habits');await page.getByRole('button',{name:'+ New habit',exact:true}).click();await page.getByLabel('Start from template').selectOption('read');await page.getByLabel('Habit title',{exact:true}).fill('Fictional midnight reading');await page.getByRole('button',{name:'Create habit',exact:true}).click();
 const card=page.getByRole('article',{name:'Fictional midnight reading',exact:true});await page.clock.setFixedTime(new Date('2026-09-23T21:59:00Z'));await card.getByRole('button',{name:'Start timer',exact:true}).click();await expect(card.getByRole('button',{name:'Pause timer',exact:true})).toBeVisible();await page.clock.setFixedTime(new Date('2026-09-23T22:01:00Z'));await card.getByRole('button',{name:'Pause timer',exact:true}).click();
 await expect(card.getByRole('region',{name:'Saved timer'})).toContainText('calendar day');await expect(card.getByRole('button',{name:'Log reviewed duration',exact:true})).toBeDisabled();await page.reload();await expect(card.getByRole('region',{name:'Saved timer'})).toContainText('calendar day');await expect(card.locator('.habit-count')).toContainText('0 / 30 minutes');
});
