import {test,expect} from '@playwright/test';
import {createEmptyHealth,saveFood,logHealthItem} from '../lib/health';
test('optional nutrients remain explicit, partial per-meal/day totals survive reload, and old snapshots stay unchanged',async({page})=>{
 const at='2026-09-20T00:00:00Z',date='2026-09-20';let data=createEmptyHealth();
 for(let i=0;i<2;i++){const id='health_food000'+i;data=saveFood(data,{id,name:'Fictional food '+i,brand:'',servingGrams:100,nutrients:{kcal:100,proteinMg:1000,carbsMg:2000,fatMg:3000,...(i===0?{fiberMg:1250,sodiumMg:0}:{})},createdAt:at,updatedAt:at});data=logHealthItem(data,{id:'health_diary00'+i,sourceId:id,sourceKind:'food',date,meal:'Breakfast',quantityMilli:1000},at);}
 await page.addInitScript(data=>{if(!sessionStorage.getItem('run11-nutrients')){localStorage.setItem('zigoals:health:v1',JSON.stringify(data));sessionStorage.setItem('run11-nutrients','1');}},data);
 await page.goto('/app/health');await page.getByLabel('Journal date',{exact:true}).fill(date);const meal=page.getByRole('region',{name:'Breakfast diary'});await meal.getByText('Breakfast nutrient totals',{exact:true}).click();await expect(meal).toContainText('1.25 g · partial (1 of 2 entries)');await expect(meal).toContainText('0 mg · partial (1 of 2 entries)');await expect(meal).toContainText('Not provided');
 await page.getByText('Daily nutrient details',{exact:true}).click();await expect(page.getByRole('region',{name:'Daily nutrition summary'})).toContainText('1.25 g · partial (1 of 2 entries)');
 await page.getByRole('button',{name:'Foods & recipes',exact:true}).click();await page.getByRole('button',{name:'Edit food Fictional food 0',exact:true}).click();await page.getByText('Additional label nutrients (optional)',{exact:true}).click();const form=page.getByRole('form',{name:'Food details'});await expect(form.getByLabel('Fiber (g)',{exact:true})).toHaveValue('1.25');await expect(form.getByLabel('Calcium (mg)',{exact:true})).toHaveValue('');await form.getByLabel('Fiber (g)',{exact:true}).fill('2.5');await form.getByRole('button',{name:'Save food',exact:true}).click();await page.reload();await page.getByLabel('Journal date',{exact:true}).fill(date);await meal.getByText('Breakfast nutrient totals',{exact:true}).click();await expect(meal).toContainText('1.25 g · partial (1 of 2 entries)');
 await page.setViewportSize({width:320,height:900});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
