import {test,expect} from '@playwright/test';
import {createEmptyHealth} from '../lib/health';
import {importObservations} from '../lib/observation-import';
import {saveMeasurement} from '../lib/body-measurements';
const at='2026-09-26T10:00:00.000Z',value={kind:'weight' as const,quantityMilli:80000,unit:'kg' as const,observedAt:at,timezone:'UTC',sourceLabel:'Fictional scale'},file={format:'zigoals-observations',version:1,provider:'Fictional export',observations:[{...value,sourceId:'stable-1'}]};
test('retained duplicate observations count once; differing corrections require an explicit group review and survive reload',async({page})=>{
 const empty=createEmptyHealth(),a=importObservations(empty,file,at).data,b=importObservations(empty,file,'2026-09-26T11:00:00.000Z').data,data={...empty,measurements:[...a.measurements!,...b.measurements!]};
 await page.addInitScript(data=>{if(!sessionStorage.getItem('observation-group-fixture')){localStorage.setItem('zigoals:health:v1',JSON.stringify(data));sessionStorage.setItem('observation-group-fixture','1');}},data);
 await page.goto('/app/health');await page.getByRole('button',{name:'Measurements',exact:true}).click();const records=page.getByRole('region',{name:'Measurement records'});await expect(records.locator('tbody tr')).toHaveCount(1);await records.getByText('Record history',{exact:true}).click();await expect(records).toContainText('2 retained copies count as one reading');
 const corrected=saveMeasurement(a,{...value,id:a.measurements![0]!.id,quantityMilli:79000},'2026-09-26T12:00:00.000Z');await page.evaluate(data=>localStorage.setItem('zigoals:health:v1',JSON.stringify(data)),{...empty,measurements:[...corrected.measurements!,...b.measurements!]});await page.reload();await page.getByRole('button',{name:'Measurements',exact:true}).click();await expect(records.locator('tbody tr')).toHaveCount(0);
 const review=page.getByRole('region',{name:'Unresolved measurement copies'});await expect(review).toContainText('excluded from charts');await expect(review.getByRole('button',{name:'Review this reading for all copies'})).toHaveCount(2);await review.getByRole('button',{name:'Review this reading for all copies'}).first().click();const form=page.getByRole('form',{name:'Body measurement entry'});await form.getByLabel('Measurement value',{exact:true}).fill('78');await expect(form.getByRole('button',{name:'Save measurement',exact:true})).toBeDisabled();await form.getByLabel('I reviewed every retained copy and want this value applied to all copies.').check();await form.getByRole('button',{name:'Save measurement',exact:true}).click();
 await expect(review).toHaveCount(0);await expect(records.locator('tbody tr')).toHaveCount(1);await expect(records).toContainText('78 kg');await page.reload();await page.getByRole('button',{name:'Measurements',exact:true}).click();await records.getByText('Record history',{exact:true}).click();await expect(records).toContainText('Previous: 79 kg');await expect(records).toContainText('Previous: 80 kg');
 const event=page.waitForEvent('download');await page.getByRole('button',{name:'Export measurements CSV',exact:true}).click();const stream=await(await event).createReadStream();let csv='';for await(const chunk of stream!)csv+=chunk.toString();expect(csv).toContain('duplicate_of');for(const r of data.measurements)expect(csv).toContain(r.id);await page.setViewportSize({width:320,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
