import {test,expect} from '@playwright/test';
import {createEmptyHealth,diarySchema,HEALTH_STORAGE_KEY} from '../lib/health';
import {healthDay,dailyData} from '../lib/health-daily';
import {addLocalDays} from '../lib/local-date';
import {DASHBOARD_SETTINGS_KEY,presetSettings} from '../lib/dashboard-settings';
// Saves are asynchronous: each step waits until Health confirms the save before leaving the page, so the next page
// never races a write that has not landed (CI, mobile project at 1280 px, once).
for(const width of [320,1280])test(`food-entry and meal pins preserve canonical edits, historical navigation and deleted state at ${width}px`,async({page},info)=>{
 await page.route('**/api/**',route=>route.fulfill({status:503,json:{error:'Controlled offline fixture'}}));
 const health=createEmptyHealth(),today=healthDay(dailyData(health).preferences.timezone),previous=addLocalDays(today,-1),stamp=new Date().toISOString();
 const row=diarySchema.parse({id:'health_entry0001',sourceId:'health_food00001',sourceKind:'food',snapshot:{name:'Fictional oats',servingGrams:40,nutrients:{kcal:100,proteinMg:5000,carbsMg:18000,fatMg:2000}},date:previous,meal:'Breakfast',quantityMilli:1500,createdAt:stamp,updatedAt:stamp});health.diary=[row,{...row,id:'health_entry0002',date:today,quantityMilli:2000}];
 await page.addInitScript(({health,healthKey,settings,settingsKey})=>{if(!sessionStorage.getItem('food-widget-fixture')){localStorage.setItem(healthKey,JSON.stringify(health));localStorage.setItem(settingsKey,JSON.stringify(settings));sessionStorage.setItem('food-widget-fixture','1');}},{health,healthKey:HEALTH_STORAGE_KEY,settings:presetSettings('health'),settingsKey:DASHBOARD_SETTINGS_KEY});
 await page.setViewportSize({width,height:900});await page.goto(`/app/health?date=${previous}`);await expect(page.getByLabel('Journal date')).toHaveValue(previous);
 const entry=page.locator('#entry-health_entry0001');await entry.getByRole('button',{name:'Options for Fictional oats diary entry'}).click();await entry.getByRole('button',{name:'Add Fictional oats calories to Today',exact:true}).click();await expect(entry).toContainText('added to Today');
 const meal=page.getByRole('region',{name:'Breakfast diary'});await meal.getByRole('button',{name:'Options for Breakfast today',exact:true}).click();await meal.getByRole('button',{name:'Add Breakfast today calories to Today',exact:true}).click();await expect(meal).toContainText('Breakfast today calories added to Today');
 await page.goto('/app');const pinned=page.getByRole('article',{name:'Fictional oats',exact:true}),breakfast=page.getByRole('article',{name:'Breakfast today',exact:true});await expect(pinned).toContainText('150 kcal');await expect(pinned).toContainText(previous);await expect(breakfast).toContainText('200 kcal');await expect(page.getByRole('region',{name:'Staked ZIG overview'})).toHaveCount(0);
 await pinned.getByRole('link',{name:'Open details'}).click();await expect(page.getByLabel('Journal date')).toHaveValue(previous);await entry.getByRole('button',{name:'Edit Fictional oats',exact:true}).click();await entry.getByLabel('Servings',{exact:true}).fill('3');await entry.getByRole('button',{name:'Save entry',exact:true}).click();await expect(page.locator('.health-feedback')).toHaveText('Diary entry updated.');await page.goto('/app');await expect(pinned).toContainText('300 kcal');await page.reload();await expect(pinned).toContainText('300 kcal');
 await pinned.getByRole('link',{name:'Open details'}).click();await entry.getByRole('button',{name:'Remove Fictional oats',exact:true}).click();await expect(page.locator('.health-feedback')).toHaveText('Diary entry removed.');await expect(entry).toHaveCount(0);await page.goto('/app');const missing=page.getByRole('article',{name:'A logged food entry',exact:true});await expect(missing).toContainText('Record unavailable');await expect(breakfast).toContainText('200 kcal');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:info.outputPath(`food-widget-${width}.png`),fullPage:true});
});
