import {test,expect} from '@playwright/test';
import {emptyPlatform,privateGoalSchema} from '../lib/positions';
test('larger Goal collections preserve pinned order and offer bounded search, sorting and pages',async({page},info)=>{
 if(info.project.name==='mobile')await page.setViewportSize({width:320,height:900});let marketCalls=0;await page.route('**/api/**',r=>{if(r.request().url().includes('market'))marketCalls++;return r.fulfill({status:503,json:{error:'Fictional manual-only collection'}});});
 const goals=Array.from({length:61},(_,i)=>privateGoalSchema.parse({id:String(1000+i),name:`Reserve ${String(i).padStart(3,'0')} with a descriptive long-term purpose`,type:'VALUE',status:i<20?'closed':'active',asset:i%2?'USD':'EUR',denom:i%2?'USD':'EUR',decimals:2,target:'999999999999999',notes:'Fictional collection acceptance',createdAt:'2026-09-23T12:00:00Z',milestones:[],pinned:i===60}));
 await page.goto('/app/goals');await page.evaluate(data=>localStorage.setItem('zigoals:platform:v1',JSON.stringify(data)),{...emptyPlatform(),goals});await page.reload();await expect(page.locator('.goal-card')).toHaveCount(24);await expect(page.locator('.goal-card').first()).toContainText('Reserve 060');const raw=await page.evaluate(()=>localStorage.getItem('zigoals:platform:v1'));
 await page.getByRole('button',{name:'Next Goals page',exact:true}).click();await expect(page.locator('.goal-card')).toHaveCount(17);await expect(page.getByRole('status').filter({hasText:/Page 2 of 2/})).toBeVisible();
 await page.getByLabel('Search Goals',{exact:true}).fill('Reserve 040');await expect(page.locator('.goal-card')).toHaveCount(1);await expect(page.locator('.goal-card')).toContainText('Reserve 040');await page.getByLabel('Search Goals',{exact:true}).fill('');await page.getByLabel('Sort Goals',{exact:true}).selectOption('name-desc');await expect(page.locator('.goal-card').first()).toContainText('Reserve 060');await page.getByLabel('Sort Goals',{exact:true}).selectOption('name-asc');await expect(page.locator('.goal-card').first()).toContainText('Reserve 020');
 await page.getByRole('button',{name:'All',exact:true}).click();await expect(page.locator('.goal-card')).toHaveCount(24);await expect(page.locator('.goal-card').first()).toContainText('Reserve 000');await page.getByRole('button',{name:'Closed',exact:true}).click();await expect(page.locator('.goal-card')).toHaveCount(20);expect(await page.getByRole('button',{name:'Next Goals page',exact:true}).count()).toBe(0);expect(await page.evaluate(()=>localStorage.getItem('zigoals:platform:v1'))).toBe(raw);expect(marketCalls).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
