import {test,expect} from '@playwright/test';
test('manual portfolio evidence yields reviewed flow-boundary return and retains correction on reload',async({page},info)=>{
 await page.goto('/app/wealth');const panel=page.getByRole('region',{name:'Financial evidence and returns'});await expect(panel).toBeVisible();
 await panel.getByLabel('Portfolio name').fill('Fictional statement');await panel.getByRole('button',{name:'Create evidence portfolio'}).click();
 const form=panel.getByRole('form',{name:'Record financial evidence'});
 async function entry(kind:string,amount:string,time:string,role?:string){await form.getByLabel('Evidence type').selectOption(kind);await form.getByLabel('Event time (UTC)').fill(time);await form.getByLabel('Amount in USD',{exact:true}).fill(amount);await form.getByLabel('Source or statement reference').fill('Fictional monthly statement');if(role){await form.getByLabel('Valuation purpose').selectOption(role);if(role!=='boundary')await form.getByLabel('Related external flow').selectOption({index:1});}await form.getByRole('button',{name:'Save evidence'}).click();await expect(panel.getByRole('status')).toHaveText('Evidence saved. Current holdings and Goals are unchanged.');}
 await entry('valuation','100','2026-01-01T00:00','boundary');await entry('external_flow','50','2026-02-01T00:00');await entry('valuation','110','2026-02-01T00:00','before_flow');await entry('valuation','160','2026-02-01T00:00','after_flow');await entry('valuation','176','2026-03-01T00:00','boundary');
 await panel.getByLabel('Start valuation').selectOption({index:1});await panel.getByLabel('End valuation').selectOption({index:2});await expect(panel).toContainText('Review this evidence');
 for(const label of ['I recorded every external cash flow for this portfolio and period.','Both endpoints and all flow boundaries value the complete same portfolio, including cash.','Income and fees are already included in these valuations.'])await panel.getByLabel(label,{exact:true}).check();
 await panel.getByRole('button',{name:'Save completeness review'}).click();await expect(panel.getByRole('status')).toHaveText('Completeness review saved.');await expect(panel.getByLabel('Cumulative time-weighted return')).toHaveText('21%');await page.setViewportSize({width:320,height:850});await panel.getByRole('region',{name:'Review time-weighted return'}).screenshot({path:`../../docs/run10/evidence/financial-evidence-320-${info.project.name}.png`});
 await page.reload();const restored=page.getByRole('region',{name:'Financial evidence and returns'});await restored.getByLabel('Start valuation').selectOption({index:1});await restored.getByLabel('End valuation').selectOption({index:2});await expect(restored.getByLabel('Cumulative time-weighted return')).toHaveText('21%');
 await restored.getByRole('button',{name:'Correct event',exact:true}).first().click();await restored.getByLabel('Correction reason').fill('Fictional wrong final value');await restored.getByRole('button',{name:'Void this evidence record'}).click();await expect(restored).toContainText('Original retained');await expect(restored.getByLabel('Cumulative time-weighted return')).toHaveCount(0);await page.reload();await expect(page.getByRole('region',{name:'Financial evidence and returns'})).toContainText('Fictional wrong final value');
 await page.setViewportSize({width:320,height:850});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('manual dated FX review keeps original EUR and converted USD separate from current wealth',async({page})=>{
 await page.goto('/app/wealth');const panel=page.getByRole('region',{name:'Financial evidence and returns'});await panel.getByLabel('Portfolio name').fill('Fictional FX statement');await panel.getByRole('button',{name:'Create evidence portfolio'}).click();await panel.getByText('Record a manual FX basis',{exact:true}).click();
 const form=panel.getByRole('form',{name:'Manual FX evidence'});await form.getByLabel('Original amount').fill('100');await form.getByLabel('Original currency',{exact:true}).selectOption('EUR');await form.getByLabel('Quote currency',{exact:true}).selectOption('USD');await form.getByLabel('Quote units per original currency unit').fill('1.12345');await form.getByLabel('FX event time (UTC)').fill('2026-02-01T00:00');await form.getByLabel('FX source reference').fill('Fictional receipt');await form.getByRole('button',{name:'Preview FX conversion'}).click();await expect(form).toContainText('100 EUR → 112.35 USD');await form.getByRole('button',{name:'Save manual FX evidence'}).click();
 const event=panel.getByRole('form',{name:'Record financial evidence'});await event.getByLabel('Evidence type').selectOption('external_flow');await event.getByLabel('Dated FX basis').selectOption({index:1});await event.getByLabel('Source or statement reference').fill('Fictional deposit');await event.getByRole('button',{name:'Save evidence'}).click();await expect(panel).toContainText('112.35 USD');await page.reload();await expect(page.getByRole('region',{name:'Financial evidence and returns'})).toContainText('100 EUR');
});
