import {test,expect} from '@playwright/test';
import {emptyPlatform,positionSchema,privateGoalSchema,PLATFORM_KEY} from '../lib/positions';
import {DASHBOARD_SETTINGS_KEY,presetSettings} from '../lib/dashboard-settings';
const fixtureAccount='10000000-0000-4000-8000-000000000001';
test.beforeEach(async({page})=>{
 await page.route('**/api/**',route=>route.fulfill({status:503,json:{error:'LOCAL_FIXTURE_ONLY'}}));});
for(const width of [320,390])test(`selected staking/rewards and allocation widgets save and reload at ${width}px`,async({page},info)=>{
 const data=emptyPlatform();data.positions=[positionSchema.parse({id:'fixture-stake',providerId:'Fixture validator',sourceType:'NATIVE_STAKING',network:'zigchain-1',account:'fictional-address',asset:'ZIG',denom:'azig',quantity:'9007199254740993000001000000000000',decimals:18,liquidity:'BONDED',verification:'VERIFIED_READ_ONLY',sync:'STALE',observedAt:'2026-09-22T12:00:00Z',provenance:'Explicit fictional browser test fixture; not a real observation.'}),positionSchema.parse({id:'fixture-rewards',providerId:'Fixture rewards',sourceType:'NATIVE_REWARDS',network:'zigchain-testnet-1',account:'fictional-other-address',asset:'ZIG',denom:'uzig',quantity:'125',decimals:6,liquidity:'LIQUID',verification:'VERIFIED_READ_ONLY',sync:'ERROR',observedAt:'2026-09-22T12:00:00Z',provenance:'Explicit fictional browser test fixture.'}),positionSchema.parse({id:'fixture-cash',providerId:'Fixture cash',sourceType:'MANUAL',network:'manual',account:'manual',asset:'USD',denom:'USD',quantity:'10001',decimals:2,liquidity:'LIQUID',verification:'MANUAL',observedAt:'2026-09-23T12:00:00Z',provenance:'Fictional cash fixture.'})];
 data.goals=[privateGoalSchema.parse({id:'42',name:'Fixture Goal',type:'VALUE',status:'active',asset:'USD',denom:'USD',decimals:2,target:'20000',notes:'Fictional',createdAt:'2026-09-23T12:00:00Z',milestones:[]})];data.allocations=[{positionId:'fixture-cash',goalId:'42',quantity:'11002'}];
 await page.addInitScript(({data,platformKey,settings,settingsKey})=>{if(!sessionStorage.getItem('fixture-widget-seeded')){localStorage.setItem(platformKey,JSON.stringify(data));localStorage.setItem(settingsKey,JSON.stringify(settings));sessionStorage.setItem('fixture-widget-seeded','true');}},{data,platformKey:PLATFORM_KEY,settings:presetSettings('health'),settingsKey:DASHBOARD_SETTINGS_KEY});
 let financialRequests=0;page.on('request',request=>{if(/\/api\/(market|positions|chain)/.test(request.url()))financialRequests++;});
 await page.setViewportSize({width,height:900});await page.goto('/app');await expect(page.getByRole('button',{name:'Customize Today',exact:true})).toBeEnabled();await expect(page.locator('.workspace-status')).toContainText('This device only');await expect(page.locator('.app-topbar')).toHaveCount(0);expect(financialRequests).toBe(0);
 await expect(page.getByRole('alert').filter({hasText:'allocation exceeds'})).toBeVisible();
 await page.getByRole('button',{name:'Customize Today',exact:true}).click();
 for(const [kind,entity,title] of [['staking','fixture-stake','My selected stake'],['staking','fixture-rewards','My selected rewards'],['allocation','fixture-cash','My source allocation']]){
  await page.getByRole('button',{name:'Add widget',exact:true}).click();const editor=page.getByRole('dialog',{name:'Add a widget'});await editor.getByRole('combobox',{name:'Widget type',exact:true}).selectOption(kind!);await editor.getByRole('combobox',{name:'Choose a record',exact:true}).selectOption(entity!);await editor.getByLabel('Title (optional)').fill(title!);if(kind==='allocation')await expect(editor).toContainText('10.01 USD');await editor.getByRole('button',{name:'Save widget'}).click();await expect(page.getByRole('article',{name:title!,exact:true})).toBeVisible();
 }
 await page.reload();const stake=page.getByRole('article',{name:'My selected stake',exact:true}),rewards=page.getByRole('article',{name:'My selected rewards',exact:true}),allocation=page.getByRole('article',{name:'My source allocation',exact:true});
 await expect(stake).toContainText('9,007,199,254,740,993.000001 ZIG');await expect(stake).toContainText('zigchain-1');await expect(stake).toContainText('stale');await expect(rewards).toContainText('0.000125 ZIG');await expect(rewards).toContainText('refresh failed');await expect(allocation).toContainText('110.02 USD');await expect(allocation).toContainText('10.01 USD');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:info.outputPath(`widgets-scope-${width}.png`),fullPage:true});
});
test('cold selected account has a global locked status and settings action with no identity leakage',async({page},info)=>{
 await page.addInitScript(id=>sessionStorage.setItem('zigoals:account:selector:v1',JSON.stringify({version:1,accountId:id})),fixtureAccount);await page.setViewportSize({width:320,height:900});await page.goto('/app');await expect(page.locator('.workspace-status')).toContainText('Account locked');await expect(page.locator('.workspace-status')).not.toContainText(fixtureAccount);await expect(page.locator('.mode-strip')).toHaveCount(0);await expect(page.locator('.workspace-status a')).toHaveAttribute('href','/app/settings#encrypted-sync');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);await page.screenshot({path:info.outputPath('account-locked-shell-320.png'),fullPage:true});
});
