import {test,expect} from '@playwright/test';
test.use({video:'on'});
test('recorded hero and evidence-line entrances settle once per visit and preserve exact history',async({page,isMobile},info)=>{
 await page.route('**/api/**',r=>r.fulfill({status:503,json:{error:'Offline fictional motion fixture'}}));
 await page.addInitScript(()=>{const samples:{name:string;start:string;mid?:string;end?:string}[]=[];Object.assign(window,{run11Lines:samples});document.addEventListener('animationstart',event=>{const node=event.target;if(!(node instanceof Element)||event.animationName!=='evidence-draw')return;const sample={name:location.pathname+':'+(node.closest('figure')?.getAttribute('aria-label')??''),start:getComputedStyle(node).strokeDashoffset,mid:undefined as string|undefined,end:undefined as string|undefined};samples.push(sample);setTimeout(()=>{sample.mid=getComputedStyle(node).strokeDashoffset;},200);node.addEventListener('animationend',()=>{sample.end=getComputedStyle(node).strokeDashoffset;},{once:true});},true);});
 await page.goto('/app/settings');await page.getByRole('button',{name:'Load Showcase Demo',exact:true}).click();await page.waitForURL('**/app');await page.locator('.slogan-entrance').scrollIntoViewIfNeeded();await expect(page.locator('.slogan-entrance')).toHaveAttribute('data-entrance','once');await expect.poll(()=>page.locator('.slogan-entrance').evaluate(e=>e.getAnimations().some(a=>a.playState==='running'))).toBe(false);
 await page.getByRole('link',{name:'Wealth',exact:true}).first().click();const chart=page.locator('.wealth-history .evidence-chart').first();await chart.scrollIntoViewIfNeeded();await expect.poll(()=>page.evaluate(()=>(window as unknown as {run11Lines:{end?:string}[]}).run11Lines.some(s=>s.end!==undefined))).toBe(true);
 const samples=await page.evaluate(()=>(window as unknown as {run11Lines:{name:string;start:string;mid?:string;end?:string}[]}).run11Lines);for(const sample of samples.filter(s=>s.end!==undefined)){expect(sample.start).not.toBe(sample.end);expect(sample.mid).not.toBe(sample.end);expect(sample.end).toBe('0px');}
 await chart.getByText('View exact history',{exact:true}).click();const original=await chart.locator('tbody').innerText();expect(original.length).toBeGreaterThan(100);const label='/app/wealth:'+await chart.getAttribute('aria-label'),count=samples.filter(s=>s.name===label).length;
 // Open and close an overlay: Quick add on mobile; desktop Wealth has no Quick add (it moved to the Today hero), so use its Add asset dialog.
 await (isMobile?page.getByRole('button',{name:'+ Quick add',exact:true}):page.getByRole('button',{name:'+ Add asset',exact:true}).first()).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.waitForTimeout(750);
 expect(await chart.locator('tbody').innerText()).toBe(original);expect(await page.evaluate(label=>(window as unknown as {run11Lines:{name:string}[]}).run11Lines.filter(s=>s.name===label).length,label)).toBe(count);await chart.screenshot({path:info.outputPath('settled-evidence-line.png')});
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await chart.scrollIntoViewIfNeeded();await expect(chart.locator('.evidence-line').first()).toHaveCSS('animation-name','none');await info.attach('motion-samples',{body:JSON.stringify(samples,null,2),contentType:'application/json'});
});
