import {test,expect} from '@playwright/test';
import {createEmptyHealth,diarySchema,HEALTH_STORAGE_KEY,healthSchema} from '../lib/health';
import {healthDay,dailyData,exportHealthCsv} from '../lib/health-daily';
import {DASHBOARD_SETTINGS_KEY,presetSettings} from '../lib/dashboard-settings';
import {openTodayWidgets} from './phone-nav';
for(const labelUnit of ['g','ml'] as const)test(`reviewed barcode per100${labelUnit} accepts unknown core fields, preserves known zero and shows partial coverage after reload`,async({page})=>{
 const health=createEmptyHealth(),date=healthDay(dailyData(health).preferences.timezone),stamp=new Date().toISOString();health.diary=[diarySchema.parse({id:'health_known0001',sourceId:'health_food00001',sourceKind:'food',snapshot:{name:'Known fixture',servingGrams:100,nutrients:{kcal:200,proteinMg:1000,carbsMg:2000,fatMg:1000}},date,meal:'Snacks',quantityMilli:1000,createdAt:stamp,updatedAt:stamp})];
 await page.route('**/api/**',route=>route.fulfill(route.request().url().includes('/food-lookup?')?{status:200,json:{barcode:'3017620422003',name:'Unknown fixture',brand:'Synthetic',basis:'unverified-100g-or-100ml',nutrients:{kcal:null,proteinMg:1000,carbsMg:null,fatMg:0},source:'Open Food Facts',apiVersion:'3.4',observedAt:stamp}}:{status:503,json:{error:'Fixture offline'}}));
 await page.addInitScript(({health,key,settings,settingsKey})=>{if(!sessionStorage.getItem('unknown-fixture')){localStorage.setItem(key,JSON.stringify(health));localStorage.setItem(settingsKey,JSON.stringify(settings));sessionStorage.setItem('unknown-fixture','1');}},{health,key:HEALTH_STORAGE_KEY,settings:presetSettings('health'),settingsKey:DASHBOARD_SETTINGS_KEY});
 await page.goto('/app/health');await page.getByText('Scan or look up a food barcode',{exact:true}).click();const lookup=page.getByRole('region',{name:'Barcode food lookup'});await lookup.getByLabel('Product barcode').fill('3017620422003');await lookup.getByRole('button',{name:'Look up barcode',exact:true}).click();await expect(lookup.getByLabel('Calories (kcal)',{exact:true})).toHaveValue('');await expect(lookup.getByLabel('Fat (g)',{exact:true})).toHaveValue('0');await lookup.getByLabel('Reviewed label basis').selectOption(labelUnit);await lookup.getByRole('checkbox').check();await lookup.getByRole('button',{name:'Confirm and log food',exact:true}).click();await expect(lookup).toContainText('Added to your private diary');
 const summary=page.getByRole('region',{name:'Daily nutrition summary'});await expect(summary).toContainText('200 kcal known · 1/2 entries supplied calories');await page.reload();await expect(summary).toContainText('200 kcal known · 1/2 entries supplied calories');
 const stored=healthSchema.parse(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),HEALTH_STORAGE_KEY));expect(stored.diary).toHaveLength(2);expect(stored.diary.at(-1)?.snapshot.servingGrams).toBe(labelUnit==='g'?100:null);expect(stored.diary.at(-1)?.snapshot.servingMl).toBe(labelUnit==='ml'?100:undefined);expect(stored.diary.at(-1)?.snapshot.nutrients).toMatchObject({kcal:null,carbsMg:null,fatMg:0});expect(exportHealthCsv(stored,date,date)).toContain('"unknown"');
 await page.goto('/app');await openTodayWidgets(page);await expect(page.getByRole('article',{name:'Meals today',exact:true})).toContainText('200 kcal known · 1/2 entries supplied calories');
});
