import {test,expect} from '@playwright/test';
import {createHabit,emptyHabitData,HABITS_KEY,habitDataSchema} from '../lib/habits';
import {emptyPlatform,privateGoalSchema,PLATFORM_KEY} from '../lib/positions';
const now='2026-09-26T00:30:00Z',before=new Date('2026-09-25T12:00:00Z'),id='59a35604-3696-4a78-b455-4015acb66885',nextId='ff829326-f352-4a26-80d0-eb8c31cde62e';
const input={title:'Fixture review',category:'Personal',description:'',notes:'',schedule:{kind:'daily' as const},target:1};
test('saved timezone, suggested stack and explicit linked Goal pause/reopen preserve history',async({page},info)=>{
 if(info.project.name==='mobile')await page.setViewportSize({width:320,height:900});
 await page.route('**/api/**',r=>r.fulfill({status:503,json:{error:'Offline fixture'}}));await page.clock.install({time:new Date(now)});await page.clock.setFixedTime(new Date(now));
 let habits=createHabit({...emptyHabitData(),timeZone:'UTC'},{...input,goalLink:{chainId:'private',owner:'local',goalId:'77'}},before,id);habits=createHabit(habits,{...input,title:'Fixture reading',measurement:{kind:'duration',unit:'minutes'},target:30,stackAfterId:id},before,nextId);
 const goal=privateGoalSchema.parse({id:'77',name:'Fixture reserve',type:'VALUE',status:'closed',asset:'USD',denom:'USD',decimals:2,target:'100',notes:'',createdAt:before.toISOString(),milestones:[]});
 await page.addInitScript(({habits,platform,hkey,pkey})=>{if(!sessionStorage.getItem('habit-fixture')){localStorage.setItem(hkey,JSON.stringify(habits));localStorage.setItem(pkey,JSON.stringify(platform));sessionStorage.setItem('habit-fixture','1');}},{habits,platform:{...emptyPlatform(),goals:[goal]},hkey:HABITS_KEY,pkey:PLATFORM_KEY});
 await page.goto('/app/habits');await page.getByText('Habit journal timezone',{exact:true}).click();await page.getByLabel('Habit timezone',{exact:true}).fill('America/Los_Angeles');await page.getByRole('button',{name:'Save Habit timezone',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Habit timezone saved'})).toContainText('Habit timezone saved');
 const review=page.getByRole('article',{name:'Fixture review',exact:true}),reading=page.getByRole('article',{name:'Fixture reading',exact:true});await review.getByRole('button',{name:'Complete Fixture review',exact:true}).click();await expect(review.getByRole('button',{name:'View Fixture reading',exact:true})).toBeVisible();await review.getByRole('button',{name:'View Fixture reading',exact:true}).click();await expect(reading).toBeFocused();await expect(reading.locator('.habit-count')).toContainText('0 / 30 minutes');
 await review.getByRole('button',{name:'Schedule linked Habit pause',exact:true}).click();await expect(review).toContainText('Scheduled change from 2026-09-26: paused');await page.reload();await page.getByRole('button',{name:'All',exact:true}).click();await expect(review).toContainText('Scheduled change from 2026-09-26: paused');
 await page.evaluate(({key,at})=>{const data=JSON.parse(localStorage.getItem(key)!);const g=data.goals[0];g.status='active';g.lifecycle=[{id:'lifecycle:77:reopened-fixture',kind:'reopened',cycle:1,at,target:g.target,asset:g.asset,decimals:g.decimals}];localStorage.setItem(key,JSON.stringify(data));window.dispatchEvent(new CustomEvent('zigoals:private-change',{detail:key}));},{key:PLATFORM_KEY,at:now});await review.getByRole('button',{name:'Schedule linked Habit resume',exact:true}).click();await expect(review).toContainText('Scheduled change from 2026-09-26: active');
 const stored=habitDataSchema.parse(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),HABITS_KEY));expect(stored.habits[0]?.entries).toHaveLength(1);expect(stored.habits[0]?.entries[0]?.date).toBe('2026-09-25');expect(stored.habits[0]?.ruleRevisions?.some(r=>r.rule.state==='paused')).toBe(true);expect(stored.habits[1]?.entries).toHaveLength(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await review.screenshot({path:info.outputPath('habit-linked-review.png')});
});
test('two tabs reject a stale future rule draft while preserving both current and retained history',async({page,context})=>{
 await context.route('**/api/**',r=>r.fulfill({status:503,json:{error:'Offline fixture'}}));await page.goto('/app/habits');const data=createHabit(emptyHabitData(),input,new Date(),id);await page.evaluate(({key,data})=>localStorage.setItem(key,JSON.stringify(data)),{key:HABITS_KEY,data});await page.reload();const other=await context.newPage();await other.goto('/app/habits');
 for(const tab of [page,other]){await tab.getByRole('button',{name:'Edit Fixture review',exact:true}).click();}
 await page.getByLabel('Target value',{exact:true}).fill('2');await other.getByLabel('Target value',{exact:true}).fill('3');await page.getByRole('button',{name:'Save habit',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Habit saved'})).toContainText('Habit saved');await other.getByRole('button',{name:'Save habit',exact:true}).click();await expect(other.getByRole('alert').filter({hasText:'changed while you were editing'})).toContainText('changed while you were editing');await expect(other.getByLabel('Target value',{exact:true})).toHaveValue('3');const stored=habitDataSchema.parse(await other.evaluate(key=>JSON.parse(localStorage.getItem(key)!),HABITS_KEY));expect(stored.habits[0]?.rules.at(-1)?.target).toBe(2);expect(stored.habits[0]?.rules[0]?.target).toBe(1);await other.close();
});
test('saved timezone timer survives reload, logs only after review and retains one diary duration',async({page})=>{
 await page.route('**/api/**',r=>r.fulfill({status:503,json:{error:'Offline fixture'}}));await page.clock.install({time:new Date('2026-09-26T12:00:00Z')});await page.clock.setFixedTime(new Date('2026-09-26T12:00:00Z'));await page.goto('/app/habits');const data=createHabit({...emptyHabitData(),timeZone:'America/New_York'},{...input,title:'Fixture timer',measurement:{kind:'duration',unit:'minutes'},target:30},new Date('2026-09-26T12:00:00Z'),id);await page.evaluate(({key,data})=>localStorage.setItem(key,JSON.stringify(data)),{key:HABITS_KEY,data});await page.reload();const card=page.getByRole('article',{name:'Fixture timer',exact:true});await card.getByRole('button',{name:'Start timer',exact:true}).click();await expect(card).toContainText('America/New_York');await page.clock.setFixedTime(new Date('2026-09-26T12:01:30Z'));await page.reload();await card.getByRole('button',{name:'Pause timer',exact:true}).click();await expect(card.getByRole('region',{name:'Saved timer'})).toContainText('1.5 minutes');await expect(card.locator('.habit-count')).toContainText('0 / 30 minutes');await card.getByRole('button',{name:'Log reviewed duration',exact:true}).click();await expect(card.locator('.habit-count')).toContainText('1.5 / 30 minutes');await page.reload();await expect(card.locator('.habit-count')).toContainText('1.5 / 30 minutes');await expect(card.getByRole('button',{name:'Log reviewed duration',exact:true})).toHaveCount(0);const stored=habitDataSchema.parse(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),HABITS_KEY));expect(stored.habits[0]?.entries).toHaveLength(1);expect(stored.habits[0]?.timerReceipts).toHaveLength(1);expect(stored.habits[0]?.timerReceipts?.[0]?.timerId).toBeTruthy();
});
