import {test,expect} from '@playwright/test';
test('Goal draft navigation and reload require an explicit discard, while cancel retains input',async({page})=>{
 await page.goto('/app/goals');await page.goto('/app/goals/new');await page.getByLabel('Goal name').fill('Retain this private draft');await page.getByLabel('Target amount').fill('25');
 let dialogs=0;page.on('dialog',async dialog=>{dialogs++;await dialog.dismiss();});
 await page.getByRole('link',{name:'Today',exact:true}).first().click();await expect(page.getByLabel('Goal name')).toHaveValue('Retain this private draft');expect(dialogs).toBe(1);
 await page.evaluate(()=>history.back());await expect(page.getByLabel('Goal name')).toHaveValue('Retain this private draft');await expect.poll(()=>dialogs).toBe(2);
 await page.evaluate(()=>location.reload());await expect(page.getByLabel('Goal name')).toHaveValue('Retain this private draft');await expect.poll(()=>dialogs).toBe(3);
 page.removeAllListeners('dialog');page.once('dialog',dialog=>dialog.accept());const destination=await page.getByRole('link',{name:'Today',exact:true}).first().getAttribute('href');await page.getByRole('link',{name:'Today',exact:true}).first().click();await expect(page).toHaveURL(new RegExp(destination+'$'));
});
test('saved Goal detail edits retain input on canceled navigation and discard only the selected form',async({page})=>{
 await page.goto('/app/goals/new');await page.getByLabel('Goal name').fill('Saved Goal');await page.getByLabel('Target amount').fill('25');await page.getByRole('button',{name:'Create goal',exact:true}).click();await expect(page).toHaveURL(/tracked/);await page.locator('#edit-goal > summary').click();await page.getByLabel('Edit Goal name').fill('Unsaved edit');page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('link',{name:'Today',exact:true}).first().click();await expect(page.getByLabel('Edit Goal name')).toHaveValue('Unsaved edit');await page.getByRole('button',{name:'Cancel Goal edits'}).click();await expect(page.getByLabel('Edit Goal name')).toHaveValue('Saved Goal');await page.getByLabel('Edit Goal name').fill('Saved edit');await page.getByRole('button',{name:'Save Goal details'}).click();await expect(page.getByRole('heading',{name:'Saved edit',exact:true})).toBeVisible();let asked=false;page.on('dialog',async d=>{asked=true;await d.dismiss();});await page.getByRole('link',{name:'Today',exact:true}).first().click();expect(asked).toBe(false);
});
