import {test,expect} from '@playwright/test';
import {openMealLog} from './phone-nav';
import {createEmptyHealth,HEALTH_STORAGE_KEY,healthSchema} from '../lib/health';
test('volume label, measured recipe yield and immutable version survive diary, planning and reload',async({page},testInfo)=>{
 if(testInfo.project.name==='mobile')await page.setViewportSize({width:320,height:844});
 await page.route('**/api/**',r=>r.fulfill({status:503,json:{error:'Synthetic offline'}}));
 await page.addInitScript(({data,key})=>{if(!sessionStorage.getItem('volume-fixture')){localStorage.setItem(key,JSON.stringify(data));sessionStorage.setItem('volume-fixture','1');}},{data:createEmptyHealth(),key:HEALTH_STORAGE_KEY});
 await page.goto('/app/health');await page.getByRole('button',{name:'Foods & recipes',exact:true}).click();await page.getByRole('button',{name:'New food',exact:true}).click();
 const food=page.getByRole('form',{name:'Food details'});await food.getByLabel('Food name',{exact:true}).fill('Fixture juice');await food.getByLabel('Nutrition label basis').selectOption('100ml');await food.getByLabel('Serving volume (mL)').fill('250');await food.getByLabel('Calories (kcal)').fill('40');await food.getByLabel('Fat (g)',{exact:true}).fill('0');await food.getByRole('button',{name:'Save food',exact:true}).click();await expect(page.locator('.health-library-row').filter({hasText:'Fixture juice'})).toContainText('250 mL per serving');
 await page.getByRole('button',{name:'New recipe',exact:true}).click();const recipe=page.getByRole('form',{name:'Recipe details'});await recipe.getByLabel('Recipe name',{exact:true}).fill('Fixture drink');await recipe.getByLabel('Recipe makes (servings)').fill('2');await recipe.getByLabel('Measured recipe yield unit').selectOption('ml');await recipe.getByLabel('Measured total recipe yield').fill('400');await recipe.getByRole('combobox',{name:'Ingredient 1',exact:true}).selectOption({label:'Fixture juice'});await recipe.getByLabel('Ingredient servings 1',{exact:true}).fill('2');await recipe.getByRole('button',{name:'Save recipe',exact:true}).click();
 await page.getByRole('button',{name:'Diary',exact:true}).click();await openMealLog(page);await page.getByRole('combobox',{name:'Food or recipe',exact:true}).selectOption({label:'Fixture drink · recipe'});await page.getByLabel('Quantity unit',{exact:true}).selectOption('millilitres');await page.getByLabel('Food volume (mL)').fill('200');await page.getByRole('button',{name:'Log to diary',exact:true}).click();await expect(page.locator('.health-entry-main').filter({hasText:'Fixture drink'})).toContainText('200 mL');
 await page.getByRole('button',{name:'Meals & planning',exact:true}).click();await page.getByText('Save a recipe as a meal',{exact:true}).click();await page.getByRole('button',{name:'Save Fixture drink as meal',exact:true}).click();await page.getByLabel('Planned saved meal').selectOption({label:'Fixture drink'});await page.getByRole('button',{name:'Save plan',exact:true}).click();await expect(page.getByRole('region',{name:'Grocery list',exact:true})).toContainText('250 mL');
 const groceries=page.getByRole('region',{name:'Grocery list',exact:true});await groceries.getByRole('button',{name:'Edit grocery Fixture juice',exact:true}).click();await groceries.getByLabel('Shopping name').fill('Juice carton');await groceries.getByLabel('Shopping quantity (optional)').fill('500');await groceries.getByRole('button',{name:'Save grocery correction',exact:true}).click();await groceries.getByRole('checkbox',{name:'Bought Juice carton',exact:true}).click();await expect(groceries.getByRole('checkbox',{name:'Bought Juice carton',exact:true})).toBeChecked();await expect(groceries).toContainText('Shopping: 500 mL');await page.reload();await page.getByRole('button',{name:'Meals & planning',exact:true}).click();await expect(groceries.getByRole('checkbox',{name:'Bought Juice carton',exact:true})).toBeChecked();await expect(groceries).toContainText('Planned: 250 mL');await groceries.scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath('grocery-volume.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Foods & recipes',exact:true}).click();await page.getByRole('button',{name:'Edit recipe Fixture drink',exact:true}).click();await recipe.getByLabel('Measured total recipe yield').fill('600');await recipe.getByRole('button',{name:'Save recipe',exact:true}).click();
 // Saving is asynchronous; reload only after the new recipe version is stored, or the reload can cut the save short.
 await expect.poll(()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).recipes?.[0]?.revision,HEALTH_STORAGE_KEY)).toBe(2);await page.reload();
 const stored=healthSchema.parse(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),HEALTH_STORAGE_KEY));expect(stored.foods[0]).toMatchObject({servingGrams:null,servingMl:250,nutrients:{kcal:100,proteinMg:null,fatMg:0}});expect(stored.recipes[0]?.revision).toBe(2);expect(stored.diary[0]?.snapshot).toMatchObject({servingGrams:null,servingMl:200,recipeVersion:1,recipeYield:{quantityMilli:400000,unit:'ml'}});expect(stored.daily?.plans[0]?.items[0]?.snapshot.recipeVersion).toBe(1);
});
