import {test,expect,type Page} from '@playwright/test';
import {emptyPlatform,type Platform} from '../lib/positions';
import {emptyHabitData} from '../lib/habits';
import {createEmptyHealth} from '../lib/health';

export async function loadShowcase(page:Page){await page.goto('/app/settings');await page.getByRole('button',{name:'Load Showcase Demo',exact:true}).click();await page.waitForURL('**/app');await expect(page.getByRole('complementary',{name:'Showcase data'})).toBeVisible();await expect(page.getByRole('region',{name:'Life and Wealth snapshot'})).toContainText('13 assets');}
export async function showcaseState(page:Page):Promise<Platform>{return page.evaluate(()=>{const marker=JSON.parse(sessionStorage.getItem('zigoals:showcase:active:v1')!);return JSON.parse(sessionStorage.getItem(`zigoals:showcase:v1:${marker.generation}:zigoals:platform:v1`)!);});}
const normalBytes=(page:Page)=>page.evaluate(()=>Object.fromEntries(Object.keys(localStorage).sort().map(k=>[k,localStorage.getItem(k)])));

test('Showcase journey: populated product, explicit history, reset and byte-exact return to normal data',async({page})=>{
 test.setTimeout(120000);await page.goto('/app/settings');await expect(page.getByRole('button',{name:'Load Showcase Demo',exact:true})).toBeEnabled();
 await page.evaluate(({platform,habits,health})=>{localStorage.setItem('zigoals:platform:v1',JSON.stringify(platform));localStorage.setItem('zigoals:habits:v1',JSON.stringify(habits));localStorage.setItem('zigoals:health:v1',JSON.stringify(health));localStorage.setItem('owner-unrelated-sentinel','normal bytes must remain exactly intact');},{platform:emptyPlatform(),habits:emptyHabitData(),health:createEmptyHealth()});
 await page.reload();await expect(page.getByRole('button',{name:'Load Showcase Demo',exact:true})).toBeEnabled();const original=await normalBytes(page);await loadShowcase(page);
 await expect(page.getByRole('region',{name:'Today financial intelligence'})).toContainText('Emergency fund');await expect(page.getByRole('region',{name:'Your funding agenda'})).toContainText('Japan adventure');await expect(page.locator('.needs-attention')).toContainText('Review asset');
 const seed=await showcaseState(page);expect(seed.positions).toHaveLength(13);expect(seed.goals).toHaveLength(6);expect(seed.watchlist).toHaveLength(7);expect(seed.contributions.some(c=>c.reversesId)).toBe(true);
 await page.goto('/app/goals');await expect(page.locator('main')).toContainText('First home deposit');await expect(page.locator('main')).toContainText('Launch my creative studio');await expect(page.locator('main')).toContainText('AHEAD');await expect(page.locator('main')).toContainText('ON TRACK');await expect(page.locator('main')).toContainText('BEHIND');
 await page.goto('/app/goals/tracked/9204');await expect(page.getByTestId('tracked-progress')).toContainText('0.1');await expect(page.locator('main')).toContainText('Completed');
 await page.goto('/app/goals/tracked/9201');await expect(page.getByRole('region',{name:'Funding Wealth overview'})).toContainText('$750');await expect(page.getByRole('region',{name:'Goal progress evidence'})).toContainText('SHOWCASE DATA');await expect(page.getByRole('region',{name:'Goal timeline'})).toContainText('Contribution recorded');await page.getByText('View exact history',{exact:true}).click();await expect(page.locator('[aria-label="Goal progress evidence"] tbody tr').first()).toBeVisible();
 await page.goto('/app/wealth');await expect(page.locator('.owned-asset-card')).toHaveCount(13);await expect(page.locator('.watch-card')).toHaveCount(7);await expect(page.locator('.portfolio-composition')).toContainText('EUR');await expect(page.locator('.portfolio-composition')).toContainText('ETFs');await expect(page.locator('.wealth-history')).toContainText('fictional dated portfolio');expect(await page.locator('.wealth-history circle').count()).toBeGreaterThan(10);
 await page.goto('/app/wealth/asset/showcase-btc');await expect(page.locator('.asset-detail')).toContainText('Bitcoin');await expect(page.getByRole('region',{name:'Your holding'})).toContainText('0.45 BTC');await expect(page.locator('.price-chart')).toBeVisible();
 await page.goto('/app/markets');await page.getByRole('button',{name:'Favourites',exact:true}).click();await expect(page.locator('.market-product-card')).toHaveCount(7);await expect(page.locator('.market-product-card').filter({hasText:'Solana'})).toContainText('Favourite only');await page.getByRole('button',{name:'Owned',exact:true}).click();await expect(page.locator('.market-product-card').filter({hasText:'Solana'})).toHaveCount(0);
 await page.goto('/app/goals/positions');const crypto=page.getByRole('region',{name:'Tracked crypto'});for(const name of ['Bitcoin','Ethereum','USDC'])await expect(crypto).toContainText(name);for(const name of ['Apple','Gold','Family home','EUR'])await expect(crypto).not.toContainText(name);await expect(page.getByRole('region',{name:'Showcase crypto reward examples'})).toContainText('ZIG');
 await page.goto('/app/habits');await expect(page.getByRole('region',{name:'Habit consistency history'})).toContainText('Showcase example history');await page.goto('/app/health');await expect(page.getByRole('region',{name:'Daily nutrition summary'})).toContainText('1,970');await expect(page.locator('.health-roadmap')).toContainText('Not connected');
 await page.goto('/app/activity');await expect(page.locator('.unified-activity')).toContainText('Showcase example history');await page.getByRole('button',{name:'Wealth',exact:true}).click();await expect(page.locator('.unified-activity')).toContainText('Metal');await page.goto('/app/ecosystem');await expect(page.locator('main')).toContainText('ZIGChain');
 await page.goto('/app/wealth/asset/showcase-usd');await page.getByRole('button',{name:'Edit asset',exact:true}).click();await page.getByLabel('Cash balance').fill('26000');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await showcaseState(page)).positions.find(p=>p.id==='showcase-usd')?.quantity).not.toEqual(seed.positions.find(p=>p.id==='showcase-usd')?.quantity);
 await page.goto('/app/settings');await page.getByRole('button',{name:'Reset Showcase Demo',exact:true}).click();await page.waitForURL('**/app');await expect(page.getByRole('complementary',{name:'Showcase data'})).toBeVisible();expect((await showcaseState(page)).positions).toEqual(seed.positions);expect(await normalBytes(page)).toEqual(original);
 await page.goto('/app/settings');await page.getByRole('button',{name:'Return to my data',exact:true}).click();await expect(page.getByRole('button',{name:'Load Showcase Demo',exact:true})).toBeEnabled();await expect(page.getByRole('complementary',{name:'Showcase data'})).toHaveCount(0);expect(await normalBytes(page)).toEqual(original);expect(await page.evaluate(()=>sessionStorage.getItem('zigoals:showcase:active:v1'))).toBeNull();
});

test('Quick Add keyboard, repeatable asset intent, Goal chooser and history-only contribution',async({page})=>{
 await loadShowcase(page);const trigger=page.getByRole('button',{name:'+ Quick add',exact:true});await trigger.click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('button',{name:'Close Quick add'})).toBeFocused();await page.keyboard.press('Escape');await expect(trigger).toBeFocused();
 await page.goto('/app/wealth');for(let n=0;n<2;n++){await trigger.click();await page.getByRole('navigation',{name:'Quick add actions'}).getByRole('link').filter({hasText:'Asset'}).click();await expect(page.getByRole('dialog',{name:'Add to your wealth'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);}
 const before=await showcaseState(page);await trigger.click();await page.getByRole('button',{name:/^Contribution Choose a Goal/}).click();await page.getByRole('navigation',{name:'Choose a Goal to contribute to'}).getByRole('link').filter({hasText:'Emergency fund'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Record history only',exact:true}).click();await page.getByLabel('Actual amount in USD',{exact:true}).fill('12');await page.getByRole('button',{name:'Save history only',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);const after=await showcaseState(page);expect(after.contributions.length).toBe(before.contributions.length+1);expect(after.positions).toEqual(before.positions);expect(after.allocations).toEqual(before.allocations);
});

test('Market search and favourites keep ownership independent, and blocked images retain identities',async({page})=>{
 await page.route('**/api/market-logo**',route=>route.abort());await loadShowcase(page);await page.goto('/app/markets');const before=await showcaseState(page);await page.getByLabel('Search this market view').fill('Solana');await expect(page.locator('.market-product-card')).toHaveCount(1);await expect(page.locator('.market-product-card')).toContainText('SOL');await page.getByRole('button',{name:'Remove Solana favourite',exact:true}).click();await expect(page.locator('.market-product-card')).toContainText('Market reference');expect((await showcaseState(page)).positions).toEqual(before.positions);await page.getByLabel('Search this market view').fill('');await page.getByRole('button',{name:'ETFs',exact:true}).click();await expect(page.locator('.market-product-card')).toContainText('Vanguard');await expect(page.locator('.market-product-card')).toHaveCount(1);
});

for(const width of [1440,1024,390,320])test(`Product composition and exact two-line slogan at ${width}px`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:1000});await loadShowcase(page);const heading=page.getByRole('heading',{name:"Today's Goals, Habits & Health = Tomorrow's Wealth",exact:true});await expect(heading).toBeVisible();await expect(heading.locator('.slogan-line').nth(0)).toHaveText("Today's Goals, Habits & Health");await expect(heading.locator('.slogan-line').nth(1)).toHaveText(" = Tomorrow's Wealth");
 const layout=await heading.evaluate(h=>[...h.querySelectorAll('.slogan-line')].map(line=>({line:line.getBoundingClientRect().toJSON(),children:[...line.children].map(child=>child.getBoundingClientRect().toJSON())})));expect(layout[0]!.children[0]!.y).toBeCloseTo(layout[0]!.children[1]!.y,1);expect(layout[1]!.line.y).toBeGreaterThan(layout[0]!.line.y);for(const line of layout)expect(line.children.at(-1)!.right).toBeLessThanOrEqual(width);const gradients=await heading.locator('.slogan-gradient').evaluateAll(items=>items.map(i=>getComputedStyle(i).backgroundImage));expect(gradients[0]).toEqual(gradients[1]);expect(gradients[0]).toContain('linear-gradient');
 const heroBounds=await page.locator('.today-hero').evaluate(h=>({right:h.getBoundingClientRect().right,actions:[...h.querySelectorAll('.hero-actions a')].map(a=>a.getBoundingClientRect().right)}));for(const right of heroBounds.actions)expect(right).toBeLessThanOrEqual(heroBounds.right);
 const issues:unknown[]=[];for(const route of ['/app','/app/goals','/app/goals/tracked/9201','/app/wealth','/app/markets','/app/wealth/asset/showcase-btc','/app/goals/positions']){await page.goto(route);await expect(page.locator('main h1').first()).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width===320){const small=await page.locator('main').evaluate(root=>[...root.querySelectorAll<HTMLElement>('p,small,span,label,input,button,select,summary,a,b,dt,dd')].filter(el=>el.getClientRects().length&&!el.closest('.eyebrow,[aria-hidden="true"],.scene-art')&&!!el.innerText?.trim()&&parseFloat(getComputedStyle(el).fontSize)<14).map(el=>({text:el.innerText.slice(0,55),size:getComputedStyle(el).fontSize,class:el.className})));if(small.length)issues.push({route,small});}}
 expect(issues).toEqual([]);
});
