import {test,expect} from '@playwright/test';
import {createServer,type Server} from 'node:http';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
test.skip(process.env.RUN92_CAPTURE!=='1','Opt-in final Showcase visual evidence; real public provider responses only.');
let server:Server,landingUrl:string;
test.beforeAll(async()=>{const html=readFileSync(resolve(process.cwd(),'../../landing/index.html'));server=createServer((_req,res)=>res.writeHead(200,{'content-type':'text/html; charset=utf-8'}).end(html));await new Promise<void>(done=>server.listen(0,'127.0.0.1',done));const addr=server.address();if(!addr||typeof addr==='string')throw Error('No local landing address');landingUrl=`http://127.0.0.1:${addr.port}`;});
test.afterAll(async()=>{if(server)await new Promise<void>(done=>server.close(()=>done()));});
for(const width of [1440,1024,390,320])test(`final Showcase visuals ${width}`,async({page},info)=>{
 test.skip(info.project.name!=='desktop','One capture per explicit viewport');test.setTimeout(180000);await page.setViewportSize({width,height:1000});const folder=resolve(process.cwd(),'../../docs/verification/run9-2');mkdirSync(folder,{recursive:true});
 const capture=async(name:string,selector?:string)=>{await page.evaluate(()=>document.fonts.ready);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${name} ${width}px overflow`).toBe(true);if(selector)await page.locator(selector).screenshot({path:`${folder}/${name}-${width}.png`,animations:'disabled',scale:'css'});else await page.screenshot({path:`${folder}/${name}-${width}.png`,fullPage:true,animations:'disabled',scale:'css'});};
 await page.route('https://fonts.googleapis.com/**',route=>route.abort());await page.route('https://fonts.gstatic.com/**',route=>route.abort());await page.goto(landingUrl);await expect(page.locator('.consumer-slogan')).toHaveText("Today's Goals, Habits & Health = Tomorrow's Wealth");const line=page.locator('.consumer-slogan .slogan-line').first();expect(await line.evaluate(el=>el.children[1]!.getBoundingClientRect().right)).toBeLessThanOrEqual(width);await capture('landing');
 await page.goto('/app/settings');await expect(page.getByRole('button',{name:'Load Showcase Demo',exact:true})).toBeEnabled();await capture('showcase-activation','.showcase-controls');await page.getByRole('button',{name:'Load Showcase Demo',exact:true}).click();await page.waitForURL('**/app');await expect(page.getByRole('complementary',{name:'Showcase data'})).toBeVisible();await expect(page.getByRole('region',{name:'Life and Wealth snapshot'})).toContainText('13 assets');
 await page.goto('/app/wealth/asset/showcase-btc');await expect(page.locator('.price-chart-plot')).toBeVisible({timeout:30000});await expect.poll(()=>page.locator('.price-chart [data-observation]').count()).toBeGreaterThan(10);await expect(page.locator('.asset-detail-price')).not.toHaveText('Unavailable');
 const publicEvidence=await page.locator('.price-chart').innerText();writeFileSync(`${folder}/public-chart-${width}.txt`,publicEvidence);
 const routes:[string,string,string?][]=[['today','/app'],['hero-slogan','/app','.today-hero'],['needs-attention','/app','.needs-attention'],['goals','/app/goals'],['goal-create','/app/goals/new'],['goal-detail','/app/goals/tracked/9201'],['funding-wealth','/app/goals/tracked/9201','[aria-label="Funding Wealth overview"]'],['wealth','/app/wealth'],['watchlist','/app/wealth','.market-watch'],['portfolio-composition','/app/wealth','.portfolio-composition'],['markets','/app/markets'],['asset-detail','/app/wealth/asset/showcase-btc'],['market-chart','/app/wealth/asset/showcase-btc','.price-chart'],['positions','/app/goals/positions'],['habits','/app/habits'],['habit-history','/app/habits','.habit-consistency'],['health','/app/health'],['activity','/app/activity'],['ecosystem','/app/ecosystem'],['settings','/app/settings'],['showcase-control','/app/settings','.showcase-controls']];
 for(const [name,route,selector] of routes){await page.goto(route);await expect(page.locator('main h1').first()).toBeVisible();await expect(page.getByRole('complementary',{name:'Showcase data'})).toBeVisible();if(route==='/app')await expect(page.getByRole('region',{name:'Life and Wealth snapshot'})).toContainText('13 assets');if(route==='/app/wealth')await expect(page.locator('.owned-asset-card')).toHaveCount(13);if(route==='/app/markets')await expect(page.locator('.market-product-card').first()).toBeVisible();if(route==='/app/goals/tracked/9201')await expect(page.getByRole('region',{name:'Goal timeline'})).toContainText('Contribution recorded');if(name==='asset-detail'||name==='market-chart')await expect(page.locator('.price-chart-plot')).toBeVisible();await capture(name,selector);}
 await page.goto('/app/wealth');await page.getByRole('button',{name:'+ Add asset',exact:true}).first().click();await expect(page.getByRole('dialog',{name:'Add to your wealth'})).toBeVisible();await expect(page.getByRole('searchbox',{name:'Search assets'})).toBeEnabled({timeout:30000});await page.getByRole('searchbox',{name:'Search assets'}).fill('Bitcoin');await expect(page.getByRole('list',{name:'Market assets'}).getByRole('button').first()).toBeVisible();await page.getByRole('list',{name:'Market assets'}).getByRole('button').first().scrollIntoViewIfNeeded();await page.screenshot({path:`${folder}/asset-add-${width}.png`,animations:'disabled',scale:'css'});await page.getByRole('dialog',{name:'Add to your wealth'}).getByRole('button',{name:'Close dialog',exact:true}).click();await expect(page.getByRole('dialog',{name:'Add to your wealth'})).not.toBeVisible();await page.getByRole('button',{name:'+ Quick add',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.screenshot({path:`${folder}/quick-add-${width}.png`,animations:'disabled',scale:'css'});
});
