import {test,expect,type Page} from '@playwright/test';
import {applyLocal,initialLedger} from '../lib/local-ledger';
import {emptyPlatform,positionSchema,privateGoalSchema} from '../lib/positions';
const fixture=()=>({...emptyPlatform(),positions:['a','b','c'].map((id,i)=>positionSchema.parse({id,providerId:'native-zig',sourceType:'NATIVE_STAKING',network:'zigchain-1',account:'fictional-preview-account',asset:'ZIG',denom:'uzig',decimals:6,quantity:['200000000000','63559957014','263000000'][i],verification:'VERIFIED_READ_ONLY',sync:'CURRENT',observedAt:new Date().toISOString(),liquidity:'BONDED',provenance:'Fictional preview fixture',validator:{address:`fictional-validator-${id}`,name:`Example validator ${id.toUpperCase()}`,status:'BONDED',commission:'0.05',votingTokens:'1000000000000'}})),goals:['81','82','83'].map((id,i)=>privateGoalSchema.parse({id,name:['300K ZIG Goal','Small start','Reached destination'][i],type:'QUANTITY',status:'completed',asset:'ZIG',denom:'azig',decimals:18,target:i===2?'1000000000000000000':'300000000000000000000000',notes:'Fictional preview',createdAt:new Date().toISOString(),milestones:[]})),allocations:[{goalId:'81',positionId:'a',quantity:'200000000000'},{goalId:'81',positionId:'b',quantity:'63559957014'},{goalId:'82',positionId:'c',quantity:'262000000'},{goalId:'83',positionId:'c',quantity:'1000000'}]});
async function seed(page:Page,data=fixture()){await page.goto('/app/goals');await page.evaluate(s=>localStorage.setItem('zigoals:platform:v1',JSON.stringify(s)),data);if(data.goals.length){await page.evaluate(({ledger,metadata})=>{localStorage.setItem('zigoals:local-ledger:v1',JSON.stringify(ledger));localStorage.setItem('zigoals:metadata:v1:local-simulation:local-demo-user',JSON.stringify(metadata));},{ledger:applyLocal(applyLocal(initialLedger(),{kind:'create'},'2026-09-17T00:00:00.000Z'),{kind:'deposit',id:'1',amount:'100000000000000000000'},'2026-09-17T00:00:00.000Z'),metadata:{schemaVersion:1,chainId:'local-simulation',walletAddress:'local-demo-user',goals:{'1':{name:'Kyoto in spring',category:'Travel',targetValue:'1200',currency:'ZIG',targetDate:'2027-09-18',startingAmount:'0',monthlyContribution:'100',riskPreference:'Conservative',liquidityPreference:'Anytime',deadlineFlexible:false,notes:''}}}});}await page.reload();}
test('one collection reconciles incomplete flags, preserves deep links and shows ownership inline',async({page},info)=>{
 await seed(page);await expect(page.getByRole('navigation',{name:'Goal views'})).toHaveCount(1);
 await expect(page.getByRole('heading',{name:'300K ZIG Goal',exact:true})).toBeVisible();await expect(page.locator('.goal-card').filter({hasText:'300K ZIG Goal'})).toContainText('87.85%');
 await expect(page.getByRole('heading',{name:'Small start',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Kyoto in spring',exact:true})).toBeVisible();
 if(process.env.RUN81_CAPTURE==='1')await page.screenshot({path:info.outputPath('unified-goals-active.png'),fullPage:true});
 await page.getByRole('button',{name:'Completed',exact:true}).click();await expect(page.getByRole('heading',{name:'Reached destination',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'300K ZIG Goal',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Small start',exact:true})).toHaveCount(0);
 if(process.env.RUN81_CAPTURE==='1')await page.screenshot({path:info.outputPath('completed-filter.png'),fullPage:true});
 await page.goto('/app/goals/tracked');await expect(page.getByRole('heading',{name:'Your goals.',exact:true})).toBeVisible();
 await page.goto('/app/goals/positions');const card=page.getByRole('article').filter({has:page.getByRole('heading',{name:'Example validator A',exact:true})});await expect(card).toContainText('Allocated to Goals');await expect(card).toContainText('300K ZIG Goal');await expect(card.getByRole('link',{name:'Manage allocation →'})).toHaveAttribute('href','/app/goals/tracked/81#allocate');
 if(process.env.RUN81_CAPTURE==='1')await card.screenshot({path:info.outputPath('allocation-ownership.png')});
 await page.goto('/app/goals/tracked/82#allocate');const form=page.locator('#allocate form');await form.getByLabel('Position to allocate').selectOption('a');await expect(form).toContainText('Available for this Goal: 0 ZIG');await expect(form).toContainText('300K ZIG Goal');await form.getByLabel('Allocation quantity').fill('1');await form.getByRole('button',{name:'Save allocation'}).click();await expect(form.getByRole('alert')).toContainText('Only 0 ZIG');
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('zigoals:platform:v1')!));expect(before.goals[0].status).toBe('completed');await form.getByLabel('Allocation quantity').fill('0');await form.getByRole('button',{name:'Save allocation'}).click();await expect(form.getByRole('alert')).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('zigoals:platform:v1')!).goals[0].status)).toBe('active');
});
test('unified creator explicitly allocates existing wealth and optionally creates a Habit without financial authority',async({page},info)=>{
 const data=fixture();data.goals=[];data.allocations=[];await seed(page,data);
 await page.goto('/app/goals/positions');await page.getByRole('link',{name:'Create a Goal for this Position →'}).first().click();await expect(page).toHaveURL(/\/app\/goals\/new\?position=a/);
 const requests:string[]=[];page.on('request',r=>{if(r.method()==='POST'||/rpc|api\/positions/.test(r.url()))requests.push(r.url());});await page.evaluate(()=>Object.defineProperty(window,'keplr',{get(){throw Error('Wallet access prohibited');}}));
 await page.getByLabel('Goal name',{exact:true}).fill('My new destination');await page.getByLabel('Target amount',{exact:true}).fill('300000');
 if(process.env.RUN81_CAPTURE==='1')await page.screenshot({path:info.outputPath('unified-create.png'),fullPage:true});
 await page.getByRole('button',{name:'Continue →'}).click();await expect(page.getByText(/^Available stake:/)).toBeVisible();
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('zigoals:platform:v1')!).allocations)).toEqual([]);
 if(process.env.RUN81_CAPTURE==='1')await page.screenshot({path:info.outputPath('position-source-selection.png'),fullPage:true});
 await page.getByLabel('Allocate available stake up to Goal target',{exact:true}).check();await page.getByLabel('Add a contribution plan').check();await page.getByLabel('Planned amount',{exact:true}).fill('500');await page.getByLabel('Contribution asset',{exact:true}).fill('USD');await page.getByLabel('Price per Goal unit').fill('0.05');await page.getByRole('button',{name:'Continue →'}).click();await page.getByLabel('Create supporting Habit',{exact:true}).check();await page.getByRole('button',{name:'Continue →'}).click();await expect(page.getByText('No funds move. Allocations are private Goal accounting.',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('zigoals:platform:v1')!).allocations)).toEqual([]);
 await page.getByRole('button',{name:'Create goal',exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('87.94%');await expect(page.getByRole('heading',{name:'Buy ZIG',exact:true})).toBeVisible();await page.getByRole('button',{name:'Complete Buy ZIG',exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('87.94%');expect(requests).toEqual([]);
});
test('creation without allocation confirmation saves an empty Goal',async({page})=>{
 const data=fixture();data.goals=[];data.allocations=[];await seed(page,data);await page.goto('/app/goals/new?position=a');await page.getByLabel('Goal name',{exact:true}).fill('No allocation');await page.getByLabel('Target amount',{exact:true}).fill('300000');for(let i=0;i<3;i++)await page.getByRole('button',{name:'Continue →'}).click();await page.getByRole('button',{name:'Create goal',exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('0.00%');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('zigoals:platform:v1')!).allocations)).toEqual([]);
});
test('unified creator preserves Local Demo and legacy detail',async({page})=>{
 await page.goto('/app/goals/new');await page.getByLabel('Goal name',{exact:true}).fill('Local destination');await page.getByLabel('Target amount',{exact:true}).fill('1200');await page.getByRole('button',{name:'Continue →'}).click();await page.getByLabel('ZIGoals funding / Local simulation',{exact:true}).check();await page.getByRole('button',{name:'Continue →'}).click();await page.getByRole('button',{name:'Continue →'}).click();await expect(page.getByText('Simulation only.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Create goal',exact:true}).click();await page.getByRole('button',{name:'Confirm simulation'}).click();await expect(page).toHaveURL(/\/app\/goals\/\d+$/);await expect(page.getByRole('heading',{name:'Local destination',exact:true})).toBeVisible();await page.goto('/app/goals');await expect(page.getByRole('heading',{name:'Local destination',exact:true})).toBeVisible();
});
test('unified responsive Goals and creator keep navigation and Health intact',async({page},info)=>{
 await seed(page);await page.emulateMedia({reducedMotion:'reduce'});
 for(const width of info.project.name==='desktop'?[1440,768]:[390,320]){
  await page.setViewportSize({width,height:1000});for(const [name,route] of [['goals','/app/goals'],['create','/app/goals/new']]){await page.goto(route!);await expect(page.locator('main h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${name} ${width}`).toBe(true);if(process.env.RUN81_CAPTURE==='1')await page.screenshot({path:info.outputPath(`${name}-${width}.png`),fullPage:true});if(name==='create'){await page.getByLabel('Goal name',{exact:true}).fill('My next chapter');await page.getByLabel('Target amount',{exact:true}).fill('300000');for(let step=1;step<=3;step++){await page.getByRole('button',{name:'Continue →'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`creator step ${step+1} at ${width}`).toBe(true);}}}
 }
 await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Stake / Positions',exact:true}).click();await expect(page).toHaveURL(/\/goals\/positions$/);await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Health',exact:true}).click();await expect(page).toHaveURL(/\/app\/health$/);expect(await page.evaluate(()=>localStorage.getItem('zigoals:health:v1'))).toBeNull();
});

test('Project completion follows milestones and Value/Reward Goals keep their own source semantics',async({page})=>{
 await page.goto('/app/goals/new');await page.getByLabel('Goal name',{exact:true}).fill('Learn something');await page.getByLabel('Goal type').selectOption('PROJECT');await page.getByLabel('Milestones, one per line').fill('Read\nPractice');for(let i=0;i<3;i++)await page.getByRole('button',{name:'Continue →'}).click();await page.getByRole('button',{name:'Create goal',exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('0.00%');await page.getByLabel('Read',{exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('50.00%');await page.getByLabel('Practice',{exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('100.00%');await page.goto('/app/goals');await page.getByRole('button',{name:'Completed',exact:true}).click();await expect(page.getByRole('heading',{name:'Learn something',exact:true})).toBeVisible();
 for(const type of ['VALUE','REWARD']){await page.goto('/app/goals/new');await page.getByLabel('Goal name',{exact:true}).fill(`${type} destination`);await page.getByLabel('Goal type').selectOption(type);await page.getByLabel('Target amount',{exact:true}).fill('100');for(let i=0;i<3;i++)await page.getByRole('button',{name:'Continue →'}).click();await page.getByRole('button',{name:'Create goal',exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('0.00%');}
});
test('Local simulation remains creatable when independent Position storage is malformed',async({page})=>{
 await page.goto('/app/goals/new');await page.evaluate(()=>localStorage.setItem('zigoals:platform:v1','broken'));await page.reload();await page.getByLabel('Goal name',{exact:true}).fill('Independent local Goal');await page.getByLabel('Target amount',{exact:true}).fill('1200');await page.getByRole('button',{name:'Continue →'}).click();await page.getByLabel('ZIGoals funding / Local simulation',{exact:true}).check();for(let i=0;i<2;i++)await page.getByRole('button',{name:'Continue →'}).click();await page.getByRole('button',{name:'Create goal',exact:true}).click();await page.getByRole('button',{name:'Confirm simulation'}).click();await expect(page.getByRole('heading',{name:'Independent local Goal',exact:true})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('zigoals:platform:v1'))).toBe('broken');
});
test('failed Habit write retries without duplicating Goal or re-allocating reserved units',async({page})=>{
 const data=fixture();data.goals=[];data.allocations=[];await seed(page,data);await page.goto('/app/goals/new?position=a');await page.getByLabel('Goal name',{exact:true}).fill('Retry destination');await page.getByLabel('Target amount',{exact:true}).fill('300000');await page.getByRole('button',{name:'Continue →'}).click();await page.getByLabel('Allocate a specific Position',{exact:true}).check();await page.getByLabel('Units to allocate').fill('200000');await page.getByLabel('Add a contribution plan').check();await page.getByLabel('Planned amount',{exact:true}).fill('100');await page.getByRole('button',{name:'Continue →'}).click();await page.getByLabel('Create supporting Habit',{exact:true}).check();await page.getByRole('button',{name:'Continue →'}).click();
 await page.evaluate(()=>{const original=Storage.prototype.setItem;let failed=false;Storage.prototype.setItem=function(key,value){if(key==='zigoals:habits:v1'&&!failed){failed=true;throw new Error('Injected one-time write failure');}return original.call(this,key,value);};});
 await page.getByRole('button',{name:'Create goal',exact:true}).click();await expect(page.getByRole('link',{name:'Open saved Goal →'})).toBeVisible();await expect(page.getByRole('button',{name:'Create goal',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Create goal',exact:true}).click();await expect(page.getByTestId('tracked-progress')).toContainText('66.66%');const saved=await page.evaluate(()=>({p:JSON.parse(localStorage.getItem('zigoals:platform:v1')!),h:JSON.parse(localStorage.getItem('zigoals:habits:v1')!)}));expect(saved.p.goals).toHaveLength(1);expect(saved.p.allocations).toHaveLength(1);expect(saved.h.habits).toHaveLength(1);
});
