import {test,expect} from 'vitest';
import {contributionTemplate,reconcileContributionHabit,contributionHabitEffectiveFrom,createContributionHabit} from './contribution-habit';
import {createHabit,emptyHabitData,habitRuleOn,logHabitValue} from './habits';
import {habitEditFingerprint} from './habit-actions';
import {privateGoalSchema,emptyPlatform} from './positions';
import {reviseGoalPlan} from './plan-revisions';
// The habits keep a UTC journal, as `now` and the day strings below are written (Session Y Part 2).
const now=new Date('2026-09-26T12:00:00Z'),id='59a35604-3696-4a78-b455-4015acb66885';
function fixture(){const goal=privateGoalSchema.parse({id:'77',name:'Reserve',type:'QUANTITY',status:'active',asset:'ZIG',denom:'azig',decimals:18,target:'200000000000000000000',notes:'',createdAt:now.toISOString(),milestones:[],plan:{amount:'10000',asset:'USD',decimals:2,cadence:'monthly',nextDate:'2026-09-26',active:true,habitId:id}});const habits=logHabitValue(createHabit({...emptyHabitData(),timeZone:'UTC'},contributionTemplate(goal,'2026-09-26')!,now,id),id,'2026-09-26',100,{},now);return {goal,habits};}
test('contribution reconciliation respects future plan effectiveness and retains today rules and entries',()=>{const {goal,habits}=fixture(),before=structuredClone(habits),changed=reviseGoalPlan({...emptyPlatform(),goals:[goal]},goal.id,{...goal.plan!,amount:'20000',cadence:'weekly'},'2026-10-02',+now).goals[0]!;expect(contributionHabitEffectiveFrom(changed,habits.habits[0]!,'2026-09-26')).toBe('2026-10-02');expect(()=>reconcileContributionHabit(habits,changed,id,'2026-09-27',now,habitEditFingerprint(habits.habits[0]!))).toThrow(/plan/i);const next=reconcileContributionHabit(habits,changed,id,'2026-10-02',now,habitEditFingerprint(habits.habits[0]!));expect(next.habits[0]!.entries).toEqual(before.habits[0]!.entries);expect(next.habits[0]!.rules[0]).toEqual(before.habits[0]!.rules[0]);expect(habitRuleOn(next.habits[0]!,'2026-10-02')).toMatchObject({target:200,schedule:{period:'week'}});expect(()=>reconcileContributionHabit(next,changed,id,'2026-10-02',now,habitEditFingerprint(habits.habits[0]!))).toThrow(/changed/i);});
test('inactive or ended plans pause only from the reviewed future date and cannot mutate an unrelated habit',()=>{const {goal,habits}=fixture(),changed={...goal,plan:{...goal.plan!,active:false}};const next=reconcileContributionHabit(habits,changed,id,'2026-09-27',now,habitEditFingerprint(habits.habits[0]!));expect(habitRuleOn(next.habits[0]!,'2026-09-26')?.state).toBe('active');expect(habitRuleOn(next.habits[0]!,'2026-09-27')?.state).toBe('paused');expect(()=>reconcileContributionHabit(habits,{...changed,id:'88'},id,'2026-09-27',now)).toThrow(/belongs|linked/i);expect(goal.plan?.active).toBe(true);});

test('creating a supporting Habit from future plan terms retains current behavior until the revision date',()=>{const {goal}=fixture(),changed=reviseGoalPlan({...emptyPlatform(),goals:[goal]},goal.id,{...goal.plan!,amount:'20000'},'2026-10-02',+now).goals[0]!;const next=createContributionHabit({...emptyHabitData(),timeZone:'UTC'},changed,id,now);expect(habitRuleOn(next.habits[0]!,'2026-09-26')?.target).toBe(100);expect(habitRuleOn(next.habits[0]!,'2026-10-02')?.target).toBe(200);});
