import {test,expect} from 'vitest';
import {createHabit,emptyHabitData,habitCalendarDay,saveHabitTimezone,logHabitValue,habitDataSchema} from './habits';
import {scheduleHabitEdit,startHabitTimer,pauseHabitTimer,commitHabitTimer,habitTimerPreview} from './habit-actions';
import {widgetMetric} from './dashboard-metrics';
import {emptyPlatform} from './positions';
import {createEmptyHealth} from './health';
const id='59a35604-3696-4a78-b455-4015acb66885',timer='ff829326-f352-4a26-80d0-eb8c31cde62e';
const input={title:'Read',category:'Personal',description:'',notes:'',schedule:{kind:'daily' as const},target:30,measurement:{kind:'duration' as const,unit:'minutes' as const}};
test('Today widgets use the saved Habit day independently of the device and Health day',()=>{
 const now=new Date('2026-09-26T00:30:00Z');let habits=createHabit(saveHabitTimezone(emptyHabitData(),'America/Los_Angeles'),input,now,id);habits=logHabitValue(habits,id,'2026-09-25',30,{},now);
 const sources={platform:emptyPlatform(),habits,health:createEmptyHealth(),goals:[],quotes:[],now:+now,today:'2026-09-26',healthDate:'2026-09-26'},widget={id:'today',kind:'habits' as const,metric:'today',title:'',size:'compact' as const,hidden:false,revision:1};
 expect(widgetMetric(widget,sources).value).toBe('1 of 1 complete');expect(widgetMetric({...widget,kind:'habit',entity:id},sources).detail).toContain('complete');
 expect(widgetMetric(widget,{...sources,habits:saveHabitTimezone(habits,'Europe/Brussels')}).value).toBe('0 of 1 complete');
});
test('saved Habit timezone pins calendar dates across devices and DST while preserving historical date-only entries',()=>{const now=new Date('2026-09-26T00:30:00Z');let data=saveHabitTimezone(emptyHabitData(),'America/Los_Angeles');expect(habitCalendarDay(data,now)).toBe('2026-09-25');data=createHabit(data,input,now,id);expect(data.habits[0]?.startDate).toBe('2026-09-25');data=logHabitValue(data,id,'2026-09-25',30,{},now);expect(()=>logHabitValue(data,id,'2026-09-26',30,{},now)).toThrow();expect(()=>scheduleHabitEdit(data,id,{...input,target:40},'2026-09-25',now)).toThrow();expect(scheduleHabitEdit(data,id,{...input,target:40},'2026-09-26',now).habits[0]?.rules.at(-1)?.from).toBe('2026-09-26');const old=structuredClone(data.habits);data=saveHabitTimezone(data,'Europe/Brussels');expect(data.habits).toEqual(old);expect(habitCalendarDay(data,now)).toBe('2026-09-26');expect(habitCalendarDay({timeZone:'America/New_York'},new Date('2026-11-01T05:30:00Z'))).toBe('2026-11-01');expect(habitCalendarDay({timeZone:'America/New_York'},new Date('2026-11-01T06:30:00Z'))).toBe('2026-11-01');expect(habitDataSchema.parse(JSON.parse(JSON.stringify(data)))).toEqual(data);});
test('timer uses saved journal timezone and elapsed timestamps across a repeated DST hour; zone changes require manual review',()=>{const now=new Date('2026-11-01T05:30:00Z'),data=createHabit(saveHabitTimezone(emptyHabitData(),'America/New_York'),input,now,id),running=startHabitTimer(data,id,timer,now),paused=pauseHabitTimer(running,id,timer,new Date('2026-11-01T06:30:00Z'));expect(running.habits[0]?.timer?.timeZone).toBe('America/New_York');expect(habitTimerPreview(paused.habits[0]!,new Date('2026-11-01T06:30:00Z')).value).toBe(60);expect(commitHabitTimer(paused,id,timer,new Date('2026-11-01T06:30:00Z')).habits[0]?.entries[0]?.count).toBe(60);expect(()=>commitHabitTimer(saveHabitTimezone(paused,'Europe/Brussels'),id,timer,new Date('2026-11-01T06:30:00Z'))).toThrow(/timezone/i);});
