import {expect,test} from 'vitest';
import {portfolioComposition,needsAttention,fundingAgenda,marketUniverse} from './product-insights';
import {buildShowcase} from './showcase-data';
import {emptyPlatform,PLATFORM_KEY,type Platform} from './positions';
import {wealthOverview} from './wealth';
const data=()=>JSON.parse(buildShowcase('2026-09-21').records[PLATFORM_KEY]!) as Platform;
const now=Date.parse('2026-09-21T12:00:00Z');
test('composition preserves separate currency totals and distinguishes ETFs',()=>{const p=data(),overview=wealthOverview(p,now),groups=portfolioComposition(overview);expect(groups.map(g=>g.currency)).toEqual(expect.arrayContaining(['USD','EUR']));for(const group of groups){expect(group.segments.reduce((n,s)=>n+s.value,0n)).toBe(group.total);expect(group.segments.reduce((n,s)=>n+s.basisPoints,0)).toBe(group.total?10000:0);}expect(groups.find(g=>g.currency==='USD')!.segments.some(s=>s.label==='ETFs')).toBe(true);});
test('attention has specific corrective links and excludes completed and project plan reminders',()=>{const p=data(),items=needsAttention(p,now,[]);expect(items.some(i=>i.goalId==='9203'&&i.kind==='overdue')).toBe(true);expect(items.some(i=>i.positionId==='showcase-zig')).toBe(true);expect(items.some(i=>i.goalId==='9204'||i.goalId==='9205')).toBe(false);expect(items.every(i=>i.href.startsWith('/app/')&&i.action.length>0)).toBe(true);expect(needsAttention(emptyPlatform(),now,[])).toEqual([]);});
test('agenda uses explicit schedule credits and keeps unmatched history separate',()=>{const p=data(),agenda=fundingAgenda(p,now,[]);expect(agenda.find(a=>a.goalId==='9201')?.nextDate!=='2026-08-24').toBe(true);expect(agenda.some(a=>a.goalId==='9203'&&a.overdue)).toBe(true);expect(agenda.every(a=>a.goalId!=='9205'&&a.goalId!=='9204')).toBe(true);});
test('market universe deduplicates owned favourites without manufacturing ownership',()=>{const rows=marketUniverse(data());expect(new Set(rows.map(r=>r.key)).size).toBe(rows.length);const sol=rows.find(r=>r.ref.id==='solana')!;expect(sol.favourite).toBe(true);expect(sol.positionIds).toEqual([]);const btc=rows.find(r=>r.ref.id==='bitcoin')!;expect(btc.favourite).toBe(true);expect(btc.positionIds).toEqual(['showcase-btc']);expect(rows.every(r=>r.ref.provider==='coingecko')).toBe(true);});
test('composition exposes top holdings and reconciled allocated/available values within each currency',()=>{
 const p=emptyPlatform();const base=data().positions.find(p=>p.id==='showcase-usd')!;p.positions=[{...base,id:'usd-a',providerId:'Larger USD',quantity:'10000',valuation:{...base.valuation!,value:'10000'}},{...base,id:'usd-b',providerId:'Smaller USD',quantity:'5000',valuation:{...base.valuation!,value:'5000'}},{...base,id:'eur',providerId:'EUR asset',asset:'EUR',quantity:'20000',valuation:{...base.valuation!,value:'20000',currency:'EUR'}}];p.goals=[data().goals[0]!];p.allocations=[{goalId:p.goals[0]!.id,positionId:'usd-a',quantity:'2500'}];
 const groups=portfolioComposition(wealthOverview(p,now));const usd=groups.find(g=>g.currency==='USD')!,eur=groups.find(g=>g.currency==='EUR')!;expect(usd).toMatchObject({total:15000n,allocated:2500n,available:12500n,topHoldings:[{id:'usd-a',name:'Larger USD',value:10000n},{id:'usd-b',name:'Smaller USD',value:5000n}]});expect(eur).toMatchObject({total:20000n,allocated:0n,available:20000n,topHoldings:[{id:'eur',value:20000n}]});
});
