/** Fictional, deterministic example records. Never written into a normal private or market store. */
import {emptyPlatform,platformSchema,PLATFORM_KEY,type Platform,type Position,type PrivateGoal,type ContributionEvent} from './positions';
import {contributionTotals} from './goal-intelligence';
import {emptyHabitData,createHabit,habitDataSchema,HABITS_KEY,type HabitInput} from './habits';
import {createEmptyHealth,healthSchema,HEALTH_STORAGE_KEY,HEALTH_MEALS} from './health';
import type {MarketAssetRef} from './market-assets';
const coin=(id:string):MarketAssetRef=>({provider:'coingecko',kind:'coin',id});
const rwa=(id:string,assetType:'stock'|'etf'|'commodity'):MarketAssetRef=>({provider:'coingecko',kind:'rwa',id,assetType});
export function buildShowcase(day:string){
 const clock=Date.parse(day+'T12:00:00Z');if(!/^20\d{2}-\d{2}-\d{2}$/.test(day)||!Number.isFinite(clock)||new Date(clock).toISOString().slice(0,10)!==day)throw Error('Use a real showcase date.');
 const date=(offset:number)=>new Date(clock+offset*86400000).toISOString().slice(0,10),at=(offset:number)=>new Date(date(offset)+'T00:00:00').toISOString(),now=at(0),start=at(-90);
 const specs:{asset:string;name:string;class:Position['assetClass'];quantity:string;decimals:number;value?:string;currency?:string;ref?:MarketAssetRef}[]=[
  {asset:'BTC',name:'Bitcoin',class:'Crypto',quantity:'45000000',decimals:8,value:'4500000',ref:coin('bitcoin')},
  {asset:'ETH',name:'Ethereum',class:'Crypto',quantity:'400000000',decimals:8,value:'1600000',ref:coin('ethereum')},
  {asset:'ZIG',name:'ZIG reward reserve',class:'Crypto',quantity:'300000000000',decimals:6,value:'1800000',ref:coin('zignaly')},
  {asset:'USDC',name:'USD Coin',class:'Stablecoins',quantity:'12000000000',decimals:6,value:'1200000',ref:coin('usd-coin')},
  {asset:'AAPL',name:'Apple',class:'Stocks',quantity:'30',decimals:0,value:'750000',ref:rwa('apple','stock')},
  {asset:'NVDA',name:'Nvidia',class:'Stocks',quantity:'40',decimals:0,value:'760000',ref:rwa('nvidia','stock')},
  {asset:'GOLD',name:'Gold · troy ounces',class:'Precious Metals',quantity:'10',decimals:0,value:'4400000',ref:rwa('gold','commodity')},
  {asset:'SILVER',name:'Silver · troy ounces',class:'Precious Metals',quantity:'100',decimals:0,value:'520000',ref:rwa('silver','commodity')},
  {asset:'VOO',name:'Vanguard S&P 500 ETF',class:'Stocks',quantity:'100',decimals:0,value:'6000000',ref:rwa('vanguard-s-p-500-etf','etf')},
  {asset:'USD',name:'USD cash reserve',class:'Cash',quantity:'2500000',decimals:2,value:'2500000'},
  {asset:'EUR',name:'EUR travel cash',class:'Cash',quantity:'800000',decimals:2,value:'800000',currency:'EUR'},
  {asset:'HOME',name:'Riverside apartment',class:'Property',quantity:'1',decimals:0,value:'32000000'},
  {asset:'CUSTOM',name:'Collectible camera',class:'Custom',quantity:'1',decimals:0,value:'250000'},
 ];
 let platform:Platform={...emptyPlatform(),positions:specs.map(s=>({id:`showcase-${s.asset.toLowerCase()}`,providerId:s.name,sourceType:s.asset==='ZIG'?'NATIVE_REWARDS':'MANUAL',network:'manual',account:'showcase-fictional',asset:s.asset,denom:s.asset,quantity:s.quantity,decimals:s.decimals,assetClass:s.class,marketRef:s.ref,valuationMode:'manual',quoteCurrency:s.currency==='EUR'?'EUR':'USD',valuation:s.value?{value:s.value,currency:s.currency??'USD',decimals:2,source:'MANUAL',observedAt:now}:undefined,liquidity:s.class==='Property'?'LOCKED':'LIQUID',verification:'MANUAL',sync:s.asset==='ZIG'?'STALE':'MANUAL',observedAt:s.asset==='ZIG'?at(-3):now,trackingStartedAt:start,provenance:'SHOWCASE DATA · fictional manual example, no wallet observation',notes:s.name,risk:'Showcase example only',executionAuthority:'NONE'}))};
 const goal=(id:string,name:string,type:PrivateGoal['type'],target:string,extra:Partial<PrivateGoal>={}):PrivateGoal=>({id,name,type,target,asset:'USD',denom:'USD',decimals:2,status:'active',network:'zigchain-1',notes:'SHOWCASE DATA · fictional plan and history',createdAt:start,milestones:[],...extra});
 const plan=(amount:string,asset='USD',decimals=2)=>({amount,asset,decimals,cadence:'monthly' as const,nextDate:date(-28),endDate:date(450),active:true});
 platform.goals=[goal('9201','Emergency fund','VALUE','2000000',{category:'Emergency Fund',pinned:true,plan:plan('50000'),targetDate:date(365)}),goal('9202','First home deposit','VALUE','8000000',{category:'First Home',plan:plan('200000'),targetDate:date(450)}),goal('9203','Japan adventure','VALUE','600000',{category:'Travel',plan:plan('50000'),targetDate:date(150)}),goal('9204','My first 0.1 BTC','QUANTITY','10000000',{asset:'BTC',denom:'BTC',decimals:8,category:'Financial Freedom'}),goal('9205','Launch my creative studio','PROJECT','4',{decimals:0,asset:'milestones',denom:'milestones',milestones:[{id:'studio-1',title:'Define the offer',done:true},{id:'studio-2',title:'Create the portfolio',done:true},{id:'studio-3',title:'Find the first client',done:false},{id:'studio-4',title:'Launch the studio',done:false}]}),goal('9206','Reward income reserve','REWARD','20000000000',{asset:'ZIG',denom:'ZIG',decimals:6,plan:plan('1000000000','ZIG',6),targetDate:date(365)})];
 platform.allocations=[{goalId:'9201',positionId:'showcase-usd',quantity:'500000'},{goalId:'9201',positionId:'showcase-usdc',quantity:'4000000000'},{goalId:'9202',positionId:'showcase-voo',quantity:'50'},{goalId:'9202',positionId:'showcase-gold',quantity:'5'},{goalId:'9203',positionId:'showcase-usd',quantity:'250000'},{goalId:'9204',positionId:'showcase-btc',quantity:'10000000'},{goalId:'9206',positionId:'showcase-zig',quantity:'10000000000'}];
 const event=(id:string,goalId:string,quantity:string,offset:number,extra:Partial<ContributionEvent>={}):ContributionEvent=>({id,goalId,goalScope:'private',direction:'IN',quantity,asset:'USD',decimals:2,occurredAt:at(offset),provenance:'MANUAL_ATTRIBUTION',fundingMode:'FUND_GOAL',note:'SHOWCASE DATA · fictional contribution',...extra});
 platform.contributions=[...[-25,-20,-15,-10,-5,0].map((offset,i)=>event(`example-emergency-${i}`,'9201','12500',offset,{positionId:'showcase-usd',scheduledDate:date(-28)})),...[-26,-19,-12,-5].map((offset,i)=>event(`example-home-${i}`,'9202','50000',offset,{scheduledDate:date(-28)})),event('example-travel','9203','10000',-12,{scheduledDate:date(-28)}),event('example-history','9203','2500',-1,{fundingMode:'HISTORY_ONLY'}),event('example-correction','9203','2500',0,{direction:'OUT',fundingMode:'HISTORY_ONLY',reversesId:'example-history'}),event('example-unmatched','9201','1',0,{asset:'CUSTOM',decimals:0,fundingMode:'HISTORY_ONLY'}),event('example-reward','9206','500000000',-2,{asset:'ZIG',decimals:6,provenance:'REWARD_INCOME',fundingMode:'HISTORY_ONLY'})];
 platform.watchlist=[...specs.filter(s=>['BTC','ETH','ZIG','NVDA','GOLD','VOO'].includes(s.asset)).map(s=>({ref:s.ref!,name:s.name,symbol:s.asset})),{ref:coin('solana'),name:'Solana',symbol:'SOL'}];
 platform.assetEvents=platform.positions.map((p,i)=>({id:`example-asset-${i}`,positionId:p.id,name:p.notes,assetClass:p.assetClass!,kind:'added',at:start,provenance:'PRIVATE_EDIT'}));
 platform.assetEvents.push(...platform.positions.filter(p=>['BTC','NVDA','GOLD','VOO','EUR','HOME','CUSTOM'].includes(p.asset)).map((p,i)=>({id:`example-asset-edit-${i}`,positionId:p.id,name:p.providerId,assetClass:p.assetClass!,kind:'edited' as const,at:at(-(i%2)),provenance:'PRIVATE_EDIT' as const})));
 // Fifteen dated observations per asset over 90 days, below the unchanged retention caps.
 for(let step=0;step<15;step++)for(const p of platform.positions){const offset=-84+step*6,ratio=840+step*11;const value=(BigInt(p.valuation!.value)*BigInt(ratio)/1000n).toString();platform.valuationSnapshots.push({id:`example-value-${p.id}-${step}`,positionId:p.id,quantity:p.quantity,quantityDecimals:p.decimals,value,decimals:2,currency:p.valuation!.currency,source:'MANUAL',observedAt:at(offset),capturedAt:at(offset)});}
 const currents:Record<string,string>={'9201':'900000','9202':'5200000','9203':'250000','9204':'10000000','9205':'2','9206':'10000000000'};
 for(let step=0;step<30;step++)for(const g of platform.goals){const current=(BigInt(currents[g.id]!)*BigInt(55+step*45/29|0)/100n).toString();platform.goalHistory.push({id:`example-goal-${g.id}-${step}`,goalId:g.id,kind:'valuation',capturedAt:at(-29+step),current,target:g.target,asset:g.asset,decimals:g.decimals,actualContributed:contributionTotals(platform,g.id,Date.parse(at(-29+step))).net,rewardIncome:contributionTotals(platform,g.id,Date.parse(at(-29+step))).rewardIncome,planned:g.plan?.amount??'0',requiresReview:g.id==='9206',evidence:[]});}
 for(const p of platform.positions)if(['BTC','ETH'].includes(p.asset)){p.valuationMode='automatic';delete p.valuation;}
 platform.goalHistory.push({id:'example-plan-change',goalId:'9202',kind:'plan',capturedAt:at(-14),label:'Monthly contribution plan reviewed · Showcase',provenance:'LOCAL_EDIT'},{id:'example-milestone',goalId:'9205',kind:'milestone',capturedAt:at(-1),label:'Portfolio completed · Showcase',provenance:'LOCAL_EDIT'});
 platform=platformSchema.parse(platform);
 let habits=emptyHabitData();const titles=['Read','Exercise','Walk','Meditate','Contribute','Drink water'],targets=[30,30,8000,10,1,8],units=['minutes','minutes','steps','minutes','times','glasses'];
 titles.forEach((title,i)=>{const id=`92000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`;const input:HabitInput={title,category:i===4?'Wealth':i===0?'Learning':'Wellbeing',description:'A small daily step toward tomorrow.',notes:'SHOWCASE DATA · fictional 30-day history',schedule:{kind:'daily'},target:targets[i]!,measurement:{kind:'count',unit:units[i]!}};habits=createHabit(habits,input,new Date(at(-29)),id);const h=habits.habits.at(-1)!;h.entries=Array.from({length:30},(_,n)=>({date:date(-29+n),count:n===29?(i%2===0?targets[i]!:Math.floor(targets[i]!/2)):(n+i)%9===0?0:targets[i]!,disposition:(n+i)%9===0&&n!==29?'skipped' as const:'logged' as const,note:'Showcase example',updatedAt:at(-29+n)}));h.updatedAt=now;});habits=habitDataSchema.parse(habits);
 const health=createEmptyHealth();health.targets={kcal:2200,proteinMg:120000,carbsMg:260000,fatMg:73000,weightGrams:72000,steps:8000};
 const meals=[['Berry overnight oats',420,22000,59000,12000],['Chicken and quinoa bowl',620,44000,70000,18000],['Salmon, rice and greens',690,48000,69000,25000],['Yogurt and almonds',240,17000,19000,10000]] as const;
 meals.forEach(([name,kcal,proteinMg,carbsMg,fatMg],i)=>health.foods.push({id:`health_food-000${i}`,name,brand:'Showcase kitchen',servingGrams:300,nutrients:{kcal,proteinMg,carbsMg,fatMg},createdAt:start,updatedAt:start}));
 for(let n=0;n<30;n++){const d=date(-29+n),stamp=at(-29+n);health.foods.forEach((f,i)=>health.diary.push({id:`health_diary-${String(n).padStart(3,'0')}-${i}`,sourceId:f.id,sourceKind:'food',snapshot:{name:f.name,servingGrams:f.servingGrams,nutrients:f.nutrients},date:d,meal:HEALTH_MEALS[i]!,quantityMilli:n===29?1000:900+(n%5)*50,createdAt:stamp,updatedAt:stamp}));health.activity.push({id:`health_activity-${String(n).padStart(3,'0')}`,date:d,name:'Showcase walk',steps:6000+(n%5)*700,minutes:35+n%4*5,createdAt:stamp,updatedAt:stamp});if(n%4===0)health.weights.push({id:`health_weight-${String(n).padStart(3,'0')}`,date:d,grams:74600-n*40,createdAt:stamp,updatedAt:stamp});}
 const records:Record<string,string>={[PLATFORM_KEY]:JSON.stringify(platform),[HABITS_KEY]:JSON.stringify(habits),[HEALTH_STORAGE_KEY]:JSON.stringify(healthSchema.parse(health))};
 return {day,records};
}
