import Link from 'next/link';
import type {ReactNode} from 'react';
import {PageHeader} from '../page-header';
import {InstallGuide} from './install-guide';
import {KeepData} from './keep-data';
import {HelpQuestion} from './help-question';
import {SendFeedback} from './send-feedback';
import './help.css';
import {SYNC_WRITES} from '../../lib/vault/sync-writes';


const TOPICS: [id: string, label: string][] = [
  ['getting-started', 'Getting started'], ['data-and-sync', 'Your data and sync'], ['recovery-secret', 'Your recovery secret'],
  ['install', 'Install on iPhone'], ['backups', 'Optional backups'], ['your-ai', 'ZIGi · your AI'], ['questions', 'Questions'], ['whole-life', 'New: your whole life'], ['whats-new-alpha', 'What\'s new'], ['known-limitations', 'Known limitations'], ['feedback', 'Send feedback'],
];

function Section({id, eyebrow, title, children}: {id: string; eyebrow: string; title: string; children: ReactNode}) {
  return <section className="panel help-section" id={id} aria-labelledby={`help-${id}`}>
    <p className="eyebrow">{eyebrow}</p>
    <h2 id={`help-${id}`}>{title}</h2>
    {children}
  </section>;
}
function Question({question, children}: {question: string; children: ReactNode}) {
  return <details className="help-question"><summary>{question}</summary><div>{children}</div></details>;
}

/**
 * Help (Session L): plain answers for the friends Alpha, following the owner principle. Static text plus two small
 * client parts (the install guide and "Keep my data on this device"). It makes no request and writes nothing on view.
 */
export function HelpPage() {
  return <div className="help-page">
    <PageHeader titleId="help-title" eyebrow="Help & guides" title="Help." lede="How ZIGoals keeps your plans, and how to get the most out of the Alpha."/>
    <p className="help-back"><Link className="text-link" href="/app/settings">← Back to Settings</Link></p>
    <nav className="help-topics" aria-label="Help topics">{TOPICS.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>

    <Section id="getting-started" eyebrow="GETTING STARTED" title="Three small first steps">
      <ol className="help-steps">
        <li><strong>Your first Goal.</strong> In <Link className="text-link" href="/app/goals">Goals</Link>, choose <strong>+ Create a goal</strong>: name it, pick what you are aiming for, and follow the steps.</li>
        <li><strong>Your first Habit.</strong> In <Link className="text-link" href="/app/habits">Habits</Link>, choose <strong>+ New habit</strong>, start from a template or your own title, and tap it each day you do it.</li>
        <li><strong>Quick counters.</strong> In <Link className="text-link" href="/app/health">Health</Link>, <strong>Quick counters</strong> add today&rsquo;s repetitions with one tap, and the Water card in the Diary logs a set amount with one tap (Add 250 mL, or sizes you choose).</li>
      </ol>
      <p>Today brings them together. Want the guided tour again? <Link className="text-link" href="/app/welcome">Show the welcome</Link>.</p>
    </Section>

    <Section id="data-and-sync" eyebrow="YOUR DATA AND SYNC" title="Where your data lives">
      <h3>Before accounts open</h3>
      <p>Your Goals, Habits, Health and Wealth live only on this device, in this browser. Browser storage is not encrypted: anyone who can use this browser profile could read it, so keep your phone and computer locked.</p>
      <h3>Once accounts open</h3>
      <p>You sign in with a code sent to your email, and turn on encrypted sync once: it&rsquo;s offered right after you sign in. From then on, every device you unlock stays up to date automatically. No backups or transfers by hand. Turn on encrypted sync on your first device before you start using a second one.</p>
      <p>Your data is end-to-end encrypted on your device before it leaves; nobody else can read it, as long as the app code we serve has not been tampered with. A device you chose to remember can open it too. The server stores that encrypted data plus what it needs to deliver it: your account, record identifiers, sizes, times, and which part of the app a record belongs to. It cannot read your plans, habits or health entries. Health syncs only if you turn it on, separately.</p>
      <h3>Signing in is not recovery</h3>
      <p>Your email code proves it&rsquo;s you. It cannot unlock your data: only your recovery secret can. ZIGoals asks for it when you open your account on a device; a password manager can fill it in. On your own phone or computer you can tick &ldquo;Remember on this device&rdquo;: ZIGoals then opens your account there without asking again, until you lock it or choose Forget this device in Settings. Locking locks every tab of this browser. Don&rsquo;t use it on a shared computer.</p>
    </Section>

    <Section id="recovery-secret" eyebrow="YOUR RECOVERY SECRET" title="The one thing to keep safe">
      <p>When you turn on encrypted sync, your device creates a long random <strong>recovery secret</strong>. It is the only key to your encrypted data you can write down (a device you chose to remember holds the vault key too), and it is shown only then.</p>
      <ul className="help-list">
        <li><strong>Keep it in a password manager</strong>, or written down somewhere safe and offline.</li>
        <li><strong>Never share it</strong>: not in screenshots, chats or support emails. We will never ask for it.</li>
        <li><strong>Lost a device?</strong> Revoke it under Settings → Devices and sessions, then rotate the vault key (Settings → Rotate vault encryption) so a remembered copy cannot open new records. Sign in on another device and unlock with the secret; sync brings everything back.</li>
        <li><strong>Lost the secret, but a device still opens your account?</strong> On that device, choose Rotate vault encryption in Settings to get a new secret, and save it.</li>
        <li><strong>Lost the secret and every device that opens your account?</strong> Then the data is gone. Nobody, including us, can unlock it.</li>
      </ul>
    </Section>

    <Section id="install" eyebrow="INSTALL ON IPHONE" title="Install ZIGoals on your iPhone">
      <InstallGuide/>
      <h3>Protect what&rsquo;s on this device</h3>
      <p>Before accounts open, your data lives only on this device: installing ZIGoals and keeping its data on this device protect it. Once accounts open, you turn encrypted sync on once, and every device you unlock stays up to date automatically. A backup is only an optional extra safety net.</p>
      <h3>Keep my data on this device</h3>
      <KeepData/>
    </Section>

    <Section id="backups" eyebrow="OPTIONAL BACKUPS" title="An extra safety net, never a chore">
      <p>You don&rsquo;t need backups to stay up to date: once sync is on, your devices keep each other current. A backup is just an extra copy you can keep if you like, and the way to move records you already made in Safari into the installed app.</p>
      <ul className="help-list">
        <li><strong>Encrypted backup:</strong> one file protected by its own separate secret. Make or restore one under <Link className="text-link" href="/app/settings#private-vault">Settings → Keep a protected copy</Link>.</li>
        <li><strong>Readable exports</strong> of a single part (the Positions and Goals, Habits or Health backup) are plain files with your personal data: store them privately.</li>
      </ul>
    </Section>

    <Section id="your-ai" eyebrow="ZIGI · YOUR AI" title="Your own AI, page by page">
      <p><strong>ZIGi</strong> is a chat inside ZIGoals that answers with an AI <em>you</em> connect: an API key you pay for, a model running on your own computer, or, if you only have a ChatGPT, Claude, Grok or Gemini subscription, a prompt you copy into that app. It is <strong>Premium, free during the Alpha</strong>. Set it up in <Link className="text-link" href="/app/settings#your-ai">Settings &rarr; ZIGi &middot; your AI</Link>; then the ZIGi button sits at the bottom right (above the tabs on a phone), and &#8984;K / Ctrl+K opens it too.</p>
      <p>ZIGi is not the Guide. The Guide is ZIGoals&rsquo; own calm note from your records, made on this device with no AI service at all. ZIGi is your AI talking about your records, and it also answers simple questions about them on this device, with no AI at all.</p>
      <HelpQuestion id="your-ai-what" question="What does ZIGi send, and to whom?"><p>Only to the provider you connected, straight from your browser: your message, the records your question needs and the page&rsquo;s data as plain text if sharing is on for those areas, your own instructions, and the last few messages within your context budget. Nothing passes through ZIGoals&rsquo; servers and nothing is logged there (ZIGoals hosted, when it is offered to you, is the one exception, and you agree to it first). Sharing starts on for Today, Goals, Habits, Wealth and Help and <strong>off for Health</strong>; Health needs its own switch too. Open the chat and expand &ldquo;What your AI sees&rdquo; for the exact text. Identifiers, wallet addresses, chain details, account and sync data are never included.</p></HelpQuestion>
      <HelpQuestion id="your-ai-writes" question="Can ZIGi change my records?"><p>Not by itself. When you ask it to log or create something, it shows a card that says exactly what would be written and where. You add it, edit it or dismiss it, and you can undo an addition for ten seconds. Money is different: ZIGi can only pre-fill the add-asset form, which you review and save yourself. It can never contribute, allocate, stake, touch a wallet or chain, or change sync, export, deletion or settings.</p></HelpQuestion>
      <HelpQuestion id="your-ai-cost" question="What does it cost?"><p>ZIGoals bills nothing. An API key is pay-as-you-go with your provider, who shows you the usage; ZIGi shows the token counts your provider reports under each reply and in Settings &rarr; ZIGi &middot; your AI &rarr; Usage, and money only as an estimate from prices you enter yourself, with an optional monthly cap. The reply length is capped (Settings &rarr; Output cap), and ZIGi asks before sending more page data than your context budget. A local model costs nothing to run.</p></HelpQuestion>
      <HelpQuestion id="your-ai-subscriptions" question="I pay for ChatGPT, Claude, Grok or Gemini. Can ZIGi use that?"><p>Not directly: those subscriptions have no connection a browser app may use, and ZIGoals will never ask for your password or read your cookies. Choose &ldquo;I only have a subscription&rdquo;: ZIGi writes the question with your page data, you press <strong>Copy for my AI</strong>, open the app and paste. OpenRouter is the one provider with an official sign-in for apps like this one; it gives ZIGoals a key you can see and revoke on OpenRouter.</p></HelpQuestion>
      <HelpQuestion id="your-ai-local" question="How do I use a model on my own computer?"><p>Run Ollama or LM Studio, then choose &ldquo;I run a model on this computer&rdquo; and test the connection. <strong>Ollama</strong> must allow this site: set <code>OLLAMA_ORIGINS=https://alpha.zigoals.app</code> (macOS: <code>launchctl setenv OLLAMA_ORIGINS https://alpha.zigoals.app</code>; Linux: <code>systemctl edit ollama.service</code> with <code>Environment=&quot;OLLAMA_ORIGINS=https://alpha.zigoals.app&quot;</code>; Windows: a user environment variable), then restart it. <strong>LM Studio</strong>: Developer &rarr; Server Settings &rarr; <strong>Enable CORS</strong>. <strong>Chrome 142</strong> and later asks once whether this site may connect to devices on your local network: allow it. A phone cannot reach a computer&rsquo;s localhost.</p></HelpQuestion>
      <HelpQuestion id="your-ai-keys" question="Where is my key kept?"><p>On this device only, never synced, never exported, never shown back. With &ldquo;Remember on this device&rdquo; it is encrypted at rest with a key that never leaves this browser, which protects against casual reading of the disk or a backup, not against malware on the device. Without it, the key lives in the page and is forgotten when the tab closes. Showcase keeps keys for the session only. Disconnect or &ldquo;Turn off ZIGi&rdquo; removes them; signing out of an account removes that account&rsquo;s remembered keys.</p></HelpQuestion>
      <HelpQuestion id="your-ai-voice" question="Can I talk to ZIGi?"><p>Yes, two ways you choose in Settings. Your browser&rsquo;s speech recognition: Chrome may send the audio to Google unless on-device recognition is available, Safari may send it to Apple, Firefox has none. Or a recording of up to a minute transcribed by your provider with your key (OpenAI documents this). The words land in the message box for you to edit. ZIGi can also read replies aloud with your device&rsquo;s voices; that is off by default.</p></HelpQuestion>
      <HelpQuestion id="your-ai-honest" question="Does ZIGi give health or money advice?"><p>No. It summarises what you recorded and helps you log; it gives no medical, dietary, financial or investment advice, no targets and no judgement. Food values it estimates are marked &ldquo;AI estimate&rdquo;, and anything it cannot know stays &ldquo;unknown&rdquo;. Every reply is labelled as your AI&rsquo;s answer, not ZIGoals&rsquo;. Your AI can be wrong: check what matters.</p></HelpQuestion>
      <HelpQuestion id="your-ai-data" question="Can I ask ZIGi about my records, like “How many minutes did I meditate this month?”"><p>Yes. ZIGi reads the dates in your question (today, yesterday, this or last week, this or last month, the last 30 days, since a date, between two dates, a named month) in your own time zone, and finds the habit, goal, food or coin you name. Totals, counts, minutes, averages, streaks, best days, progress and &ldquo;when did I last&rdquo; are answered <strong>on this device, with no AI at all</strong>, labelled &ldquo;Answered on your device &middot; no AI used&rdquo;, with the records it used. That works before you connect an AI, and in Showcase. When two things match, ZIGi asks which one you mean instead of guessing; when it does not know, it says so. &ldquo;Ask my AI for more&rdquo; sends the same question with the same records to your AI. Health is only read when its gate is open.</p></HelpQuestion>
      <HelpQuestion id="your-ai-tools" question="How does my AI get the records it needs?"><p>Two ways, both read-only. With <strong>Tools</strong>, your AI asks ZIGi for exactly what it needs (&ldquo;meditation, this month&rdquo;), ZIGi looks it up on this device and sends back only that; the reply shows &ldquo;ZIGi looked at:&rdquo; chips you can open to see the data. With <strong>Attach</strong>, ZIGi picks the records from your question and the page and shows them as chips you can remove before you send. <strong>Automatic</strong> (the default) uses tools where your model takes them and attaches otherwise. Either way only what your switches allow, never on private screens, and changes still come only as cards you confirm. &ldquo;Think deeper&rdquo; asks again with a second model you choose. Settings &rarr; ZIGi &middot; your AI &rarr; Advanced.</p></HelpQuestion>
      <HelpQuestion id="your-ai-act" question="What can ZIGi log or plan for me?"><p>Ask in your own words, type <code>/log</code>, or hold the microphone and talk: ZIGi turns one message into cards, for example a breakfast as a meal, a glass of water and a habit check-in, with &ldquo;Add all&rdquo; and one Undo. It can propose foods, recipes, a meal plan, grocery items, counters, check-ins in minutes or amounts, reminders, a goal plan with milestones, a new habit with its reminder, and your weekly intention. Nothing is written until you add a card. With a model that reads images and Health shared, you can add a <strong>photo of a meal</strong>: it goes only with that message to your AI and is never kept; the cards say &ldquo;Estimated by your AI from a photo&rdquo;, and what it cannot know stays unknown. Money stays a pre-filled form you save yourself. Confirmed actions are listed under Activity &rarr; Actions by ZIGi.</p></HelpQuestion>
      <HelpQuestion id="your-ai-notes" question="What does ZIGi know about me?"><p>Only the notes you keep in Settings &rarr; ZIGi &middot; your AI &rarr; <strong>What ZIGi knows about me</strong>: goals, preferences, constraints, diet style, schedule, up to 100 notes. ZIGi may suggest one on a &ldquo;Remember this?&rdquo; card; nothing is kept until you confirm. Notes go to your AI only while &ldquo;Use my notes&rdquo; is on, as an &ldquo;About me&rdquo; chip you see first; notes about health or your diet style only while Health is shared with ZIGi. Delete one or all at any time; they are in Export everything and never synced.</p></HelpQuestion>
      <HelpQuestion id="your-ai-pack" question="What is the context pack?"><p>A file of your records for your AI&rsquo;s own project knowledge (Claude Projects, ChatGPT Projects, Gemini Gems and similar), so an AI you use outside ZIGoals knows your goals, habits and wealth between chats. Settings &rarr; ZIGi &middot; your AI &rarr; <strong>Context pack for my AI</strong>, or <code>/pack</code>: choose the areas and the period (90 days unless you change it), see the preview, then download it (Markdown or JSON) or copy it. Health is in it only with its gate open and its own box ticked. It carries no account data, ids, keys, wallet addresses or recovery data. <strong>It is not encrypted:</strong> anyone and any AI you give it to can read it. A weekly &ldquo;new context pack&rdquo; reminder is optional.</p></HelpQuestion>
      <HelpQuestion id="your-ai-suggestions" question="Where do ZIGi’s chips, brief and patterns come from?"><p>From your records, worked out on this device; nothing is sent to make them. The chips above the message box change daily and can be dismissed. With a Friendly greeting ZIGi opens the day with a short brief (what is due, one win from yesterday, one focus), and a quiet brief card can show on Today while ZIGi is connected. &ldquo;Ask ZIGi&rdquo; next to a number puts that number in the message box; nothing is sent before you press Send. Patterns appear only with enough days, are &ldquo;a pattern, not proof&rdquo;, and never medical or financial advice. <code>/review</code> walks through your week with you.</p></HelpQuestion>
      <HelpQuestion id="your-ai-commands" question="Which slash commands and shortcuts does ZIGi know?"><p>Type <code>/</code> in the message box for the list: <code>/log</code> logs what you did, ate or drank as cards; <code>/ask</code> sends a question straight to your AI; <code>/plan</code> plans a goal or a habit as cards; <code>/review</code> goes through your week on this device; <code>/pack</code> opens the context pack; <code>/insights</code> shows patterns in your records; <code>/remember</code> proposes a note for What ZIGi knows about me; <code>/help</code> lists them. Press <kbd>?</kbd> outside the message box for the keyboard shortcuts; &#8984;K / Ctrl+K opens and closes ZIGi.</p></HelpQuestion>
      <HelpQuestion id="your-ai-mini-window" question="What is ZIGi’s mini window?"><p>On a computer with Chrome or Edge 116 and later, or Firefox 151 and later, <strong>Pop out</strong> in ZIGi&rsquo;s panel opens the same chat in a small window that stays on top of your other apps while ZIGoals&rsquo; tab is open. &ldquo;Back to tab&rdquo; returns it; closing the tab closes it. When the tab shows a private screen, the window blurs and waits. Safari and phones do not offer it, so the button is not shown there. A companion that lives on your desktop without the tab would need a native app, which ZIGoals does not have.</p></HelpQuestion>
      <HelpQuestion id="your-ai-knock" question="Can ZIGi knock when a reminder is due?"><p>If you turn it on: ZIGi asks you once, or use &ldquo;Knock when a reminder is due&rdquo; in ZIGi&rsquo;s look and feel. When a habit, your water or one of ZIGi&rsquo;s weekly reminders is due, ZIGi peeks out above its button and knocks once, with <strong>Do it now</strong>, <strong>Snooze</strong> (15 minutes, 1 hour or tonight) and <strong>Not today</strong>. At most three a day, never between 22:00 and 08:00, never on private screens or while ZIGi is hidden, never on Today (the reminder has its own card there), and no sound. ZIGi&rsquo;s weekly reminders are listed, with Remove, under Settings &rarr; ZIGi &middot; your AI &rarr; Reminders.</p></HelpQuestion>
      <HelpQuestion id="your-ai-agents" question="Can an AI agent in my browser use ZIGoals?"><p>Only if your browser offers tools to its AI agents (WebMCP, an early Chrome feature; today only with <code>chrome://flags/#enable-webmcp-testing</code> turned on) <strong>and</strong> you turn on &ldquo;Let browser AI agents use ZIGoals tools&rdquo; in Settings &rarr; ZIGi &middot; your AI. It is off by default and the card only shows in such a browser. An agent then gets ZIGi&rsquo;s read-only lookups under the same switches as your AI, and can propose changes, which appear as cards in ZIGi&rsquo;s panel for you to add. Every request shows at once in a ZIGi notice with exactly what went back and &ldquo;Turn off browser agents&rdquo;. Nothing on Settings or private screens.</p></HelpQuestion>
      <HelpQuestion id="your-ai-which-setup" question="Which setup fits me?"><p>Settings &rarr; ZIGi &middot; your AI &rarr; <strong>Which setup fits me?</strong> asks three or four questions (what you have today, where you use ZIGoals, what matters most to you and, on a computer, its memory) and suggests one way, with honest pros and cons and the exact steps: your subscription through Copy for my AI, a model on your computer (Ollama or LM Studio), an API key with a spending limit set at your provider first, or Chrome&rsquo;s on-device model (and ZIGoals hosted, once it is offered to you). It is worked out on this device; nothing is sent.</p></HelpQuestion>
      <HelpQuestion id="your-ai-on-device" question="What is Chrome’s on-device model?"><p>A small model inside Chrome on some computers (Chrome 148 and later on Windows, macOS, Linux and some Chromebooks; not on phones). Where Chrome has it, Settings shows a card for it; Chrome downloads the model only when you press its button there, a one-time download that needs about 22 GB of free space. Then, while no AI is connected, it words ZIGi&rsquo;s brief, helps ZIGi understand a question, and gives short general answers labelled &ldquo;Answered by Chrome&rsquo;s on-device model&rdquo;. It gets only your words, never your records, and nothing leaves the computer.</p></HelpQuestion>
      <HelpQuestion id="your-ai-hosted" question="What is ZIGoals hosted?"><p>An AI that ZIGoals runs and pays for, for invited accounts during the Alpha, so you need no key or app of your own. It is <strong>not available yet</strong>; when it is offered to you, it appears in Settings &rarr; ZIGi &middot; your AI. Before first use you read what passes through and agree: your messages and the records ZIGi attaches go through ZIGoals&rsquo; server to the AI provider named there, which writes the reply. ZIGoals stores and logs none of it and keeps only counts for the daily limit. Health goes only if you tick its own box and the Health gate is open. Replies say &ldquo;Answer from &lt;provider&gt; via ZIGoals hosted&rdquo;. Stop using it at any time.</p></HelpQuestion>
      <HelpQuestion id="your-ai-look" question="Can I change how ZIGi looks?"><p>Yes: <strong>Customize</strong> in ZIGi&rsquo;s panel, or ZIGi&rsquo;s look and feel in Settings. Choose the look, the animation (Calm by default, Full or Off), the side, the size, the greeting and the edge tab. Reduced motion and Motion Off always win: ZIGi then holds still. <Link className="text-link" href="/app/zigi">Meet ZIGi</Link> shows all its moods.</p></HelpQuestion>
      <HelpQuestion id="your-ai-off" question="How do I turn ZIGi off, or hide the button?"><p>Settings &rarr; ZIGi &middot; your AI &rarr; Advanced &rarr; <strong>Turn off ZIGi</strong> removes the keys from this device and resets the switches; tick &ldquo;Also delete all chats&rdquo; to remove the conversations too. The small arrow under the button, <strong>Hide ZIGi</strong>, hides it (undo for ten seconds); the &ldquo;Show ZIGi&rdquo; tab at the edge of the screen, &ldquo;Show the ZIGi button&rdquo; in Settings, or &ldquo;Show ZIGi again&rdquo; in a phone&rsquo;s More sheet brings it back. You can turn the edge tab off in ZIGi&rsquo;s look and feel.</p></HelpQuestion>
    </Section>

    <Section id="questions" eyebrow="QUESTIONS" title="Good to know about the Alpha">
      <Question question="Is any of this real money?"><p>No. The Alpha is a local simulation and a testnet preview: nothing is bought, sold or sent, and testnet tokens have no value.</p></Question>
      <Question question="Are my Goals on the blockchain?"><p>Not yet. The on-chain Goal contract is not deployed, so Goals stay in this app.</p></Question>
      <Question question="Where do prices come from?"><p>Automatic prices come from CoinGecko and are labelled with their source. ZIGoals asks only about the public assets you choose, never your amounts, Goals or wallet. If automatic prices are unavailable, the app says so and your own values keep working: a value you enter yourself is labelled as a manual value, never shown as a live quote.</p></Question>
      <Question question="Can I look up a food by its barcode?"><p>When product lookup is available, yes: in Health&rsquo;s Diary, open &ldquo;Scan or look up a food barcode&rdquo;. Only the barcode number is sent, through ZIGoals to Open Food Facts; the camera picture stays on your device. If the live camera is blocked or missing, you can take one photo of the barcode instead; it is read on your device too. When lookups are busy, the button waits for the time shown and then works again. If lookup is unavailable or a product isn&rsquo;t found, add the food yourself in Foods &amp; recipes.</p></Question>
      <Question question="Is my data encrypted on this device?"><p>No. Browser storage isn&rsquo;t encrypted, so lock your device. With encrypted sync, your data is encrypted on your device before it leaves.</p></Question>
      <Question question="I asked for a sign-in code and none arrived"><p>During the friends Alpha, only invited email addresses can sign in, and ZIGoals answers every code request the same way, so it never tells anyone which addresses are invited. If no code arrives: wait a minute and check your spam folder; make sure you typed the address your invite went to; then try again later, because codes can be held back when many are sent at once. Still nothing? Ask the person who invited you, or write to <a className="text-link" href="mailto:contact@zigoals.app">contact@zigoals.app</a>. Nothing on this device changes while you wait: your local records stay where they are.</p></Question>
      <Question question="Sync says &ldquo;Sync needs attention&rdquo;. Did I lose something?"><p>No. Your changes are kept on this device. When sync found two versions it won&rsquo;t merge by itself, it keeps both until you choose: open <Link className="text-link" href="/app/settings#encrypted-sync">Settings → Account &amp; devices</Link> (Account &amp; sync on a phone), unlock, and choose &ldquo;Review conflicting account records&rdquo;.</p></Question>
      {SYNC_WRITES && <Question question="Can my Portfolio sync too?"><p>Yes, if you choose: in Settings, under account sync, tick &ldquo;Also sync my Portfolio (optional)&rdquo;. An encrypted copy of your whole Portfolio then travels with your account, separate from your other records, and never feeds Wealth or Goals. If it changed on two devices, ZIGoals asks which one to keep. After you change your vault key, open ZIGoals on a device that has your Portfolio so it can upload it again.</p></Question>}
    </Section>

    {/* Session W Part 24: this release's features, each answer linkable from What's new and the feature itself. */}
    <Section id="whole-life" eyebrow="NEW: YOUR WHOLE LIFE" title="Sleep, mind, music, chess, links and more">
      <p>This release adds sleep, meditation, focus sounds, chess, your own links and a music player, ways to bring your data from other apps, and more control over what shows. Everything is optional, works on this device first, and keeps your numbers honest.</p>
      <HelpQuestion id="w-pages" question="Can I hide pages and buttons I don&rsquo;t use?"><p>Yes: Settings &rarr; <Link className="text-link" href="/app/settings#your-pages">Your pages &amp; buttons</Link> has a switch for every page and button (Settings and Help always show), the page ZIGoals opens on, and &ldquo;Show everything again&rdquo;. A hidden page keeps its records and still opens from a link, with a note to show it again. With sync on, the choices travel with your settings.</p></HelpQuestion>
      <HelpQuestion id="w-welcome" question="Can I see the welcome again?"><p>Yes: <Link className="text-link" href="/app/welcome">Show the welcome</Link>. Picking what you want to improve sets your pages and Today; nothing is saved before &ldquo;Finish setup&rdquo;, and running it again adds nothing twice.</p></HelpQuestion>
      <HelpQuestion id="w-sleep" question="How does Sleep work, and what is sleep debt?"><p>Health &rarr; Sleep: log a night or a nap, or tap &ldquo;I&rsquo;m going to bed&rdquo; and &ldquo;I woke up&rdquo;; add quality, tags and a note. Sleep debt is, for each logged night of the last 7 days, your goal minus the time you slept, added up; bedtime consistency is how much your bedtimes vary over the last 14 nights (at least 4). Time asleep says &ldquo;estimated&rdquo; until you add how long it took to fall asleep and how long you were awake in the night. This is not medical advice: if poor sleep goes on, talk to a doctor.</p></HelpQuestion>
      <HelpQuestion id="w-meditation" question="What does Meditation keep?"><p>The sessions you time or breathe through, your mood before and after if you note it, a note, minutes you did elsewhere, and a weekly goal if you set one, in your Health journal like the rest of Health. The breathing circle moves only while the page is visible and motion is allowed; otherwise words and a count guide you.</p></HelpQuestion>
      <HelpQuestion id="w-sounds" question="Where do the focus sounds come from?"><p>In Health &rarr; Meditation, or in the music player once you show it. They are made in your browser: no file is downloaded and nothing is requested. A timer up to 90 minutes fades them out; &ldquo;Stop when I leave ZIGoals&rdquo; stops them when you switch away; a reload stops them too.</p></HelpQuestion>
      <HelpQuestion id="w-import" question="Can I bring my data from Apple Health, Fitbit or other apps?"><p>Yes: Settings &rarr; <Link className="text-link" href="/app/settings#switch-import">Switch to ZIGoals</Link> reads Apple Health&rsquo;s export.zip, Fitbit or Google Health (a Takeout CSV), Samsung Health, Oura (CSV) and Loop Habit Tracker on this device, nothing uploaded. A preview shows what fits, Health&rsquo;s box starts unticked, and each import can be undone. Garmin, Fitbit&rsquo;s older JSON export and Streaks are recognised but not read yet, and say why.</p></HelpQuestion>
      <HelpQuestion id="w-devices" question="Can I connect my watch, ring or scale?"><p>In Health, open Devices from &ldquo;Next on your Health journey&rdquo; (<a className="text-link" href="/app/health?view=devices">Health &rarr; Devices</a>{/* eslint-disable-line @next/next/no-html-link-for-pages -- a full load: Health's Bluetooth policy applies to its own document */}): a Bluetooth heart-rate monitor or scale works in Chrome or Edge on a computer or an Android phone (not on iPhone: Safari has no Web Bluetooth). Oura, Withings, Polar and Strava are built but need ZIGoals to register with each service first, so they say &ldquo;Needs setup by ZIGoals&rdquo;. Apple Health has no web connection: import its export (above). Health Connect on Android has none either, and no export ZIGoals reads: import from the app that writes to it, such as Samsung Health or Google Health.</p></HelpQuestion>
      <HelpQuestion id="w-quick" question="What are the quick buttons in the diary?"><p>&ldquo;Copy yesterday&rsquo;s&rdquo; breakfast, lunch, dinner or snacks, &ldquo;Repeat yesterday&rdquo;, your pinned and usual items as one-tap chips, and your own water sizes. Each copies exactly what you logged.</p></HelpQuestion>
      <HelpQuestion id="w-habits" question="What are challenges and stacks?"><p>A challenge is a habit with its own end date, 30 days or your choice from 7 to 365, with one calm note when it ends; rest days are neutral. A stack shows habits you do one after another together, with an optional reminder on this device.</p></HelpQuestion>
      <HelpQuestion id="w-goals" question="What do milestones and &ldquo;On track?&rdquo; show?"><p>Milestones with a value and a date, marked on the goal&rsquo;s bar. &ldquo;On track?&rdquo; works with zero return and your own numbers: what is left, the date it points to, and what it needs per week or month. A &ldquo;what if it grew&rdquo; figure is your own assumption and is never stored.</p></HelpQuestion>
      <HelpQuestion id="w-wealth" question="Where do my accounts and debts live?"><p>On this device, until account sync carries them in a later release. Net worth is shown per currency, never converted; holdings with a known value count as their own line, and an unknown value is never counted as zero. A payoff date appears only from your own rate and payments. Nothing links to a bank, and nothing moves money.</p></HelpQuestion>
      <HelpQuestion id="w-wrapup" question="What is the evening wrap-up?"><p>A card on Today, off until you turn it on in Settings &rarr; <Link className="text-link" href="/app/settings#wrap-up">Evening wrap-up</Link>: from the time you choose (18:00 unless you change it) it lets you tick off the day, write tomorrow&rsquo;s intention and, if you like, note a mood (kept in Health).</p></HelpQuestion>
      <HelpQuestion id="w-chess" question="What does Chess send to chess.com and Lichess?"><p>Only the usernames you enter, each to its own site, from your browser, one request at a time, for public data. Puzzles and TV load only when you tap them, and &ldquo;Play&rdquo; opens the site. Chess is hidden until you show it under Your pages &amp; buttons.</p></HelpQuestion>
      <HelpQuestion id="w-portfolio" question="Where do Portfolio&rsquo;s charts and changes come from?"><p>From your own transactions and CoinGecko&rsquo;s dated prices; a gap is never guessed. The 1-hour and 7-day changes and the market figures need the updated market service and say &ldquo;Not provided&rdquo; until it runs.</p></HelpQuestion>
      <HelpQuestion id="w-links" question="What can I put in My links?"><p>Your socials, apps and sites as https links, with your own name and a plain icon (never a network&rsquo;s logo). Each opens in a new tab without a referrer; ZIGoals adds nothing to the address and fetches nothing from it.</p></HelpQuestion>
      <HelpQuestion id="w-music" question="Can ZIGoals play my Spotify or Apple Music?"><p>The focus sounds always play. Spotify works once this site&rsquo;s owner has registered it, with Spotify Premium: ZIGoals controls Spotify&rsquo;s own apps and speakers and plays nothing in the page, and while Spotify keeps ZIGoals in development mode only up to five accounts the owner lists can connect. The Spotify sign-in stays sealed on this device. Apple Music opens in its own app; playing it inside ZIGoals needs an Apple Developer membership. The music player is hidden until you show it.</p></HelpQuestion>
      <HelpQuestion id="w-signout" question="How do I sign out all my other devices?"><p>Settings &rarr; <Link className="text-link" href="/app/settings#encrypted-sync">Account &amp; devices</Link> (Account &amp; sync on a phone) &rarr; Devices and sessions &rarr; &ldquo;Sign out all other devices&rdquo;: every other device stops syncing at once and is signed out at the email provider; this one stays signed in. What they already downloaded stays on them, so after losing a device also rotate the vault key.</p></HelpQuestion>
      <HelpQuestion id="w-newer-section" question="What does &ldquo;saved by a newer ZIGoals&rdquo; mean?"><p>Using sleep, meditation, your pages or links raises the format of that part of your data (Health, or Today&rsquo;s settings). An older ZIGoals, on a device not yet updated or opening a copy made here, can&rsquo;t read that part: it says so, keeps it as it is and changes nothing. Update that device and everything is read again; nothing is lost.</p></HelpQuestion>
      <HelpQuestion id="w-web-limits" question="What can&rsquo;t a web app do?"><p>It can&rsquo;t sync in the background, and it can&rsquo;t remind you while it is closed unless you turn on &ldquo;Reminders when closed&rdquo;; Bluetooth works only in Chrome and Edge (not on iPhone); on an installed iPhone app, connect services from Safari, because their sign-in pages open outside the app; and Apple Health has no web access at all, so use its export.</p></HelpQuestion>
    </Section>

    <Section id="whats-new-alpha" eyebrow="WHAT&rsquo;S NEW" title="New in this Alpha, in your own words">
      <p>Eleven small things arrived together. Each is optional and counts only your own entries.</p>
      <HelpQuestion id="auto-checkins" question="Can a habit tick itself off from my Health journal?"><p>Yes. Edit a habit you are building and, under &ldquo;From your Health journal&rdquo;, choose &ldquo;Done automatically when&rdquo;: water, steps, active minutes, a weight reading{SYNC_WRITES ? ', time asleep, in bed by a time, mindful minutes' : ''} or one of your exercise counters, with a target if you like. When you open Today, Habits or Health and the day&rsquo;s Health records reach it, the habit is ticked off once, and the card says so. Tapping the habit yourself always wins, and Undo keeps it off for that day. {SYNC_WRITES ? <>The rule and the marks it leaves are kept with your Health records, so with Health sync on another device won&rsquo;t tick the same day off again; the check-ins it makes are ordinary check-ins.</> : <>The rule stays on this device; the check-ins it makes are ordinary check-ins.</>}</p></HelpQuestion>
      <HelpQuestion id="health-goals" question="What is a health goal, and where does its progress come from?"><p>A health goal watches one thing you already record in Health: steps, water, an exercise counter, active minutes, or your weight trend. You choose the target and the window; ZIGoals only counts your own entries, and shows &ldquo;No data yet&rdquo; when there is nothing to count. It never suggests a target, never grades a result and gives no medical advice. {SYNC_WRITES ? 'Health goals are kept with your Health records, and sync only when you turn on Health sync.' : 'Health goals stay on this device for now.'}</p></HelpQuestion>
      <HelpQuestion id="skips" question="I&rsquo;m away for a week. Will my streak break?"><p>No. A skipped day is neutral: it neither adds to a streak nor breaks it. Plan a skip from a habit&rsquo;s &ldquo;History &amp; reflection&rdquo; for a single day, or mark a whole range with &ldquo;Vacation&rdquo; at the top of Habits. Reminders stay quiet on skipped days, and you can remove a planned skip at any time. Rest days need no marking at all: the days off your schedule never count against you.</p></HelpQuestion>
      <HelpQuestion id="weekly-review" question="What is the weekly review?"><p>On the day you choose in Settings, Today offers a short look back at your week: what went well, your goals, habits, health and wealth, and one intention for next week. Every step shows your own numbers for that week, and every field is optional. Finish it, or skip it with one tap; it never nags. {SYNC_WRITES ? 'Your review is kept with your Today settings and your words about health with your Health records: with encrypted sync on, the review syncs with your settings, and the health words only when Health sync is on.' : 'Your words stay on this device for now.'}</p></HelpQuestion>
      <HelpQuestion id="fasting" question="How does the fasting timer work, and is it right for me?"><p>It is a clock: choose 12:12, 14:10, 16:8 or your own target up to 18 hours, start, and stop when you decide. It keeps your last fasts as hours and targets, nothing more: no streaks, no records, no calories, and it never compares one fast with another. A fast is stopped automatically at 24 hours. Fasting isn&rsquo;t for everyone: if you&rsquo;re pregnant, under 18, have a medical condition or an eating disorder, or take medication, talk to a doctor first, and stop if you feel unwell. ZIGoals gives no medical advice.</p></HelpQuestion>
      <HelpQuestion id="insights" question="What are the &ldquo;Something you might notice&rdquo; cards?"><p>When your journals hold at least two weeks of matching records, Today may show a simple pairing in them, in counts: for example, on how many of the days you walked more you also logged water, compared with the other days. The numbers are only your own entries, and the card shows exactly how it counted them. A pairing is not a cause and not advice. Dismiss a card and it stays away for four weeks.</p></HelpQuestion>
      <HelpQuestion id="imports" question="Can I import a CSV from another app?"><p>Yes, from any spreadsheet or export that has a header row: choose the file, match its columns, check the preview and confirm. Transactions go into a Portfolio, holdings into Wealth, meals into Health&rsquo;s diary. The file is read on this device and never uploaded; blank cells stay unknown rather than becoming zero; a coin that isn&rsquo;t recognised is yours to choose or skip. One tap undoes an import until you change any of the records it added. A MyFitnessPal or Cronometer file is recognised and its columns are matched for you to check. Whole exports from Apple Health, Fitbit / Google Health, Samsung Health, Oura and Loop Habit Tracker come in from Settings → Switch to ZIGoals.</p></HelpQuestion>
      <HelpQuestion id="export-everything" question="Can I get all my data out?"><p>Yes, any time: Settings &rarr; &ldquo;Export everything&rdquo; makes one ZIP on your device with a JSON file of every record and a CSV per area that opens in a spreadsheet. You never need it: sync and the encrypted backup keep your records. It is readable, so keep it private, and it is not a restore format.</p></HelpQuestion>
      <HelpQuestion id="quick-add" question="What can I type into Quick add?"><p>A short English line about water, weight, steps, a run, walk, cycle or swim with its minutes, sleep, one of your exercise counters, or a habit by its name: &ldquo;drank 2 glasses of water&rdquo;, &ldquo;weight 78.4&rdquo;, &ldquo;walked 8,000 steps&rdquo;, &ldquo;ran 5k in 28 min&rdquo;, &ldquo;slept 7h&rdquo;, &ldquo;+2 pushups&rdquo;, &ldquo;meditated&rdquo;. ZIGoals shows what it will save before you tap Save, and tells you when it did not understand. Add &ldquo;yesterday&rdquo; to log for yesterday.</p></HelpQuestion>
      <HelpQuestion id="push-reminders" question="Can a reminder reach me when ZIGoals is closed?"><p>Yes, if you turn it on for a device: Settings &rarr; &ldquo;Reminders when closed&rdquo;. After a reminder time you set, your device shows one notification, &ldquo;A reminder from ZIGoals&rdquo;; if you turn on &ldquo;Show what a reminder is for in notifications&rdquo; there, it names the habit instead, written on this device and never sent to the server. Opening it brings you to Today. It needs a signed-in account, and on an iPhone it works only in the app saved to your Home Screen. The server gets your reminder times, your time zone and the weekdays, your quiet hours, and the address your browser hands out for push messages, never a habit&rsquo;s name, a count or anything you record. Turn it off any time: &ldquo;Turn off and delete from the server&rdquo; removes everything about that device at once. It is not available in every build; the panel says so.</p></HelpQuestion>
      <HelpQuestion id="guide" question="What is the Guide, and what does it read?"><p>The Guide is a short note on Today, at most one a day, made from your own records on this device: an open habit in the evening, a streak at a round number, a goal&rsquo;s next date, your weekly review when it is ready. It is off until you turn it on in Settings &rarr; &ldquo;Guide on this device&rdquo;, and every note is labelled &ldquo;Guide &middot; on this device, no AI service&rdquo;: fixed rules, no model, no service, nothing sent anywhere. It never gives money or medical advice and never moves anything. &ldquo;Not today&rdquo; hides a note; the switch in Settings turns the Guide off again.</p></HelpQuestion>
    </Section>

    {/* Session X Part 11: what the Alpha can't do yet, in plain words. Each line is checked against the code or an owner decision. */}
    <Section id="known-limitations" eyebrow="KNOWN LIMITATIONS" title="What the Alpha can&rsquo;t do yet">
      <ul className="help-list">
        <li><strong>Accounts and sync aren&rsquo;t open yet</strong> on alpha.zigoals.app. Until they are, what you enter stays in the browser or installed app you use, and only there. On an iPhone, <a className="text-link" href="#install">install ZIGoals</a> first and tap &ldquo;Keep my data on this device&rdquo;; <Link className="text-link" href="/app/settings#export-everything">Export everything</Link> gives you your own copy any time.</li>
        <li><strong>Reminders when ZIGoals is closed</strong> need an account, so they wait for accounts too. Until then, due reminders show as cards on Today while ZIGoals is open.</li>
        <li><strong>No real money moves.</strong> Wealth, Portfolio and Staking show what you enter and public data; nothing is bought, sold, sent or staked from ZIGoals, and the test network&rsquo;s tokens have no value.</li>
        <li><strong>Prices</strong> come from CoinGecko and can be missing for a while; a missing price stays &ldquo;unknown&rdquo;, never zero.</li>
        <li><strong>ZIGi</strong> works with an AI you bring, or answers from your records on this device; the AI that ZIGoals would run for you isn&rsquo;t offered yet (<a className="text-link" href="#your-ai">ZIGi · your AI</a>).</li>
        <li><strong>Devices and apps:</strong> Bluetooth works in Chrome and Edge, not on iPhone; Oura, Withings, Polar and Strava say &ldquo;Needs setup by ZIGoals&rdquo; until ZIGoals registers with them; Apple Health has no web access, so use its export; Fitbit&rsquo;s web access is turned off on 30 October 2026, so use Google Takeout.</li>
        <li><strong>Spotify</strong> needs Premium, and only accounts the owner lists can connect while Spotify keeps ZIGoals in development mode.</li>
        <li><strong>Older copies of ZIGoals</strong> can&rsquo;t read what this one saves for sleep, meditation, your pages or links: they say so, keep it and change nothing.</li>
        <li><strong>Goals count in US dollars or euros.</strong> Accounts and assets keep any currency, each on its own; nothing is converted, so a holding in another currency doesn&rsquo;t count toward a Goal.</li>
        <li><strong>English only</strong> for now; numbers follow your device&rsquo;s language settings.</li>
      </ul>
      <p className="fine">It&rsquo;s an Alpha: pages can change, and something may break. If it does, please <a className="text-link" href="#feedback">tell us</a>.</p>
    </Section>

    <Section id="feedback" eyebrow="SEND FEEDBACK" title="Tell us what you think">
      <SendFeedback/>
    </Section>
  </div>;
}
