'use client';
import {useState} from 'react';
import Link from 'next/link';
import {usePlatform} from './use-platform';
import {useMarketQuotes} from './use-market-quotes';
import {useEvidenceNow} from './use-evidence-now';
import {useValuationHistory} from './use-valuation-history';
import {wealthMarketRequests,wealthOverview} from '../../lib/wealth';
import {marketRefKey} from '../../lib/market-assets';
import {addFavourite,removeFavourite,archiveAsset} from '../../lib/asset-management';
import {quoteIsStale} from '../../lib/market-quotes';
import {formatGoalAmount} from '../../lib/goal-summary';
import {amount} from './common';
import {AssetIcon,FreshnessBadge,MetricCard,Sheet} from './financial-ui';
import {AssetEditor} from './asset-editor';
import {PriceChart} from './price-chart';
import './wealth-product.css';
const money=(value:bigint,currency:string)=>formatGoalAmount(amount(value.toString(),2),currency);
export function AssetDetail({id}:{id:string}){const store=usePlatform(),[editing,setEditing]=useState(false),[removing,setRemoving]=useState(false),[error,setError]=useState('');const p=store.data.positions.find(p=>p.id===id),fav=store.data.watchlist.find(a=>marketRefKey(a.ref)===id),ref=p?.marketRef??fav?.ref;const market=useMarketQuotes([...wealthMarketRequests(store.data),...(ref?[{marketRef:ref,currency:p?.quoteCurrency??'USD' as const}]:[])]);useValuationHistory(store,market);const now=useEvidenceNow(store.data,market.now);
 if(!store.loaded)return <div className="dashboard"><p>Loading asset…</p></div>;if(store.error)return <div className="dashboard"><p role="alert">{store.error}</p></div>;if(!p&&!fav)return <div className="dashboard"><h1>Asset unavailable</h1><Link href="/app/wealth">Return to Wealth</Link></div>;
 const row=p?wealthOverview(store.data,now,market.quotes).rows.find(r=>r.position.id===p.id):undefined,name=p?.providerId??fav!.name,symbol=p?.asset??fav!.symbol,currency=p?.quoteCurrency??'USD';const q=ref?market.quotes.find(q=>q.marketRef&&marketRefKey(q.marketRef)===marketRefKey(ref)&&q.currency===currency):undefined;
 const owners=p?store.data.allocations.filter(a=>a.positionId===p.id):[],isFavourite=ref&&store.data.watchlist.some(a=>marketRefKey(a.ref)===marketRefKey(ref));
 const localPoints=p?store.data.valuationSnapshots.filter(v=>v.positionId===p.id&&v.currency===currency&&v.source==='COINGECKO'&&v.price!==undefined&&v.priceDecimals!==undefined).map(v=>({at:v.capturedAt,value:v.price!,decimals:v.priceDecimals!})):[];
 async function archive(){try{await store.update(s=>{if(JSON.stringify(s.positions.find(x=>x.id===p!.id))!==JSON.stringify(p)||JSON.stringify(s.allocations.filter(a=>a.positionId===p!.id))!==JSON.stringify(owners))throw Error('Asset allocations changed. Close and reopen this confirmation.');return archiveAsset(s,p!.id,owners.length>0);});setRemoving(false);}catch(e){setError(e instanceof Error?e.message:'Could not archive.');}}
 return <div className="dashboard asset-detail"><Link className="text-link" href="/app/wealth">← Your wealth</Link><section className="asset-detail-hero"><div><p className="eyebrow">{fav?'YOUR MARKET WATCH':'YOUR ASSET'}</p><div className="asset-detail-heading"><AssetIcon symbol={symbol} kind={p?.assetClass??(ref?.kind==='rwa'&&ref.assetType==='commodity'?'Precious Metals':undefined)}/><div><h1>{name}</h1><p>{symbol.toUpperCase()} · {p?.assetClass??(ref?.kind==='rwa'?ref.assetType:'Crypto')}</p></div></div></div><div><p className="fine">{ref?'Current reference price':'Holding value'}</p><strong className="asset-detail-price">{q?formatGoalAmount(amount(q.price,q.priceDecimals),currency):row?.value!==undefined?money(row.value,row.currency!):'Unavailable'}</strong><p><FreshnessBadge state={ref?q?quoteIsStale(q,market.now)?'stale':'fresh':'missing':row?.valuationState??'manual'}/></p></div></section>
 <div className="asset-detail-actions">{p?.sourceType==='MANUAL'&&!p.archivedAt&&<button className="primary" onClick={()=>setEditing(true)}>Edit asset</button>}{ref&&<><button className="secondary" disabled={market.loading} onClick={()=>void market.refresh()}>{market.loading?'Refreshing…':'Refresh price'}</button><button className="secondary" onClick={()=>void store.update(s=>isFavourite?removeFavourite(s,marketRefKey(ref)):addFavourite(s,{ref,name,symbol})).catch(e=>setError(String(e)))}>{isFavourite?'Remove favourite':'☆ Add favourite'}</button></>}{p?.sourceType==='MANUAL'&&!p.archivedAt&&<button className="quiet" onClick={()=>setRemoving(true)}>Archive asset</button>}</div>{error&&<p role="alert">{error}</p>}
 {p?.archivedAt&&<p className="notice">Archived. Your historical records are retained. Restore this asset from Wealth to track it again.</p>}
 {row&&<section className="asset-detail-grid" aria-label="Your holding"><MetricCard label="Holding value" value={row.value===undefined?'Needs valuation':money(row.value,row.currency!)} detail={`${amount(p!.quantity,p!.decimals)} ${symbol}`}/><MetricCard label="Allocated to Goals" value={row.allocatedValue===undefined?'—':money(row.allocatedValue,row.currency!)} detail={`${owners.length} linked Goals`}/><MetricCard label="Available for Goals" value={row.unallocatedValue===undefined?'—':money(row.unallocatedValue,row.currency!)} detail={`${amount(row.balance.unallocated,p!.decimals)} ${symbol}`}/></section>}
 {ref?<PriceChart marketRef={ref} currency={currency} localPoints={localPoints}/>:<section className="panel"><h2>Your value, your record</h2><p>Manual assets use your entered valuation. Edit it when your estimate changes.</p></section>}
 <section className="panel"><p className="eyebrow">SOURCE & FRESHNESS</p><h2>{ref?.kind==='rwa'?'CoinGecko tokenized RWA reference':ref?'CoinGecko market data':'Manual valuation'}</h2><p>{ref?.kind==='rwa'?'Tokenized reference units. This is not an exchange execution price or physical-metal spot price.':ref?'Public price data. Your quantity and Goal details stay private.':'A value you entered, without a live market connection.'}</p>{q&&<p>Price updated {new Date(q.observedAt??q.fetchedAt!).toLocaleString()} · {currency}</p>}{p&&<p>Holding last updated {new Date(p.observedAt).toLocaleString()}</p>}</section>
 {p&&!p.archivedAt&&<section className="panel"><p className="eyebrow">WEALTH WITH PURPOSE</p><h2>Your linked Goals</h2>{owners.map(a=>{const g=store.data.goals.find(g=>g.id===a.goalId)!;return <div className="asset-goal-row" key={a.goalId}><div><strong>{g.name}</strong><p>{amount(a.quantity,p.decimals)} {p.asset} allocated</p></div><Link className="text-link" href={`/app/goals/tracked/${g.id}#allocate`}>Manage or release allocation →</Link></div>;})}{!owners.length&&<p>This asset is available to support your next Goal.</p>}<div className="asset-detail-actions">{store.data.goals.filter(g=>g.status!=='closed'&&g.type!=='PROJECT').map(g=><Link className="secondary" key={g.id} href={`/app/goals/tracked/${g.id}#allocate`}>Allocate to {g.name}</Link>)}<Link className="text-link" href={`/app/goals/new?position=${encodeURIComponent(p.id)}`}>Create a Goal with this asset →</Link></div></section>}
 {editing&&p&&<Sheet title={`Edit ${name}`} onClose={()=>setEditing(false)}><AssetEditor position={p} update={store.update} onSaved={()=>setEditing(false)}/></Sheet>}{removing&&p&&<Sheet title={`Archive ${name}`} onClose={()=>setRemoving(false)}><p>Remove this holding from current wealth. Historical contributions and valuations remain available, and you can restore the asset later.</p>{owners.length>0&&<><h3>These allocations will be released</h3><ul>{owners.map(a=><li key={a.goalId}>{store.data.goals.find(g=>g.id===a.goalId)?.name}: {amount(a.quantity,p.decimals)} {p.asset}</li>)}</ul></>}<button className="primary" onClick={()=>void archive()}>{owners.length?'Release allocations & archive':'Confirm archive'}</button>{error&&<p role="alert">{error}</p>}</Sheet>}</div>;
}
