'use client';
import {useState,type FormEvent} from 'react';
import {parseUnits} from '@zigoals/chain-config';
import {positionSchema,type Platform,type Position} from '../../lib/positions';
import {saveAsset} from '../../lib/asset-management';
import {amount} from './common';
import {AssetIcon} from './financial-ui';
export function AssetEditor({position:p,update,onSaved}:{position:Position;update:(fn:(s:Platform)=>Platform)=>Promise<void>;onSaved:()=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState(p.valuation?'manual':p.marketRef?'automatic':'manual');
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget),now=new Date().toISOString(),quantity=parseUnits(String(f.get('quantity')),p.decimals).toString(),cash=p.assetClass==='Cash',value=String(f.get('value')||'');const {valuation,...rest}=p;void valuation;const next=positionSchema.parse({...rest,providerId:String(f.get('name')),quantity,observedAt:now,notes:String(f.get('notes')||''),valuationMode:cash?'manual':mode,valuation:cash?{value:(BigInt(quantity)*100n/10n**BigInt(p.decimals)).toString(),currency:p.asset,decimals:2,source:'MANUAL',observedAt:now}:mode==='manual'&&value?{value:parseUnits(value,2).toString(),currency:String(f.get('currency')||'USD').toUpperCase(),decimals:2,source:'MANUAL',observedAt:now}:undefined});await update(s=>{if(JSON.stringify(s.positions.find(x=>x.id===p.id))!==JSON.stringify(p))throw Error('This asset changed in another tab. Close and reopen the editor.');return saveAsset(s,next);});onSaved();}catch(e){setError(e instanceof Error?e.message:'Asset could not be saved.');}finally{setBusy(false);}}
 return <form className="picker-draft-form" onSubmit={save}><div className="picker-selected wide"><AssetIcon symbol={p.asset} kind={p.assetClass}/><div><h3>{p.providerId}</h3><p>{p.asset} · {p.marketRef?'Market identity is fixed. Add a new asset to replace it.':'Private holding'}</p></div></div><label className="field">Asset name<input name="name" defaultValue={p.providerId} required maxLength={100}/></label><label className="field">{p.assetClass==='Cash'?'Cash balance':'Asset quantity'}<input name="quantity" defaultValue={amount(p.quantity,p.decimals)} required inputMode="decimal"/></label>{p.marketRef&&<div className="picker-tabs wide" aria-label="Valuation mode">{['automatic','manual'].map(m=><button key={m} type="button" aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='automatic'?'Automatic prices':'Manual value'}</button>)}</div>}{mode==='manual'&&p.assetClass!=='Cash'&&<><label className="field">Total holding value<input name="value" defaultValue={p.valuation?amount(p.valuation.value,p.valuation.decimals):''} inputMode="decimal"/></label><label className="field">Valuation currency<input name="currency" defaultValue={p.valuation?.currency??p.quoteCurrency??'USD'} required maxLength={3}/></label></>}<label className="field wide">Note<textarea name="notes" defaultValue={p.notes} maxLength={2000}/></label><p className="picker-mode-note wide">Saving updates your tracked wealth. Existing allocations stay in place; a balance below allocations will require review.</p><button className="primary wide" disabled={busy}>Save changes</button>{error&&<p className="wide" role="alert">{error}</p>}</form>;
}
