'use client';
import {useMemo,useRef,useState,type FormEvent} from 'react';
import {formatUnits,parseUnits} from '@zigoals/chain-config';
import type {Platform} from '../../lib/positions';
import {financialEvidenceBasis,activeFinancialEvents,appendFinancialEvidence,evaluateTwr,makeManualFx,recordPerformanceReview,voidFinancialEvent,type EvidenceMoney,type FinancialEvent,type ManualFx} from '../../lib/financial-events';
import './financial-evidence.css';
const money=(m:EvidenceMoney)=>`${formatUnits(m.value,m.decimals)} ${m.currency}`;
const utcInput=()=>new Date().toISOString().slice(0,16);
const instant=(value:FormDataEntryValue|null)=>new Date(`${String(value)}Z`).toISOString();
export function FinancialEvidence({data,update}:{data:Platform;update:(fn:(s:Platform)=>Platform)=>Promise<void>}){
 const [selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const guard=useRef(false);
 const portfolios=data.financialPortfolios??[],portfolio=portfolios.find(p=>p.id===selected)??portfolios[0];
 const [kind,setKind]=useState('valuation'),[role,setRole]=useState('boundary'),[eventAt,setEventAt]=useState(utcInput),[eventAmount,setEventAmount]=useState(''),[fxId,setFxId]=useState('');
 const [fxPreview,setFxPreview]=useState<ManualFx|null>(null),[startId,setStart]=useState(''),[endId,setEnd]=useState(''),[page,setPage]=useState(0),[correction,setCorrection]=useState('');
 const [reviewedBasis,setReviewedBasis]=useState<string|null>(null);
 const [flowsComplete,setFlowsComplete]=useState(false),[valuationsComplete,setValuationsComplete]=useState(false),[incomeComplete,setIncomeComplete]=useState(false);
 const active=portfolio?activeFinancialEvents(data,portfolio.id):[],events=(data.financialEvents??[]).filter(e=>e.portfolioId===portfolio?.id),boundaries=active.filter(e=>e.kind==='valuation'&&e.role==='boundary').sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt));
 const currentBasis=useMemo(()=>financialEvidenceBasis(data,portfolio?.id??'',startId,endId),[data,portfolio?.id,startId,endId]);
 const reviewStale=reviewedBasis!==null&&reviewedBasis!==currentBasis;
 const result=useMemo(()=>evaluateTwr(data,portfolio?.id??'',startId,endId),[data,portfolio?.id,startId,endId]),fx=data.manualFx??[],voids=new Set(events.filter(e=>e.kind==='void').map(e=>e.reversesId));
 async function run(operation:()=>Promise<void>,success:string){if(guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');try{await operation();setMessage(success);}catch(e){setError(e instanceof Error?e.message:'Evidence could not be saved.');}finally{guard.current=false;setBusy(false);}}
 function confirmPart(part:'flows'|'valuations'|'income',checked:boolean){if(!checked){resetReview();return;}if(!flowsComplete&&!valuationsComplete&&!incomeComplete)setReviewedBasis(currentBasis);if(part==='flows')setFlowsComplete(true);if(part==='valuations')setValuationsComplete(true);if(part==='income')setIncomeComplete(true);}
 function resetReview(){setReviewedBasis(null);setFlowsComplete(false);setValuationsComplete(false);setIncomeComplete(false);}
 function choose(id:string){setSelected(id);setStart('');setEnd('');setCorrection('');setFxId('');setPage(0);resetReview();}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),id=crypto.randomUUID(),createdAt=new Date().toISOString();await run(async()=>{await update(s=>appendFinancialEvidence(s,{portfolio:{id,name:String(form.get('name')),currency:String(form.get('currency')),createdAt}}));choose(id);},'Evidence portfolio created.');}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!portfolio)return;const form=new FormData(e.currentTarget),recordedAt=new Date().toISOString(),id=crypto.randomUUID();await run(async()=>{
  const occurredAt=instant(form.get('time')),amount={value:parseUnits(eventAmount,2).toString(),decimals:2,currency:portfolio.currency};
  const common={id,portfolioId:portfolio.id,occurredAt,recordedAt,source:'MANUAL' as const,sourceLabel:String(form.get('source')),note:String(form.get('note')??''),...(form.get('contribution')?{relatedContributionId:String(form.get('contribution'))}:{}),...(form.get('revision')?{relatedPlanRevisionId:String(form.get('revision'))}:{})};
  const symbol=String(form.get('asset')??'').trim(),quantity=String(form.get('quantity')??'').trim();
  if(Boolean(symbol)!==Boolean(quantity))throw Error('Provide both original asset symbol and quantity, or leave both blank.');
  const originalAsset=symbol?{symbol,network:String(form.get('network')||'manual'),denom:String(form.get('denom')||`manual:${symbol}`),units:parseUnits(quantity,18).toString(),decimals:18}:undefined;
  const event:FinancialEvent=kind==='valuation'?{...common,kind:'valuation',amount,role:role as 'boundary'|'before_flow'|'after_flow',...(role!=='boundary'?{flowId:String(form.get('flow'))}:{})}:kind==='external_flow'?{...common,kind:'external_flow',amount,direction:String(form.get('direction')) as 'IN'|'OUT',...(fxId?{fxId}:{}),...(originalAsset?{originalAsset}:{})}:{...common,kind:kind as 'income'|'fee'|'transfer'|'quantity_correction'|'unclassified',amount,...(originalAsset?{originalAsset}:{})};
  await update(s=>appendFinancialEvidence(s,{event}));resetReview();setPage(0);
 },'Evidence saved. Current holdings and Goals are unchanged.');}
 async function previewFx(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setError('');try{setFxPreview(makeManualFx({id:crypto.randomUUID(),occurredAt:instant(form.get('time')),recordedAt:new Date().toISOString(),sourceLabel:String(form.get('source')),original:{value:parseUnits(String(form.get('amount')),2).toString(),decimals:2,currency:String(form.get('base'))},quoteCurrency:String(form.get('quote')),quoteDecimals:2,rate:{value:parseUnits(String(form.get('rate')),18).toString(),decimals:18}}));}catch(e){setError(e instanceof Error?e.message:'Review the FX entry.');}}
 async function review(){if(!portfolio||!flowsComplete||!valuationsComplete||!incomeComplete||reviewStale||!reviewedBasis)return;const expected=reviewedBasis,id=crypto.randomUUID(),recordedAt=new Date().toISOString();await run(()=>update(s=>{if(financialEvidenceBasis(s,portfolio.id,startId,endId)!==expected)throw Error('Evidence changed while you reviewed it. Review the current records again.');return recordPerformanceReview(s,{id,portfolioId:portfolio.id,startId,endId,recordedAt,flowsComplete:true,valuationsComplete:true,incomeAndFeesIncluded:true});}),'Completeness review saved.');}
 return <section className="financial-evidence panel" aria-label="Financial evidence and returns"><p className="eyebrow">YOUR DATED FINANCIAL RECORDS</p><h2>Evidence &amp; returns</h2><p>Record a named portfolio from your statements, including its cash and all holdings. These manual records are separate from current Wealth, Goals and contributions; no balances or funds move.</p>
 <form className="financial-evidence-form" onSubmit={create}><label>Portfolio name<input name="name" required maxLength={120} placeholder="For example: my brokerage statement"/></label><label>Portfolio currency<select name="currency"><option>USD</option><option>EUR</option></select></label><button className="secondary" disabled={busy}>Create evidence portfolio</button></form>
 {!!portfolios.length&&<><label>Evidence portfolio<select value={portfolio?.id} onChange={e=>choose(e.target.value)}>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name} · {p.currency}</option>)}</select></label>
 <form className="financial-evidence-form" aria-label="Record financial evidence" onSubmit={save}><h3>Record a statement fact</h3><label>Evidence type<select value={kind} onChange={e=>{setKind(e.target.value);setFxId('');}}><option value="valuation">Complete portfolio valuation</option><option value="external_flow">External deposit / withdrawal</option><option value="income">Income included in valuation</option><option value="fee">Fee included in valuation</option><option value="transfer">Transfer needing classification</option><option value="quantity_correction">Quantity correction needing review</option><option value="unclassified">Unclassified difference</option></select></label>
 <label>Event time (UTC)<input name="time" type="datetime-local" step="1" required value={eventAt} onChange={e=>setEventAt(e.target.value)}/></label><label>Amount in {portfolio!.currency}<input inputMode="decimal" required value={eventAmount} onChange={e=>setEventAmount(e.target.value)}/></label>
 {kind==='valuation'&&<><label>Valuation purpose<select value={role} onChange={e=>setRole(e.target.value)}><option value="boundary">Period start / end</option><option value="before_flow">Immediately before a flow</option><option value="after_flow">Immediately after a flow</option></select></label>{role!=='boundary'&&<label>Related external flow<select name="flow" required defaultValue=""><option value="">Choose a recorded flow</option>{active.filter(e=>e.kind==='external_flow').map(e=><option key={e.id} value={e.id}>{e.occurredAt} · {'amount'in e?money(e.amount):''}</option>)}</select></label>}<p className="fine">Use a complete valuation of the same portfolio. Flow boundaries must have the exact flow timestamp and reflect the instant before or after it.</p></>}
 {kind==='external_flow'&&<><label>Flow direction<select name="direction"><option value="IN">External deposit</option><option value="OUT">External withdrawal</option></select></label><label>Dated FX basis<select value={fxId} onChange={e=>{setFxId(e.target.value);const value=fx.find(f=>f.id===e.target.value);if(value){setEventAt(value.occurredAt.slice(0,19));setEventAmount(formatUnits(value.converted.value,value.converted.decimals));}}}><option value="">Already in portfolio currency</option>{fx.filter(f=>f.converted.currency===portfolio!.currency).map(f=><option key={f.id} value={f.id}>{f.occurredAt} · {money(f.original)} → {money(f.converted)}</option>)}</select></label><p className="fine">Only money or assets entering/leaving this entire portfolio are external flows. Buying an asset within the portfolio, Goal allocation, income and fees are not external deposits.</p></>}
 <label>Source or statement reference<input name="source" required maxLength={300}/></label><label>Evidence note<textarea name="note" maxLength={1000}/></label>
 {kind!=='valuation'&&<details><summary>Original asset units (optional)</summary><label>Original asset symbol<input name="asset" maxLength={30}/></label><label>Original quantity<input name="quantity" inputMode="decimal"/></label><label>Original network<input name="network" defaultValue="manual"/></label><label>Original unit identity<input name="denom" placeholder="Manual symbol when blank"/></label></details>}
 <details><summary>Link existing financial evidence (optional)</summary><label>Related contribution<select name="contribution"><option value="">No contribution link</option>{data.contributions.map(e=><option key={e.id} value={e.id}>{e.occurredAt} · {formatUnits(e.quantity,e.decimals)} {e.asset}</option>)}</select></label><label>Related plan revision<select name="revision"><option value="">No plan link</option>{data.goals.flatMap(g=>(g.planRevisions??[]).map(r=><option key={r.id} value={r.id}>{g.name} · effective {r.effectiveFrom}</option>))}</select></label><p className="fine">References help trace evidence. They do not create, reclassify or apply another contribution.</p></details><button className="primary" disabled={busy}>Save evidence</button></form>
 <details><summary>Record a manual FX basis</summary><form className="financial-evidence-form" aria-label="Manual FX evidence" onSubmit={previewFx} onChange={()=>setFxPreview(null)}><p>Use the dated conversion source for this event. This never converts current Wealth or rewrites earlier returns. Rates are quote-currency units per one original-currency unit; converted amounts round half-up to cents.</p><label>Original amount<input name="amount" inputMode="decimal" required/></label><label>Original currency<select name="base" aria-label="Original currency" defaultValue="EUR"><option>USD</option><option>EUR</option></select></label><label>Quote currency<select name="quote" aria-label="Quote currency"><option>USD</option><option>EUR</option></select></label><label>Quote units per original currency unit<input name="rate" inputMode="decimal" required/></label><label>FX event time (UTC)<input name="time" type="datetime-local" step="1" required defaultValue={utcInput()}/></label><label>FX source reference<input name="source" required maxLength={300}/></label><button className="secondary" disabled={busy}>Preview FX conversion</button>{fxPreview&&<div className="notice"><p>{money(fxPreview.original)} → {money(fxPreview.converted)}</p><p>Manual rate {formatUnits(fxPreview.rate.value,fxPreview.rate.decimals)} · {fxPreview.occurredAt} · {fxPreview.sourceLabel}</p><button type="button" className="primary" disabled={busy} onClick={()=>void run(async()=>{await update(s=>appendFinancialEvidence(s,{fx:fxPreview}));setFxPreview(null);},'Manual FX evidence saved.')}>Save manual FX evidence</button></div>}</form></details>
 {!!fx.length&&<details><summary>Retained manual FX ({fx.length})</summary><ul>{fx.map(f=><li key={f.id}>{money(f.original)} → {money(f.converted)} · rate {formatUnits(f.rate.value,f.rate.decimals)} · <time>{f.occurredAt}</time> · Manual: {f.sourceLabel}<small> FX record {f.id}</small></li>)}</ul></details>}
 <section aria-label="Review time-weighted return"><h3>Review a period</h3><div className="financial-evidence-form"><label>Start valuation<select value={startId} onChange={e=>{setStart(e.target.value);resetReview();}}><option value="">Choose start</option>{boundaries.map(e=><option key={e.id} value={e.id}>{e.occurredAt} · {'amount'in e?money(e.amount):''}</option>)}</select></label><label>End valuation<select value={endId} onChange={e=>{setEnd(e.target.value);resetReview();}}><option value="">Choose end</option>{boundaries.map(e=><option key={e.id} value={e.id}>{e.occurredAt} · {'amount'in e?money(e.amount):''}</option>)}</select></label></div>
 {result.available?<><strong className="financial-return" aria-label="Cumulative time-weighted return">{result.returnPercent}%</strong><p>{result.reason}</p><p>{result.wealthChange!==null?`Recorded value change: ${money({value:result.wealthChange.replace('-',''),decimals:result.decimals,currency:result.currency})}${result.wealthChange.startsWith('-')?' decrease':''}. `:''}This value change is not itself an investment return.</p><div className="financial-table-wrap" tabIndex={0} role="region" aria-label="Scrollable exact subperiod values"><table><caption>Exact subperiod evidence</caption><thead><tr><th>Start UTC</th><th>End UTC</th><th>Opening</th><th>Closing before flow</th><th>Return</th></tr></thead><tbody>{result.subperiods.map((r,i)=><tr key={i}><td>{r.from}</td><td>{r.to}</td><td>{money(r.opening)}</td><td>{money(r.closing)}</td><td>{r.returnPercent}%</td></tr>)}</tbody></table></div></>:<p className="notice">Time-weighted return unavailable. {result.reason}</p>}
 <p className="fine">{result.mwrReason}</p><div className="financial-review"><label><input type="checkbox" checked={flowsComplete} onChange={e=>confirmPart('flows',e.target.checked)}/>I recorded every external cash flow for this portfolio and period.</label><label><input type="checkbox" checked={valuationsComplete} onChange={e=>confirmPart('valuations',e.target.checked)}/>Both endpoints and all flow boundaries value the complete same portfolio, including cash.</label><label><input type="checkbox" checked={incomeComplete} onChange={e=>confirmPart('income',e.target.checked)}/>Income and fees are already included in these valuations.</label><button className="secondary" disabled={busy||reviewStale||!startId||!endId||!flowsComplete||!valuationsComplete||!incomeComplete} onClick={()=>void review()}>Save completeness review</button>{reviewStale&&<p role="alert">Evidence changed during your review. <button className="quiet" onClick={resetReview}>Reset confirmations and review again</button></p>}</div>
 <details><summary>How this return is calculated</summary><p>Each subperiod ends immediately before an external flow; the next begins immediately after it. We multiply each closing/opening value ratio and subtract one. No valuation or flow time is estimated, no annualization is applied, and currencies are never combined. Percentages round only for display, to eight decimal places. A zero post-flow portfolio, ambiguous simultaneous flows or unresolved events makes this method unavailable.</p><p><a href="https://www.gipsstandards.org/standards/gips-standards-for-firms/gips-standards-handbook-for-firms/" target="_blank" rel="noreferrer">CFA Institute GIPS handbook: time-weighted subperiod linking</a>. This manual calculator is not independently verified investment performance or a claim of GIPS compliance.</p></details></section>
 <section aria-label="Retained financial events"><h3>Retained statement events</h3><p className="fine">Corrections keep the original and append a void record. Record the replacement separately with its original event time. This changes only this evidence ledger.</p><ol className="financial-event-list">{[...events].reverse().slice(page*10,page*10+10).map(e=><li key={e.id}><strong>{e.kind.replaceAll('_',' ')}{'amount'in e?` · ${money(e.amount)}`:''}</strong><p><time>{e.occurredAt}</time> UTC · Manual: {e.sourceLabel}</p>{e.note&&<p>{e.note}</p>}{e.kind==='void'?<p>Original retained · voids {e.reversesId}</p>:voids.has(e.id)?<p>Original retained · voided by explicit correction</p>:<button className="quiet" disabled={busy} onClick={()=>setCorrection(e.id)}>Correct event</button>}<details><summary>Record details</summary><p>ID {e.id}</p><p>Recorded {e.recordedAt}</p>{e.relatedContributionId&&<p>Related contribution {e.relatedContributionId}</p>}{e.relatedPlanRevisionId&&<p>Related plan revision {e.relatedPlanRevisionId}</p>}{e.kind==='valuation'&&<p>{e.role.replaceAll('_',' ')}{e.flowId?` · flow ${e.flowId}`:''}</p>}{e.kind==='external_flow'&&<p>{e.direction}{e.fxId?` · manual FX ${e.fxId}`:''}</p>}{'originalAsset'in e&&e.originalAsset&&<p>Original {formatUnits(e.originalAsset.units,e.originalAsset.decimals)} {e.originalAsset.symbol} · {e.originalAsset.network} · {e.originalAsset.denom}</p>}</details></li>)}</ol>{!events.length&&<p>No statement events recorded.</p>}<div className="actions"><button className="quiet" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Newer events</button><span>{events.length?`${page*10+1}–${Math.min(events.length,page*10+10)} of ${events.length}`:'0 records'}</span><button className="quiet" disabled={(page+1)*10>=events.length} onClick={()=>setPage(p=>p+1)}>Older events</button></div>
 {correction&&<form className="financial-evidence-form notice" onSubmit={e=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get('reason')),id=crypto.randomUUID(),at=new Date().toISOString();void run(async()=>{await update(s=>voidFinancialEvent(s,correction,id,at,reason));setCorrection('');resetReview();},'Correction retained. Review the period again.');}}><h4>Void an incorrect evidence record</h4><p>The original remains in history. This is not a withdrawal or balance adjustment. Any prior return review becomes out of date.</p><label>Correction reason<input name="reason" required maxLength={1000}/></label><button className="secondary" disabled={busy}>Void this evidence record</button><button className="quiet" type="button" onClick={()=>setCorrection('')}>Cancel correction</button></form>}</section></>}
 {error&&<p role="alert" className="notice">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
