'use client';
import {useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import './financial-ui.css';
export function AssetIcon({symbol,kind='Crypto',logoUrl}:{symbol:string;kind?:string;logoUrl?:string|null}){const [failed,setFailed]=useState('');const logo=logoUrl?.startsWith('/api/market-logo?url=')&&failed!==logoUrl?logoUrl:null;const fallback=kind==='ETFs'?'▦':kind==='Stocks'?'▥':kind==='Stablecoins'?'◎':kind==='Precious Metals'||kind==='Precious metals'?'△':kind==='Property'?'⌂':kind==='Custom'?'✧':kind==='Cash'?symbol==='EUR'?'€':'$':symbol==='BTC'?'₿':symbol==='ETH'?'Ξ':symbol.slice(0,3).toUpperCase();return <span className="asset-orb" data-kind={kind} aria-hidden="true">{logo?
 // The validated, same-origin raster proxy bounds bytes and host; no client provider credential.
 // eslint-disable-next-line @next/next/no-img-element
 <img src={logo} alt="" width={48} height={48} loading="lazy" onError={()=>setFailed(logo)}/>:fallback}</span>;}
export function ProgressRing({percent,size=112,label='Goal progress'}:{percent:number;size?:number;label?:string}){const safe=Math.max(0,Math.min(100,Number.isFinite(percent)?percent:0));return <div className="flow-ring" role="img" aria-label={`${label}: ${safe.toFixed(2)}%`} style={{'--progress':`${safe}%`,'--ring-size':`${size}px`} as CSSProperties}><span>{safe.toFixed(2)}<small>%</small></span></div>;}
export function FreshnessBadge({state}:{state:string}){return <span className="freshness-badge" data-state={state}>{state==='fresh'?'Current':state==='stale'?'Needs refresh':state==='manual'?'Manual value':'Needs value'}</span>;}
export function MetricCard({label,value,detail}:{label:string;value:ReactNode;detail?:ReactNode}){return <div className="financial-metric"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
export function Sheet({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);return <dialog ref={ref} className="wealth-sheet" onCancel={onClose} aria-label={title}><header><div><p className="eyebrow">YOUR PRIVATE WEALTH</p><h2>{title}</h2></div><button type="button" className="secondary icon-button" aria-label="Close dialog" onClick={onClose}>×</button></header><div className="wealth-sheet-body">{children}</div></dialog>;}
