'use client';
import {useMemo,useState} from 'react';
import {pageGoalTimeline,type GoalTimelineEvent} from '../../lib/goal-intelligence';
import {type Platform} from '../../lib/positions';
import {amount} from './common';
export function GoalTimeline({events,records,decimals,canEdit,reverse}:{events:GoalTimelineEvent[];records:Platform['contributions'];decimals:number;canEdit:boolean;reverse:(id:string)=>Promise<void>}){
 const [page,setPage]=useState(0),[kind,setKind]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const valid=!from||!to||from<=to,result=useMemo(()=>pageGoalTimeline(events,{page,kind,...(valid?{from,to}:{})}),[events,page,kind,from,to,valid]);
 const byId=useMemo(()=>new Map(records.map(r=>['contribution:'+r.id,r])),[records]),reversed=useMemo(()=>new Set(records.flatMap(r=>r.reversesId?[r.reversesId]:[])),[records]);
 return <section className="panel" aria-label="Goal timeline"><p className="eyebrow">YOUR JOURNEY</p><h2>Goal timeline</h2><p className="fine">History reversals correct records only. Adjust assets separately if a balance changed.</p>
 <div className="intelligence-actions"><label>Event type<select aria-label="Event type" value={kind} onChange={e=>{setKind(e.target.value);setPage(0);}}><option value="">All events</option>{[...new Set(events.map(e=>e.kind))].sort().map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>)}</select></label><label>From date (UTC)<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/></label><label>Through date (UTC)<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(0);}}/></label></div>
 {!valid&&<p role="alert">Choose an end date on or after the start date.</p>}
 <ol className="intelligence-timeline" start={result.page*12+1}>{result.events.map(event=>{const record=byId.get(event.id);return <li key={event.id}><div><strong>{event.kind==='contribution'?'Contribution recorded':event.kind==='reversal'?'Contribution reversed':event.label}</strong>{event.quantity&&<p>{amount(event.quantity,event.decimals??decimals)} {event.asset}</p>}<time dateTime={event.at}>{new Date(event.at).toLocaleString()}</time><br/><small>{event.provenance.replaceAll('_',' ').toLowerCase()}</small><details><summary>Record details</summary><dl><dt>Record ID</dt><dd style={{overflowWrap:'anywhere'}}>{event.id}</dd><dt>Recorded instant (UTC)</dt><dd>{new Date(event.at).toISOString()}</dd><dt>Evidence source</dt><dd>{event.provenance}</dd>{event.quantity&&<><dt>Exact amount</dt><dd>{amount(event.quantity,event.decimals??decimals)} {event.asset}</dd></>}{record?.note&&<><dt>Note</dt><dd>{record.note}</dd></>}{record?.reversesId&&<><dt>Corrects record</dt><dd>{record.reversesId}</dd></>}</dl></details>{record&&!record.reversesId&&!reversed.has(record.id)&&<div><button className="quiet" disabled={!canEdit} onClick={()=>void reverse(record.id)}>Reverse history entry</button></div>}</div></li>;})}</ol>
 {!result.total&&<p className="fine">No retained events match this selection.</p>}<nav aria-label="Goal history pages" className="intelligence-actions"><button disabled={result.page===0} onClick={()=>setPage(result.page-1)}>Newer events</button><span role="status">Page {result.page+1} of {result.pages} · {result.total} retained events</span><button disabled={result.page+1>=result.pages} onClick={()=>setPage(result.page+1)}>Older events</button></nav><p className="fine">Times are shown in this device’s timezone; date filters use UTC. Earlier observations removed by older app versions cannot be reconstructed.</p></section>;
}
