'use client';
import './goal-detail.css';
import {useState,type FormEvent} from 'react';
import {MANUAL_SOURCES,manualSourcePosition,type ManualSource} from '../../lib/manual-source';
import {saveManualPosition,type Platform,type Position} from '../../lib/positions';
export function ManualSourceCards({update,onSaved}:{update:(fn:(s:Platform)=>Platform)=>Promise<void>;onSaved:(p:Position)=>void}){
 const [category,setCategory]=useState<ManualSource['category']>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!category)return;setError('');setBusy(true);try{const f=new FormData(e.currentTarget);const value=(key:string)=>String(f.get(key)||'');const p=manualSourcePosition({category,name:value('name'),quantity:value('quantity'),currency:value('currency'),symbol:value('symbol'),metal:value('metal'),unit:value('unit'),value:value('value'),price:value('price'),notes:value('notes')});await update(s=>saveManualPosition(s,p));onSaved(p);setCategory(undefined);}catch(e){setError(e instanceof Error?e.message:'Could not save this asset.');}finally{setBusy(false);}}
 return <section className="manual-source-selector"><h3>Add another asset source</h3><div className="manual-source-options">{MANUAL_SOURCES.map((c,i)=><button type="button" className="secondary" aria-expanded={category===c} key={c} onClick={()=>{setCategory(category===c?undefined:c);setError('');}}><span aria-hidden="true">{['◈','◇','◎','▥','△','⌂','✧'][i]}</span> {c}</button>)}</div>{category&&<form key={category} className="platform-form panel" onSubmit={save}><h3>{category}</h3><p className="fine">Manual entry · not verified. Saved to your Positions; allocate it when you create the Goal.</p><label className="field">{category==='Property'?'Property name':'Asset name'}<input name="name" required maxLength={100}/></label>{!['Cash','Precious metals','Property','Custom asset'].includes(category)&&<label className="field">Symbol / ticker<input name="symbol" required maxLength={30}/></label>}{category==='Precious metals'&&<><label className="field">Metal<select name="metal"><option>Gold</option><option>Silver</option><option>Custom metal</option></select></label><label className="field">Weight unit<select name="unit"><option>grams</option><option>kilograms</option><option>troy ounces</option></select></label></>}<label className="field">{category==='Cash'?'Cash amount':category==='Precious metals'?'Weight':category==='Stocks'?'Share quantity':category==='Property'?'Quantity / share':'Quantity'}{['Custom asset','Property'].includes(category)?' (optional)':''}<input name="quantity" inputMode="decimal" required={!['Custom asset','Property'].includes(category)}/></label><label className="field">Valuation currency<input name="currency" defaultValue="USD" required maxLength={3}/></label>{category!=='Cash'&&<><label className="field">Manual total value {['Custom asset','Property'].includes(category)?'':'(optional)'}<input name="value" inputMode="decimal" required={['Custom asset','Property'].includes(category)}/></label>{category!=='Property'&&<label className="field">Manual price per entered unit (optional)<input name="price" inputMode="decimal"/></label>}<p className="fine">Total value takes precedence over unit price. No price or currency conversion is assumed.{category==='Stablecoins'?' A stablecoin is not automatically valued at $1.':''}{category==='Precious metals'?' Automatic precious-metal market pricing deferred to Run #9.':''}</p></>}<label className="field">Asset note (optional)<textarea name="notes" maxLength={2000}/></label><button className="primary" disabled={busy}>Save manual source</button>{error&&<p role="alert">{error}</p>}</form>}</section>;
}
