'use client';
import './goal-detail.css';
import {useState,type FormEvent} from 'react';
import {MANUAL_SOURCES,manualSourcePosition,type ManualSource} from '../../lib/manual-source';
import {saveManualPosition,type AssetClass,type Platform,type Position} from '../../lib/positions';
import type {MarketCatalogAsset} from '../../lib/market-assets';
import {AssetSearch,automaticSourcePosition,automaticUnitLabel} from './asset-search';
export function ManualSourceCards({update,onSaved}:{update:(fn:(s:Platform)=>Platform)=>Promise<void>;onSaved:(p:Position)=>void}){
 const [mode,setMode]=useState<'automatic'|'manual'>('manual'),[category,setCategory]=useState<ManualSource['category']>(),[selected,setSelected]=useState<MarketCatalogAsset>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!category)return;setError('');setBusy(true);try{const f=new FormData(e.currentTarget);const value=(key:string)=>String(f.get(key)||'');const p=manualSourcePosition({category,name:value('name'),quantity:value('quantity'),currency:value('currency'),symbol:value('symbol'),metal:value('metal'),unit:value('unit'),value:value('value'),price:value('price'),notes:value('notes')});await update(s=>saveManualPosition(s,p));onSaved(p);setCategory(undefined);}catch(e){setError(e instanceof Error?e.message:'Could not save this asset.');}finally{setBusy(false);}}
 async function saveAutomatic(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setError('');setBusy(true);try{const form=new FormData(e.currentTarget);const p=automaticSourcePosition({asset:selected,assetClass:String(form.get('assetClass')) as AssetClass,quantity:String(form.get('quantity')),currency:String(form.get('currency')) as 'USD'|'EUR',notes:String(form.get('notes')||'')});await update(s=>saveManualPosition(s,p));onSaved(p);setSelected(undefined);}catch(e){setError(e instanceof Error?e.message:'Could not save this asset.');}finally{setBusy(false);}}
 return <section className="manual-source-selector"><h3>Add another asset source</h3><p className="fine">Choose how this Position receives its value. Its quantity and classification always remain your explicit input.</p><div className="valuation-mode" role="group" aria-label="Valuation method"><button type="button" className="valuation-mode-card" aria-pressed={mode==='automatic'} onClick={()=>{setMode('automatic');setCategory(undefined);setError('');}}><strong>Automatic prices</strong><span>Choose an exact CoinGecko identity</span></button><button type="button" className="valuation-mode-card" aria-pressed={mode==='manual'} onClick={()=>{setMode('manual');setSelected(undefined);setError('');}}><strong>Manual value</strong><span>Enter and maintain your own valuation</span></button></div>
 {mode==='automatic'&&<><AssetSearch selected={selected} onSelect={asset=>{setSelected(asset);setError('');}} onManual={()=>setMode('manual')} disabled={busy}/>{selected&&<form key={`${selected.ref.kind}:${selected.ref.id}`} className="platform-form panel automatic-source-form" onSubmit={saveAutomatic}><div className="automatic-source-summary"><span className="asset-result-symbol">{(selected.symbol.trim()||selected.name.trim()||selected.ref.id).slice(0,12).toUpperCase()}</span><div><p className="eyebrow">Selected market identity</p><h3>{selected.name}</h3><p className="fine">CoinGecko ID {selected.ref.id} · {selected.ref.kind==='rwa'?`${selected.ref.assetType.toUpperCase()} · tokenized RWA reference`:'crypto asset'}</p></div></div><label className="field">Wealth classification<select name="assetClass" defaultValue="" required><option value="" disabled>Choose a classification</option><option>Crypto</option><option>Stablecoins</option><option>Stocks</option><option>Precious Metals</option><option>Custom</option></select></label><label className="field">{automaticUnitLabel(selected)}<input name="quantity" inputMode="decimal" required/></label><label className="field">Quote currency<select name="currency" defaultValue="USD"><option>USD</option>{selected.ref.kind==='coin'&&<option>EUR</option>}</select></label><label className="field">Asset note (optional)<textarea name="notes" maxLength={2000}/></label>{selected.ref.kind==='rwa'&&<p className="fine automatic-rwa-notice">CoinGecko RWA values are tokenized market references in USD. They are not exchange prices, broker execution prices, or physical Gold/Silver spot. Enter tokenized reference units here; use manual entry for grams, kilograms, or troy ounces.</p>}<p className="fine">The public quote can change your current valuation. It never creates a contribution, verifies ownership, or changes the quantity you entered.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Save automatic-price source'}</button>{error&&<p role="alert">{error}</p>}</form>}</>}
 {mode==='manual'&&<><div className="manual-source-options">{MANUAL_SOURCES.map((c,i)=><button type="button" className="secondary" aria-expanded={category===c} key={c} onClick={()=>{setCategory(category===c?undefined:c);setError('');}}><span aria-hidden="true">{['◈','◇','◎','▥','△','⌂','✧'][i]}</span> {c}</button>)}</div>{category&&<form key={category} className="platform-form panel" onSubmit={save}><h3>{category}</h3><p className="fine">Manual entry · not verified. Saved to your Positions; allocate it when you create the Goal.</p><label className="field">{category==='Property'?'Property name':'Asset name'}<input name="name" required maxLength={100}/></label>{!['Cash','Precious metals','Property','Custom asset'].includes(category)&&<label className="field">Symbol / ticker<input name="symbol" required maxLength={30}/></label>}{category==='Precious metals'&&<><label className="field">Metal<select name="metal"><option>Gold</option><option>Silver</option><option>Custom metal</option></select></label><label className="field">Weight unit<select name="unit"><option>grams</option><option>kilograms</option><option>troy ounces</option></select></label></>}<label className="field">{category==='Cash'?'Cash amount':category==='Precious metals'?'Weight':category==='Stocks'?'Share quantity':category==='Property'?'Quantity / share':'Quantity'}{['Custom asset','Property'].includes(category)?' (optional)':''}<input name="quantity" inputMode="decimal" required={!['Custom asset','Property'].includes(category)}/></label><label className="field">Valuation currency<input name="currency" defaultValue="USD" required maxLength={3}/></label>{category!=='Cash'&&<><label className="field">Manual total value {['Custom asset','Property'].includes(category)?'':'(optional)'}<input name="value" inputMode="decimal" required={['Custom asset','Property'].includes(category)}/></label>{category!=='Property'&&<label className="field">Manual price per entered unit (optional)<input name="price" inputMode="decimal"/></label>}<p className="fine">Total value takes precedence over unit price. No price or currency conversion is assumed.{category==='Stablecoins'?' A stablecoin is not automatically valued at $1.':''}{category==='Precious metals'?' Physical weights always use your manual total or per-unit value.':''}</p></>}<label className="field">Asset note (optional)<textarea name="notes" maxLength={2000}/></label><button className="primary" disabled={busy}>Save manual source</button>{error&&<p role="alert">{error}</p>}</form>}</>}</section>;
}
