'use client';
import Link from 'next/link';
import {useState} from 'react';
import {usePlatform} from './use-platform';
import {useMarketQuotes} from './use-market-quotes';
import {useMarketInsights} from './use-market-insights';
import {marketUniverse,marketCategory,FEATURED_MARKETS,type MarketRow} from '../../lib/product-insights';
import {marketRefKey,marketRequestKey,type MarketAssetRef} from '../../lib/market-assets';
import {addFavourite,removeFavourite} from '../../lib/asset-management';
import {formatGoalAmount} from '../../lib/goal-summary';
import {amount} from './common';
import {AssetIcon,FreshnessBadge,Sheet} from './financial-ui';
import {MarketMovement} from './market-movement';
import {quoteIsStale} from '../../lib/market-quotes';
import {AssetPicker} from './asset-picker';
import './wealth-product.css';
import './markets-pagination.css';
const PAGE_SIZE=24;
export function MarketsView(){
 const store=usePlatform(),[filter,setFilter]=useState('All markets'),[query,setQuery]=useState(''),[adding,setAdding]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(0),[selectedRefs,setSelectedRefs]=useState<MarketAssetRef[]|null>(null);
 const known=marketUniverse(store.data),rows:MarketRow[]=[...known,...FEATURED_MARKETS.filter(a=>!known.some(r=>r.key===marketRefKey(a.ref))).map(a=>({...a,key:marketRefKey(a.ref),category:marketCategory(a.ref,a.symbol),favourite:false,positionIds:[]}))];
 // Search filters local identities only. Acquisition changes on explicit views/pages or loading prices.
 const acquiredRefs=selectedRefs??(store.loaded?rows.slice(0,PAGE_SIZE).map(r=>r.ref):[]),acquiredKeys=new Set(acquiredRefs.map(marketRefKey));
 const market=useMarketQuotes(acquiredRefs.map(marketRef=>({marketRef,currency:'USD'}))),insights=useMarketInsights(acquiredRefs);
 const matching=(view:string)=>rows.filter(r=>(view==='All markets'||view==='Owned'&&r.positionIds.length||view==='Favourites'&&r.favourite||view===r.category)&&`${r.name} ${r.symbol} ${r.ref.id}`.toLowerCase().includes(query.toLowerCase().trim()));
 const matches=matching(filter),lastPage=Math.max(0,Math.ceil(matches.length/PAGE_SIZE)-1),currentPage=Math.min(page,lastPage),visible=matches.slice(currentPage*PAGE_SIZE,(currentPage+1)*PAGE_SIZE),unselected=visible.some(r=>!acquiredKeys.has(r.key));
 function selectView(view:string){setFilter(view);setPage(0);setSelectedRefs(matching(view).slice(0,PAGE_SIZE).map(r=>r.ref));}
 function selectPage(next:number){setPage(next);setSelectedRefs(matches.slice(next*PAGE_SIZE,(next+1)*PAGE_SIZE).map(r=>r.ref));}
 function loadPrices(){if(unselected)setSelectedRefs(visible.map(r=>r.ref));else{void market.refresh();void insights.refresh();}}
 function toggle(row:MarketRow){setError('');void store.update(s=>row.favourite?removeFavourite(s,row.key):addFavourite(s,{ref:row.ref,name:row.name,symbol:row.symbol})).catch(e=>setError(e instanceof Error?e.message:'Could not update favourite.'));}
 return <div className="dashboard markets-page"><section className="markets-hero"><div><p className="eyebrow financial-orbit">YOUR FINANCIAL ORBIT</p><h1>A wider view.<br/><span className="nebula-text">Your markets.</span></h1><p>Follow the assets that interest you. Bring the ones you own into your wealth picture.</p></div><div className="markets-intro-card"><strong>{store.data.watchlist.length}<span> / 8</span></strong><p>Your favourites</p><button className="primary" disabled={!store.loaded||!!store.error} onClick={()=>setAdding(true)}>+ Find a market</button><small>Watching an asset never adds it to your wealth.</small></div></section>
 <section className="market-explorer" aria-label="Explore markets"><div className="market-toolbar"><label className="market-search">Search this market view<input type="search" value={query} placeholder="Bitcoin, Nvidia, Gold…" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><button className="secondary" disabled={!visible.length||market.loading||insights.loading} onClick={loadPrices}>{unselected?'Load prices for this view':'↻ Refresh market data'}</button></div><div className="picker-tabs" aria-label="Market views">{['All markets','Owned','Favourites','Crypto','Stablecoins','Stocks','ETFs','Precious Metals'].map(c=><button key={c} aria-pressed={filter===c} onClick={()=>selectView(c)}>{c}</button>)}</div>{(error||store.error)&&<p role="alert">{error||store.error}</p>}{(market.error||insights.error)&&<p className="notice" role="status">Some market data could not refresh. Last verified values retain their timestamps.</p>}
 <div className="market-pagination"><p aria-live="polite">{matches.length?`Showing ${currentPage*PAGE_SIZE+1}–${currentPage*PAGE_SIZE+visible.length} of ${matches.length} markets`:'No matching markets'}</p>{matches.length>PAGE_SIZE&&<nav aria-label="Market pages"><button className="secondary" disabled={currentPage===0} onClick={()=>selectPage(currentPage-1)}>Previous</button><span>Page {currentPage+1} of {lastPage+1}</span><button className="secondary" disabled={currentPage===lastPage} onClick={()=>selectPage(currentPage+1)}>Next</button></nav>}</div>{unselected&&<p className="fine">Search updates instantly using known markets. Choose “Load prices for this view” for fresh evidence; cached values remain visible.</p>}
 <div className="markets-grid">{visible.map(r=>{const q=market.quotes.find(q=>q.marketRef&&marketRefKey(q.marketRef)===r.key&&q.currency==='USD'),result=insights.results[marketRequestKey({marketRef:r.ref,currency:'USD'})],href=`/app/wealth/asset/${encodeURIComponent(r.positionIds[0]??r.key)}`;return <article className="market-product-card" key={r.key}><header><AssetIcon symbol={r.symbol} kind={r.category} logoUrl={result?.insight?.logoUrl}/><div><h2><Link href={href}>{r.name}</Link></h2><p>{r.symbol.toUpperCase()} · {r.category}</p></div><button className="market-favourite" aria-label={`${r.favourite?'Remove':'Add'} ${r.name} favourite`} aria-pressed={r.favourite} disabled={!store.loaded||!!store.error} onClick={()=>toggle(r)}>{r.favourite?'★':'☆'}</button></header><div className="market-card-price"><strong>{q?formatGoalAmount(amount(q.price,q.priceDecimals),'USD'):acquiredKeys.has(r.key)||result?'Price unavailable':'Price not loaded'}</strong><FreshnessBadge state={q?quoteIsStale(q,market.now)?'stale':'fresh':'missing'}/></div><MarketMovement result={result} notRequested={!result&&!acquiredKeys.has(r.key)}/><footer><span className="market-ownership" data-owned={!!r.positionIds.length}>{r.positionIds.length?'Owned asset':r.favourite?'Favourite only':'Market reference'}</span><Link className="text-link" href={href}>Explore →</Link></footer></article>;})}</div>{!visible.length&&<div className="panel"><h2>No matches in this view</h2><p>Try another name or browse the full CoinGecko catalog.</p><button className="secondary" onClick={()=>setAdding(true)}>Find a market</button></div>}</section><p className="market-method-note">Crypto prices use CoinGecko. Stocks, ETFs and metals use tokenized RWA references, which can differ from the underlying market. Seven-day sequences have no individual timestamps. No trading or return forecast is implied.</p>{adding&&<Sheet title="Find a market" onClose={()=>setAdding(false)}><AssetPicker onFavourite={a=>void store.update(s=>addFavourite(s,a)).then(()=>setAdding(false)).catch(e=>setError(String(e)))}/>{error&&<p role="alert">{error}</p>}</Sheet>}</div>;
}
