'use client';
import type {Platform,PrivateGoal} from '../../lib/positions';
import {revisionInstallments,canceledRevisionInstallments} from '../../lib/plan-revisions';
import {amount} from './common';
export function PlanHistory({goal,data,now}:{goal:PrivateGoal;data:Platform;now:number}){
 const today=new Date(now).toISOString().slice(0,10),end=new Date(now+366*86400000).toISOString().slice(0,10);
 const revisions=goal.planRevisions??[];let error='',installments:ReturnType<typeof revisionInstallments>=[],canceled:ReturnType<typeof revisionInstallments>=[];
 try{if(revisions.length){installments=revisionInstallments(goal,revisions[0]!.effectiveFrom,end,data.contributions,now);canceled=canceledRevisionInstallments(goal,end,data.contributions,now);}}catch{error='Installments need compatible currency assumptions before they can be shown.';}
 const shown=[...installments.filter(x=>x.date<today).slice(-6),...installments.filter(x=>x.date>=today).slice(0,6)];
 return <>
 <section aria-label="Retained plan terms"><h3>Retained plan terms</h3><p className="fine">Changes apply from their effective day in UTC. Earlier terms remain unchanged. A later revision on the same future day supersedes that day’s earlier intention. Habit links are separate.</p>{!revisions.length?<p>This legacy plan has no retained revision history. Earlier versions are unknown. Its first edit will start a recorded history.</p>:<><p>{revisions[0]?.priorHistory==='unknown'?'Earlier plan terms are unknown. Planned totals begin on the first recorded effective day.':'Plan terms have been retained since this Goal was created.'}</p><ol>{revisions.map((r,i)=><li key={r.id}><strong>Effective {r.effectiveFrom}</strong> · {r.terms?`${amount(r.terms.amount,r.terms.decimals)} ${r.terms.asset} · ${r.terms.cadence} · ${r.terms.active?'active':'paused'}`:'No plan'}<p className="fine">Recorded {new Date(r.recordedAt).toLocaleString()} · target {amount(r.target,r.decimals)} {r.asset}{r.targetDate?` by ${r.targetDate}`:''}{i===revisions.length-1&&r.effectiveFrom>today?' · scheduled change':''}</p></li>)}</ol></>}</section>
 {!!revisions.length&&<section aria-label="Plan installments"><h3>Plan installments</h3>{canceled.length>0&&<details><summary>Superseded future installments ({canceled.length} in this window)</summary><p>These intentions were canceled by a later plan revision. Any recorded funding remains recorded wealth and history; it is not automatically reassigned to a new installment.</p><ul>{canceled.map(x=><li key={x.id}>{x.date} · {amount(x.amount,goal.decimals)} {goal.asset} canceled intention · {amount(x.credited,goal.decimals)} {goal.asset} previously matched</li>)}</ul></details>}{error?<p className="notice">{error}</p>:<><p className="fine">Showing up to six recent and six upcoming installments within the next year. Only explicitly matched funding reduces an installment. History-only records never count as funding.</p>{shown.length?<ul>{shown.map(x=><li key={x.id}><strong>{x.date}</strong> · {amount(x.amount,goal.decimals)} {goal.asset} planned · {amount(x.remaining,goal.decimals)} {goal.asset} remaining</li>)}</ul>:<p>No installments in this window.</p>}</>}</section>}
 </>;
}
export function GoalMilestones({goal}:{goal:PrivateGoal}){
 return <section aria-label="Retained Goal milestones"><h3>Retained Goal milestones</h3><p>Current attainment can rise or fall. A target reached with sufficient evidence stays in this history. A revised target or reopened Goal starts a new cycle.</p>{goal.lifecycle?.length?<ol>{goal.lifecycle.map(e=><li key={e.id}><strong>{e.kind==='completed'?'Target reached':e.kind==='closed'?'Closed':e.kind==='reopened'?'Reopened':'Target revised'}</strong> · {new Date(e.at).toLocaleString()} · target {amount(e.target,e.decimals)} {e.asset}{e.current!==undefined?` · counted ${amount(e.current,e.decimals)} ${e.asset}`:''}</li>)}</ol>:<p>No milestones have been observed and retained yet. Earlier completion dates are not inferred.</p>}</section>;
}
