'use client';
import { useState, type FormEvent } from 'react';
import { parseUnits } from '@zigoals/chain-config';
import { usePlatform } from './use-platform';
import { amount, Freshness, PlatformNav } from './common';
import { rescaleUnits, allocationBalance, FUTURE_PROVIDERS, positionSchema, stakingProjection, saveManualPosition, replaceObservation, markObservationError, positionSync, type Position } from '../../lib/positions';
import { READ_NETWORKS, readPublicPositions, type ReadMode } from '../../lib/position-reader';
export function PositionsView(){
 const store=usePlatform();const [mode,setMode]=useState<ReadMode>('MAINNET_READ_ONLY');const [account,setAccount]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState<Position>(),[apr,setApr]=useState('');
 const network=READ_NETWORKS[mode].chainId;
 const observed=store.data.positions.filter(p=>p.network===network&&p.providerId==='native-zig');
 const total=(type?:Position['sourceType'])=>observed.filter(p=>!type||p.sourceType===type).reduce((n,p)=>n+BigInt(rescaleUnits(p.quantity,p.decimals,18)),0n).toString();
 const allocated=observed.reduce((n,p)=>n+BigInt(rescaleUnits(allocationBalance(store.data,p.id).allocated,p.decimals,18)),0n).toString();
 const unallocated=observed.reduce((n,p)=>n+BigInt(rescaleUnits(allocationBalance(store.data,p.id).unallocated,p.decimals,18)),0n).toString();
 async function read(event:FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{
  const data=await readPublicPositions(mode,account.trim());await store.update(s=>replaceObservation(s,network,account.trim(),data));setMessage('Public snapshot saved. No wallet authority requested.');
 }catch{try{await store.update(s=>markObservationError(s,network,account.trim()));}catch{/* A storage failure must not replace the preserved record. */}setError('Could not verify public positions at one block height. Check the address and network availability. Previous quantities are preserved; a failed refresh needs review.');}finally{setBusy(false);}}
 async function manual(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setError('');setBusy(true);try{
  const asset=editing?.asset??String(form.get('asset')).trim().toUpperCase();const precision=editing?.decimals??18;const now=new Date().toISOString();
  const p=positionSchema.parse({id:editing?.id??crypto.randomUUID(),providerId:String(form.get('name')).trim(),sourceType:'MANUAL',network:editing?.network??'manual',account:editing?.account??'local',asset,denom:editing?.denom??(asset==='ZIG'?'azig':`manual:${asset}`),decimals:precision,quantity:parseUnits(String(form.get('quantity')),precision).toString(),verification:'MANUAL',sync:'MANUAL',liquidity:'UNKNOWN',observedAt:now,provenance:'Explicit user entry; not synchronized or chain-verified',notes:String(form.get('notes')),valuation:form.get('value')?{value:parseUnits(String(form.get('value')),2).toString(),currency:String(form.get('currency')).toUpperCase(),decimals:2,source:'MANUAL',observedAt:now}:undefined});
  await store.update(s=>saveManualPosition(s,p));setEditing(undefined);setMessage('Manual position saved. Review allocations after changing a balance.');
 }catch{setError('Position was not saved. Use valid non-negative quantities and values.');}finally{setBusy(false);}}
 function projection(days:number){try{return amount(stakingProjection(total('NATIVE_STAKING'),apr,days));}catch{return '—';}}
 return <div className="dashboard platform-workspace"><div className="page-heading"><div><p className="eyebrow">Wealth where it already works</p><h1>Your ZIG / Positions</h1><p>Observe public wealth and track manual positions. Allocations are private accounting, without moving funds.</p></div></div><PlatformNav/>
 <section className="panel"><h2>Mainnet Read-Only / Watch-Only</h2><p>Tracking an address does not establish ownership. This reader has no signer, staking, claim or transaction capability. Local Demo and Testnet Wallet remain separate in Wallet &amp; data.</p>
 <form onSubmit={read} className="platform-form"><label className="field">Read-only network<select value={mode} onChange={e=>setMode(e.target.value as ReadMode)}><option value="MAINNET_READ_ONLY">Mainnet Read-Only / Watch-Only</option><option value="TESTNET_READ_ONLY">Testnet public read-only</option></select></label><label className="field">Public ZIG address<input value={account} onChange={e=>setAccount(e.target.value)} required maxLength={90} placeholder="zig1…" autoComplete="off"/></label><button className="primary" disabled={busy||!store.loaded||!!store.error}>Read public positions</button></form><p className="fine">Only the public address and selected network are sent to ZIGoals’ read-only relay, which verifies official chain data at one block height, on your request. Goal names, allocations, notes and Habits stay in this browser. Cached snapshots are not live balances.</p></section>
 {(error||store.error)&&<p role="alert" className="notice">{error||store.error}</p>}{message&&<p role="status">{message}</p>}
 <section className="summary-strip" aria-label={`${network} observed totals`}>{[['Total observed',total()],['Liquid',total('WALLET_LIQUID')],['Staked principal',total('NATIVE_STAKING')],['Unclaimed rewards',total('NATIVE_REWARDS')],['Unbonding',total('NATIVE_UNBONDING')],['Allocated',allocated],['Unallocated',unallocated]].map(([label,value])=><div key={label}><small>{label} · {network}</small><strong>{amount(value!)} ZIG</strong></div>)}</section>
 <section className="panel"><h2>Staking reward scenario</h2><p>Canonical current APR is not verified. Commission is shown per validator below. Enter your own net delegator APR assumption after commission for an illustrative scenario.</p><label className="field">Assumed net APR %<input value={apr} onChange={e=>setApr(e.target.value)} inputMode="decimal" placeholder="No rate assumed"/></label><div className="summary-strip">{[7,30,365].map(days=><div key={days}><small>{days}-day future rewards</small><strong>{projection(days)} ZIG</strong></div>)}</div><p className="fine">Simple APR. Estimate assumes current stake and APR remain unchanged. No automatic compounding or guaranteed yield. Future rewards never count as current Goal progress.</p></section>
 <section className="goal-grid" aria-label="Positions">{[...observed,...store.data.positions.filter(p=>p.sourceType==='MANUAL')].map(p=>{const b=allocationBalance(store.data,p.id);return <article className="panel" key={p.id}><p className="eyebrow">{p.sourceType.replaceAll('_',' ')} · {p.verification}</p><h2>{p.sourceType==='MANUAL'?p.providerId:p.validator?.name??'Liquid wallet'}</h2><strong>{amount(p.quantity,p.decimals)} {p.asset}</strong><p>{p.network} · {p.liquidity} · {positionSync(p)}</p><p>Allocated {amount(b.allocated,p.decimals)} · Unallocated {amount(b.unallocated,p.decimals)}</p>{b.deficit!=='0'&&<p role="alert" className="notice">Allocation deficit: {amount(b.deficit,p.decimals)} {p.asset}. Review your Goals.</p>}{p.validator&&<p>Validator {p.validator.address}<br/>{p.validator.status} · commission {Number(p.validator.commission)*100}% · voting stake {amount(p.validator.votingTokens,p.decimals)} ZIG</p>}{p.exitDate&&<p>Expected unbonding completion <time>{new Date(p.exitDate).toLocaleString()}</time></p>}<p className="fine"><Freshness at={p.observedAt} sync={positionSync(p)}/></p><p className="fine">{p.provenance}</p>{p.risk&&<p>{p.risk}</p>}{p.notes&&<p>{p.notes}</p>}{p.valuation&&<p>Manual value {amount(p.valuation.value,p.valuation.decimals)} {p.valuation.currency}</p>}{p.sourceType==='MANUAL'&&<button className="secondary" onClick={()=>setEditing(p)}>Edit {p.providerId}</button>}</article>;})}</section>
 <section className="panel"><h2>{editing?'Update manual position':'Add a manual position'}</h2><p>MANUAL · not synchronized or chain-verified. Use explicit updates for unsupported accounts and providers. An existing Position’s asset identity is fixed; add a new Position for a different asset.</p><form key={editing?.id??'new'} className="platform-form" onSubmit={manual}><label className="field">Position name<input name="name" required maxLength={100} defaultValue={editing?.providerId}/></label><label className="field">Position asset<input name="asset" required readOnly={!!editing} maxLength={30} defaultValue={editing?.asset??'ZIG'}/></label><label className="field">Position quantity<input name="quantity" required inputMode="decimal" defaultValue={editing?amount(editing.quantity,editing.decimals):''}/></label><label className="field">Optional manual value<input name="value" inputMode="decimal" defaultValue={editing?.valuation?amount(editing.valuation.value,editing.valuation.decimals):''}/></label><label className="field">Value currency<input name="currency" maxLength={10} defaultValue={editing?.valuation?.currency??'USD'}/></label><label className="field">Position notes<textarea name="notes" maxLength={2000} defaultValue={editing?.notes}/></label><button className="primary" disabled={busy||!store.loaded||!!store.error}>Save manual position</button>{editing&&<button type="button" className="secondary" onClick={()=>setEditing(undefined)}>Cancel edit</button>}</form></section>
 <details className="panel"><summary>Future provider architecture</summary><p>No live integration or execution is implied.</p><ul>{FUTURE_PROVIDERS.map(p=><li key={p.name}>{p.name} · {p.state}</li>)}</ul></details></div>;
}
