"use client";
import Link from 'next/link';
import {useState,type CSSProperties} from 'react';
import './run92-gap-fixes.css';
import {portfolioComposition,needsAttention,fundingAgenda} from '../../lib/product-insights';
import type {Platform} from '../../lib/positions';
import type {MarketQuote} from '../../lib/market-quotes';
import {wealthOverview} from '../../lib/wealth';
import {formatGoalAmount} from '../../lib/goal-summary';
import {amount} from './common';
import {useEntrance} from '../use-entrance';
import {smoothConicGradient} from '../../lib/visual-gradients';
const money=(value:bigint,currency:string)=>formatGoalAmount(amount(value.toString(),2),currency);
export function PortfolioComposition({overview}:{overview:ReturnType<typeof wealthOverview>}){
 const groups=portfolioComposition(overview);
 const entrance=useEntrance<HTMLElement>('portfolio-composition',groups.length>0);
 return <section ref={entrance} className="portfolio-composition panel" aria-labelledby="composition-title"><header className="section-heading"><div><p className="eyebrow">THE SHAPE OF YOUR WEALTH</p><h2 id="composition-title">Portfolio composition</h2><p>Asset classes, your largest holdings and what is available for Goals. Currencies stay separate.</p></div></header>{groups.length?groups.map(group=>{
 let offset=0;const stops=group.segments.map(s=>{const from=offset;offset+=s.basisPoints/100;return {color:s.color,offset:from,size:s.basisPoints/100};});
 return <div className="composition-group" key={group.currency} aria-label={`${group.currency} portfolio composition`}><div className="composition-currency"><div className="composition-donut" role="img" aria-label={`${group.currency} composition: ${group.segments.map(s=>`${s.label} ${(s.basisPoints/100).toFixed(2)}%`).join(', ')}`} style={{'--composition':smoothConicGradient(stops)} as CSSProperties}><span><small>{group.currency} known total</small><strong>{money(group.total,group.currency)}</strong></span></div><dl className="composition-legend">{group.segments.map(s=><div key={s.label}><dt><i style={{background:s.color}}/>{s.label}</dt><dd><strong>{money(s.value,group.currency)}</strong><span>{(s.basisPoints/100).toFixed(2)}%</span></dd></div>)}</dl></div><div className="composition-details"><section className="composition-allocation" aria-label={`${group.currency} allocated and available`}><h3>Purpose &amp; possibility</h3><div className="composition-allocation-bar" role="img" aria-label={`${(group.allocatedBasisPoints/100).toFixed(2)}% allocated to Goals`}><span style={{width:`${group.allocatedBasisPoints/100}%`}}/></div><dl><div><dt>Allocated to Goals</dt><dd>{money(group.allocated,group.currency)}</dd></div><div><dt>Available for Goals</dt><dd>{money(group.available,group.currency)}</dd></div></dl>{group.incomplete&&<p className="fine">Known valued holdings only. Unvalued assets are excluded.</p>}</section><section className="composition-top-holdings" aria-label={`${group.currency} top holdings`}><h3>Top holdings <small>{group.currency}</small></h3><ol>{group.topHoldings.map(holding=><li key={holding.id}><Link href={`/app/wealth/asset/${encodeURIComponent(holding.id)}`}><span>{holding.name}</span><strong>{money(holding.value,group.currency)}</strong></Link><div className="top-holding-bar" aria-hidden="true"><span style={{width:`${holding.basisPoints/100}%`}}/></div><small>{(holding.basisPoints/100).toFixed(2)}% of {group.currency} known wealth</small></li>)}</ol></section></div></div>;
 }):<p>Add a valued asset to see how your portfolio fits together.</p>}</section>;
}
export function NeedsAttention({data,now,quotes}:{data:Platform;now:number;quotes:readonly MarketQuote[]}){const items=needsAttention(data,now,quotes),[all,setAll]=useState(false);return <section className="needs-attention panel" id="needs-attention" aria-labelledby="attention-title"><header className="section-heading"><div><p className="eyebrow">YOUR NEXT USEFUL STEP</p><h2 id="attention-title">Needs attention <span className="attention-count">{items.length}</span></h2></div></header>{items.length?<ul>{(all?items:items.slice(0,4)).map(i=><li key={i.id} data-kind={i.kind}><span className="attention-symbol" aria-hidden="true">{i.kind==='overdue'?'↗':i.kind==='plan'?'+':'!'}</span><div><h3>{i.title}</h3><p>{i.detail}</p><Link href={i.href} className="text-link">{i.action} →</Link></div></li>)}</ul>:<div className="attention-clear"><span aria-hidden="true">✓</span><h3>A clear view ahead</h3><p>No funding or valuation issues need your attention right now.</p><Link className="text-link" href="/app/goals">Explore your Goals →</Link></div>}{items.length>4&&<button className="quiet" onClick={()=>setAll(!all)}>{all?'Show fewer':`View all ${items.length} items`}</button>}</section>;}
export function FundingAgenda({data,now,quotes}:{data:Platform;now:number;quotes:readonly MarketQuote[]}){const rows=fundingAgenda(data,now,quotes);return <section className="funding-agenda panel" aria-labelledby="agenda-title"><header className="section-heading"><div><p className="eyebrow">MAKE ROOM FOR PROGRESS</p><h2 id="agenda-title">Your funding agenda</h2><p>Contribution plans and recorded funding, in one place.</p></div></header>{rows.length?<ol>{rows.map(r=><li key={r.goalId}><div className="agenda-date"><strong>{r.nextDate?new Date(r.nextDate+'T12:00:00Z').getUTCDate():'—'}</strong><span>{r.nextDate?new Date(r.nextDate+'T12:00:00Z').toLocaleDateString('en',{month:'short',timeZone:'UTC'}):'No date'}</span></div><div><h3><Link href={r.href}>{r.name}</Link></h3><p>{formatGoalAmount(amount(r.amount,r.decimals),r.asset)} · {r.cadence}</p><span className="agenda-status" data-overdue={r.overdue}>{r.overdue?'Contributions behind plan':r.status==='REVIEW'?'Funding evidence needs review':'Next planned contribution'}</span></div><Link href={r.href} className="text-link">Review →</Link></li>)}</ol>:<p>Set a contribution plan on a financial Goal to see its next funding date.</p>}<p className="fine">Only contributions explicitly linked to a scheduled date satisfy that installment.</p></section>;}
