'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { parseUnits } from '@zigoals/chain-config';
import { localDate } from '../../lib/local-date';
import { useHabits } from '../habits/use-habits';
import { goalLinkMatches } from '../../lib/habits';
import { usePlatform } from './use-platform';
import { amount, PlatformNav } from './common';
import { scenarioHorizon, planScenario, goalProgress, privateGoalSchema, type PrivateGoal } from '../../lib/positions';
export function TrackedGoals({compact=false}:{compact?:boolean}){
 const store=usePlatform(),habits=useHabits();const [filter,setFilter]=useState('Active'),[type,setType]=useState<PrivateGoal['type']>('QUANTITY'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const visible=store.data.goals.filter(g=>filter==='All'||filter==='Active'&&g.status==='active'||filter==='Completed'&&g.status==='completed'||filter==='Closed'&&g.status==='closed'||g.type===filter.toUpperCase());
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{
  const asset=String(form.get('asset')||(type==='VALUE'?'USD':'ZIG')).toUpperCase();const decimals=type==='VALUE'?2:type==='PROJECT'?0:18;
  const goal=privateGoalSchema.parse({id:BigInt('0x'+crypto.randomUUID().replaceAll('-','')).toString(),name:String(form.get('name')),network:form.get('network'),type,status:'active',asset,denom:type==='VALUE'?asset:asset==='ZIG'?'azig':`manual:${asset}`,decimals,target:type==='PROJECT'?'1':parseUnits(String(form.get('target')),decimals).toString(),notes:String(form.get('notes')),createdAt:new Date().toISOString(),targetDate:form.get('date')||undefined,milestones:type==='PROJECT'?String(form.get('milestones')).split('\n').filter(s=>s.trim()).map(title=>({id:crypto.randomUUID(),title:title.trim(),done:false})):[]});
  if(type==='PROJECT'&&!goal.milestones.length)throw Error('Add at least one milestone.');
  await store.update(s=>({...s,goals:[...s.goals,goal]}));setFilter('Active');
 }catch{setError('Goal was not saved. Check the name, positive target, date and milestones.');}finally{setBusy(false);}}
 return <section className="platform-workspace">{!compact&&<><div className="page-heading"><div><p className="eyebrow">Your goals. Onchain.</p><h1>Tracked goals</h1><p>Connect wealth you already have to what matters. No custody or Goal Manager deployment required.</p></div></div><PlatformNav/></>}{compact&&<div className="section-heading"><h2>Your wealth, your goals</h2><Link className="text-link" href="/app/goals/tracked">Create a tracked goal →</Link></div>}
 {(store.error||error)&&<p role="alert" className="notice">{store.error||error}</p>}
 <nav className="tab-row view-tabs platform-nav" aria-label="Tracked Goal filters">{['Active','Completed','Closed','All','Quantity','Value','Reward','Project'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</nav>
 <div className="goal-grid">{visible.map(g=>{const p=goalProgress(store.data,g.id);let funding='No plan';try{if(g.plan)funding=planScenario(g,p.current,g.plan,scenarioHorizon(localDate(),g.targetDate),localDate()).fundingHealth.replaceAll('_',' ');}catch{funding='Review assumptions';}const linked=habits.data.habits.filter(h=>goalLinkMatches(h.goalLink,{chainId:'private',owner:'local',goalId:g.id})).length;return <article className="panel" key={g.id}><p className="eyebrow">{g.type} · {g.status} · Private tracking</p><h2><Link href={`/app/goals/tracked/${g.id}`}>{g.name}</Link></h2><strong>{amount(p.current,g.decimals)} / {amount(p.target,g.decimals)} {g.type==='PROJECT'?'milestones':g.asset}</strong><p>{p.progressPct}% · {amount(p.remaining,g.decimals)} remaining</p><progress max={100} value={Math.min(100,Number(p.progressPct))} aria-label={`${g.name} progress`}/><p>{linked} linked Habits · Funding Health: {funding}</p><p>{p.breakdown.length} Position sources{g.plan?` · ${g.plan.cadence} plan`:''}</p>{p.requiresReview&&<p className="notice">Allocation or valuation needs review.</p>}<p className="fine">Manual {amount(p.manual,g.decimals)} · Verified snapshot {amount(p.verified,g.decimals)}</p></article>;})}</div>
 {store.loaded&&!visible.length&&<p className="notice">No {filter.toLowerCase()} tracked goals yet. Add a Position, then allocate some of it to a Goal. Allocation never moves funds.</p>}
 {!compact&&<section className="panel"><h2>Create a tracked goal</h2><form className="platform-form" onSubmit={create}><label className="field">Goal name<input name="name" required maxLength={100}/></label><label className="field">Wealth scope<select name="network"><option value="zigchain-1">Mainnet + manual</option><option value="zig-test-2">Testnet + manual</option></select></label><label className="field">Goal type<select value={type} onChange={e=>setType(e.target.value as PrivateGoal['type'])}><option value="QUANTITY">Quantity · accumulate ZIG</option><option value="VALUE">Value · explicit valuations</option><option value="REWARD">Reward · unclaimed staking rewards</option><option value="PROJECT">Project · milestones</option></select></label>{type!=='PROJECT'&&<label className="field">{type==='VALUE'?'Goal currency':'Goal asset'}<input key={type} name="asset" required maxLength={30} defaultValue={type==='VALUE'?'USD':'ZIG'}/></label>}{type!=='PROJECT'?<label className="field">Target amount<input name="target" inputMode="decimal" required/></label>:<label className="field">Milestones, one per line<textarea name="milestones" required rows={4}/></label>}<label className="field">Target date (optional)<input name="date" type="date"/></label><label className="field">Goal notes<textarea name="notes" maxLength={2000}/></label><button className="primary" disabled={busy||!store.loaded||!!store.error}>Create tracked goal</button></form><p className="fine">Value Goals require explicit manual valuations until a verified price provider exists. Reward Goals track currently unclaimed rewards, not cumulative claimed income.</p></section>}
 </section>;
}
