'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { z } from 'zod';
import { parseUnits } from '@zigoals/chain-config';
import { availableNativeStake, quickAllocateStake } from '../../lib/owner-preview';
import { usePlatform } from './use-platform';
import { amount, Freshness, PlatformNav } from './common';
import { positionSync, allocatedNativePrincipal, scenarioHorizon, stakingProjection, assetMatches, allocate, allocationBalance, closeGoal, contributionSchema, privateGoalSchema, goalProgress, planScenario, type PrivateGoal } from '../../lib/positions';
import { useHabits } from '../habits/use-habits';
import { HabitCompletion } from '../habits/habit-card';
import { createHabit, editHabit, latestHabitRule, setHabitState, goalLinkMatches, habitStats, type HabitInput } from '../../lib/habits';
import { localDate } from '../../lib/local-date';
function contributionTemplate(goal:PrivateGoal,today:string):HabitInput|undefined {
 const plan=goal.plan;if(!plan||plan.cadence==='irregular')return;
 const numeric=Number(amount(plan.amount,plan.decimals));
 const purchase=goal.asset==='ZIG'&&['USD','EUR'].includes(plan.asset)&&numeric>0&&numeric<=1_000_000_000;
 const period=plan.cadence==='weekly'?'week':plan.cadence==='yearly'?'year':'month';
 return {title:purchase?'Buy ZIG':`Contribute ${amount(plan.amount,plan.decimals)} ${plan.asset} ${plan.cadence}`.slice(0,100),category:'Financial',description:`Supporting behavior for ${goal.name}. Once per calendar ${period}; plan date ${plan.nextDate}. Completion does not add financial progress.`.slice(0,500),notes:'',goalLink:{chainId:'private',owner:'local',goalId:goal.id},type:'build',measurement:purchase?{kind:'quantity',unit:plan.asset}:{kind:'boolean'},schedule:{kind:'frequency',times:1,period},target:purchase?numeric:1,targetPeriod:'day',endCondition:plan.endDate&&plan.endDate>=today?{kind:'date',date:plan.endDate}:{kind:'none'}};
}
export function TrackedDetail({id}:{id:string}){
 const store=usePlatform(),habits=useHabits();const [apr,setApr]=useState('');const [error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const goal=store.data.goals.find(g=>g.id===id);if(!store.loaded)return <p role="status">Loading tracked Goal…</p>;
 if(!goal)return <section className="panel"><h1>Tracked Goal unavailable</h1><p>{store.error||'This private Goal is not stored in this browser.'}</p><PlatformNav/></section>;
 const progress=goalProgress(store.data,id);const linked=habits.data.habits.filter(h=>goalLinkMatches(h.goalLink,{chainId:'private',owner:'local',goalId:id}));
 const staking=progress.breakdown.filter(b=>store.data.positions.find(p=>p.id===b.positionId)?.sourceType==='NATIVE_STAKING');
 const quickStake=availableNativeStake(store.data,goal);
 const principal=allocatedNativePrincipal(store.data,id);
 function rewardEstimate(days:number){try{return amount(stakingProjection(principal,apr,days));}catch{return '—';}}
 const template=contributionTemplate(goal,habits.today);
 const referencedHabit=habits.data.habits.find(h=>h.id===goal.plan?.habitId);
 const contributionHabit=referencedHabit&&goalLinkMatches(referencedHabit.goalLink,{chainId:'private',owner:'local',goalId:id})?referencedHabit:undefined;
 const mismatchedHabit=!!referencedHabit&&!contributionHabit;
 const expectedHabitState=goal.plan?.active&&(!goal.plan.endDate||goal.plan.endDate>=habits.today)?'active':'paused';
 const rule=contributionHabit?latestHabitRule(contributionHabit):undefined;
 const habitDrift=!!contributionHabit&&(!template||contributionHabit.title!==template.title||contributionHabit.description!==template.description||!goalLinkMatches(contributionHabit.goalLink,template.goalLink!)||JSON.stringify(rule?.schedule)!==JSON.stringify(template.schedule)||rule?.state!==expectedHabitState||rule?.type!=='build'||JSON.stringify(rule?.measurement)!==JSON.stringify(template.measurement)||rule?.target!==template.target||rule?.targetPeriod!=='day'||JSON.stringify(rule?.endCondition)!==JSON.stringify(template.endCondition));
 const eligible=store.data.positions.filter(p=>(p.network==='manual'||p.network===goal.network)).filter(p=>goal.type==='VALUE'||goal.type==='REWARD'&&p.sourceType==='NATIVE_REWARDS'||goal.type==='QUANTITY'&&assetMatches(goal,p));
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');setMessage('');try{await action();setMessage('Private Goal saved. No funds moved.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 async function saveAllocation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const position=eligible.find(p=>p.id===f.get('position'));if(!position)return;await run(()=>store.update(s=>allocate(s,id,position.id,parseUnits(String(f.get('quantity')),position.decimals).toString())));}
 async function savePlan(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>{
  const asset=String(f.get('asset')).toUpperCase();const decimals=asset==='USD'||asset==='EUR'?2:18;
  const plan=contributionSchema.parse({amount:parseUnits(String(f.get('amount')),decimals).toString(),asset,decimals,cadence:f.get('cadence'),nextDate:f.get('next'),habitId:goal!.plan?.habitId,endDate:f.get('end')||undefined,active:f.get('active')==='on',price:f.get('price')?{value:parseUnits(String(f.get('price')),18).toString(),decimals:18,currency:asset}:undefined});
  if(goal!.asset!==asset&&!plan.price)throw Error('Enter a price assumption to project this contribution currency into the Goal asset.');
  return store.update(s=>({...s,goals:s.goals.map(g=>g.id===id?{...g,plan}:g)}));
 });}
 async function reconcileContributionHabit(){
  if(!template||!contributionHabit)return;
  await run(()=>habits.update(data=>{
   const current=data.habits.find(h=>h.id===contributionHabit.id);if(!current||!goalLinkMatches(current.goalLink,{chainId:'private',owner:'local',goalId:id}))throw Error('Contribution habit no longer belongs to this Goal. Create a new linked habit instead.');
   const now=new Date();
   const next=editHabit(data,current.id,{...template,notes:current.notes,timeOfDay:current.timeOfDay,stackAfterId:current.stackAfterId},now);
   return setHabitState(next,current.id,expectedHabitState,now);
  }));
 }
 async function createContributionHabit(){
  if(!template)return;
  await run(async()=>{
   let reservedId='';
   // Reserve under the platform lock first. A failed Habit write leaves one retryable ID.
   await store.update(data=>{
    const current=data.goals.find(g=>g.id===id);if(!current?.plan||current.status==='closed')throw Error('Contribution plan is unavailable.');
    const previousId=current.plan.habitId;
    const referenced=habits.data.habits.find(h=>h.id===previousId);
    reservedId=previousId&&z.uuid().safeParse(previousId).success&&(!referenced||goalLinkMatches(referenced.goalLink,{chainId:'private',owner:'local',goalId:id}))?previousId:crypto.randomUUID();
    return {...data,goals:data.goals.map(g=>g.id===id&&g.plan?{...g,plan:{...g.plan,habitId:reservedId}}:g)};
   });
   await habits.update(data=>{
    const existing=data.habits.find(h=>h.id===reservedId);
    if(existing){
     if(!goalLinkMatches(existing.goalLink,{chainId:'private',owner:'local',goalId:id}))throw Error('Reserved habit belongs to another Goal. Existing history was preserved.');
     return data;
    }
    const now=new Date();return setHabitState(createHabit(data,template,now,reservedId),reservedId,expectedHabitState,now);
   });
  });
 }
 let scenario:ReturnType<typeof planScenario>|undefined;let scenarioError='';
 if(goal.plan)try{scenario=planScenario(goal,progress.current,goal.plan,scenarioHorizon(localDate(),goal.targetDate),localDate());}catch{scenarioError='Projection unavailable: review dates and explicit price assumptions.';}
 return <div className="dashboard platform-workspace"><div className="page-heading"><div><p className="eyebrow">{goal.type} · {goal.status} · Private tracking</p><h1>{goal.name}</h1><p>{goal.notes}</p></div></div><PlatformNav/>{(error||store.error)&&<p role="alert" className="notice">{error||store.error}</p>}{message&&<p role="status">{message}</p>}
 {goal.type!=='PROJECT'&&<nav className="goal-setup" aria-label="Goal setup"><a href="#allocate" aria-current={!progress.breakdown.length?'step':undefined}><b>{progress.breakdown.length?'✓':'01'}</b><span>Link / allocate wealth<small>Give existing ZIG a purpose</small></span></a><a href="#contribution-plan" aria-current={!!progress.breakdown.length&&!goal.plan?'step':undefined}><b>{goal.plan?'✓':'02'}</b><span>Set contribution plan<small>Choose your amount and rhythm</small></span></a><a href="#supporting-habits" aria-current={!!goal.plan&&!contributionHabit?'step':undefined}><b>{contributionHabit?'✓':'03'}</b><span>Create supporting Habit<small>Build consistency</small></span></a><a href="#tracked-progress"><b>04</b><span>Track progress<small>Review observed wealth</small></span></a></nav>}
 <section id="tracked-progress" className="panel" data-testid="tracked-progress"><p className="eyebrow">Observed / explicitly entered state</p><h2>{amount(progress.current,goal.decimals)} / {amount(progress.target,goal.decimals)} {goal.type==='PROJECT'?'milestones':goal.asset}</h2><strong>{progress.progressPct}%</strong><p>{amount(progress.remaining,goal.decimals)} remaining{goal.targetDate?` · Target ${goal.targetDate}`:''}</p><progress max={100} value={Math.min(100,Number(progress.progressPct))} aria-label="Goal progress"/><p>Manual {amount(progress.manual,goal.decimals)} · Verified snapshots {amount(progress.verified,goal.decimals)}</p>{progress.requiresReview&&<p className="notice">Review required. An allocation deficit, stale sync or missing valuation affects this Goal. Deficits count only a proportional share of available units, rounded down; intended allocations are preserved.</p>}</section>
 {goal.type!=='PROJECT'&&<section id="allocate" className="panel"><p className="eyebrow">01 · Link / allocate wealth</p><h2>Position breakdown</h2>{goal.status!=='closed'&&quickStake.length>0&&progress.remaining!=='0'&&<div className="setup-next"><h3>Use my staked ZIG for this Goal</h3><p>Reserve available stake across eligible validators, up to your remaining target.</p><button className="primary" disabled={busy||!!store.error} onClick={()=>void run(()=>store.update(s=>quickAllocateStake(s,id)))}>Allocate available stake up to Goal target</button><p className="fine">Private accounting only. No transaction, delegation change or movement of funds.</p></div>}{progress.breakdown.length>0&&<p><a href="#contribution-plan" className="text-link">{goal.plan?'Review contribution plan':'Next: set your contribution plan'} →</a></p>}{progress.breakdown.map(b=>{const p=store.data.positions.find(p=>p.id===b.positionId)!;const balance=allocationBalance(store.data,p.id);return <div className="platform-position-row" key={p.id}><h3>{p.validator?.name??p.providerId} · {p.sourceType.replaceAll('_',' ')}</h3><p>{amount(b.quantity,p.decimals)} {p.asset} intended · {amount(b.counted,goal.decimals)} {goal.asset} counted · {p.liquidity} · {p.verification}</p>{balance.deficit!=='0'&&<p className="notice">Position-wide deficit: {amount(balance.deficit,p.decimals)} {p.asset}</p>}<p className="fine"><Freshness at={p.observedAt} sync={positionSync(p)}/></p>{p.validator&&<p>Commission {Number(p.validator.commission)*100}% · {p.validator.status}</p>}{p.exitDate&&<p>Expected exit: {p.exitDate}</p>}{p.risk&&<p>{p.risk}</p>}</div>;})}{!progress.breakdown.length&&<p>No allocation yet. <Link href="/app/goals/positions">Add or refresh a Position →</Link></p>}{goal.status!=='closed'&&!!eligible.length&&<form className="platform-form" onSubmit={saveAllocation}><label className="field">Position to allocate<select name="position">{eligible.map(p=><option key={p.id} value={p.id}>{p.providerId} · {p.validator?.name??p.sourceType} · {amount(p.quantity,p.decimals)} {p.asset}</option>)}</select></label><label className="field">Allocation quantity<input name="quantity" required inputMode="decimal"/></label><button className="primary" disabled={busy||!!store.error}>Save allocation</button><p className="fine">Sets this Goal’s allocation. Enter 0 to release it. Units cannot be allocated twice. This is not a transfer.</p></form>}</section>}
 {!!staking.length&&<section className="panel"><h2>Staking supporting this Goal</h2><p>Allocated observed principal: {amount(principal)} ZIG. Validator identities, commission and liquidity are listed in the Position breakdown.</p><label className="field">Goal net APR assumption %<input inputMode="decimal" value={apr} onChange={e=>setApr(e.target.value)} placeholder="No current rate verified"/></label><div className="summary-strip">{[7,30,365].map(days=><div key={days}><small>{days}-day projected future rewards</small><strong>{rewardEstimate(days)} ZIG</strong></div>)}</div><p className="fine">Simple APR scenario, after commission. Estimate assumes current stake and APR remain unchanged. No automatic compounding. Projected rewards do not count as current Goal progress.</p><Link href="/app/goals/positions" className="text-link">Review unclaimed rewards, validators and unbonding →</Link></section>}
 <section className="panel"><h2>Milestones</h2>{goal.milestones.length?goal.milestones.map(m=><label className="checkbox" key={m.id}><input type="checkbox" checked={m.done} disabled={busy||goal.status==='closed'} onChange={e=>void run(()=>store.update(s=>({...s,goals:s.goals.map(g=>g.id===id?{...g,milestones:g.milestones.map(old=>old.id===m.id?{...old,done:e.target.checked}:old)}:g)})))}/>{m.title}</label>):<p>No milestones yet.</p>}{goal.status!=='closed'&&<form className="platform-form" onSubmit={e=>{e.preventDefault();const title=String(new FormData(e.currentTarget).get('title'));void run(()=>store.update(s=>({...s,goals:s.goals.map(g=>g.id===id?{...g,milestones:[...g.milestones,{id:crypto.randomUUID(),title,done:false}]}:g)})));}}><label className="field">New milestone<input name="title" maxLength={100} required/></label><button className="secondary" disabled={busy}>Add milestone</button></form>}</section>
 {goal.type!=='PROJECT'&&<section id="contribution-plan" className="panel"><p className="eyebrow">02 · Plan the next step</p><h2>Contribution plan</h2><p>Private intention only. Recording behavior or changing a price assumption never changes observed progress.</p><form className="platform-form" onSubmit={savePlan} key={JSON.stringify(goal.plan)}><label className="field">Planned amount<input name="amount" required inputMode="decimal" defaultValue={goal.plan?amount(goal.plan.amount,goal.plan.decimals):''}/></label><label className="field">Contribution asset<input name="asset" required defaultValue={goal.plan?.asset??goal.asset} maxLength={30}/></label><label className="field">Cadence<select name="cadence" defaultValue={goal.plan?.cadence??'monthly'}>{['weekly','monthly','yearly','irregular'].map(c=><option key={c}>{c}</option>)}</select></label><label className="field">Next expected date<input name="next" required type="date" min={localDate()} defaultValue={goal.plan?.nextDate??localDate()}/></label><label className="field">Plan end (optional)<input name="end" type="date" defaultValue={goal.plan?.endDate}/></label><label className="field">Price per Goal unit in contribution currency (if different)<input name="price" inputMode="decimal" defaultValue={goal.plan?.price?amount(goal.plan.price.value,goal.plan.price.decimals):''}/></label><label className="checkbox"><input name="active" type="checkbox" defaultChecked={goal.plan?.active??true}/>Active plan</label><button className="primary" disabled={busy||goal.status==='closed'}>Save contribution plan</button></form>{template&&!contributionHabit&&<div className="setup-next"><p>Plan saved. Turn your {goal.plan?.cadence} intention into a supporting Habit.</p><a className="primary" href="#supporting-habits">Create supporting Habit →</a></div>}</section>}
 {scenario&&<section className="panel"><p className="eyebrow">Planned contribution scenario · zero future return</p><h2>Funding Health: {scenario.fundingHealth.replaceAll('_',' ')}</h2><p>Planned contributions: {amount(scenario.contributions,goal.decimals)} {goal.asset} across {scenario.dates.length} scheduled dates.</p><p>Projected completion: {scenario.completionDate??"Not reached within this scenario"}</p><p>Projected balance: {amount(scenario.projected,goal.decimals)} · Shortfall: {amount(scenario.shortfall,goal.decimals)} · Surplus: {amount(scenario.surplus,goal.decimals)}</p><p className="fine">Through {scenarioHorizon(localDate(),goal.targetDate)}. This scenario is not current wealth or a guarantee. Unbonding and provider liquidity may prevent access by your deadline.</p></section>}{scenarioError&&<p className="notice">{scenarioError}</p>}
 <section id="supporting-habits" className="panel"><p className="eyebrow">03 · Find your rhythm</p><h2>Supporting habits</h2>{linked.map(h=><div key={h.id}><h3>{h.title}</h3><p>Behavior consistency {habitStats(h,habits.today).weeklyConsistency}% this week</p><HabitCompletion habit={h} store={habits}/></div>)}{!linked.length&&<p>No supporting Habit yet.</p>}<button className="secondary" disabled={busy||!habits.loaded||!!habits.error||goal.status==='closed'} onClick={()=>void run(async()=>{await habits.create({title:`Review ${goal.name}`.slice(0,100),category:'Goals',description:'Review progress and planned contributions.',notes:'',goalLink:{chainId:'private',owner:'local',goalId:id},schedule:{kind:'weekdays',days:[1]},target:1});})}>Add weekly Goal review habit</button>{mismatchedHabit&&<p className="notice">Saved contribution habit belongs to another Goal. Create a new linked habit; the unrelated habit and its history will be kept.</p>}{habitDrift&&<div className="notice"><p>Contribution habit differs from this plan. Its existing behavior and history have not been changed.</p>{template?<><p>Apply the current amount, asset, cadence and active state from today onward; earlier rules and entries stay intact.</p><button className="secondary" disabled={busy||!habits.loaded||!!habits.error||goal.status==='closed'} onClick={()=>void reconcileContributionHabit()}>Apply plan to contribution habit</button></>:<p>This plan is irregular. <Link href="/app/habits">Review the existing habit separately in Habits.</Link></p>}</div>}{template&&!contributionHabit&&<button className="primary" disabled={busy||!habits.loaded||!!habits.error||goal.status==='closed'} onClick={()=>void createContributionHabit()}>Create supporting Habit →</button>}<p className="fine">Habit completion records behavior only. It never changes Positions or financial progress. <Link href="/app/habits">Manage habits →</Link></p></section>
 <section className="panel"><h2>Observation history</h2><p className="fine">Snapshots show quantities, not inferred contributions or causes. Market movement, rewards and manual adjustments are not interchangeable.</p><ul>{store.data.snapshots.filter(s=>progress.breakdown.some(b=>b.positionId===s.positionId)).slice(-12).reverse().map((s,i)=>{const p=store.data.positions.find(p=>p.id===s.positionId)!;return <li key={`${s.positionId}:${s.observedAt}:${i}`}>{s.observedAt} · {p.sourceType} · {amount(s.quantity,p.decimals)} {p.asset}</li>;})}</ul></section>
 <details className="panel"><summary>Edit Goal details</summary><form className="platform-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>store.update(s=>({...s,goals:s.goals.map(g=>g.id===id?privateGoalSchema.parse({...g,name:String(f.get('name')),notes:String(f.get('notes')),target:g.type==='PROJECT'?g.target:parseUnits(String(f.get('target')),g.decimals).toString(),targetDate:f.get('date')||undefined}):g)})));}}><label className="field">Edit Goal name<input name="name" required maxLength={100} defaultValue={goal.name}/></label>{goal.type!=='PROJECT'&&<label className="field">Edit target<input name="target" inputMode="decimal" required defaultValue={amount(goal.target,goal.decimals)}/></label>}<label className="field">Edit deadline<input name="date" type="date" defaultValue={goal.targetDate}/></label><label className="field">Edit Goal notes<textarea name="notes" maxLength={2000} defaultValue={goal.notes}/></label><button className="secondary" disabled={busy||goal.status==='closed'}>Save Goal details</button></form></details>
 <section className="panel"><h2>Goal status</h2><p>Closing releases all allocations. Completing keeps them reserved until you explicitly close the Goal.</p>{goal.status!=='closed'&&<div className="actions"><button className="secondary" disabled={busy} onClick={()=>void run(()=>store.update(s=>({...s,goals:s.goals.map(g=>g.id===id?{...g,status:g.status==='completed'?'active':'completed'}:g)})))}>{goal.status==='completed'?'Reopen Goal':'Mark completed'}</button><button className="secondary" disabled={busy} onClick={()=>void run(()=>store.update(s=>closeGoal(s,id)))}>Close Goal and release allocations</button></div>}</section>
 </div>;
}
