'use client';
import {useState} from 'react';
import Link from 'next/link';
import {usePlatform} from './use-platform';
import {useMarketQuotes} from './use-market-quotes';
import {marketRefKey} from '../../lib/market-assets';
import {addFavourite,removeFavourite,moveFavourite} from '../../lib/asset-management';
import {quoteIsStale} from '../../lib/market-quotes';
import {AssetPicker} from './asset-picker';
import {AssetIcon,FreshnessBadge,Sheet} from './financial-ui';
import {amount} from './common';
import {formatGoalAmount} from '../../lib/goal-summary';
export function Watchlist({compact=false}:{compact?:boolean}){const store=usePlatform(),[adding,setAdding]=useState(false),[error,setError]=useState('');const market=useMarketQuotes(store.data.watchlist.map(a=>({marketRef:a.ref,currency:'USD' as const})));
 function change(fn:Parameters<typeof store.update>[0]){setError('');void store.update(fn).catch(e=>setError(e instanceof Error?e.message:'Watchlist could not be changed.'));}
 return <section className={`market-watch ${compact?'compact-watch':''}`} aria-label="Favourite markets"><header className="wealth-section-heading"><div><p className="eyebrow">MARKETS THAT MATTER TO YOU</p><h2>{compact?'Your market watch':'Your favourites'}</h2>{!compact&&<p>Follow the price. Ownership is optional.</p>}</div><button type="button" className="secondary" onClick={()=>setAdding(true)} disabled={!store.loaded||!!store.error}>+ Add favourite</button></header>{error&&<p role="alert">{error}</p>}<div className="watchlist-grid">{store.data.watchlist.map((a,i)=>{const key=marketRefKey(a.ref),q=market.quotes.find(q=>q.marketRef&&marketRefKey(q.marketRef)===key&&q.currency==='USD');return <article className="watch-card" key={key}><Link className="watch-card-link" href={`/app/wealth/asset/${encodeURIComponent(key)}`}><div className="owned-asset-heading"><AssetIcon symbol={a.symbol} kind={a.ref.kind==='rwa'&&a.ref.assetType==='commodity'?'Precious Metals':'Crypto'}/><div><h3>{a.name}</h3><p>{a.symbol.toUpperCase()} · {a.ref.kind==='rwa'?a.ref.assetType:'Crypto'}</p></div></div><strong className="watch-price">{q?formatGoalAmount(amount(q.price,q.priceDecimals),'USD'):'Price unavailable'}</strong><div className="asset-card-source"><span>{a.ref.kind==='rwa'?'CoinGecko RWA reference':'CoinGecko'}</span><FreshnessBadge state={q?quoteIsStale(q,market.now)?'stale':'fresh':'missing'}/></div></Link>{!compact&&<div className="watch-actions"><button className="quiet" disabled={i===0} aria-label={`Move ${a.name} earlier`} onClick={()=>change(s=>moveFavourite(s,key,-1))}>← Move earlier</button><button className="quiet" aria-label={`Remove ${a.name} favourite`} onClick={()=>change(s=>removeFavourite(s,key))}>Remove</button></div>}</article>;})}{!store.data.watchlist.length&&<button className="watch-empty" type="button" onClick={()=>setAdding(true)}><span>✧</span><strong>Your first favourite awaits</strong><p>Bitcoin, Nvidia, Gold… follow what interests you.</p></button>}</div>{!compact&&<p className="fine">Favourites never count toward your wealth or Goal allocations.</p>}{adding&&<Sheet title="Add a favourite" onClose={()=>setAdding(false)}><AssetPicker onFavourite={a=>{setError('');void store.update(s=>addFavourite(s,a)).then(()=>setAdding(false)).catch(e=>setError(e instanceof Error?e.message:'Could not add favourite.'));}}/>{error&&<p role="alert">{error}</p>}</Sheet>}</section>;
}
