'use client';
import type {LayoutAttrs} from '../layout-edit';
import {useMemo,useState} from 'react';
import {formatUnits} from '@zigoals/chain-config';
import {type Platform} from '../../lib/positions';
import {wealthHistory} from '../../lib/wealth';
import {ownedWealthChanges,CHANGE_LABELS} from '../../lib/wealth-changes';
import {formatDateTime,formatPlainDecimal} from '../../lib/visual-format';
import {plural} from '../../lib/plural';
const money=(v:string,currency:string)=>`${BigInt(v)<0n?'-':''}${formatPlainDecimal(formatUnits((BigInt(v)<0n?-BigInt(v):BigInt(v)).toString(),2))} ${currency}`;
export function WealthChanges({data,...layout}:LayoutAttrs&{data:Platform}){
 const histories=useMemo(()=>wealthHistory(data),[data]),[currency,setCurrency]=useState(''),[from,setFrom]=useState(''),[through,setThrough]=useState(''),[page,setPage]=useState(0),series=histories.find(h=>h.currency===currency)??histories[0],start=series?.points.find(p=>p.at===from)?.at??series?.points[0]?.at,end=series?.points.find(p=>p.at===through)?.at??series?.points.at(-1)?.at;
 let result:ReturnType<typeof ownedWealthChanges>|undefined,error='';if(series&&start&&end&&start!==end)try{result=ownedWealthChanges(data,series.currency,start,end);}catch(e){error=e instanceof Error?e.message:'Choose valid recorded observations.';}
 const pages=Math.max(1,Math.ceil((result?.records.length??0)/20)),selectedPage=Math.min(page,pages-1);
 return <details {...layout} className="panel" id="wealth-change-review"><summary>Explain recorded wealth change</summary><p>Compare complete, unambiguous recorded observations of tracked, owned wealth. Goal reallocations do not change ownership. Only explicitly linked statement evidence and supported funding/price records are classified; a remaining gap stays visible. This is not a return calculation or a claim that every transaction is recorded.</p>
 {series&&series.points.length>1?<><div className="intelligence-actions"><label>Change currency<select value={series.currency} onChange={e=>{setCurrency(e.target.value);setFrom('');setThrough('');setPage(0);}}>{histories.map(h=><option key={h.currency}>{h.currency}</option>)}</select></label><label>Opening observation<select value={start} onChange={e=>{setFrom(e.target.value);setPage(0);}}>{series.points.map(p=><option key={p.at} value={p.at}>{formatDateTime(p.at)}</option>)}</select></label><label>Closing observation<select value={end} onChange={e=>{setThrough(e.target.value);setPage(0);}}>{series.points.map(p=><option key={p.at} value={p.at}>{formatDateTime(p.at)}</option>)}</select></label></div>
 {result&&<><dl><dt>Opening owned wealth</dt><dd>{money(result.opening,result.currency)}</dd><dt>Closing owned wealth</dt><dd>{money(result.closing,result.currency)}</dd><dt>Total recorded change</dt><dd>{money(result.change,result.currency)}</dd>{Object.entries(CHANGE_LABELS).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{money(result!.totals[key as keyof typeof CHANGE_LABELS],result!.currency)}</dd></div>)}<dt>Unclassified reconciliation gap</dt><dd>{money(result.gap,result.currency)}</dd></dl>{result.warnings.map(w=><p className="notice" key={w}>{w}</p>)}<p className="fine">Totals use currency minor units, rounded toward zero where a source has greater precision. Exact original amounts and source identities remain below. A zero gap is numerical agreement, not independent proof of complete records.</p><ol start={selectedPage*20+1}>{result.records.slice(selectedPage*20,selectedPage*20+20).map(r=><li key={r.id} style={{overflowWrap:'anywhere'}}><a href={r.href}>{CHANGE_LABELS[r.kind]} · {r.label}</a><p>{money(r.value,result!.currency)} · {formatDateTime(r.at)}</p><details><summary>Exact source record</summary><p>{r.id}</p><p>{formatPlainDecimal(formatUnits(r.exact.value,r.exact.decimals))} {r.exact.currency} · {r.at}</p></details></li>)}</ol><nav aria-label="Wealth change record pages"><button disabled={selectedPage===0} onClick={()=>setPage(selectedPage-1)}>Previous change records</button><span>Page {selectedPage+1} of {pages} · {result.records.length}{` ${plural(result.records.length,'record')}`}</span><button disabled={selectedPage+1>=pages} onClick={()=>setPage(selectedPage+1)}>Next change records</button></nav></>}{!result&&!error&&<p>Choose a closing observation after the opening observation.</p>}</>:<p>Two complete observations in one currency are needed. Missing earlier evidence and competing observations at the same instant stay unresolved.</p>}{error&&<p role="alert">{error}</p>}
 </details>;
}
