'use client';
import './wealth.css';
import './intelligence.css';
import Link from 'next/link';
import {usePlatform} from './use-platform';
import {useMarketQuotes} from './use-market-quotes';
import {useValuationHistory} from './use-valuation-history';
import {useEvidenceNow} from './use-evidence-now';
import {EvidenceChart} from './evidence-chart';
import {amount} from './common';
import {wealthMarketRequests,wealthOverview,ASSET_COLORS} from '../../lib/wealth';
import {formatGoalAmount} from '../../lib/goal-summary';
import {SceneArt} from '../scene-art';
import {AppIcon} from '../app-icon';
import type {AssetClass} from '../../lib/positions';

const visuals:Record<AssetClass,{icon:string;scene:'horizon'|'aurora'|'home'|'garden'|'mountains'}>={Crypto:{icon:'chain',scene:'horizon'},Stablecoins:{icon:'goals',scene:'aurora'},Stocks:{icon:'activity',scene:'mountains'},'Precious Metals':{icon:'future',scene:'mountains'},Property:{icon:'home',scene:'home'},Cash:{icon:'wallet',scene:'garden'},Custom:{icon:'star',scene:'aurora'}};
const money=(n:bigint,currency:string)=>`${n<0n?'-':''}${formatGoalAmount(amount((n<0n?-n:n).toString(),2),currency)}`;
const when=(at?:string)=>at&&Number.isFinite(Date.parse(at))?new Date(at).toLocaleString():undefined;

export function WealthView(){
 const store=usePlatform(),requests=wealthMarketRequests(store.data),market=useMarketQuotes(requests);
 useValuationHistory(store,market);
 const evidenceNow=useEvidenceNow(store.data,market.now),overview=wealthOverview(store.data,evidenceNow,market.quotes);
 if(!store.loaded)return <div className="dashboard wealth-workspace"><section className="panel wealth-loading"><span aria-hidden="true"/><h1>Your Wealth</h1><p>Bringing your private Positions into view…</p></section></div>;
 if(store.error)return <div className="dashboard wealth-workspace"><section className="panel wealth-loading"><h1>Your Wealth</h1><p role="alert">{store.error}</p></section></div>;
 const automatic=overview.rows.filter(row=>row.position.valuationMode==='automatic'||row.source?.startsWith('CoinGecko'));
 const fresh=automatic.filter(row=>row.valuationState==='fresh').length,attention=automatic.filter(row=>row.valuationState==='stale'||row.valuationState==='missing').length;
 const metric=(key:'value'|'allocated'|'unallocated')=>overview.subtotals.length?overview.subtotals.map(s=><span key={s.currency}>{money(s[key],s.currency)}</span>):<span>{overview.rows.length?'Valuation unavailable':'No wealth tracked yet'}</span>;
 return <div className="dashboard wealth-workspace">
  <section className="wealth-hero panel">
   <div className="wealth-hero-scene"><SceneArt scene="horizon"/></div><div className="wealth-orbit wealth-orbit-one"/><div className="wealth-orbit wealth-orbit-two"/>
   <div className="wealth-hero-copy"><p className="eyebrow">YOUR FINANCIAL ORBIT</p><h1>Wealth, with every <span className="nebula-text">source in view.</span></h1><p className="wealth-intro">See what is allocated to your Goals, what remains available, and exactly which evidence supports each value.</p><div className="wealth-actions"><Link className="primary" href="/app/goals/positions">Manage Positions</Link>{requests.length>0&&<button className="secondary" type="button" onClick={()=>void market.refresh()} disabled={market.loading}><AppIcon name="refresh" size={16}/>{market.loading?'Refreshing…':'Refresh prices'}</button>}</div><p className="fine">Read-only wealth tracking. Allocations organize your plan; no funds move.</p></div>
   <div className="wealth-hero-total" aria-label={overview.incomplete?'Known tracked wealth':'Total tracked wealth'}><span>{overview.incomplete?'KNOWN TRACKED WEALTH':'TOTAL TRACKED WEALTH'}</span><strong className="nebula-number">{metric('value')}</strong><small>{overview.subtotals.length>1?'Currencies remain separate · no FX assumed':overview.rows.length?`${overview.rows.length} tracked ${overview.rows.length===1?'Position':'Positions'}`:'Start with your first Position'}</small></div>
   <dl className="wealth-split"><div><dt><span className="split-dot allocated"/>Allocated to Goals</dt><dd>{metric('allocated')}</dd></div><div><dt><span className="split-dot available"/>Available for Goals</dt><dd>{metric('unallocated')}</dd></div></dl>
  </section>

  <section className="wealth-evidence-bar" aria-label="Valuation evidence status"><div><span className="evidence-signal" data-state={attention?'attention':'fresh'}/><p><strong>{automatic.length?`${fresh} of ${automatic.length} automatic ${automatic.length===1?'value':'values'} current`:'Manual values only'}</strong><small>{attention?`${attention} automatic ${attention===1?'value needs':'values need'} attention`:'Evidence freshness is shown on every Position'}</small></p></div>{market.error&&<p role="status">Provider refresh unavailable. Any last-good quotes remain visible and labeled by freshness.</p>}{!market.error&&market.loading&&<p role="status">Checking public market evidence…</p>}{overview.incomplete&&<p>Some Positions still need a valuation. Known totals remain available.</p>}</section>

  <section className="wealth-history panel" aria-labelledby="wealth-history-title"><div className="wealth-section-heading"><div><p className="eyebrow">RECORDED LOCALLY</p><h2 id="wealth-history-title">Your wealth history starts with evidence</h2><p>Daily points appear only after ZIGoals has recorded a complete currency total. Missing days and earlier performance are never filled in.</p></div>{overview.history.some(item=>item.points.length>1)&&<div className="wealth-change-stack">{overview.history.filter(item=>item.points.length>1).map(item=><span key={item.currency}><small>Since first complete snapshot · {item.currency}</small><strong className="nebula-number">{BigInt(item.change)>=0n?'+':''}{money(BigInt(item.change),item.currency)}{item.changePercent&&<em>{BigInt(item.change)>=0n?'+':''}{item.changePercent}%</em>}</strong></span>)}</div>}</div>{overview.history.length?<div className="wealth-history-grid">{overview.history.map(item=><div className="wealth-history-chart" key={item.currency}><h3>{item.currency} recorded wealth</h3><EvidenceChart label={`${item.currency} recorded tracked wealth`} currency={item.currency} decimals={item.decimals} series={[{label:'Complete local snapshot',color:'#72ddd4',points:item.points}]}/></div>)}</div>:<EvidenceChart label="Recorded tracked wealth" currency="USD" decimals={2} series={[]}/>}</section>

  <div className="wealth-category-grid">{overview.categories.map(category=><section className="panel wealth-category" key={category.assetClass} aria-label={category.assetClass}><div className="wealth-category-art"><SceneArt scene={visuals[category.assetClass].scene}/><div className="wealth-category-icon"><AppIcon name={visuals[category.assetClass].icon} size={30} luminous/></div><span>{String(category.items.length).padStart(2,'0')}</span></div><div className="wealth-category-body"><div className="wealth-category-heading"><div><p className="eyebrow">ASSET CLASS</p><h2><span className="asset-swatch" style={{background:ASSET_COLORS[category.assetClass]}}/><span>{category.assetClass}</span></h2></div><p>{category.items.length} {category.items.length===1?'Position':'Positions'}</p></div>{category.subtotals.map(total=><div className="wealth-category-total" key={total.currency}><div><small>{total.currency} total</small><strong className="nebula-number">{money(total.value,total.currency)}</strong></div><dl><div><dt>Allocated</dt><dd>{money(total.allocated,total.currency)}</dd></div><div><dt>Available</dt><dd>{money(total.unallocated,total.currency)}</dd></div></dl></div>)}{category.incomplete&&<p className="wealth-category-alert">Some Positions need valuation evidence.</p>}{!category.items.length&&<div className="wealth-category-empty"><span aria-hidden="true">◌</span><p>No {category.assetClass.toLowerCase()} tracked yet.</p></div>}<ul className="wealth-assets">{category.items.map(row=>{
    const source=row.source??'Valuation needed',stamp=when(row.valuedAt),rwa=source==='CoinGecko tokenized RWA reference';
    return <li key={row.position.id}><div className="wealth-asset-top"><div><strong>{row.position.providerId==='native-zig'?`${row.position.asset} · ${row.position.sourceType.replaceAll('_',' ').toLowerCase()}`:row.position.providerId}</strong><span>{amount(row.position.quantity,row.position.decimals)} {row.position.asset}</span></div><span className="valuation-chip" data-state={row.valuationState}>{row.valuationState==='fresh'?'Current':row.valuationState==='manual'?'Manual':row.valuationState==='stale'?'Last good':'Needs value'}</span></div><strong className="wealth-asset-value">{row.value===undefined?'Valuation unavailable':money(row.value,row.currency!)}</strong><dl className="wealth-asset-allocation"><div><dt>Allocated</dt><dd>{amount(row.balance.allocated,row.position.decimals)} {row.position.asset}</dd></div><div><dt>Available</dt><dd>{amount(row.balance.unallocated,row.position.decimals)} {row.position.asset}</dd></div></dl><div className="wealth-source-line"><span>{source}</span>{stamp&&<time dateTime={row.valuedAt}>{stamp}</time>}</div>{rwa&&<p className="fine">Tokenized/onchain RWA market reference · not an exchange, broker, or physical-metal spot price.</p>}{row.balance.deficit!=='0'&&<p className="wealth-category-alert">Allocation deficit · review Positions</p>}{row.stale&&<p className="fine">Position observation or valuation evidence needs refresh.</p>}</li>;
   })}</ul></div></section>)}</div>
 </div>;
}
