'use client';
import './wealth.css';
import Link from 'next/link';
import {usePlatform} from './use-platform';
import {useMarketQuotes} from './use-market-quotes';
import {amount} from './common';
import {wealthOverview,ASSET_COLORS} from '../../lib/wealth';
import {formatGoalAmount} from '../../lib/goal-summary';
import {SceneArt} from '../scene-art';
import {AppIcon} from '../app-icon';
import type {AssetClass} from '../../lib/positions';
const visuals:Record<AssetClass,{icon:string;scene:'horizon'|'aurora'|'home'|'garden'|'mountains'}>={Crypto:{icon:'chain',scene:'horizon'},Stablecoins:{icon:'goals',scene:'aurora'},Stocks:{icon:'activity',scene:'mountains'},'Precious Metals':{icon:'future',scene:'mountains'},Property:{icon:'home',scene:'home'},Cash:{icon:'wallet',scene:'garden'},Custom:{icon:'star',scene:'aurora'}};
const money=(n:bigint,currency:string)=>formatGoalAmount(amount(n.toString(),2),currency);
export function WealthView(){
 const store=usePlatform(),market=useMarketQuotes(store.data.positions.some(p=>p.providerId==='native-zig'&&p.network==='zigchain-1'));
 const overview=wealthOverview(store.data,market.now,market.quotes);
 if(!store.loaded)return <div className="dashboard"><h1>Your Wealth</h1><p>Loading your Positions…</p></div>;
 if(store.error)return <div className="dashboard"><h1>Your Wealth</h1><p role="alert">{store.error}</p></div>;
 const metric=(key:'value'|'allocated'|'unallocated')=>overview.subtotals.length?overview.subtotals.map(s=><span key={s.currency}>{money(s[key],s.currency)}</span>):<span>{overview.rows.length?'Valuation unavailable':'No wealth tracked yet'}</span>;
 return <div className="dashboard wealth-workspace"><section className="panel wealth-overview"><div className="wealth-scene"><SceneArt scene="horizon"/></div><p className="eyebrow">YOUR FINANCIAL ORBIT</p><h1 className="wealth-heading">Your <span className="nebula-text">Wealth</span></h1><p>Everything you track, with a purpose or room for your next one.</p><dl className="wealth-metrics"><div><dt>{overview.incomplete?'Known tracked wealth':'Total tracked wealth'}</dt><dd className="nebula-number">{metric('value')}</dd></div><div><dt>Allocated to Goals</dt><dd>{metric('allocated')}</dd></div><div><dt>Unallocated wealth</dt><dd>{metric('unallocated')}</dd></div></dl>{overview.incomplete&&<p className="notice">Valuation incomplete. Some assets need valuation. Currency subtotals are shown separately; no conversion is assumed.</p>}<p className="fine">Manual values and read-only observations. Allocations organize your wealth; no funds move.</p><Link className="secondary" href="/app/goals/positions">Manage Positions →</Link></section>
 <div className="wealth-category-grid">{overview.categories.map(c=><section className="panel wealth-category" key={c.assetClass} aria-label={c.assetClass}><div className="wealth-category-art"><SceneArt scene={visuals[c.assetClass].scene}/><AppIcon name={visuals[c.assetClass].icon} size={38} luminous/></div><div className="wealth-category-body"><h2><span className="asset-swatch" style={{background:ASSET_COLORS[c.assetClass]}}/><span className="wealth-heading">{c.assetClass}</span></h2><p className="fine">{c.items.length} {c.items.length===1?'Position':'Positions'}</p>{c.subtotals.map(t=><div className="wealth-category-total" key={t.currency}><strong className="nebula-number">{money(t.value,t.currency)}</strong><p className="fine">Allocated {money(t.allocated,t.currency)} · Unallocated {money(t.unallocated,t.currency)}</p></div>)}{c.incomplete&&<p className="fine">Valuation incomplete</p>}{!c.items.length&&<p>No assets tracked yet.</p>}<ul className="wealth-assets">{c.items.map(r=><li key={r.position.id}><strong>{r.position.providerId==='native-zig'?`${r.position.asset} · ${r.position.sourceType.replaceAll('_',' ').toLowerCase()}`:r.position.providerId}</strong><p>{amount(r.position.quantity,r.position.decimals)} {r.position.asset}</p><p>{r.value===undefined?'Valuation unavailable':`${r.position.valuation?.source==='MANUAL'?'Manual value':r.stale?'Last observed value':'Current value'} ${money(r.value,r.currency!)}`}</p><p className="fine">Allocated {amount(r.balance.allocated,r.position.decimals)} · Unallocated {amount(r.balance.unallocated,r.position.decimals)} {r.position.asset}</p>{r.balance.deficit!=='0'&&<p className="fine">Allocation deficit · review Positions</p>}{r.stale&&<p className="fine">Observation or valuation needs refresh</p>}</li>)}</ul></div></section>)}</div></div>;
}
