'use client';
import {useEffect,useState} from 'react';
import {ACCOUNT_CHANGE,getAccountGeneration,getAccountScope} from '../lib/account-session';
import {encryptBackup} from '../lib/vault/backup';
import {captureData} from '../lib/vault/account-data';
import {getAppStorage} from '../lib/showcase-storage';
type Result={deleted:boolean;providerDeleted?:boolean;providerPending?:boolean};
type Props={account:string|null;opened:boolean;busy:boolean;erase:(identity:boolean)=>Promise<Result|null>};
export function AccountDeletion(c:Props){
 const [backup,setBackup]=useState<{file:string;recovery:string}|null>(null),[saved,setSaved]=useState(false),[downloaded,setDownloaded]=useState(false),[identity,setIdentity]=useState(false),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[preparing,setPreparing]=useState(false);
 useEffect(()=>{const clear=()=>{setBackup(null);setSaved(false);setDownloaded(false);setConfirm('');};window.addEventListener(ACCOUNT_CHANGE,clear);return()=>window.removeEventListener(ACCOUNT_CHANGE,clear);},[]);
 async function prepare(){setPreparing(true);try{const account=c.account,generation=getAccountGeneration();const data=await captureData(getAppStorage(),['finance','habits','health','settings']);const result=await encryptBackup(data);if(account!==getAccountScope()||generation!==getAccountGeneration())throw Error('Account changed. Backup cancelled.');setBackup(result);setSaved(false);setDownloaded(false);setMessage('Encrypted recovery copy prepared. Separate local records will be retained.');}catch{setMessage('Backup was not prepared. Nothing was deleted.');}finally{setPreparing(false);}}
 function download(){if(!backup||!saved||!c.opened)return;const url=URL.createObjectURL(new Blob([backup.file],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='zigoals-before-cloud-deletion.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true);}
 // Session M (owner decision M2): deletion needs no download. A copy stays one optional step away, with today's steps.
 async function erase(){const result=await c.erase(identity),kept=downloaded?' and the copy you downloaded':'';if(result)setMessage(result.providerPending?`Cloud vault deleted and stale access blocked. Provider identity deletion remains pending; a durable recovery job will retry. Local copies${kept} are retained.`:result.providerDeleted?`Cloud vault and provider identity deletion confirmed. Local copies${kept} are retained.`:`Cloud vault deleted and stale access blocked. Provider identity and local copies${kept} are retained.`);}
 return <section className="panel" aria-label="Account deletion"><h2>Delete cloud records</h2><p>Cloud deletion removes active encrypted records and prevents offline devices from recreating this vault. It does not erase another device’s downloaded data or your exports. Infrastructure backups follow their retention policy. Signing out is a separate action.</p>
 {c.opened&&<><div className="deletion-copy"><h3>Download a copy first (optional)</h3><p>Deletion does not need a download. After deletion ZIGoals cannot open this account’s cloud records again, on any device, and signing in later cannot bring them back. If you may want them, keep an encrypted copy first.</p><button className="secondary" disabled={c.busy||preparing} onClick={()=>void prepare()}>Prepare backup before deletion</button>{backup&&<div className="notice"><label>Deletion backup recovery secret<input readOnly value={backup.recovery} autoComplete="off" spellCheck={false}/></label><label><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>I saved the deletion backup secret separately.</label><button disabled={!saved} onClick={download}>Download deletion recovery copy</button></div>}</div>
 <label><input type="checkbox" checked={identity} disabled={c.busy} onChange={e=>{setIdentity(e.target.checked);setConfirm('');}}/>Also delete my email provider identity.</label><p>Local account data stays on this browser, locked after deletion. Signing in later cannot restore the deleted vault.</p><label>Deletion confirmation<input autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder={identity?'DELETE ACCOUNT':'DELETE CLOUD DATA'}/></label><button className="secondary" disabled={c.busy||confirm!==(identity?'DELETE ACCOUNT':'DELETE CLOUD DATA')} onClick={()=>void erase()}>Confirm cloud deletion</button></>}
 {message&&<p role="status">{message}</p>}</section>;
}
