'use client';
import {useMemo,useState} from 'react';
import {resolveConflicts,validateResolution,type Choices,type ConflictReview,type ConflictChoice} from '../lib/vault/conflict-review';
export function ConflictReviewControls({busy,review,prepare,confirm,cancel}:{busy:boolean;review:ConflictReview|null;prepare:()=>Promise<void>;confirm:(choices:Choices)=>Promise<void>;cancel:()=>void}){
 const [choices,setChoices]=useState<Choices>({}),[saved,setSaved]=useState(false),[downloaded,setDownloaded]=useState(false),[phrase,setPhrase]=useState('');
 const result=useMemo(()=>{if(!review)return null;try{const base=Object.fromEntries(review.domains.filter(d=>review.original.base[d]!==undefined).map(d=>[d,review.original.base[d]])),plan=resolveConflicts(base,review.local,review.cloud,choices);let error='';if(!plan.unresolved)try{validateResolution({...review,original:{...review.original,base}},plan.data);}catch(e){error=e instanceof Error?e.message:'Resolution is invalid.';}return {...plan,error};}catch(e){return {data:{},conflicts:[],unresolved:1,error:e instanceof Error?e.message:'Review unavailable.'};}},[review,choices]);
 function download(){if(!review||!saved)return;const url=URL.createObjectURL(new Blob([review.file],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='zigoals-conflict-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true);}
 const display=(v:unknown)=>v===undefined?'Removed':typeof v==='string'?v:JSON.stringify(v);
 return <details><summary>Review conflicting account records</summary><p>Keep a protected copy of the original journal and both versions before choosing changes. Independent additions stay together. Accepted financial evidence cannot be removed or rewritten. Automatic sync pauses during review.</p>
 {!review&&<button disabled={busy} onClick={()=>{setChoices({});setSaved(false);setDownloaded(false);setPhrase('');void prepare();}}>Prepare conflict review</button>}
 {review&&result&&<div className="notice"><p>Sections: {review.domains.join(', ')}. {result.unresolved} fields still need a choice.</p><label>Conflict recovery secret<input readOnly value={review.recovery} autoComplete="off" spellCheck={false}/></label><label><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>I saved the conflict recovery secret separately.</label><button disabled={!saved||busy} onClick={download}>Download both conflict copies</button>
 {result.conflicts.map(c=><fieldset key={c.id} style={{minWidth:0,overflowWrap:'anywhere'}}><legend>{c.path}</legend><details><summary>Compare values</summary><p>On this browser: {display(c.local)}</p><p>In cloud: {display(c.cloud)}</p>{c.combined!==undefined&&<p>Combined exact change: {c.combined}. Review the complete allocation before confirming.</p>}</details><label>Choose value for {c.path}<select value={choices[c.id]??''} onChange={e=>setChoices({...choices,[c.id]:e.target.value as ConflictChoice})}><option value="">Choose explicitly</option><option value="local">Use this browser’s value</option><option value="cloud">Use cloud value</option>{c.combined!==undefined&&<option value="combined">Combine exact changes</option>}</select></label></fieldset>)}
 {result.error&&<p role="alert">{result.error}</p>}<label>Conflict confirmation<input value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder="RESOLVE RECORDS" autoComplete="off"/></label><button disabled={busy||!downloaded||!!result.error||result.unresolved>0||phrase!=='RESOLVE RECORDS'} onClick={()=>void confirm(choices)}>Confirm reviewed resolution</button><button disabled={busy} onClick={cancel}>Cancel conflict review</button></div>}
 </details>;
}
