'use client';
import {useState} from 'react';
import {type Domain} from '../lib/vault/cloud-sync';
import {type DomainReview} from '../lib/vault/domain-lifecycle';
const names={finance:'Goals and Wealth',habits:'Habits',health:'Health',settings:'Today preferences'};
export function DomainCloudControls({busy,review,prepare,confirm,cancel}:{busy:boolean;review:DomainReview|null;prepare:(kind:DomainReview['kind'],domain:Domain)=>Promise<void>;confirm:()=>Promise<void>;cancel:()=>void}){
 const [domain,setDomain]=useState<Domain>('health'),[saved,setSaved]=useState(false),[downloaded,setDownloaded]=useState(false),[phrase,setPhrase]=useState('');
 function start(kind:DomainReview['kind']){setSaved(false);setDownloaded(false);setPhrase('');void prepare(kind,domain);}
 function download(){if(!review||!saved)return;const url=URL.createObjectURL(new Blob([review.file],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='zigoals-domain-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true);}
 return <details><summary>Cloud copies by section</summary><p>Turning Health sync off keeps its encrypted cloud copy. Delete a section here to remove its active cloud records while retaining this browser’s records. Old devices must explicitly review before restoring a deleted section. Downloaded copies and infrastructure backups are separate.</p><label>Cloud section<select value={domain} disabled={busy||!!review} onChange={e=>setDomain(e.target.value as Domain)}>{Object.entries(names).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 {!review&&<div className="actions"><button disabled={busy} onClick={()=>start('delete')}>Review section deletion</button><button disabled={busy} onClick={()=>start('restore')}>Review restoring local section</button><button disabled={busy} onClick={()=>start('keep')}>Keep deleted section local only</button></div>}
 {review&&<div className="notice"><p>{review.kind==='delete'?`Delete the ${names[review.domain]} cloud copy. Other sections and local records stay.`:review.kind==='keep'?`Keep ${names[review.domain]} on this browser while other sections sync.`:`Restore this browser’s ${names[review.domain]} records as a new cloud copy. This is an explicit reversal of the earlier deletion.`}</p><p>The encrypted recovery file includes separate local and cloud copies captured for this review.</p><label>Section recovery secret<input readOnly value={review.recovery} autoComplete="off" spellCheck={false}/></label><label><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>I saved this section recovery secret separately.</label><button disabled={!saved||busy} onClick={download}>Download section recovery copy</button><label>Section confirmation<input value={phrase} onChange={e=>setPhrase(e.target.value)} autoComplete="off" placeholder={review.kind==='delete'?'DELETE SECTION':review.kind==='keep'?'KEEP LOCAL':'RESTORE SECTION'}/></label><button disabled={busy||!downloaded||phrase!==(review.kind==='delete'?'DELETE SECTION':review.kind==='keep'?'KEEP LOCAL':'RESTORE SECTION')} onClick={()=>void confirm()}>Confirm {review.kind==='delete'?'section deletion':review.kind==='keep'?'local-only section':'section restore'}</button><button disabled={busy} onClick={cancel}>Cancel section review</button></div>}
 </details>;
}
