'use client';
import {useState} from 'react';
import {directoryEntries,directoryResources,directoryCategories,directoryReviewedAt,filterDirectory} from '@zigoals/ecosystem-registry/providers';
import {PinToToday} from './pin-to-today';
import './ecosystem-directory.css';
export function EcosystemDirectory(){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All');const visible=filterDirectory(directoryEntries,query,category);
 function clear(){setQuery('');setCategory('All');}
 return <section className="ecosystem-directory" aria-labelledby="ecosystem-directory-title">
  <div className="ecosystem-intro"><p className="eyebrow">The Goal Layer for ZIGChain</p><h1 id="ecosystem-directory-title">Explore the ZIGChain ecosystem.</h1><p>Discover projects, understand their role, and follow official sources. Your plan stays yours.</p><div className="ecosystem-review"><span>{directoryEntries.length} research records</span><span>Sources reviewed <time dateTime={directoryReviewedAt}>{directoryReviewedAt}</time></span><span>No external execution in ZIGoals</span></div></div>
  <p className="ecosystem-context">An ecosystem listing is not a ZIGoals partnership, endorsement or security audit. Descriptions summarize project or network sources. External sites set their own network, access rules and terms.</p>
  <div className="ecosystem-controls"><label>Search projects<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, role or topic"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{directoryCategories.map(c=><option key={c}>{c}</option>)}</select></label><button type="button" className="quiet" onClick={clear} disabled={!query&&category==='All'}>Clear filters</button></div>
  <p className="ecosystem-result" role="status">{visible.length} of {directoryEntries.length} projects{category!=='All'?` · ${category}`:''}</p>
  {!visible.length?<div className="panel ecosystem-no-results"><h2>No projects match these filters.</h2><p>Try another name, topic or category.</p></div>:<div className="ecosystem-projects">{visible.map(entry=>{const p=entry.provider;return <article className="ecosystem-project" key={entry.id} id={`project-${entry.id}`}>
   <header><span className="ecosystem-initials" aria-label={`${entry.name} initials; official logo unavailable`} title={entry.logo.reason}>{entry.name.split(/\s+/).map(w=>w[0]).slice(0,2).join('')}</span><div><p className="eyebrow">{entry.category}</p><h2>{entry.name}</h2></div><PinToToday label={entry.name} choices={[{kind:'ecosystem',metric:'directory',entity:entry.id,label:`${entry.name} research shortcut`}]}/></header>
   <p className="ecosystem-description">{entry.description}</p><div className="ecosystem-labels"><span>{entry.inclusion}</span><span>{p.phase==='READ_ONLY'?'Read-only links':'Research only'}</span></div>
   <div className="ecosystem-project-actions">{entry.actions.map(action=><a key={action.kind} href={action.url} target="_blank" rel="noopener noreferrer">{action.kind==='Website'?'Visit website':action.kind==='App'?'Open app':'Read docs'} ↗</a>)}{!entry.actions.length&&<span>Website unavailable in this review</span>}</div>
   <details className="ecosystem-evidence"><summary>Evidence &amp; access</summary><p><a href={entry.descriptionSource} target="_blank" rel="noopener noreferrer">Description source ↗</a> · Reviewed {entry.reviewedAt}</p><p><strong>Destination:</strong> {entry.linkStatus}. Link review does not verify a live product or financial capability.</p><h3>ZIGoals capability</h3><p>{p.notes}</p><h3>Eligibility and access</h3><p>{p.eligibility.note}</p><h3>Networks in the existing record</h3><ul>{p.networks.map((n,i)=><li key={i}><strong>{n.chainId}</strong> · {n.status.toLowerCase().replaceAll('_',' ')}<br/>{n.note}</li>)}</ul><h3>Unresolved risks</h3><ul>{p.risks.map(r=><li key={r}>{r}</li>)}</ul><p>Capability evidence last reviewed {p.lastVerified}. Historical audit references do not establish the safety of current deployed code.</p><h3>Sources and attribution</h3><ul><li><a href={entry.inclusionSource} target="_blank" rel="noopener noreferrer">Inclusion evidence ↗</a></li>{p.sources.map((s,i)=><li key={`${s.url}:${i}`}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} ↗</a><small>{s.supports}</small></li>)}</ul><p className="fine">Logo: {entry.logo.reason}</p></details>
  </article>;})}</div>}
  <details className="ecosystem-coverage"><summary>About this directory’s coverage</summary><p>The reviewed set is the existing 18-provider registry, the official ZIGChain homepage and network documentation on {directoryReviewedAt}. It is a dated research snapshot, not an exhaustive or continually monitored list.</p><p>Additional official resources outside the existing provider registry:</p><ul>{directoryResources.map(r=><li key={r.name}><a href={r.url} target="_blank" rel="noopener noreferrer">Visit {r.name} ↗</a> · {r.description} <a href={r.source} target="_blank" rel="noopener noreferrer">Source ↗</a></li>)}</ul><p>The homepage’s unnamed social-only RWA lending listing could not be resolved during this review and was not merged into a provider by assumption.</p><p>Project logos have not been licensed and sanitized for local use, so every card uses a labeled initials fallback. No third-party images load on this page.</p><a href="https://zigchain.com/" target="_blank" rel="noopener noreferrer">Review the official ecosystem source ↗</a></details>
 </section>;
}
