'use client';
import {useEffect,useId,useState} from 'react';
import type {Domain} from '../lib/vault/cloud-sync';
import type {AttachPlan} from '../lib/vault/local-attach';
const names:Record<Domain,string>={finance:'Goals and Wealth',habits:'Habits',health:'Health',settings:'Today preferences'};
type Props={busy:boolean;health:boolean;preview:{plan:AttachPlan}|null;prepare:(domains:Domain[])=>Promise<void>;confirm:()=>Promise<void>;cancel:()=>void};
export function LocalAccountAttach({busy,health,preview,prepare,confirm,cancel}:Props){
 // Session M (owner decision M2): the copy happens in place, with no file. The originals stay on this device, so nothing
 // needs saving first; the explicit approval below is still required, and nothing is approved on the person's behalf.
 const [selected,setSelected]=useState<Domain[]>([]),[approved,setApproved]=useState(false),id=useId();
 useEffect(()=>{setApproved(false);},[preview]);
 return <section className="panel" aria-label="Copy local records to account"><p className="eyebrow">YOUR EXISTING LOCAL RECORDS</p><h2>Choose what joins your account.</h2><p>You can keep using this account separately, or copy selected records from this browser’s local workspace. Nothing is copied by signing in. Showcase and transaction journals are excluded. Populated account sections cannot be replaced here.</p>
 {!preview?<><fieldset disabled={busy}><legend>Sections to copy</legend>{(Object.keys(names) as Domain[]).map(domain=><label className="checkbox" key={domain} htmlFor={id+domain}><input id={id+domain} type="checkbox" checked={selected.includes(domain)} disabled={domain==='health'&&!health} aria-describedby={domain==='health'?id+'health-note':undefined} onChange={e=>setSelected(v=>e.target.checked?[...v,domain]:v.filter(d=>d!==domain))}/>{names[domain]}</label>)}</fieldset><p id={id+'health-note'}>Health requires its separate sync permission above. Keep referenced Goals or assets together with their Today widgets where needed.</p><button className="secondary" disabled={busy||!selected.length||selected.includes('health')&&!health} onClick={()=>void prepare(selected)}>Review selected local records</button></>:<><p>No records copied yet. Original local records will remain available separately.</p><ul>{preview.plan.inventory.map(item=><li key={item.domain}><strong>{names[item.domain]}</strong>: {Object.entries(item.collections).map(([name,count])=>`${name.split('.').map(part=>part.replace(/([a-z])([A-Z])/g,'$1 $2')).join(' · ')}: ${count}`).join(' · ')||'Saved preferences'}</li>)}</ul><p>The copy happens here, in this browser: no file to save. These records join your account and sync like the rest of it; the originals stay on this device, unchanged.</p><label className="checkbox" htmlFor={id+'approve'}><input id={id+'approve'} type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Copy these records into this account. The originals stay on this device.</label><button className="primary" disabled={busy||!approved} onClick={()=>void confirm()}>Copy selected records and sync</button><button className="secondary" disabled={busy} onClick={cancel}>Keep records local</button></>}
 </section>;
}
