'use client';
import {useEffect,useState} from 'react';
import type {Domain} from '../lib/vault/cloud-sync';
import type {AttachPlan} from '../lib/vault/local-attach';
const names:Record<Domain,string>={finance:'Goals and Wealth',habits:'Habits',health:'Health',settings:'Today preferences'};
type Props={busy:boolean;health:boolean;preview:{plan:AttachPlan;file:string;recovery:string}|null;prepare:(domains:Domain[])=>Promise<void>;confirm:()=>Promise<void>;cancel:()=>void};
export function LocalAccountAttach({busy,health,preview,prepare,confirm,cancel}:Props){
 const [selected,setSelected]=useState<Domain[]>([]),[saved,setSaved]=useState(false),[downloaded,setDownloaded]=useState(false),[approved,setApproved]=useState(false);
 useEffect(()=>{setSaved(false);setDownloaded(false);setApproved(false);},[preview]);
 function download(){if(!preview||!saved)return;const url=URL.createObjectURL(new Blob([preview.file],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='zigoals-before-local-copy.encrypted.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true);}
 return <section className="panel" aria-label="Copy local records to account"><p className="eyebrow">YOUR EXISTING LOCAL RECORDS</p><h2>Choose what joins your account.</h2><p>You can keep using this account separately, or copy selected records from this browser’s local workspace. Nothing is copied by signing in. Showcase and transaction journals are excluded. Populated account sections cannot be replaced here.</p>
 {!preview?<><fieldset disabled={busy}><legend>Sections to copy</legend>{(Object.keys(names) as Domain[]).map(domain=><label className="checkbox" key={domain}><input type="checkbox" checked={selected.includes(domain)} disabled={domain==='health'&&!health} onChange={e=>setSelected(v=>e.target.checked?[...v,domain]:v.filter(d=>d!==domain))}/>{names[domain]}</label>)}</fieldset><p>Health requires its separate sync permission above. Keep referenced Goals or assets together with their Today widgets where needed.</p><button className="secondary" disabled={busy||!selected.length||selected.includes('health')&&!health} onClick={()=>void prepare(selected)}>Review selected local records</button></>:<><p>No records copied yet. Original local records will remain available separately.</p><ul>{preview.plan.inventory.map(item=><li key={item.domain}><strong>{names[item.domain]}</strong>: {Object.entries(item.collections).map(([name,count])=>`${name.split('.').map(part=>part.replace(/([a-z])([A-Z])/g,'$1 $2')).join(' · ')}: ${count}`).join(' · ')||'Saved preferences'}</li>)}</ul><label>Local copy backup secret<input readOnly value={preview.recovery} autoComplete="off" spellCheck={false}/></label><p>This secret unlocks the protected pre-copy backup; it is separate from your account vault secret. Save it privately.</p><label className="checkbox"><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>I saved this local-copy backup secret separately.</label><button className="secondary" disabled={!saved||busy} onClick={download}>Download protected local copy</button><label className="checkbox"><input type="checkbox" checked={approved} disabled={!downloaded} onChange={e=>setApproved(e.target.checked)}/>I saved the backup file and want these selected records copied into this account.</label><button className="primary" disabled={busy||!saved||!downloaded||!approved} onClick={()=>void confirm()}>Copy selected records and sync</button><button className="secondary" disabled={busy} onClick={cancel}>Keep records local</button></>}
 </section>;
}
