"use client";
import Link from 'next/link';
import {useRef,useState} from 'react';
import {AppIcon} from './app-icon';
import {useUnifiedGoals} from './use-unified-goals';
function ContributionChoices({close}:{close:()=>void}){const collection=useUnifiedGoals(),goals=collection.goals.filter(g=>g.status==='active'&&g.type!=='Project Goal');return <nav aria-label="Choose a Goal to contribute to">{!collection.loaded?<p>Loading your Goals…</p>:!goals.length?<><p>Create a financial Goal to start recording contributions.</p><Link href="/app/goals/new" onClick={close}>Create a Goal →</Link></>:goals.map(g=><Link key={g.key} href={g.key.startsWith('private:')?`${g.href}?contribute=1#funding-wealth`:`${g.href}#local-simulation`} onClick={close}><span className="icon-medallion"><AppIcon name="goals" luminous/></span><span><strong>{g.name}</strong><small>{g.type} · {g.fundingHealth.replaceAll('_',' ')}</small></span><span aria-hidden="true">↗</span></Link>)}</nav>;}
export function QuickAdd(){
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null),[contribution,setContribution]=useState(false);
 const actions=[{name:'Goal',copy:'Give your next chapter a target.',href:'/app/goals/new',icon:'goals'},{name:'Asset',copy:'Add something to your wealth picture.',href:'/app/wealth?add=asset',icon:'wallet'},{name:'Contribution',copy:'Choose a Goal and record your next step.',href:'/app/goals?add=contribution',icon:'activity'},{name:'Habit',copy:'Build a rhythm that lasts.',href:'/app/habits?add=habit',icon:'habits'},{name:'Health entry',copy:'Log a meal, movement or weight.',href:'/app/health?add=entry',icon:'health'}];
 return <><button ref={trigger} className="secondary quick-add-trigger" onClick={()=>{setContribution(false);dialog.current?.showModal();}}>+ Quick add</button><dialog ref={dialog} className="quick-add-dialog" aria-labelledby="quick-add-title" onClose={()=>trigger.current?.focus()} onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}><div><header className="section-heading"><div><p className="eyebrow">A SMALL STEP TODAY</p><h2 id="quick-add-title">{contribution?'Choose your Goal':'What would you like to add?'}</h2></div><button autoFocus className="quiet" aria-label="Close Quick add" onClick={()=>dialog.current?.close()}>×</button></header>{contribution?<><button className="quiet" onClick={()=>setContribution(false)}>← All actions</button><ContributionChoices close={()=>dialog.current?.close()}/></>:<nav aria-label="Quick add actions">{actions.map(a=>{const content=<><span className="icon-medallion"><AppIcon name={a.icon} luminous/></span><span><strong>{a.name}</strong><small>{a.copy}</small></span><span aria-hidden="true">↗</span></>;return a.name==='Contribution'?<button className="quick-action" key={a.name} onClick={()=>setContribution(true)}>{content}</button>:<Link key={a.name} href={a.href} onClick={()=>dialog.current?.close()}>{content}</Link>;})}</nav>}</div></dialog></>;
}
