import {test,expect} from 'vitest';
import {createRequire} from 'node:module';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {privateAccountRequest} from '../../apps/web/lib/server/private-account';
import {createPrivateMiniflare,fixtureToken} from './private-runtime.mjs';
import {armSyncCompletion} from './sync-completion.mjs';
const require=createRequire(new URL('../../apps/web/package.json',import.meta.url)),{chromium}=require('@playwright/test');
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const identity=header=>JSON.parse(Buffer.from(header.slice(7).split('.')[1],'base64url').toString()).sub;
test.runIf(process.env.RUN10_BROWSER==='1')('late encrypted account A response cannot enter the actual signed-in B browser workspace',async()=>{
 const origin=process.env.RUN11_REVIEW_ORIGIN??'http://127.0.0.1:3112',mf=await createPrivateMiniflare({origin,persist:await mkdtemp(join(tmpdir(),'run11-switch-')),outboundService:async request=>Response.json({id:identity(request.headers.get('authorization'))})});const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext(),page=await context.newPage();let armed=false,entered,release,delivered,workerRequests=0;const held=new Promise(r=>{entered=r;}),resume=new Promise(r=>{release=r;}),delivery=new Promise(r=>{delivered=r;});
 try{
  await context.route('**/api/private-account*',async route=>{let wasHeld=false;const r=route.request(),headers=await r.allHeaders(),req=new Request(r.url(),{method:r.method(),headers,...(r.postData()?{body:r.postData()}:{})});const result=await privateAccountRequest(req,{authOrigin:'https://fixture.supabase.co',publicKey:'public-fixture',syncOrigin:'https://fixture.workers.dev'},async(url,init)=>{const u=new URL(url);if(u.hostname==='fixture.workers.dev'){workerRequests++;const response=await mf.dispatchFetch(url,init);if(armed&&u.pathname==='/v1/vault'&&(!init?.method||init.method==='GET')){armed=false;wasHeld=true;entered();await resume;}return response;}if(u.pathname.endsWith('/verify')){const id=JSON.parse(init.body).email.startsWith('a@')?A:B;return Response.json({access_token:fixtureToken('browser-'+id,id),expires_in:3600,user:{id}});}if(u.pathname.endsWith('/user'))return Response.json({id:identity(new Headers(init.headers).get('authorization'))});return Response.json({});});await route.fulfill({status:result.status,headers:{...Object.fromEntries(result.headers),...(result.headers.getSetCookie().length?{'set-cookie':result.headers.getSetCookie().join('\n')}:{})},body:await result.text()});if(wasHeld)delivered();});
  const synced=async()=>{await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Sync now'&&!b.disabled));await page.getByRole('region',{name:'Encrypted account sync',exact:true}).getByText(/Account records synced and acknowledged/).waitFor();};
  const enroll=async email=>{await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByRole('button',{name:'Send email code',exact:true}).click();await page.getByLabel('Email code',{exact:true}).fill('123456');await page.getByRole('button',{name:'Verify email code',exact:true}).click();await page.getByRole('button',{name:'Create encrypted account vault',exact:true}).waitFor();await page.getByLabel('Sync my Health records with this account.',{exact:false}).check();await page.getByRole('button',{name:'Create encrypted account vault',exact:true}).click();const recovery=await page.getByLabel('New vault recovery secret',{exact:true}).inputValue();await page.getByLabel('I saved this vault recovery secret separately.').check();const created=await armSyncCompletion(page);await page.getByRole('button',{name:'Confirm and create vault',exact:true}).click();await created();return recovery;};
  await page.goto(origin+'/app/settings');await enroll('a@example.invalid');await page.getByRole('link',{name:'Habits',exact:true}).first().click();await page.getByRole('button',{name:'+ New habit',exact:true}).click();await page.getByLabel('Start from template').selectOption('read');await page.getByLabel('Habit title',{exact:true}).fill('Private A late-response marker');await page.getByRole('button',{name:'Create habit',exact:true}).click();await page.getByRole('article',{name:'Private A late-response marker',exact:true}).waitFor();await page.getByRole('link',{name:'Settings',exact:true}).first().click();const fresh=await armSyncCompletion(page);await page.getByRole('button',{name:'Sync now',exact:true}).click();await fresh();
  armed=true;await page.getByRole('button',{name:'Sync now',exact:true}).click();await held;await page.getByRole('button',{name:'Sign out',exact:true}).click();const recoveryB=await enroll('b@example.invalid');await page.getByRole('link',{name:'Habits',exact:true}).first().click();await page.getByRole('button',{name:'+ New habit',exact:true}).click();await page.getByLabel('Start from template').selectOption('read');await page.getByLabel('Habit title',{exact:true}).fill('Private B preserved marker');await page.getByRole('button',{name:'Create habit',exact:true}).click();await page.getByRole('article',{name:'Private B preserved marker',exact:true}).waitFor();release();await delivery;await page.getByRole('link',{name:'Settings',exact:true}).first().click();const freshB=await armSyncCompletion(page);await page.getByRole('button',{name:'Sync now',exact:true}).click();await freshB();expect(await page.getByRole('region',{name:'Encrypted account sync',exact:true}).getByRole('alert').count()).toBe(0);await page.getByRole('link',{name:'Habits',exact:true}).first().click();await page.getByRole('article',{name:'Private B preserved marker',exact:true}).waitFor();await page.getByRole('button',{name:'+ New habit',exact:true}).waitFor();expect(await page.getByRole('article',{name:'Private A late-response marker',exact:true}).count()).toBe(0);expect(await page.locator('main').innerText()).not.toContain('Private A late-response marker');await page.getByRole('link',{name:'Settings',exact:true}).first().click();await synced();
  const privateBytes=async()=>page.evaluate(async()=>{const result={local:Object.fromEntries(Object.keys(localStorage).sort().map(k=>[k,localStorage.getItem(k)])),databases:{}};for(const name of ['zigoals-private-vault-v1','zigoals-account-sync-v1']){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(name);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const names=[...db.objectStoreNames],tx=db.transaction(names,'readonly');result.databases[name]=await Promise.all(names.map(async store=>{const s=tx.objectStore(store),read=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return {store,keys:await read(s.getAllKeys()),values:await read(s.getAll())};}));db.close();}return result;});
  const beforeShowcase=await privateBytes(),sentBefore=workerRequests;await page.getByRole('button',{name:'Load Showcase Demo',exact:true}).click();await page.getByRole('complementary',{name:'Showcase data'}).waitFor();await page.getByRole('link',{name:'Health',exact:true}).first().click();await page.getByRole('button',{name:'Add 250 mL',exact:true}).click();await page.getByRole('link',{name:'Settings',exact:true}).first().click();await page.getByRole('button',{name:'Reset Showcase Demo',exact:true}).click();await page.getByRole('complementary',{name:'Showcase data'}).waitFor();expect(await privateBytes()).toEqual(beforeShowcase);expect(workerRequests).toBe(sentBefore);expect(await page.getByRole('button',{name:'Sync now',exact:true}).count()).toBe(0);await page.getByRole('link',{name:'Settings',exact:true}).first().click();await page.getByRole('button',{name:'Return to my data',exact:true}).click();await page.getByLabel('Vault recovery secret',{exact:true}).waitFor();expect(await privateBytes()).toEqual(beforeShowcase);await page.getByLabel('Vault recovery secret',{exact:true}).fill(recoveryB);const unlocked=await armSyncCompletion(page);await page.getByRole('button',{name:'Unlock account vault',exact:true}).click();await unlocked();await page.getByRole('link',{name:'Habits',exact:true}).first().click();await page.getByRole('article',{name:'Private B preserved marker',exact:true}).waitFor();expect(await page.getByRole('article',{name:'Private A late-response marker',exact:true}).count()).toBe(0);await page.getByRole('link',{name:'Settings',exact:true}).first().click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('link',{name:'Habits',exact:true}).first().click();expect(await page.getByRole('article',{name:'Private A late-response marker',exact:true}).count()).toBe(0);
 }finally{release();await browser.close();await mf.dispose();}
},60000);
