import {test,expect} from 'vitest';
import {DurableMarketAccount,type AtomicMarketStorage} from './durable-market-account';
class Storage implements AtomicMarketStorage{
 rows=new Map<string,unknown>();fail=false;private gate=Promise.resolve();
 async get<T>(key:string){return structuredClone(this.rows.get(key)) as T|undefined;}async put(key:string,value:unknown){if(this.fail)throw Error('injected storage failure');this.rows.set(key,structuredClone(value));}
 async transaction<T>(fn:(tx:AtomicMarketStorage)=>Promise<T>):Promise<T>{let release!:()=>void;const previous=this.gate;this.gate=new Promise(r=>{release=r;});await previous;const tx=new Storage();tx.rows=structuredClone(this.rows);tx.fail=this.fail;try{const result=await fn(tx);this.rows=tx.rows;return result;}finally{release();}}
}
const policy={providerMinuteLimit:10,providerMonthlyLimit:100,operating:{minute:8,monthly:80},monitoringReserve:{minute:1,monthly:10},monitoringMaximum:{minute:1,monthly:10},optionalCeiling:{minute:5,monthly:50},concurrent:1,queueLimit:4,reservationMs:10000,ownershipMs:2000};
const work=(id:string)=>({operation:'quote',pair:{marketRef:{provider:'coingecko',kind:'coin',id},currency:'USD'}});
const config={policy,month:{id:'synthetic',start:0,end:100000},quoteCost:3,leaseMs:1000,maxAttempts:16,maxWorks:8};
function setup(overrides={}){const storage=new Storage();let now=100;const account=new DurableMarketAccount(storage,()=>now,JSON.stringify({...config,...overrides}));return {storage,account,advance:(n:number)=>{now=n;}};}
async function attempt(account:DurableMarketAccount,ids=['bitcoin']){const associations=[];for(const id of ids){const acquired=await account.apply({action:'acquire',work:work(id)});associations.push({work:work(id),lease:acquired.lease});}const response=await account.apply({action:'enqueue',priority:'interactive',kind:'request',associations});return {associations,...response,id:response.id};}
test('missing mandatory policy and private fields fail closed without writes',async()=>{const s=new Storage();expect(await new DurableMarketAccount(s,()=>100,undefined).apply({action:'inspect'})).toMatchObject({ok:false,reason:'POLICY_UNAVAILABLE'});const {account}=setup();expect(await account.apply({action:'acquire',work:{...work('bitcoin'),wallet:'private'}})).toMatchObject({reason:'MALFORMED'});expect(s.rows.size).toBe(0);});
test('a lease cannot enqueue twice; expiration prevents dispatch and late publication',async()=>{const {account,advance}=setup();const a=await attempt(account);expect(await account.apply({action:'enqueue',priority:'interactive',kind:'request',associations:[...a.associations,...a.associations]})).toMatchObject({reason:'MALFORMED'});expect(await account.apply({action:'enqueue',priority:'interactive',kind:'request',associations:a.associations})).toMatchObject({reason:'DUPLICATE_OPERATION'});await account.apply({action:'reserve',id:a.id});await account.apply({action:'own',id:a.id});advance(1100);expect(await account.apply({action:'dispatch',id:a.id})).toMatchObject({reason:'FENCED'});expect(await account.apply({action:'cancel',id:a.id})).toMatchObject({ok:true});});
test('many public keys charge one configured attempt; holds and dispatched failures remain distinct',async()=>{const {account}=setup();const a=await attempt(account,['bitcoin','ethereum','solana']);await account.apply({action:'reserve',id:a.id});expect(await account.apply({action:'inspect'})).toMatchObject({chargedCredits:0,attempts:1});await account.apply({action:'own',id:a.id});await account.apply({action:'dispatch',id:a.id});await account.apply({action:'settle',id:a.id,outcome:'failure'});expect(await account.apply({action:'inspect'})).toMatchObject({chargedCredits:3,attempts:1});expect(await account.apply({action:'cancel',id:a.id})).toMatchObject({ok:false});expect(await account.apply({action:'settle',id:a.id,outcome:'failure'})).toMatchObject({ok:false});});
test('clock regression, fixed period expiry and bounded retention never recreate allowance',async()=>{const {account,advance}=setup({maxAttempts:1,maxWorks:2});const a=await attempt(account);expect(await account.apply({action:'cancel',id:a.id})).toMatchObject({ok:true});expect(await attempt(account,['ethereum'])).toMatchObject({reason:'RETENTION_CAPACITY'});advance(99);expect(await account.apply({action:'inspect'})).toMatchObject({reason:'CLOCK_OR_PERIOD'});const b=setup();const op=await attempt(b.account);b.advance(100000);expect(await b.account.apply({action:'reserve',id:op.id})).toMatchObject({reason:'CLOCK_OR_PERIOD'});});
test('shared key capacity and storage failure deny new ownership instead of losing accounting',async()=>{const {account,storage}=setup({maxWorks:1});await account.apply({action:'acquire',work:work('bitcoin')});expect(await account.apply({action:'acquire',work:work('ethereum')})).toMatchObject({reason:'CACHE_CAPACITY'});const before=structuredClone(storage.rows);storage.fail=true;expect(await account.apply({action:'acquire',work:work('solana')})).toMatchObject({reason:'STORAGE_UNAVAILABLE'});expect(storage.rows).toEqual(before);});
test('an expired owner cannot publish after a successor',async()=>{
 const {account,advance}=setup();const a=await attempt(account);await account.apply({action:'reserve',id:a.id});await account.apply({action:'own',id:a.id});await account.apply({action:'dispatch',id:a.id});
 const quote={base:{network:'coingecko-coin',denom:'bitcoin',decimals:0},marketRef:work('bitcoin').pair.marketRef,currency:'USD',price:'123',priceDecimals:2,source:'CoinGecko',providerAssetId:'bitcoin',verification:'VERIFIED',fetchedAt:new Date(100).toISOString()};
 advance(1100);expect(await account.apply({action:'acquire',work:work('bitcoin')})).toMatchObject({status:'OWNER'});expect(await account.apply({action:'publish',id:a.id,work:work('bitcoin'),quote})).toMatchObject({ok:false,reason:'FENCED'});
});
test('refresh cannot overwrite retained evidence with an older provider observation',async()=>{
 const {account,advance}=setup({month:{id:'long-fixture',start:0,end:10000000}});const quote={base:{network:'coingecko-coin',denom:'bitcoin',decimals:0},marketRef:work('bitcoin').pair.marketRef,currency:'USD',price:'123',priceDecimals:2,source:'CoinGecko',providerAssetId:'bitcoin',verification:'VERIFIED',fetchedAt:new Date(100).toISOString()};
 async function dispatch(){const a=await attempt(account);for(const action of ['reserve','own','dispatch'])expect(await account.apply({action,id:a.id})).toMatchObject({ok:true});return a;}
 const first=await dispatch();expect(await account.apply({action:'publish',id:first.id,work:work('bitcoin'),quote})).toMatchObject({ok:true});await account.apply({action:'settle',id:first.id,outcome:'success'});
 advance(900101);const second=await dispatch();expect(await account.apply({action:'publish',id:second.id,work:work('bitcoin'),quote:{...quote,fetchedAt:new Date(50).toISOString()}})).toMatchObject({reason:'STALE_EVIDENCE'});expect(await account.apply({action:'acquire',work:work('bitcoin')})).toMatchObject({status:'WAITING',degraded:true,quote});
});
