import {z} from 'zod';
import {historyRequestSchema} from '../market-history';
import {marketRequestSchema} from '../market-assets';
import type {BudgetDecision,BudgetState,ReservationRequest} from './market-budget-policy';
import type {ProviderFailureCategory} from './provider-failure';
/** No account selector, wallet, user, portfolio or credential belongs in a work key.
 * Future implementation selects its account from server configuration.
 */
export const publicMarketWorkSchema=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('quote'),pair:marketRequestSchema}).strict(),
 z.object({operation:z.literal('insights'),pair:marketRequestSchema}).strict(),
 z.object({operation:z.literal('history'),pair:marketRequestSchema,range:historyRequestSchema.shape.range}).strict(),
 z.object({operation:z.literal('catalog'),provider:z.literal('coingecko'),kind:z.enum(['coin','rwa'])}).strict(),
]);
export type PublicMarketWork=z.infer<typeof publicMarketWorkSchema>;
export function publicMarketWorkKey(raw:PublicMarketWork):string {
 const work=publicMarketWorkSchema.parse(raw);
 return work.operation==='catalog'?JSON.stringify([work.operation,work.provider,work.kind]):JSON.stringify([work.operation,work.pair.marketRef.provider,work.pair.marketRef.kind,work.pair.marketRef.id,work.pair.currency,...(work.pair.marketRef.kind==='rwa'?[work.pair.marketRef.assetType]:[]),...(work.operation==='history'?[work.range]:[])]);
}
export type WorkLease={token:string;fence:number;expiresAt:number};
export type BreakerState={state:'closed'|'open'|'half-open';retryAt?:number};
/** Specification only: no implementation, persistence, binding, network or runtime use.
 * IDs/tokens below must be generated by the coordinator, not accepted from end users.
 * Transitions must serialize per account; markDispatched must persist before I/O.
 * Lease release/publication requires matching fence; expiry is not a budget refund.
 * Sanitized outcomes only. Replay/tombstone retention requires a separate design.
 */
export interface MarketCoordinator {
 reserve(work:PublicMarketWork,attempt:ReservationRequest):Promise<BudgetDecision>;
 markDispatched(reservationId:string):Promise<BudgetDecision>;
 settle(reservationId:string,outcome:'success'|'failure'):Promise<BudgetDecision>;
 cancelUndispatched(reservationId:string):Promise<BudgetDecision>;
 acquireWorkLease(work:PublicMarketWork):Promise<WorkLease|null>;
 releaseWorkLease(work:PublicMarketWork,lease:WorkLease):Promise<void>;
 breakerState(work:PublicMarketWork):Promise<BreakerState>;
 recordOutcome(work:PublicMarketWork,outcome:'VERIFIED'|ProviderFailureCategory):Promise<void>;
}
/** BudgetState contains opaque operations and numeric policy accounting only. */
export type CoordinatorAccounting=BudgetState;
