import {z} from 'zod';
import {historyRequestSchema} from '../market-history';
import {marketRequestSchema} from '../market-assets';
import type {BudgetDecision,BudgetState,ReservationRequest} from './market-budget-policy';
import {publishWork,type WorkLease,type WorkState,type PublicationDecision} from './market-work-fence';
export type {WorkLease} from './market-work-fence';
import type {ProviderFailureCategory} from './provider-failure';
/** No account selector, wallet, user, portfolio or credential belongs in a work key.
 * Future implementation selects its account from server configuration.
 */
export const publicMarketWorkSchema=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('quote'),pair:marketRequestSchema}).strict(),
 z.object({operation:z.literal('insights'),pair:marketRequestSchema}).strict(),
 z.object({operation:z.literal('history'),pair:marketRequestSchema,range:historyRequestSchema.shape.range}).strict(),
 z.object({operation:z.literal('catalog'),provider:z.literal('coingecko'),kind:z.enum(['coin','rwa'])}).strict(),
]);
export type PublicMarketWork=z.infer<typeof publicMarketWorkSchema>;
export function publicMarketWorkKey(raw:PublicMarketWork):string {
 const work=publicMarketWorkSchema.parse(raw);
 return work.operation==='catalog'?JSON.stringify([work.operation,work.provider,work.kind]):JSON.stringify([work.operation,work.pair.marketRef.provider,work.pair.marketRef.kind,work.pair.marketRef.id,work.pair.currency,...(work.pair.marketRef.kind==='rwa'?[work.pair.marketRef.assetType]:[]),...(work.operation==='history'?[work.range]:[])]);
}
export type ProviderAttempt={id:string;reservation:ReservationRequest;associations:readonly {work:PublicMarketWork;lease:WorkLease}[]};
/** One HTTP call = one reservation, regardless of work-key count. Endpoint credit cost
 * comes from configuration. Retain immutable associations through settlement/publication. */
export function createProviderAttempt(reservation:ReservationRequest,associations:ProviderAttempt['associations']):ProviderAttempt {
 if(!/^[A-Za-z0-9_-]{1,100}$/.test(reservation.id)||!Number.isSafeInteger(reservation.cost)||reservation.cost<=0||!associations.length)throw Error('Invalid provider attempt.');
 const keys=associations.map(a=>publicMarketWorkKey(a.work));
 if(new Set(keys).size!==keys.length)throw Error('Duplicate work association.');
 return {id:reservation.id,reservation:{...reservation},associations:associations.map(a=>({work:publicMarketWorkSchema.parse(a.work),lease:{...a.lease}}))};
}
/** The durable adapter supplies canonically validated per-work values. This reference
 * checks authorization/association/fence, never infers validation from an HTTP status. */
export function publishAttemptWork<T>(attempt:ProviderAttempt,budget:BudgetState,work:PublicMarketWork,state:WorkState<T>,validated:T,completedAt:number,now:number):PublicationDecision<T>{
 const charged=Object.hasOwn(budget.reservations,attempt.id)?budget.reservations[attempt.id]:undefined;
 const association=attempt.associations.find(a=>publicMarketWorkKey(a.work)===publicMarketWorkKey(work));
 if(!charged||!['DISPATCHED','SETTLED'].includes(charged.status)||charged.cost!==attempt.reservation.cost||charged.dispatchedAt!>completedAt||!association)return {ok:false,state,reason:'FENCED'};
 return publishWork(state,association.lease,validated,completedAt,now,true);
}
import type {BreakerState,BreakerScope} from './market-breaker';
/** Specification only: no implementation, persistence, binding, network or runtime use.
 * IDs/tokens below must be generated by the coordinator, not accepted from end users.
 * Transitions must serialize per account; markDispatched must persist before I/O.
 * Lease release/publication requires matching fence; expiry is not a budget refund.
 * Sanitized outcomes only. Replay/tombstone retention requires a separate design.
 */
export interface MarketCoordinator {
 enqueue(attempt:ProviderAttempt):Promise<BudgetDecision>;
 reserve(attempt:ProviderAttempt):Promise<BudgetDecision>;
 ownDispatch(attemptId:string):Promise<BudgetDecision>;
 markDispatched(reservationId:string):Promise<BudgetDecision>;
 settle(reservationId:string,outcome:'success'|'failure'):Promise<BudgetDecision>;
 cancelUndispatched(reservationId:string):Promise<BudgetDecision>;
 acquireWorkLease(work:PublicMarketWork):Promise<WorkLease|null>;
 releaseWorkLease(work:PublicMarketWork,lease:WorkLease):Promise<void>;
 /** Publication validates operation-specific evidence and atomically checks current lease,
  * attempt association, DISPATCHED/SETTLED state and exclusive deadline before committing.
  * Settlement does not publish, refund costs, or bypass fences. */
 publishResult(attemptId:string,work:PublicMarketWork,lease:WorkLease,result:unknown,completedAt:number):Promise<'PUBLISHED'|'FENCED'|'TIMEOUT'|'MALFORMED'>;
 breakerState(scope:BreakerScope):Promise<BreakerState>;
 recordOutcome(scope:BreakerScope,attemptId:string,outcome:'VERIFIED'|ProviderFailureCategory|'BLOCKED'):Promise<void>;
}
/** BudgetState contains opaque operations and numeric policy accounting only. */
export type CoordinatorAccounting=BudgetState;
