/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.local.jsonc --include-runtime=false` (hash: 78d719df7cb65fe5e90121228647f274)
interface __BaseEnv_Env {
	MARKETS: DurableObjectNamespace<import("./worker").MarketAccount>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "MarketAccount";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
