'use client';
import Link from 'next/link';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {OrbitSlogan} from '../orbit-slogan';
import {AppIcon} from '../app-icon';
import {usePrivateStore} from '../use-private-store';
import {usePlatform} from '../platform/use-platform';
import {useGoals} from '../goal-provider';
import {useHabits} from '../habits/use-habits';
import {useHealth} from '../health/use-health';
import {HabitsToday} from '../habits/habits-today';
import {HabitCompletion} from '../habits/habit-card';
import {useMarketQuotes} from '../platform/use-market-quotes';
import {useEvidenceNow} from '../platform/use-evidence-now';
import {useLocalToday} from '../use-local-today';
import {ProgressRing} from '../platform/financial-ui';
import {TodayIntelligence} from '../platform/today-intelligence';
import {wealthMarketRequests} from '../../lib/wealth';
import {unifiedGoalSummaries} from '../../lib/goal-summary';
import {dailyData,healthDay} from '../../lib/health-daily';
import {DASHBOARD_SETTINGS_KEY,dashboardSettingsSchema,emptyDashboardSettings,PRESETS,presetSettings,saveWidget,moveWidget,removeWidget,visibleDomains,WIDGET_CATALOG,type DashboardPreset,type DashboardWidget,type DashboardSettings,type WidgetKind} from '../../lib/dashboard-settings';
import {dashboardIntegrityWarning,stakingWidgetSource,widgetMetric,widgetMetricLabel,type DashboardSources,type WidgetMetric} from '../../lib/dashboard-metrics';
import './dashboard.css';
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,dialog=ref.current;dialog?.showModal();return()=>{dialog?.close();previous?.focus();};},[]);
 return <dialog ref={ref} className="dashboard-dialog" aria-label={title} onCancel={onClose}><header><h2>{title}</h2><button className="secondary" type="button" onClick={onClose} aria-label="Close customization">Close</button></header>{children}</dialog>;
}
function Metric({metric,identity}:{metric:WidgetMetric;identity:string}){return <><div className="dashboard-metric-value">{metric.percent!==undefined&&<ProgressRing percent={metric.percent} complete={metric.complete} size={88} identity={`widget-${identity}`} label={`${metric.title} progress`}/>}<strong>{metric.value}</strong></div><p className="fine">{metric.detail}</p>{metric.facts&&<dl className="dashboard-metric-facts">{metric.facts.map(f=><div key={f.label}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl>}{metric.warning&&<p className="notice">{metric.warning}</p>}<Link className="text-link" href={metric.href}>{metric.missing?'Review record':'Open details'} →</Link></>;}
function WidgetEditor({initial,sources,onSave,onClose}:{initial?:DashboardWidget;sources:DashboardSources;onSave:(w:DashboardWidget,revision?:number)=>Promise<void>;onClose:()=>void}){
 const [kind,setKind]=useState<WidgetKind>(initial?.kind??'health'),[metric,setMetric]=useState(initial?.metric??'kcal'),[entity,setEntity]=useState(initial?.entity??''),[title,setTitle]=useState(initial?.title??''),[size,setSize]=useState<DashboardWidget['size']>(initial?.size??'compact');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);const id=useRef(initial?.id??crypto.randomUUID());
 const entities=kind==='goal'?sources.goals.map(g=>({id:g.key,label:`${g.name} · ${g.source}`})):kind==='habit'?sources.habits.habits.map(h=>({id:h.id,label:h.title})):['asset','allocation','staking'].includes(kind)?sources.platform.positions.filter(p=>kind!=='staking'||stakingWidgetSource(p)).map(p=>({id:p.id,label:`${p.providerId} · ${p.asset} · ${p.network} · ${p.sourceType.toLowerCase().replaceAll('_',' ')}${p.archivedAt?' · archived':''}`})):[];
 const requiresEntity=['goal','habit','asset','staking','allocation'].includes(kind);
 const draft:DashboardWidget={id:id.current,kind,metric,...(requiresEntity?{entity}:{}),title,size,hidden:initial?.hidden??false,revision:initial?.revision??1};
 const preview=widgetMetric(draft,sources);
 async function save(){setBusy(true);setError('');try{await onSave(draft,initial?.revision);onClose();}catch(e){setError(e instanceof Error?e.message:'Could not save this widget.');}finally{setBusy(false);}}
 return <Modal title={initial?'Edit widget':'Add a widget'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();void save();}}><div className="form-grid"><label>Widget type<select value={kind} onChange={e=>{const next=e.target.value as WidgetKind;setKind(next);setMetric(WIDGET_CATALOG[next].metrics[0]);setEntity('');}}>{Object.entries(WIDGET_CATALOG).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label><label>Metric<select value={metric} onChange={e=>setMetric(e.target.value)}>{WIDGET_CATALOG[kind].metrics.map(m=><option key={m} value={m}>{widgetMetricLabel(m)}</option>)}</select></label>{requiresEntity&&<label className="span-two">Choose a {['asset','staking','allocation'].includes(kind)?'record':kind}<select required value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Choose a saved record</option>{entity&&!entities.some(e=>e.id===entity)&&<option value={entity}>Previously selected record · unavailable</option>}{entities.map(e=><option value={e.id} key={e.id}>{e.label}</option>)}</select>{!entities.length&&<small>No saved records yet. You can create one from its page first.</small>}</label>}<label>Title (optional)<input maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Size<select value={size} onChange={e=>setSize(e.target.value as DashboardWidget['size'])}><option value="compact">Compact</option><option value="wide">Wide</option></select></label></div><section className="dashboard-widget-preview" aria-label="Widget preview"><p className="eyebrow">PREVIEW · YOUR CURRENT RECORDS</p><h3>{preview.title}</h3><strong>{preview.value}</strong><p>{preview.detail}</p>{preview.facts&&<dl className="dashboard-metric-facts">{preview.facts.map(f=><div key={f.label}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl>}{preview.warning&&<p>{preview.warning}</p>}</section>{error&&<p role="alert">{error}</p>}<div className="dashboard-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy||requiresEntity&&!entity}>{busy?'Saving…':'Save widget'}</button></div></form></Modal>;
}
export function TodayDashboard(){
 const settings=usePrivateStore(DASHBOARD_SETTINGS_KEY,dashboardSettingsSchema,emptyDashboardSettings),platform=usePlatform(),legacy=useGoals(),habits=useHabits(),health=useHealth(),today=useLocalToday();
 const domains=visibleDomains(settings.data),financial=domains.includes('wealth')||domains.includes('goals');
 const market=useMarketQuotes(settings.loaded&&financial?wealthMarketRequests(platform.data):false),now=useEvidenceNow(platform.data,market.now);
 const goals=unifiedGoalSummaries(legacy.goals,legacy.metadata?.goals??{},platform.data,market.quotes,now,legacy.mode==='local'?'Local simulation':'Future Goal Manager').filter(g=>!g.key.startsWith('legacy:')||!platform.data.legacyGoalUi?.[`${legacy.chain}:${legacy.owner}:${g.id}`]?.archived);
 const sources:DashboardSources={platform:platform.data,goals,habits:habits.data,health:health.data,quotes:market.quotes,now,today,healthDate:healthDay(dailyData(health.data).preferences.timezone)};
 const [customize,setCustomize]=useState(false),[editor,setEditor]=useState<DashboardWidget|'new'|null>(null),[preset,setPreset]=useState<DashboardPreset|null>(null),[status,setStatus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const loaded=(domain:string)=>domain==='health'?health.loaded:domain==='habits'?habits.loaded:platform.loaded&&legacy.loaded;
 const domainError=(domain:string)=>domain==='health'?health.error:domain==='habits'?habits.error:platform.error;
 async function change(update:(s:DashboardSettings)=>DashboardSettings,message='Layout saved on this device.') {setBusy(true);setError('');try{await settings.update(update);setStatus(message);}catch(e){setError(e instanceof Error?e.message:'Could not save the layout.');throw e;}finally{setBusy(false);}}
 async function reorder(id:string,direction:-1|1,title:string){try{await change(s=>moveWidget(s,id,direction),`${title} moved ${direction===-1?'up':'down'}. Layout saved on this device.`);requestAnimationFrame(()=>document.getElementById(`dashboard-widget-${id}`)?.focus());}catch{}}
 const apply=(update:(s:DashboardSettings)=>DashboardSettings,message?:string)=>void change(update,message).catch(()=>{});
 const integrityWarning=platform.loaded&&!platform.error?dashboardIntegrityWarning(platform.data):undefined;
 const selectedSummary=domains.map(domain=>({goals:['goals','overview'],habits:['habits','overview'],health:['health','kcal'],wealth:['wealth','USD']}[domain]!));
 return <div className="today-page personalized-today" data-interests={settings.data.preset}>
 <section className="today-hero" aria-labelledby="dashboard-title"><div className="cosmic-glow ambient-light" aria-hidden="true"/><div className="today-hero-copy"><p className="eyebrow financial-orbit">YOUR FINANCIAL ORBIT</p><h1 id="dashboard-title" className="orbit-slogan"><OrbitSlogan/></h1><p>Choose what matters today.<br/>Make space for the life you’re building.</p><div className="hero-actions"><Link className="primary" href={financial?'/app/goals/new':'/app/health'}>{financial?'+ Create a goal':'Open Health'}</Link><a href="#how-it-works" className="secondary"><AppIcon name="play"/> See how it works</a></div><p className="hero-truth">Private daily tracking · watch-only wealth · no financial execution</p></div><div className="hero-pillars" aria-label="Your connected journey">{[['goals','Your goals','A destination with meaning.'],['habits','Your rhythm','Small steps, your pace.'],['health','Your wellbeing','Care for the everyday.']].map(([icon,title,detail])=><div key={icon}><span className="icon-medallion"><AppIcon name={icon!} size={30} luminous/></span><span><strong>{title}</strong><small>{detail}</small></span></div>)}</div></section>
 <section className="dashboard-summary panel" aria-label="Life and Wealth snapshot"><div className="section-heading"><div><p className="eyebrow">YOUR WHOLE LIFE, AT A GLANCE</p><h2>Today, in your orbit.</h2></div><button className="secondary" onClick={()=>setCustomize(x=>!x)} disabled={!settings.loaded||!!settings.error}>{customize?'Finish customizing':'Customize Today'}</button></div>{!settings.loaded?<p role="status">Loading your layout…</p>:<div className="dashboard-summary-grid">{selectedSummary.map(([kind,metric])=>{const domain=WIDGET_CATALOG[kind as WidgetKind].domain,value=widgetMetric({id:`summary-${kind}`,kind:kind as WidgetKind,metric:metric!,title:'',size:'compact',hidden:false,revision:1},sources);return <Link key={kind} href={value.href} className="dashboard-summary-item"><AppIcon name={domain==='wealth'?'wallet':domain} size={28} luminous/><span><small>{WIDGET_CATALOG[kind as WidgetKind].label}</small><strong>{!loaded(domain)?'Loading…':domainError(domain)?'Needs attention':value.value}</strong>{value.warning&&loaded(domain)&&!domainError(domain)&&<small className="dashboard-warning">{value.warning}</small>}</span></Link>;})}{!domains.length&&<p>Your layout is empty. Add a widget or choose a preset.</p>}</div>}</section>
 {[settings.error,platform.error,habits.error,health.error].filter(Boolean).map((message,i)=><p role="alert" className="notice" key={i}>{message}</p>)}
 {financial&&platform.error&&legacy.loaded&&!legacy.error&&goals.some(g=>g.key.startsWith('legacy:'))&&<section className="panel" aria-label="Available local simulation Goals"><h2>Your local simulation Goals are still available.</h2><p>Private tracked records need recovery. These separate local simulation records remain readable.</p><ul>{goals.filter(g=>g.key.startsWith('legacy:')).map(g=><li key={g.key} data-goal-key={g.key}><Link href={g.href}>{g.name}</Link></li>)}</ul></section>}
 {integrityWarning&&<p role="alert" className="notice">{integrityWarning} <Link href="/app/wealth">Review saved sources →</Link></p>}
 {settings.loaded&&!settings.error&&!settings.data.onboarded&&<section className="dashboard-welcome panel"><h2>Make Today yours.</h2><p>Start with your interests. Your records stay as they are, and no wallet or account is required.</p><div className="dashboard-preset-choices">{PRESETS.map(p=><button className="secondary" key={p.id} onClick={()=>setPreset(p.id)}><strong>{p.label}</strong><span>{p.description}</span></button>)}</div><button className="text-link" onClick={()=>apply(s=>({...s,onboarded:true}))}>Keep Balanced and continue</button><p className="fine">Saved locally. Explore account, backup and encrypted-sync options in <Link href="/app/settings">Settings</Link>.</p></section>}
 <section aria-label="Your Today widgets" className="dashboard-widget-area"><div className="section-heading"><h2>Your daily space</h2>{customize&&<div className="dashboard-actions"><button className="primary" disabled={busy||settings.data.widgets.length>=24} onClick={()=>setEditor('new')}>Add widget</button><button className="secondary" onClick={()=>setPreset(settings.data.preset)}>Choose preset</button></div>}</div><p role="status" className="dashboard-save-status">{status}</p>{error&&<p role="alert">{error}</p>}<div className="dashboard-widget-grid">{settings.loaded&&!settings.error&&settings.data.widgets.filter(w=>customize||!w.hidden).map(w=>{const metric=widgetMetric(w,sources),domain=WIDGET_CATALOG[w.kind].domain,index=settings.data.widgets.findIndex(x=>x.id===w.id),habit=w.kind==='habit'?habits.data.habits.find(h=>h.id===w.entity):undefined;return <article key={w.id} id={`dashboard-widget-${w.id}`} tabIndex={-1} className="dashboard-widget panel" data-size={w.size} data-hidden={w.hidden?'true':undefined} aria-label={metric.title}><div className="dashboard-widget-heading"><AppIcon name={domain==='wealth'?'wallet':domain} luminous/><h3>{metric.title}</h3>{w.hidden&&<span className="pill">Hidden</span>}</div>{!loaded(domain)?<p role="status">Loading records…</p>:domainError(domain)?<p role="alert">This data needs attention. Open Settings to recover it.</p>:w.kind==='habits'?<HabitsToday/>:<><Metric metric={metric} identity={w.id}/>{habit&&w.metric==='today'&&<HabitCompletion habit={habit} store={habits} compact/>}{w.kind==='goals'&&<ul className="dashboard-goal-links">{goals.filter(g=>g.status==='active').slice(0,3).map(g=><li key={g.key}><Link href={g.href}>{g.name}</Link></li>)}</ul>}</>}{customize&&<div className="dashboard-widget-controls"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditor(w)}>Edit</button><button type="button" className="secondary" disabled={busy} onClick={()=>apply(s=>saveWidget(s,{...w,hidden:!w.hidden},w.revision))}>{w.hidden?'Show':'Hide'}</button><button type="button" className="secondary" aria-label={`Move ${metric.title} up`} disabled={busy||index===0} onClick={()=>void reorder(w.id,-1,metric.title)}>↑ Move up</button><button type="button" className="secondary" aria-label={`Move ${metric.title} down`} disabled={busy||index===settings.data.widgets.length-1} onClick={()=>void reorder(w.id,1,metric.title)}>↓ Move down</button><button type="button" className="secondary" disabled={busy} onClick={()=>apply(s=>removeWidget(s,w.id),'Widget removed. Your underlying record was kept.')}>Remove</button></div>}</article>;})}</div>{!settings.data.widgets.some(w=>!w.hidden)&&<p>No visible widgets. Customize Today to show one or reset your layout.</p>}</section>
 {settings.loaded&&financial&&<><TodayIntelligence/><section className="destination-panel dashboard-destination" aria-labelledby="destination-title"><p className="eyebrow">Start with what matters</p><h2 id="destination-title">A destination for your <span className="nebula-text">next chapter.</span></h2><p>Make your next goal personal. Create a plan with the assets, habits and milestones that matter to you.</p><Link href="/app/goals/new" className="primary">{goals.length?'Plan my next goal →':'Plan my first goal →'}</Link></section></>}
 <section id="how-it-works" className="journey-panel" aria-label="How it works"><div><p className="eyebrow">One journey. Your pace.</p><h2>What matters to you.<br/><span className="nebula-text">One day at a time.</span></h2></div><ol><li><strong>01 · Choose your interests</strong><p>Pick a starting layout. Add the Goals, Habits, assets and Health metrics you use.</p></li><li><strong>02 · Take a small step</strong><p>Log a Habit or meal, review a Goal, or record your tracked wealth. Financial execution remains disabled.</p></li><li><strong>03 · Keep your records safe</strong><p>Use Settings for local storage, backups and optional account setup. Browser storage is not a backup.</p></li></ol></section>
 {editor&&<WidgetEditor key={editor==='new'?'new':editor.id} initial={editor==='new'?undefined:editor} sources={sources} onClose={()=>setEditor(null)} onSave={(w,rev)=>change(s=>saveWidget(s,w,rev),'Widget saved on this device.')}/>}
 {preset&&<Modal title="Choose your Today layout" onClose={()=>setPreset(null)}><fieldset className="dashboard-preset-choices"><legend>Choose a starting point</legend>{PRESETS.map(p=><label key={p.id}><input type="radio" name="dashboard-preset" value={p.id} checked={preset===p.id} onChange={()=>setPreset(p.id)}/><span><strong>{p.label}</strong><small>{p.description}</small></span></label>)}</fieldset><h3>Layout preview</h3><ul>{presetSettings(preset).widgets.map(w=><li key={w.id}>{WIDGET_CATALOG[w.kind].label} · {widgetMetricLabel(w.metric)}</li>)}</ul><p>This replaces your widget layout only. Goals, Habits, Health and assets are kept.</p><div className="dashboard-actions"><button className="secondary" onClick={()=>setPreset(null)}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void change(()=>presetSettings(preset),'Preset saved on this device.').then(()=>setPreset(null)).catch(()=>{})}>Apply layout</button></div>{error&&<p role="alert">{error}</p>}</Modal>}
 </div>;
}
