'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {normalizeBarcode,foodProductSchema,type FoodProduct} from '../../lib/food-lookup';
import {HEALTH_MEALS,newHealthId,logHealthItem,saveFood,parseHealthNumber,type HealthData,type HealthDiaryEntry} from '../../lib/health';
import {getAppStorage} from '../../lib/showcase-storage';
import {ACCOUNT_CHANGE} from '../../lib/account-session';
type Detector={detect:(source:HTMLVideoElement)=>Promise<{rawValue:string}[]>};
type DetectorConstructor={new(options:{formats:string[]}):Detector;getSupportedFormats:()=>Promise<string[]>};
const fields=[['kcal','Calories (kcal)',1],['proteinMg','Protein (g)',1000],['carbsMg','Carbs (g)',1000],['fatMg','Fat (g)',1000]] as const;
export function BarcodeFoodLookup({date,update}:{date:string;update:(updater:(s:HealthData)=>HealthData)=>Promise<void>}){
 const [code,setCode]=useState(''),[product,setProduct]=useState<FoodProduct|null>(null),[values,setValues]=useState<Record<string,string>>({}),[grams,setGrams]=useState('100'),[meal,setMeal]=useState<HealthDiaryEntry['meal']>('Snacks'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[scanning,setScanning]=useState(false),[massConfirmed,setMassConfirmed]=useState(false),[reloadCamera,setReloadCamera]=useState(false);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),scanner=useRef<{stop:()=>void}|null>(null),scanGeneration=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null),request=useRef<AbortController|null>(null),scope=useRef<Storage|null>(null),cache=useRef(new Map<string,FoodProduct>());
 const stop=useCallback(()=>{scanGeneration.current++;scanner.current?.stop();scanner.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(timer.current)clearTimeout(timer.current);setScanning(false);},[]);
 useEffect(()=>{const generation=scanGeneration,details=video.current?.closest('details');const stopHidden=()=>{if(document.hidden)stop();};const stopClosed=()=>{if(details&&!details.open)stop();};const stopAccount=()=>{stop();request.current?.abort();cache.current.clear();setProduct(null);};document.addEventListener('visibilitychange',stopHidden);details?.addEventListener('toggle',stopClosed);window.addEventListener(ACCOUNT_CHANGE,stopAccount);return()=>{generation.current++;scanner.current?.stop();stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);request.current?.abort();document.removeEventListener('visibilitychange',stopHidden);details?.removeEventListener('toggle',stopClosed);window.removeEventListener(ACCOUNT_CHANGE,stopAccount);};},[stop]);
 async function camera(){stop();const generation=scanGeneration.current;setMessage('');
  try{const policy=(document as Document&{featurePolicy?:{allowsFeature:(name:string)=>boolean}}).featurePolicy;if(policy&&!policy.allowsFeature('camera')){setReloadCamera(true);throw Error('Open Health as a fresh page to enable its camera permission, or enter the barcode below.');}setReloadCamera(false);if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera barcode decoding is unavailable in this browser. Enter the code below.');
   const C=(window as unknown as {BarcodeDetector?:DetectorConstructor}).BarcodeDetector;const formats=C?(await C.getSupportedFormats()).filter(f=>['ean_13','ean_8','upc_a'].includes(f)):[];
   // The reviewed decoder is loaded only after the person explicitly starts scanning.
   const fallback=formats.length?null:await Promise.all([import('@zxing/browser'),import('@zxing/library')]);
   if(generation!==scanGeneration.current)return;
   const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(generation!==scanGeneration.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;setScanning(true);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));if(!video.current){stop();return;}
   let previous='';const accept=(raw:string)=>{let candidate='';try{candidate=normalizeBarcode(raw);}catch{candidate='';}if(candidate&&candidate===previous){setCode(candidate);stop();setMessage('Barcode captured on this device. Select Look up barcode to send only the code.');return true;}previous=candidate;return false;};
   if(fallback){const [{BrowserMultiFormatOneDReader},{BarcodeFormat,DecodeHintType}]=fallback;const hints=new Map([[DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_8,BarcodeFormat.EAN_13,BarcodeFormat.UPC_A]]]);const reader=new BrowserMultiFormatOneDReader(hints);const controls=await reader.decodeFromStream(media,video.current,(result,_error,controls)=>{if(generation!==scanGeneration.current)return;scanner.current=controls;if(result)accept(result.getText());});if(generation!==scanGeneration.current){controls.stop();return;}scanner.current=controls;return;}
   const detector=new C!({formats});video.current.srcObject=media;await video.current.play();
   const scan=async()=>{if(generation!==scanGeneration.current||!video.current)return;try{const found=await detector.detect(video.current);if(generation!==scanGeneration.current)return;if(accept(found[0]?.rawValue??''))return;}catch{stop();setMessage('Could not decode this label. Enter the barcode manually.');return;}timer.current=setTimeout(()=>void scan(),400);};void scan();
  }catch(e){stop();setMessage(e instanceof Error&&e.name==='NotAllowedError'?'Camera permission was denied. Manual barcode entry remains available.':e instanceof Error?e.message:'Camera unavailable. Enter the barcode manually.');}
 }
 async function lookup(){stop();request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setMessage('');setProduct(null);setMassConfirmed(false);scope.current=getAppStorage();const selected=scope.current;
  try{const barcode=normalizeBarcode(code);let found=cache.current.get(barcode);if(!found){const res=await fetch('/api/food-lookup?code='+barcode,{signal:controller.signal,cache:'no-store'});if(!res.ok)throw Error(res.status===404?'Product not found. Use Foods & recipes to add a private custom food.':res.status===429?'Lookup is cooling down. Wait a minute and retry.':'Food lookup is unavailable or awaiting provider setup. Your private food library still works.');const text=await res.text();if(text.length>10000)throw Error('Product response exceeded capacity.');found=foodProductSchema.parse(JSON.parse(text));if(found.barcode!==barcode)throw Error('Barcode identity mismatch.');if(cache.current.size>=50)cache.current.clear();cache.current.set(barcode,found);}
   if(controller.signal.aborted||selected!==getAppStorage())return;setProduct(found);setValues(Object.fromEntries(fields.map(([key,,scale])=>[key,found!.nutrients[key]===null?'':String(found!.nutrients[key]!/scale)])));setMessage('Review the package and correct any fields privately. Nothing has been logged.');
  }catch(e){if(!controller.signal.aborted)setMessage(e instanceof Error?e.message:'Lookup failed.');}finally{if(request.current===controller)setBusy(false);}
 }
 async function log(){if(!product||busy||!massConfirmed)return;setBusy(true);try{if(scope.current!==getAppStorage())throw Error('Your data mode changed. Look up and review the product again.');const at=new Date().toISOString(),id=newHealthId(),amount=parseHealthNumber(grams,1000,1,100_000_000),nutrients=Object.fromEntries(fields.map(([key,,scale])=>[key,parseHealthNumber(values[key]??'',scale,0,scale===1?1_000_000:1_000_000_000)])) as {kcal:number;proteinMg:number;carbsMg:number;fatMg:number};
   await update(s=>logHealthItem(saveFood(s,{id,name:product.name,brand:product.brand,servingGrams:100,nutrients,createdAt:at,updatedAt:at,provenance:{provider:'Open Food Facts',barcode:product.barcode,apiVersion:'3.4',observedAt:product.observedAt,license:'ODbL-1.0 / DbCL-1.0'}}),{id:newHealthId(),sourceId:id,sourceKind:'food',date,meal,quantityMilli:Math.round(amount/100)},at));setProduct(null);setMessage('Added to your private diary with the reviewed nutrition snapshot.');
  }catch(e){setMessage(e instanceof Error?e.message:'Could not save. Fill every nutrient from the package; unknown is not zero.');}finally{setBusy(false);}}
 return <section className="panel" aria-label="Barcode food lookup"><h2>A label, then a little review.</h2><p>Decode a product barcode on this device, or type it. Lookup sends only the barcode. No camera frames or private journal entries are uploaded.</p><div className="actions"><button type="button" className="secondary" onClick={()=>void camera()} disabled={busy}>Scan barcode</button>{scanning&&<button type="button" className="secondary" onClick={stop}>Stop camera</button>}</div><video ref={video} muted playsInline hidden={!scanning} aria-label="Barcode camera preview" style={{width:'100%',maxHeight:260}}/>{scanning&&<p role="status">Camera active · point at the product barcode.</p>}
 <label className="field">Product barcode<input inputMode="numeric" autoComplete="off" maxLength={14} value={code} onChange={e=>setCode(e.target.value)}/></label><button type="button" className="secondary" disabled={busy||!code} onClick={()=>void lookup()}>Look up barcode</button>
 {product&&<div><h3>{product.name}</h3><p>{product.brand} · Provider values may be per 100 g or per 100 mL. Verify the package basis before using this grams-based diary. Missing nutrients remain unknown.</p><div className="health-form-grid">{fields.map(([key,label])=><label className="field" key={key}>{label}<input inputMode="decimal" value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})} placeholder="Unknown"/></label>)}<label className="field">Grams eaten<input inputMode="decimal" value={grams} onChange={e=>setGrams(e.target.value)}/></label><label className="field">Barcode meal<select value={meal} onChange={e=>setMeal(e.target.value as HealthDiaryEntry['meal'])}>{HEALTH_MEALS.map(m=><option key={m}>{m}</option>)}</select></label></div><label className="checkbox"><input type="checkbox" checked={massConfirmed} onChange={e=>setMassConfirmed(e.target.checked)}/>I checked the package: these values are per 100 g, or I privately corrected every field to a known per-100-g basis.</label><p>If the package gives only 100 mL, cancel this preview and create a custom serving from known label evidence. ZIGoals does not assume a liquid density. Community data is not verified medical or allergen advice. Changes here remain private.</p><button type="button" className="primary" disabled={busy||!massConfirmed} onClick={()=>void log()}>Confirm and log food</button><button type="button" className="secondary" onClick={()=>setProduct(null)}>Cancel preview</button></div>}
 <p role="status">{message}</p>{reloadCamera&&<a href="/app/health">Reload Health for camera access</a>}<p><a href="https://world.openfoodfacts.org" target="_blank" rel="noopener noreferrer">Open Food Facts</a> · <a href="https://opendatacommons.org/licenses/odbl/1-0/" target="_blank" rel="noopener noreferrer">ODbL database</a> · <a href="https://opendatacommons.org/licenses/dbcl/1-0/" target="_blank" rel="noopener noreferrer">DbCL contents</a>. No provider images used.</p></section>;
}
