'use client';
import {useState} from 'react';
import {type HealthData,parseHealthNumber,newHealthId} from '../../lib/health';
import {measurementKinds,type BodyMeasurement} from '../../lib/body-measurement-schema';
import {saveMeasurement,measurementHistory,exportMeasurementsCsv} from '../../lib/body-measurements';
import {EvidenceChart} from '../platform/evidence-chart';
type Perform=(updater:(data:HealthData)=>HealthData,message:string,after?:()=>void)=>Promise<void>;
const localTime=(iso:string)=>{const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19);};
export function BodyMeasurements({data,perform}:{data:HealthData;perform:Perform}){
 const [kind,setKind]=useState<BodyMeasurement['kind']>('weight'),[unit,setUnit]=useState<BodyMeasurement['unit']>('kg'),[value,setValue]=useState(''),[observed,setObserved]=useState(''),[source,setSource]=useState('Manual measurement'),[editing,setEditing]=useState<BodyMeasurement|null>(null),[error,setError]=useState(''),[page,setPage]=useState(0);
 const history=measurementHistory(data,kind),pages=Math.max(1,Math.ceil(history.readings.length/20)),currentPage=Math.min(page,pages-1),rows=[...history.readings].reverse().slice(currentPage*20,currentPage*20+20),timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 function edit(row:BodyMeasurement){setEditing(row);setKind(row.kind);setUnit(row.unit);setValue(String(row.quantityMilli/1000));setObserved(localTime(row.observedAt));setSource(row.sourceLabel);setError('');}
 function exportCsv(){const url=URL.createObjectURL(new Blob([exportMeasurementsCsv(data)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='zigoals-body-measurements.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="health-two-columns"><section className="panel" aria-label="Body measurement history"><h2>Measurements, with context.</h2><p>Only your recorded observations appear here. Earlier daily weight entries stay in the Weight journal without invented times. All measurement types follow your Health sync permission.</p><label className="field"><span>Measurement history type</span><select aria-label="Measurement history type" value={kind} onChange={e=>{const next=e.target.value as BodyMeasurement['kind'];setKind(next);setUnit(next==='weight'?'kg':'cm');setEditing(null);setValue('');setPage(0);}}>{measurementKinds.map(k=><option key={k} value={k}>{k[0]!.toUpperCase()+k.slice(1)}</option>)}</select></label>
 <EvidenceChart label="Recorded body measurements" decimals={kind==='weight'?6:4} currency={kind==='weight'?'kg':'cm'} series={[{label:kind,color:'#8ad7e6',points:history.readings.map(r=>({at:r.observedAt,value:String(r.canonical)}))}]}/><p className="fine">{history.readings.length<2?'Add two actual observations to show a change.':`Change between first and latest: ${(history.change!/(kind==='weight'?1000000:10000)).toLocaleString(undefined,{maximumFractionDigits:6})} ${kind==='weight'?'kg':'cm'}.`} Connecting lines describe recorded points, not measurements between them.</p>
 <div className="health-table-wrap" role="region" aria-label="Measurement records" tabIndex={0}><table><caption>Current {kind} readings · original units and source</caption><thead><tr><th>Observed time</th><th>Value</th><th>Source</th><th>History</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><time dateTime={r.observedAt}>{new Date(r.observedAt).toLocaleString()}</time><small>{r.timezone}</small></td><td>{r.quantityMilli/1000} {r.unit}</td><td>{r.sourceLabel}</td><td><button className="quiet" onClick={()=>edit(r)}>Correct measurement</button><details><summary>Record history</summary><p style={{overflowWrap:'anywhere'}}>{r.id}</p><p>{r.observedAt} · {r.source}</p>{r.corrections.map((c,i)=><p key={i}>Previous: {c.quantityMilli/1000} {c.unit} · observed {c.observedAt} · recorded {c.recordedAt} · {c.sourceLabel}</p>)}</details></td></tr>)}</tbody></table></div>
 <nav className="actions" aria-label="Measurement history pages"><button disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Newer measurements</button><span>Page {currentPage+1} of {pages}</span><button disabled={currentPage+1>=pages} onClick={()=>setPage(currentPage+1)}>Older measurements</button></nav><button className="secondary" onClick={exportCsv}>Export measurements CSV</button><p className="fine">CSV includes original units, normalized milligrams or micrometres, and previous corrections. It contains private Health data.</p></section>
 <section className="panel health-fit-panel"><h2>{editing?'Correct this measurement.':'Add a timed measurement.'}</h2><form aria-label="Body measurement entry" onSubmit={e=>{e.preventDefault();setError('');try{const date=new Date(observed);if(!Number.isFinite(date.getTime())||localTime(date.toISOString())!==observed)throw Error('Choose a real local date and time; daylight-saving gaps are not valid.');const draft={id:editing?.id??newHealthId(),kind,unit,quantityMilli:parseHealthNumber(value,1000,1,2500000),observedAt:date.toISOString(),timezone,sourceLabel:source};void perform(latest=>saveMeasurement(latest,draft,new Date().toISOString()),'Measurement saved with its original units and history.',()=>{setEditing(null);setValue('');});}catch(e){setError(e instanceof Error?e.message:'Measurement was not saved.');}}}>
 <p>Type: {kind}. Times use this device’s timezone, {timezone}.</p><div className="health-form-grid"><label className="field"><span>Measurement value</span><input type="number" inputMode="decimal" min="0.001" max="2500" step="0.001" required value={value} onChange={e=>setValue(e.target.value)}/></label><label className="field"><span>Measurement unit</span><select aria-label="Measurement unit" value={unit} onChange={e=>setUnit(e.target.value as BodyMeasurement['unit'])}>{(kind==='weight'?['kg','lb']:['cm','in']).map(u=><option key={u}>{u}</option>)}</select></label><label className="field"><span>Measured at (device time)</span><input type="datetime-local" step="1" min="1900-01-01T00:00:00" max="2199-12-31T23:59:59" required value={observed} onChange={e=>setObserved(e.target.value.length===16?e.target.value+':00':e.target.value)}/></label><label className="field"><span>Measurement source</span><input required maxLength={100} value={source} onChange={e=>setSource(e.target.value)}/></label></div>{observed&&Number.isFinite(new Date(observed).getTime())&&<p className="fine">Recorded instant: {new Date(observed).toISOString()}. Check this before saving if clocks changed that day.</p>}
 <button className="primary">Save measurement</button>{editing&&<button type="button" className="quiet" onClick={()=>{setEditing(null);setValue('');}}>Cancel measurement correction</button>}{error&&<p role="alert">{error}</p>}</form></section></div>;
}
