'use client';
import {useState} from 'react';
import {type HealthData} from '../../lib/health';
import {importObservations,observationFileSchema,type ObservationFile} from '../../lib/observation-import';
export function ObservationImport({data,perform}:{data:HealthData;perform:(updater:(data:HealthData)=>HealthData,message:string,after?:()=>void)=>Promise<void>}){
 const [review,setReview]=useState<{file:ObservationFile;basis:string;added:number;linked:number;duplicates:number}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const basis=(value:HealthData)=>JSON.stringify(value.measurements??[]);
 function example(){const sample={format:'zigoals-observations',version:1,provider:'Your export source',observations:[{sourceId:'replace-with-stable-source-id',kind:'weight',quantityMilli:70000,unit:'kg',observedAt:'2026-01-01T10:00:00.000Z',timezone:'UTC',sourceLabel:'Example only; replace with your actual observation'}]},url=URL.createObjectURL(new Blob([JSON.stringify(sample,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='observation-format-example.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <details className="panel"><summary>Import recorded measurements</summary><p>Review up to 100 normalized observations from a JSON file. Stable source IDs prevent replay duplicates. An exact measurement type, instant and normalized value matching a retained reading attaches the source to that reading; it does not add a second reading. Date-only weight entries remain separate. This is a file import, not a connected device.</p><button className="secondary" onClick={example}>Download observation format example</button><label className="field">Observation JSON file<input type="file" accept=".json,application/json" onChange={async event=>{setReview(null);setError('');const file=event.target.files?.[0];if(!file)return;try{if(file.size>131072)throw Error('Choose a file no larger than 128 KiB.');const parsed=observationFileSchema.parse(JSON.parse(await file.text())),result=importObservations(data,parsed,new Date().toISOString());setReview({file:parsed,basis:basis(data),added:result.added,linked:result.linked,duplicates:result.duplicates});}catch(e){setError(e instanceof Error?e.message:'The file could not be reviewed.');}}}/></label>{review&&<section aria-label="Measurement import review"><h3>Review measurements before importing</h3><p>{review.added} new · {review.linked} matching retained readings · {review.duplicates} already imported</p><ul>{review.file.observations.map((v,i)=><li key={i}>{v.kind}: {v.quantityMilli/1000} {v.unit} · {v.observedAt} · {v.sourceLabel}</li>)}</ul><button className="primary" disabled={busy} onClick={()=>{setBusy(true);void perform(latest=>{if(basis(latest)!==review.basis)throw Error('Measurements changed. Select the file again to review the latest matches.');return importObservations(latest,review.file,new Date().toISOString()).data;},'Reviewed measurements imported; repeated source IDs were not duplicated.',()=>setReview(null)).finally(()=>setBusy(false));}}>Confirm measurement import</button><button className="secondary" disabled={busy} onClick={()=>setReview(null)}>Cancel measurement import</button></section>}{error&&<p role="alert">{error}</p>}</details>;
}
